 
CREATE PROCEDURE SP_ZirvePuanbilInsert
    @dynamicDatabaseName NVARCHAR(128),
    @Ayindex SMALLINT,
    @Personelno INT,
    @Puantajno SMALLINT,
    @Personelgrubu NVARCHAR(15),
    @Ucret FLOAT,
    @Calismagunu FLOAT,
    @Geneltatil FLOAT,
    @Haftasonu FLOAT,
    @Sihhiizin FLOAT,
    @Yillikizin FLOAT,
    @Ucretliizin FLOAT,
    @Ucretsizizin FLOAT,
    @Mazeretgunu FLOAT,
    @Toplamisgunu SMALLINT,
    @Primgunu SMALLINT,
    @fm1 FLOAT,
    @fm2 FLOAT,
    @fm3 FLOAT,
    @Eksikcalsaati FLOAT,
    @Epgn NVARCHAR(2),
    @Cs FLOAT,
    @Hs FLOAT,
    @Dvm FLOAT,
    @Au FLOAT,
    @Fm FLOAT,
    @So FLOAT,
    @Cp FLOAT,
    @Bt FLOAT,
    @Vem FLOAT,
    @Sim FLOAT,
    @Vrgi FLOAT,
    @Gev FLOAT,
    @Sk FLOAT,
    @Isk FLOAT,
    @Dv FLOAT,
    @Sak FLOAT,
    @Kt FLOAT,
    @Netu FLOAT,
    @Isskk FLOAT,
    @Iisk FLOAT,
    @Gsigm FLOAT,
    @Uip FLOAT,
    @Aei NVARCHAR(1),
    @Fsk SMALLINT,
    @Dsm NVARCHAR(1),
    @Veriade FLOAT,
    @g1 CHAR(1),
    @g2 CHAR(1),
    @g3 CHAR(1),
    @g4 CHAR(1),
    @g5 CHAR(1),
    @g6 CHAR(1),
    @g7 CHAR(1),
    @g8 CHAR(1),
    @g9 CHAR(1),
    @g10 CHAR(1),
    @g11 CHAR(1),
    @g12 CHAR(1),
    @g13 CHAR(1),
    @g14 CHAR(1),
    @g15 CHAR(1),
    @g16 CHAR(1),
    @g17 CHAR(1),
    @g18 CHAR(1),
    @g19 CHAR(1),
    @g20 CHAR(1),
    @g21 CHAR(1),
    @g22 CHAR(1),
    @g23 CHAR(1),
    @g24 CHAR(1),
    @g25 CHAR(1),
    @g26 CHAR(1),
    @g27 CHAR(1),
    @g28 CHAR(1),
    @g29 CHAR(1),
    @g30 CHAR(1),
    @g31 CHAR(1),
    @Gelirindirim FLOAT,
    @Sskindirim FLOAT,
    @Ucretsekli CHAR(8),
    @Tahakkuksekli CHAR(5),
    @Vmb CHAR(1),
    @Vmpk CHAR(1),
    @Yil SMALLINT,
    @SSno NVARCHAR(18),
    @Belgeturu CHAR(2),
    @Dinitatil FLOAT,
    @Arti INT,
    @Kanunno NVARCHAR(5),
    @Sozlesmeturu CHAR(1),
    @Personeldurumu CHAR(1),
    @fmtutar1 FLOAT,
    @fmtutar2 FLOAT,
    @fmtutar3 FLOAT,
    @Asgari_gecim_ind_tut FLOAT,
    @Kilitli BIT,
    @Bordrotipi INT,
    @Asgari_gecim_ind_brut FLOAT,
    @Asgari_gecim_ind_oran FLOAT,
    @Grupkodu NVARCHAR(20),
    @Sanalgev FLOAT,
    @Doktoralimi FLOAT,
    @Asgarimi FLOAT,
    @Devir_ssk FLOAT,
    @Devir_ssk_kullanilan FLOAT,
    @Devir_ssk_aya_yazilacak FLOAT,
    @Devir_ssk1 FLOAT,
    @Devir_ssk2 FLOAT,
    @Devir_ssk3 FLOAT,
    @Gorevi NVARCHAR(50),
    @Meslekgrubu NVARCHAR(50),
    @Meslegi NVARCHAR(50),
    @Onbesgunluk FLOAT,
    @zi1 FLOAT,
    @r1 FLOAT,
    @zi4 FLOAT,
    @r3 FLOAT,
    @agi FLOAT,
    @zi2 FLOAT,
    @Digerkanun NVARCHAR(50),
    @Damga_Vergi_Ist FLOAT,
    @Bolgeici_Vergi_Matrahi FLOAT,
    @KisaCalismaGunu FLOAT,
    @KisaCalismaIlk7Gunu FLOAT,
    @KisaCalismaHafCalGun FLOAT,
    @KisaCalismaIlk7GunHesapla FLOAT,
    @AsgariUcretDevirVergiMatrahi FLOAT,
    @AsgariUcretVergiIstisnaTutari FLOAT,
    @DamgaVergisiMatrahiIstisnaSonrasi FLOAT,
    @GelirVergisiMatrahIndirimi FLOAT,
    @FmTutar1Brut FLOAT,
    @FmTutar2Brut FLOAT,
    @FmTutar3Brut FLOAT,
    @UcusDalisOrani FLOAT
AS
BEGIN
    DECLARE @sql NVARCHAR(MAX);

    SET @sql = '
    INSERT INTO [' + @dynamicDatabaseName + '].[dbo].[puanbil]
               ([Ayindex], [Personelno], [Puantajno], [Personelgrubu], [Ucret], [Calismagunu], [Geneltatil],
                [Haftasonu], [Sihhiizin], [Yillikizin], [Ucretliizin], [Ucretsizizin], [Mazeretgunu],
                [Toplamisgunu], [Primgunu], [fm1], [fm2], [fm3], [Eksikcalsaati], [Epgn], [Cs], [Hs],
                [Dvm], [Au], [Fm], [So], [Cp], [Bt], [Vem], [Sim], [Vrgi], [Gev], [Sk], [Isk], [Dv],
                [Sak], [Kt], [Netu], [Isskk], [Iisk], [Gsigm], [Uip], [Aei], [Fsk], [Dsm], [Veriade],
                [g1], [g2], [g3], [g4], [g5], [g6], [g7], [g8], [g9], [g10], [g11], [g12], [g13],
                [g14], [g15], [g16], [g17], [g18], [g19], [g20], [g21], [g22], [g23], [g24], [g25],
                [g26], [g27], [g28], [g29], [g30], [g31], [Gelirindirim], [Sskindirim], [Ucretsekli],
                [Tahakkuksekli], [Vmb], [Vmpk], [Yil], [SSno], [Belgeturu], [Dinitatil], [Arti], [Kanunno],
                [Sozlesmeturu], [Personeldurumu], [fmtutar1], [fmtutar2], [fmtutar3], [Asgari_gecim_ind_tut],
                [Kilitli], [Bordrotipi], [Asgari_gecim_ind_brut], [Asgari_gecim_ind_oran], [Grupkodu],
                [Sanalgev], [Doktoralimi], [Asgarimi], [Devir_ssk], [Devir_ssk_kullanilan],
                [Devir_ssk_aya_yazilacak], [Devir_ssk1], [Devir_ssk2], [Devir_ssk3], [Gorevi],
                [Meslekgrubu], [Meslegi], [Onbesgunluk], [zi1], [r1], [zi4], [r3], [agi], [zi2],
                [Digerkanun], [Damga_Vergi_Ist], [Bolgeici_Vergi_Matrahi], [KisaCalismaGunu],
                [KisaCalismaIlk7Gunu], [KisaCalismaHafCalGun], [KisaCalismaIlk7GunHesapla],
                [AsgariUcretDevirVergiMatrahi], [AsgariUcretVergiIstisnaTutari],
                [DamgaVergisiMatrahiIstisnaSonrasi], [GelirVergisiMatrahIndirimi],
                [FmTutar1Brut], [FmTutar2Brut], [FmTutar3Brut], [UcusDalisOrani])
         VALUES
               (@Ayindex, @Personelno, @Puantajno, @Personelgrubu,@Ucret, @Calismagunu, @Geneltatil,
                @Haftasonu, @Sihhiizin, @Yillikizin, @Ucretliizin, @Ucretsizizin, @Mazeretgunu,
                @Toplamisgunu, @Primgunu, @fm1, @fm2, @fm3, @Eksikcalsaati, @Epgn, @Cs, @Hs,
                @Dvm, @Au, @Fm, @So, @Cp, @Bt, @Vem, @Sim, @Vrgi, @Gev, @Sk, @Isk, @Dv,
                @Sak, @Kt, @Netu, @Isskk, @Iisk, @Gsigm, @Uip, @Aei, @Fsk, @Dsm, @Veriade,
                @g1, @g2, @g3, @g4, @g5, @g6, @g7, @g8, @g9, @g10, @g11, @g12, @g13,
                @g14, @g15, @g16, @g17, @g18, @g19, @g20, @g21, @g22, @g23, @g24, @g25,
                @g26, @g27, @g28, @g29, @g30, @g31, @Gelirindirim, @Sskindirim, @Ucretsekli,
                @Tahakkuksekli, @Vmb, @Vmpk, @Yil, @SSno, @Belgeturu, @Dinitatil, @Arti, @Kanunno,
                @Sozlesmeturu, @Personeldurumu, @fmtutar1, @fmtutar2, @fmtutar3, @Asgari_gecim_ind_tut,
                @Kilitli, @Bordrotipi, @Asgari_gecim_ind_brut, @Asgari_gecim_ind_oran, @Grupkodu,
                @Sanalgev, @Doktoralimi, @Asgarimi, @Devir_ssk, @Devir_ssk_kullanilan,
                @Devir_ssk_aya_yazilacak, @Devir_ssk1, @Devir_ssk2, @Devir_ssk3, @Gorevi,
                @Meslekgrubu, @Meslegi, @Onbesgunluk, @zi1, @r1, @zi4, @r3, @agi, @zi2,
                @Digerkanun, @Damga_Vergi_Ist, @Bolgeici_Vergi_Matrahi, @KisaCalismaGunu,
                @KisaCalismaIlk7Gunu, @KisaCalismaHafCalGun, @KisaCalismaIlk7GunHesapla,
                @AsgariUcretDevirVergiMatrahi, @AsgariUcretVergiIstisnaTutari,
                @DamgaVergisiMatrahiIstisnaSonrasi, @GelirVergisiMatrahIndirimi,
                @FmTutar1Brut, @FmTutar2Brut, @FmTutar3Brut, @UcusDalisOrani)'

			EXEC sp_executesql @sql,
        N'@Ayindex SMALLINT, @Personelno INT, @Puantajno SMALLINT, @Personelgrubu NVARCHAR(15), @Ucret FLOAT, @Calismagunu FLOAT, @Geneltatil FLOAT, @Haftasonu FLOAT, @Sihhiizin FLOAT, @Yillikizin FLOAT, @Ucretliizin FLOAT, @Ucretsizizin FLOAT, @Mazeretgunu FLOAT, @Toplamisgunu SMALLINT, @Primgunu SMALLINT, @fm1 FLOAT, @fm2 FLOAT, @fm3 FLOAT, @Eksikcalsaati FLOAT, @Epgn NVARCHAR(2), @Cs FLOAT, @Hs FLOAT, @Dvm FLOAT, @Au FLOAT, @Fm FLOAT, @So FLOAT, @Cp FLOAT, @Bt FLOAT, @Vem FLOAT, @Sim FLOAT, @Vrgi FLOAT, @Gev FLOAT, @Sk FLOAT, @Isk FLOAT, @Dv FLOAT, @Sak FLOAT, @Kt FLOAT, @Netu FLOAT, @Isskk FLOAT, @Iisk FLOAT, @Gsigm FLOAT, @Uip FLOAT, @Aei NVARCHAR(1), @Fsk SMALLINT, @Dsm NVARCHAR(1), @Veriade FLOAT, @g1 CHAR(1), @g2 CHAR(1), @g3 CHAR(1), @g4 CHAR(1), @g5 CHAR(1), @g6 CHAR(1), @g7 CHAR(1), @g8 CHAR(1), @g9 CHAR(1), @g10 CHAR(1), @g11 CHAR(1), @g12 CHAR(1), @g13 CHAR(1), @g14 CHAR(1), @g15 CHAR(1), @g16 CHAR(1), @g17 CHAR(1), @g18 CHAR(1), @g19 CHAR(1), @g20 CHAR(1), @g21 CHAR(1), @g22 CHAR(1), @g23 CHAR(1), @g24 CHAR(1), @g25 CHAR(1), @g26 CHAR(1), @g27 CHAR(1), @g28 CHAR(1), @g29 CHAR(1), @g30 CHAR(1), @g31 CHAR(1), @Gelirindirim FLOAT, @Sskindirim FLOAT, @Ucretsekli CHAR(8), @Tahakkuksekli CHAR(5), @Vmb CHAR(1), @Vmpk CHAR(1), @Yil SMALLINT, @SSno NVARCHAR(18), @Belgeturu CHAR(2), @Dinitatil FLOAT, @Arti INT, @Kanunno NVARCHAR(5), @Sozlesmeturu CHAR(1), @Personeldurumu CHAR(1), @fmtutar1 FLOAT, @fmtutar2 FLOAT, @fmtutar3 FLOAT, @Asgari_gecim_ind_tut FLOAT, @Kilitli BIT, @Bordrotipi INT, @Asgari_gecim_ind_brut FLOAT, @Asgari_gecim_ind_oran FLOAT, @Grupkodu NVARCHAR(20), @Sanalgev FLOAT, @Doktoralimi FLOAT, @Asgarimi FLOAT, @Devir_ssk FLOAT, @Devir_ssk_kullanilan FLOAT, @Devir_ssk_aya_yazilacak FLOAT, @Devir_ssk1 FLOAT, @Devir_ssk2 FLOAT, @Devir_ssk3 FLOAT, @Gorevi NVARCHAR(50), @Meslekgrubu NVARCHAR(50), @Meslegi NVARCHAR(50), @Onbesgunluk FLOAT, @zi1 FLOAT, @r1 FLOAT, @zi4 FLOAT, @r3 FLOAT, @agi FLOAT, @zi2 FLOAT, @Digerkanun NVARCHAR(50), @Damga_Vergi_Ist FLOAT, @Bolgeici_Vergi_Matrahi FLOAT, @KisaCalismaGunu FLOAT, @KisaCalismaIlk7Gunu FLOAT, @KisaCalismaHafCalGun FLOAT, @KisaCalismaIlk7GunHesapla FLOAT, @AsgariUcretDevirVergiMatrahi FLOAT, @AsgariUcretVergiIstisnaTutari FLOAT, @DamgaVergisiMatrahiIstisnaSonrasi FLOAT, @GelirVergisiMatrahIndirimi FLOAT, @FmTutar1Brut FLOAT, @FmTutar2Brut FLOAT, @FmTutar3Brut FLOAT, @UcusDalisOrani FLOAT',
        @Ayindex = @Ayindex,
        @Personelno = @Personelno,
        @Puantajno = @Puantajno,
        @Personelgrubu = @Personelgrubu,
        @Ucret = @Ucret,
        @Calismagunu = @Calismagunu,
        @Geneltatil = @Geneltatil,
        @Haftasonu = @Haftasonu,
        @Sihhiizin = @Sihhiizin,
        @Yillikizin = @Yillikizin,
        @Ucretliizin = @Ucretliizin,
        @Ucretsizizin = @Ucretsizizin,
        @Mazeretgunu = @Mazeretgunu,
        @Toplamisgunu = @Toplamisgunu,
        @Primgunu = @Primgunu,
        @fm1 = @fm1,
        @fm2 = @fm2,
        @fm3 = @fm3,
        @Eksikcalsaati = @Eksikcalsaati,
        @Epgn = @Epgn,
        @Cs = @Cs,
        @Hs = @Hs,
        @Dvm = @Dvm,
        @Au = @Au,
        @Fm = @Fm,
        @So = @So,
        @Cp = @Cp,
        @Bt = @Bt,
        @Vem = @Vem,
        @Sim = @Sim,
        @Vrgi = @Vrgi,
        @Gev = @Gev,
        @Sk = @Sk,
        @Isk = @Isk,
        @Dv = @Dv,
        @Sak = @Sak,
        @Kt = @Kt,
        @Netu = @Netu,
        @Isskk = @Isskk,
        @Iisk = @Iisk,
        @Gsigm = @Gsigm,
        @Uip = @Uip,
        @Aei = @Aei,
        @Fsk = @Fsk,
        @Dsm = @Dsm,
        @Veriade = @Veriade,
        @g1 = @g1,
        @g2 = @g2,
        @g3 = @g3,
        @g4 = @g4,
        @g5 = @g5,
        @g6 = @g6,
        @g7 = @g7,
        @g8 = @g8,
        @g9 = @g9,
        @g10 = @g10,
        @g11 = @g11,
        @g12 = @g12,
        @g13 = @g13,
        @g14 = @g14,
        @g15 = @g15,
        @g16 = @g16,
        @g17 = @g17,
        @g18 = @g18,
        @g19 = @g19,
        @g20 = @g20,
        @g21 = @g21,
        @g22 = @g22,
        @g23 = @g23,
        @g24 = @g24,
        @g25 = @g25,
        @g26 = @g26,
        @g27 = @g27,
        @g28 = @g28,
        @g29 = @g29,
        @g30 = @g30,
        @g31 = @g31,
        @Gelirindirim = @Gelirindirim,
        @Sskindirim = @Sskindirim,
        @Ucretsekli = @Ucretsekli,
        @Tahakkuksekli = @Tahakkuksekli,
        @Vmb = @Vmb,
        @Vmpk = @Vmpk,
        @Yil = @Yil,
        @SSno = @SSno,
        @Belgeturu = @Belgeturu,
        @Dinitatil = @Dinitatil,
        @Arti = @Arti,
        @Kanunno = @Kanunno,
        @Sozlesmeturu = @Sozlesmeturu,
        @Personeldurumu = @Personeldurumu,
        @fmtutar1 = @fmtutar1,
        @fmtutar2 = @fmtutar2,
        @fmtutar3 = @fmtutar3,
        @Asgari_gecim_ind_tut = @Asgari_gecim_ind_tut,
        @Kilitli = @Kilitli,
        @Bordrotipi = @Bordrotipi,
        @Asgari_gecim_ind_brut = @Asgari_gecim_ind_brut,
        @Asgari_gecim_ind_oran = @Asgari_gecim_ind_oran,
        @Grupkodu = @Grupkodu,
        @Sanalgev = @Sanalgev,
        @Doktoralimi = @Doktoralimi,
        @Asgarimi = @Asgarimi,
        @Devir_ssk = @Devir_ssk,
        @Devir_ssk_kullanilan = @Devir_ssk_kullanilan,
        @Devir_ssk_aya_yazilacak = @Devir_ssk_aya_yazilacak,
        @Devir_ssk1 = @Devir_ssk1,
        @Devir_ssk2 = @Devir_ssk2,
        @Devir_ssk3 = @Devir_ssk3,
        @Gorevi = @Gorevi,
        @Meslekgrubu = @Meslekgrubu,
        @Meslegi = @Meslegi,
        @Onbesgunluk = @Onbesgunluk,
        @zi1 = @zi1,
        @r1 = @r1,
        @zi4 = @zi4,
        @r3 = @r3,
        @agi = @agi,
        @zi2 = @zi2,
        @Digerkanun = @Digerkanun,
        @Damga_Vergi_Ist = @Damga_Vergi_Ist,
        @Bolgeici_Vergi_Matrahi = @Bolgeici_Vergi_Matrahi,
        @KisaCalismaGunu = @KisaCalismaGunu,
        @KisaCalismaIlk7Gunu = @KisaCalismaIlk7Gunu,
        @KisaCalismaHafCalGun = @KisaCalismaHafCalGun,
        @KisaCalismaIlk7GunHesapla = @KisaCalismaIlk7GunHesapla,
        @AsgariUcretDevirVergiMatrahi = @AsgariUcretDevirVergiMatrahi,
        @AsgariUcretVergiIstisnaTutari = @AsgariUcretVergiIstisnaTutari,
        @DamgaVergisiMatrahiIstisnaSonrasi = @DamgaVergisiMatrahiIstisnaSonrasi,
        @GelirVergisiMatrahIndirimi = @GelirVergisiMatrahIndirimi,
        @FmTutar1Brut = @FmTutar1Brut,
        @FmTutar2Brut = @FmTutar2Brut,
        @FmTutar3Brut = @FmTutar3Brut,
        @UcusDalisOrani = @UcusDalisOrani;


end