
SELECT

OBJECT_NAME(c.OBJECT_ID) 'TABLO', c.name 'KOLON'

FROM sys.columns c

WHERE c.NAME LIKE '%WEI%'  AND OBJECT_NAME(c.OBJECT_ID) LIKE 'LG_324%'

ORDER BY TABLO ASC


 SELECT GROSSWEIGHT,WEIGHT,WEIGHTREF,*  FROM LG_320_ITMUNITA   WHERE ITEMREF = 293


 SELECT*  FROM LG_320_ITEMS WHERE LOGICALREF = 293

 SELECT LG_324_ITMUNITA.WEIGHT,LG_320_ITMUNITA.WEIGHT,'UPDATE LG_324_ITMUNITA SET WEIGHT=' + CAST(LG_320_ITMUNITA.WEIGHT AS VARCHAR(20)) + ' WHERE LOGICALREF=' + CAST(LG_324_ITMUNITA.LOGICALREF AS VARCHAR(20)) FROM LG_320_ITMUNITA  
 LEFT JOIN LG_324_ITMUNITA ON LG_320_ITMUNITA.ITEMREF = LG_324_ITMUNITA.ITEMREF 
 WHERE LG_324_ITMUNITA.LOGICALREF IS NOT NULL and LG_320_ITMUNITA.WEIGHT> 0


 select WEIGHT,  * from LG_324_ITEMS 
LEFT JOIN LG_324_ITMUNITA ON LG_324_ITMUNITA.ITEMREF = LG_324_ITEMS.LOGICALREF AND LG_324_ITMUNITA.LINENR = 1
WHERE CYPHCODE = '03' 
