
SELECT [LG_024_BANKACC].[LOGICALREF]
      ,[CARDTYPE]
      ,[CODE]
      ,[DEFINITION_]
	  ,[IBAN]
	  ,L_CURRENCYLIST.CURCODE
      ,[SPECODE]
      ,[BANKREF]
      ,[CURRENCY]
      ,[ACCOUNTNO]
      
   
  FROM [dbo].[LG_024_BANKACC]
  LEFT JOIN L_CURRENCYLIST ON L_CURRENCYLIST.LOGICALREF = [LG_024_BANKACC].CURRENCY
WHERE CARDTYPE = 3 AND [LG_024_BANKACC].ACTIVE= 0


