 SELECT       Faiz  AS M2,BankaAdi AS CARITUR,KrediKodu AS FISNO,TahakkukTarihi AS TARIH, 
 KalanEuro * -1 AS DOVIZTUTAR,    TahakkukAy AS AY,TahakkukYil AS YIL, KrediFaizTutari as TRRATE,  
TRCURR as SOURCEINDEX, 0.00 AS DISCPER, 0 as VAT, '' AS OUTPUTIDCODE,   (Faiz + Bsmv) * -1 as AMOUNT,  (Faiz + Bsmv) * -1 as TOTAL ,(Faiz + Bsmv) * -1    LINENET    ,
 KrediKodu as CARIKODU ,KrediAdi AS CARIADI   ,BankaKodu AS MALZEMEKODU, BankaAdi AS MALZEMEADI   ,DovizCinsi AS MASRAFMERKEZIKODU, 
cast(KrediToplamTutari as varchar(20)) AS MASRAFMERKEZIADI,KrediFAizTutari AS BIRIMFIYAT            
 FROM TIGER.[dbo].[VW_BankaKredileri_24] where TahakkukYil = 2024
 UNION ALL

    SELECT   
 
	 CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,   STL.VATMATRAH  * -1  , STL.VATMATRAH  * -1 as TOTAL ,STL.VATMATRAH  * -1  as  LINENET    ,
'' as CARIKODU ,'' AS CARIADI   ,'' AS MALZEMEKODU, '' AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_STLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE EMCENTER.CODE =  'URT.180.018'     

  SELECT   
	 CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,   STL.VATMATRAH  * -1 as AMOUNT , STL.VATMATRAH  * -1 as TOTAL ,STL.VATMATRAH  * -1  as  LINENET    ,
'' as CARIKODU ,'' AS CARIADI   ,'' AS MALZEMEKODU, '' AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_STLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE EMCENTER.CODE =  'URT.180.020'   
	   

-- 2-6 BAKIM
 SELECT   
	 CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,   STL.VATMATRAH  * -1 as AMOUNT , STL.VATMATRAH  * -1 as TOTAL ,STL.VATMATRAH  * -1  as  LINENET    ,
'' as CARIKODU ,'' AS CARIADI   ,'' AS MALZEMEKODU, '' AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_STLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE ( EMCENTER.CODE IN  ( SELECT EMCENTER2.CODE FROM  TIGER.DBO.LG_024_EMCENTER EMCENTER2 WHERE   (EMCENTER2.DEFINITION_ like '%BAKIM G_DER%' AND EMCENTER2.CODE <> 'URT.180.0010') OR  
(EMCENTER2 .CODE = 'URT.070.011')  )  AND INV.SPECODE<>'BÜTÇEDIÞI')   

-- 2-7
 SELECT   
	        STL.AMOUNT   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.AMOUNT  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,STL.AMOUNT AS TRRATE,  
 0 AS SOURCEINDEX, 0.00 AS DISCPER, INV.EXIMVAT as VAT, '' AS OUTPUTIDCODE,   STL.AMOUNT  * -1 as AMOUNT , STL.AMOUNT  * -1 as TOTAL ,STL.AMOUNT  * -1  as  LINENET    ,
CL.CODE as CARIKODU ,CL.DEFINITION_ AS CARIADI   ,'' AS MALZEMEKODU, INV.GENEXP1 AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.AMOUNT AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_BNFLINE STL  WITH(NOLOCK)
 --SELECT * FROM TIGER.DBO.LG_024_01_BNFLINE
LEFT OUTER JOIN   TIGER.DBO.LG_024_01_BNFICHE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.SOURCEFREF
LEFT OUTER JOIN   TIGER.DBO.LG_024_CLCARD CL WITH(NOLOCK) ON CL.LOGICALREF=STL.CLIENTREF 
LEFT OUTER JOIN   TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
 WHERE  INV.SPECODE LIKE '_N_AAT'
 UNION ALL
  SELECT   
 STL.AMOUNT   AS M2,STL.SPECODE AS CARITUR,STL.FICHENO AS FISNO,STL.DATE_ AS TARIH, 
 ROUND((STL.AMOUNT  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(STL.DATE_) AS AY,YEAR(STL.DATE_) AS YIL,STL.AMOUNT AS TRRATE,  
 0 AS SOURCEINDEX, 0.00 AS DISCPER, 0 AS VAT  , '' AS OUTPUTIDCODE,   STL.AMOUNT  * -1 as AMOUNT , STL.AMOUNT  * -1 as TOTAL ,STL.AMOUNT  * -1  as  LINENET    ,
'' as CARIKODU ,'' AS CARIADI   ,'' AS MALZEMEKODU, STL.LINEEXP AS MALZEMEADI   ,STL.CUSTTITLE AS MASRAFMERKEZIKODU, 
'' AS MASRAFMERKEZIADI, STL.AMOUNT AS BIRIMFIYAT 
FROM
     TIGER.DBO.LG_024_01_KSLINES STL
  LEFT OUTER JOIN TIGER.DBO.LG_024_KSCARD BANK WITH(NOLOCK) ON STL.CARDREF = BANK.LOGICALREF
   LEFT JOIN TIGER.DBO.LG_EXCHANGE_024 tblEuro ON CAST( tblEuro.EDATE AS DATE) = CAST(STL.DATE_ AS DATE) AND tblEuro.CRTYPE = 20
  LEFT JOIN TIGER.DBO.LG_EXCHANGE_024 tblDolar ON CAST( tblDolar.EDATE AS DATE) = CAST(STL.DATE_  AS DATE) AND tblDolar.CRTYPE = 1
 
 WHERE  STL.SPECODE LIKE '_N_AAT'
 -- 2.8 LEASÝNG
  SELECT   
	        STL.AMOUNT   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.AMOUNT  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,STL.AMOUNT AS TRRATE,  
 0 AS SOURCEINDEX, 0.00 AS DISCPER, INV.EXIMVAT as VAT, '' AS OUTPUTIDCODE,   STL.AMOUNT  * -1 as AMOUNT , STL.AMOUNT  * -1 as TOTAL ,STL.AMOUNT  * -1  as  LINENET    ,
CL.CODE as CARIKODU ,CL.DEFINITION_ AS CARIADI   ,'' AS MALZEMEKODU, INV.GENEXP1 AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.AMOUNT AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_BNFLINE STL  WITH(NOLOCK)
 --SELECT * FROM TIGER.DBO.LG_024_01_BNFLINE
LEFT OUTER JOIN   TIGER.DBO.LG_024_01_BNFICHE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.SOURCEFREF
LEFT OUTER JOIN   TIGER.DBO.LG_024_CLCARD CL WITH(NOLOCK) ON CL.LOGICALREF=STL.CLIENTREF 
LEFT OUTER JOIN   TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
 WHERE   INV.SPECODE = 'YATIRIM' AND STL.SIGN  = 0
-- 2-9 MAK. REVÝZYON
 SELECT   
	STL.AMOUNT   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.AMOUNT  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,STL.AMOUNT AS TRRATE,  
 0 AS SOURCEINDEX, 0.00 AS DISCPER, INV.EXIMVAT as VAT, '' AS OUTPUTIDCODE,   STL.AMOUNT  * -1 as AMOUNT , STL.AMOUNT  * -1 as TOTAL ,STL.AMOUNT  * -1  as  LINENET    ,
CL.CODE as CARIKODU ,CL.DEFINITION_ AS CARIADI   ,'' AS MALZEMEKODU, INV.GENEXP1 AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.AMOUNT AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_BNFLINE STL  WITH(NOLOCK)
 --SELECT * FROM TIGER.DBO.LG_024_01_BNFLINE
LEFT OUTER JOIN   TIGER.DBO.LG_024_01_BNFICHE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.SOURCEFREF
LEFT OUTER JOIN   TIGER.DBO.LG_024_CLCARD CL WITH(NOLOCK) ON CL.LOGICALREF=STL.CLIENTREF 
LEFT OUTER JOIN   TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
 WHERE  INV.SPECODE LIKE 'MAK.REV_ZY'
 -- 2.10 BAKIM 
  SELECT   
	 CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,   STL.VATMATRAH  * -1 as AMOUNT , STL.VATMATRAH  * -1 as TOTAL ,STL.VATMATRAH  * -1  as  LINENET    ,
'' as CARIKODU ,'' AS CARIADI   ,'' AS MALZEMEKODU, '' AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_STLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE ( EMCENTER.CODE IN  ( SELECT EMCENTER2.CODE FROM  TIGER.DBO.LG_024_EMCENTER EMCENTER2 WHERE   (EMCENTER2.DEFINITION_ like '%BAKIM G_DER%' AND EMCENTER2.CODE <> 'URT.180.0010') OR  
(EMCENTER2 .CODE = 'URT.180.015')  )  AND INV.SPECODE<>'BÜTÇEDIÞI')   

-- 2.11 YARDIMCI MALZ.GÝDERLERÝ
  SELECT   
	 CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,   STL.VATMATRAH  * -1 as AMOUNT , STL.VATMATRAH  * -1 as TOTAL ,STL.VATMATRAH  * -1  as  LINENET    ,
'' as CARIKODU ,'' AS CARIADI   ,'' AS MALZEMEKODU, '' AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_STLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE EMCENTER.CODE IN  ( SELECT CODE FROM TIGER.DBO.LG_024_EMCENTER WHERE   (DEFINITION_ like '%malzeme%' AND CODE <> 'URT.180.0010')  )  AND INV.SPECODE<>'BÜTÇEDIÞI'     

-- 2.12 DÝÐER GÝDERLER
  SELECT   
	 CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,STL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,   STL.VATMATRAH  * -1 as AMOUNT , STL.VATMATRAH  * -1 as TOTAL ,STL.VATMATRAH  * -1  as  LINENET    ,
'' as CARIKODU ,'' AS CARIADI   ,'' AS MALZEMEKODU, '' AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT 
FROM         TIGER.DBO.LG_024_01_STLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
 
LEFT OUTER JOIN  TIGER.DBO.LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE   EMCENTER.SPECODE like '%D__ER%'     AND INV.SPECODE<>'BÜTÇEDIÞI' 

 --SELECT * FROM  TIGER.DBO.LG_024_01_KSLINES 


 

	   SELECT        CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,CL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,    STL.AMOUNT , STL.TOTAL  * -1 as TOTAL ,STL.LINENET  * -1  LINENET    ,
 CL.CODE as CARIKODU ,CL.DEFINITION_ AS CARIADI   ,ITM.CODE AS MALZEMEKODU, ITM.NAME AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT   FROM         TIGER..LG_024_01_STLINE STL  WITH(NOLOCK)    
 LEFT OUTER JOIN  TIGER..LG_024_ITEMS ITM WITH(NOLOCK) ON ITM.LOGICALREF=STL.STOCKREF  
 LEFT OUTER JOIN  TIGER..LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF  
 LEFT OUTER JOIN  TIGER..LG_024_CLCARD CL WITH(NOLOCK) ON INV.CLIENTREF=CL.LOGICALREF  
 LEFT OUTER JOIN  TIGER..LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF  
 WHERE  EMCENTER.DEFINITION_ LIKE  '%elekTR_K G_D%'
 
 
 