 
    SELECT  
        DISPLINE.LINENO_, 
        [ÜRETÝM EMRÝ] = PRODORD.FICHENO, 
        [PLANLANAN_ADET] = PRODORD.PLNAMOUNT, 
        [BAÞLANGIÇ TARÝHÝ] = PRODORD.DATE_, 
        [BÝTÝÞ TARÝHÝ] = DISPLINE.OPDUEDATE, 
        [MÜÞTERÝ ADI] = CLCARD.DEFINITION_, 
        [MALZEME_KODU] = ITEMS.CODE, 
        [MLZKODU_URETICIKODU] = '',
        [MALZEME ADI] = ITEMS.NAME, 
        [SÝPARÝÞ NO] = ORFICHE.FICHENO, 
        [SÝPARÝÞ TARÝHÝ] = ISNULL(ORFICHE.DATE_, GETDATE()), 
        [TESLÝM TARÝHÝ] = ISNULL(ORFLINE.DUEDATE, GETDATE()), 
        [BELGE_NO] = ORFICHE.DOCODE, 
        VARYANT_KODU = ITEMS.PRODUCERCODE, 
        [URETICI_KODU] = VARIANT.CODE, 
        [XT_RENK] = XT050.RENK, 
        [XT_EN] = XT050.EN, 
        [XT_BOY] = XT050.BOY, 
        [XT_KALINLIK] = XT050.KALINLIK, 
        [XT_SERIGRAF] = XT050.SERIGRAF, 
        [XT_KALIPLIMI] = XT050.KALIPLIMI, 
        [XT_BOMBE] = XT050.BOMBE, 
        [XT_RODAJTIPI] = XT050.RODAJTIPI, 
        [XT_OYUKLU_OYUKSUZ] = XT050.OYUKLU_OYUKSUZ, 
        [XT_TAMPERLI_LAMINE] = XT050.TAMPERLI_LAMINE, 
        [XT_FIRINTIPI] = XT050.FIRINTIPI, 
        [XT_GABARI_KALIP_NO] = XT050.GABARI_KALIP_NO, 
        [XT_SAHIT_NUMUNE_NO] = XT050.SAHIT_NUMUNE_NO, 
        [XT_ERKEK_BASMA_KALIP_NO] = XT050.ERKEK_BASMA_KALIP_NO, 
        [XT_SERIGRAF_KALIP_NO] = XT050.SERIGRAF_KALIP_NO, 
        [XT_DISI_BASMA_KALIP_NO] = XT050.DISI_BASMA_KALIP_NO, 
        [XT_DELIKACIKLAMA] = (
            SELECT ISNULL(STRING_AGG(ACIKLAMA, ','), '') 
            FROM LG_XT052 
            WHERE ITEMREF = ITEMS.LOGICALREF 
              AND TIP = 'Delik'
        ), 
        [XT_RODAJACIKLAMA] = (
            SELECT ISNULL(STRING_AGG(ACIKLAMA, ','), '') 
            FROM LG_XT052 
            WHERE ITEMREF = ITEMS.LOGICALREF 
              AND TIP = 'Rodaj'
        )
    FROM LG_024_DISPLINE DISPLINE
    LEFT JOIN LG_024_PRODORD PRODORD ON DISPLINE.PRODORDREF = PRODORD.LOGICALREF
    INNER JOIN LG_024_POLINE POLINE ON POLINE.DISPLINEREF = DISPLINE.LOGICALREF AND POLINE.LINETYPE = 4
    INNER JOIN LG_024_ITEMS ITEMS ON PRODORD.ITEMREF = ITEMS.LOGICALREF
    LEFT JOIN LG_024_PEGGING PEGGING ON PEGGING.PEGREF = PRODORD.LOGICALREF 
      AND PEGGING.AMOUNT > (CASE WHEN PRODORD.FICHENO LIKE '%ek' THEN -1 ELSE 0 END) 
      AND ITEMS.LOGICALREF = PEGGING.ITEMREF
    LEFT JOIN LG_024_01_ORFICHE ORFICHE ON ORFICHE.LOGICALREF = PEGGING.PORDFICHEREF 
     -- AND ORFICHE.DATE_ BETWEEN DATEADD(dd, -190, PRODORD.DATE_) AND DATEADD(dd, 190, PRODORD.DATE_)
    LEFT JOIN LG_024_01_ORFLINE ORFLINE ON ORFICHE.LOGICALREF = ORFLINE.ORDFICHEREF
    LEFT JOIN LG_024_01_ORFLINE ORFLINE2 ON ORFICHE.LOGICALREF = ORFLINE2.ORDFICHEREF 
      AND ITEMS.LOGICALREF = ORFLINE2.STOCKREF
    LEFT JOIN LG_024_VARIANT VARIANT ON VARIANT.LOGICALREF = ORFLINE2.VARIANTREF
    LEFT JOIN LG_024_CLCARD CLCARD ON CLCARD.LOGICALREF = ORFICHE.CLIENTREF
    INNER JOIN LG_XT050_024 XT050 ON XT050.PARLOGREF = ITEMS.LOGICALREF
    WHERE PRODORD.LOGICALREF = 5351
 