 

select 'BordroPlus (2012 ve öncesi)' as Kaynak, [LOGICALREF]
      ,[NR]
      ,[NAME]
      ,[TITLE]
      ,[STREET]
      ,[ROAD]
      ,[DOORNR]
      ,[DISTRICT]
      ,[CITY]
      ,[COUNTRY]
      ,[ZIPCODE]
      ,[PHONE1]
      ,[PHONE2]
      ,[FAX]
      ,[TAXOFF]
      ,[TAXNR]
      ,[SECURNR]
      ,[DIRECT]
      ,[CPANAME]
      ,[CPASTREET]
      ,[CPAROAD]
      ,[CPADOORNR]
      ,[CPADISTRICT]
      ,[CPACITY]
      ,[CPAPHONE]
      ,[CPATAXOFF]
      ,[CPATAXNR]
      ,[CPACHAMBNR]
      ,[BEGMON]
      ,[BEGDAY]
      ,[USEREXT]
      ,[PERNR] from bordro_db.dbo.L_CAPIFIRM
UNION ALL
select 'BordroPlus (bornova)' as Kaynak,[LOGICALREF]
      ,[NR]
      ,[NAME]
      ,[TITLE]
      ,[STREET]
      ,[ROAD]
      ,[DOORNR]
      ,[DISTRICT]
      ,[CITY]
      ,[COUNTRY]
      ,[ZIPCODE]
      ,[PHONE1]
      ,[PHONE2]
      ,[FAX]
      ,[TAXOFF]
      ,[TAXNR]
      ,[SECURNR]
      ,[DIRECT]
      ,[CPANAME]
      ,[CPASTREET]
      ,[CPAROAD]
      ,[CPADOORNR]
      ,[CPADISTRICT]
      ,[CPACITY]
      ,[CPAPHONE]
      ,[CPATAXOFF]
      ,[CPATAXNR]
      ,[CPACHAMBNR]
      ,[BEGMON]
      ,[BEGDAY]
      ,[USEREXT]
      ,[PERNR] from bordro_db_test.dbo.L_CAPIFIRM
UNION ALL
select 'BordroPlus (2020 ve sonrasý)' as Kaynak,[LOGICALREF]
      ,[NR]
      ,[NAME]
      ,[TITLE]
      ,[STREET]
      ,[ROAD]
      ,[DOORNR]
      ,[DISTRICT]
      ,[CITY]
      ,[COUNTRY]
      ,[ZIPCODE]
      ,[PHONE1]
      ,[PHONE2]
      ,[FAX]
      ,[TAXOFF]
      ,[TAXNR]
      ,[SECURNR]
      ,[DIRECT]
      ,[CPANAME]
      ,[CPASTREET]
      ,[CPAROAD]
      ,[CPADOORNR]
      ,[CPADISTRICT]
      ,[CPACITY]
      ,[CPAPHONE]
      ,[CPATAXOFF]
      ,[CPATAXNR]
      ,[CPACHAMBNR]
      ,[BEGMON]
      ,[BEGDAY]
      ,[USEREXT]
      ,[PERNR] from BORDROPLUS_DB.dbo.L_CAPIFIRM
 