USE [TIGER2_DB]
GO
INSERT INTO LG_076_20_EBOOKDETAILDOC
SELECT  LG_076_20_EMFICHE.LOGICALREF AS [EMFICHEREF]
      ,99 [DOCUMENTTYPE]
      ,'' [EXPLAIN]
      ,'' [DOCUMENTNR]
      ,null [DOCUMENTDATE]
      ,'' [PAYTYPE]
      ,1 [UNDOCUMENTED]
      ,0 [NOPAYMENT]
      ,0 [EMFLINEREF]
      ,0 [MODULENR]
      ,0 [SOURCEFREF]
  FROM LG_076_20_EMFICHE where DATE_<='20200630'
  AND LOGICALREF  NOT IN (SELECT EMFICHEREF FROM LG_076_20_EBOOKDETAILDOC)
GO


