--alter view VW_GBelgesi as 
select 
 Id,
 GIB_DOC_NO,
 BELGE_NO,
 EIRSALIYE_UUID,
 SUBSTRING(Note3, 1 , CHARINDEX('*_**_*', Note3) -1) AS   CimentoTipiVeSinifi
,SUBSTRING(Note3, CHARINDEX('*_**_*', Note3) + 6, len(note3) - CHARINDEX('*_**_*', Note3)  ) AS   KimyasalKatkiTipi
 
 
,REVERSE(PARSENAME(REPLACE(REVERSE(Note8), '*_*', '.'), 2)) AS GelisimOrani
,REVERSE(PARSENAME(REPLACE(REVERSE(Note8), '*_*', '.'), 3)) AS SuCimentoOrani
 
,SUBSTRING(Note10, 1 , CHARINDEX('*_*', Note10) -1) AS   UretimBitisTarihi
,SUBSTRING(Note11, 1 , CHARINDEX('*_*', Note11) -1) AS   SantralOperatoru
,SUBSTRING(Note21, 1 , CHARINDEX('*_*', Note21) -1) AS   GKoduBilgisi
,SUBSTRING(Note22, 1 , CHARINDEX('*_*', Note22) -1) AS   CariUnvan
,SUBSTRING(Note23, 1 , CHARINDEX('*_*', Note23) -1) AS   CariAdres
,SUBSTRING(Note24, 1 , CHARINDEX('*_*', Note24) -1) AS   Baslik1
,SUBSTRING(Note25, 1 , CHARINDEX('*_*', Note25) -1) AS   Baslik1Adres
,SUBSTRING(Note26, 1 , CHARINDEX('*_*', Note26) -1) AS   GKoduBilgisi2
,SUBSTRING(Note27, 1 , CHARINDEX('*_*', Note27) -1) AS   TsKodu
,SUBSTRING(Note28, 1 , CHARINDEX('*_*', Note28) -1) AS   DayanimSinifi
,SUBSTRING(Note29, 1 , CHARINDEX('*_*', Note29) -1) AS   KivamSinifi
,SUBSTRING(Note30, 1 , CHARINDEX('*_*', Note30) -1) AS   CevreselEtkiSinifi
,SUBSTRING(Note31, 1 , CHARINDEX('*_*', Note31) -1) AS   Dmax
,SUBSTRING(Note32, 1 , CHARINDEX('*_*', Note32) -1) AS   KlorurIcerigi
, SUBSTRING(Note33, 1 , CHARINDEX('*_*', Note33) -1) AS   YogunlukSinifi
, SUBSTRING(Note34, 1 , CHARINDEX('*_*', Note34) -1) AS   PompaciSinifi
, SUBSTRING(Note35, 1 , CHARINDEX('*_*', Note35) -1) AS   PompaciPlaka
  ,NOT1 from (
select NOT1  , 
 Id,
 GIB_DOC_NO,
 BELGE_NO,
 EIRSALIYE_UUID 
, SUBSTRING(NOT1,CHARINDEX('[1]', NOT1) + 3,CHARINDEX('[2]', NOT1) - 4 ) AS Note1
, SUBSTRING(NOT1,CHARINDEX('[2]', NOT1)  ,CHARINDEX('[3]', NOT1) -  CHARINDEX('[2]', NOT1) - 3 ) AS Note2
, SUBSTRING(NOT1,CHARINDEX('[3]', NOT1)  + 3 ,CHARINDEX('[4]', NOT1) -  CHARINDEX('[3]', NOT1) - 3  ) AS Note3
, SUBSTRING(NOT1,CHARINDEX('[4]', NOT1)  + 3 ,CHARINDEX('[5]', NOT1) -  CHARINDEX('[4]', NOT1) - 3  ) AS Note4
, SUBSTRING(NOT1,CHARINDEX('[5]', NOT1)  + 3 ,CHARINDEX('[6]', NOT1) -  CHARINDEX('[5]', NOT1) - 3  ) AS Note5
, SUBSTRING(NOT1,CHARINDEX('[6]', NOT1)  + 3 ,CHARINDEX('[7]', NOT1) -  CHARINDEX('[6]', NOT1) - 3  ) AS Note6
, SUBSTRING(NOT1,CHARINDEX('[7]', NOT1)  + 3 ,CHARINDEX('[8]', NOT1) -  CHARINDEX('[7]', NOT1) - 3  ) AS Note7
, SUBSTRING(NOT1,CHARINDEX('[8]', NOT1)  + 3 ,CHARINDEX('[9]', NOT1) -  CHARINDEX('[8]', NOT1) - 3  ) AS Note8
, SUBSTRING(NOT1,CHARINDEX('[9]', NOT1)  + 3 ,CHARINDEX('[10]', NOT1) -  CHARINDEX('[9]', NOT1) - 3  ) AS Note9
, SUBSTRING(NOT1,CHARINDEX('[10]', NOT1)  + 4 ,CHARINDEX('[11]', NOT1) -  CHARINDEX('[10]', NOT1) - 4  ) AS Note10
, SUBSTRING(NOT1,CHARINDEX('[11]', NOT1)  + 4 ,CHARINDEX('[12]', NOT1) -  CHARINDEX('[11]', NOT1) - 4  ) AS Note11
, SUBSTRING(NOT1,CHARINDEX('[12]', NOT1)  + 4 ,CHARINDEX('[13]', NOT1) -  CHARINDEX('[12]', NOT1) - 4  ) AS Note12
, SUBSTRING(NOT1,CHARINDEX('[13]', NOT1)  + 4 ,CHARINDEX('[14]', NOT1) -  CHARINDEX('[13]', NOT1) - 4  ) AS Note13
, SUBSTRING(NOT1,CHARINDEX('[14]', NOT1)  + 4 ,CHARINDEX('[15]', NOT1) -  CHARINDEX('[14]', NOT1) - 4  ) AS Note14
, SUBSTRING(NOT1,CHARINDEX('[15]', NOT1)  + 4 ,CHARINDEX('[16]', NOT1) -  CHARINDEX('[15]', NOT1) - 4  ) AS Note15
, SUBSTRING(NOT1,CHARINDEX('[16]', NOT1)  + 4 ,CHARINDEX('[17]', NOT1) -  CHARINDEX('[16]', NOT1) - 4  ) AS Note16
, SUBSTRING(NOT1,CHARINDEX('[17]', NOT1)  + 4 ,CHARINDEX('[18]', NOT1) -  CHARINDEX('[17]', NOT1) - 4  ) AS Note17
, SUBSTRING(NOT1,CHARINDEX('[18]', NOT1)  + 4 ,CHARINDEX('[19]', NOT1) -  CHARINDEX('[18]', NOT1) - 4  ) AS Note18
, SUBSTRING(NOT1,CHARINDEX('[19]', NOT1)  + 4 ,CHARINDEX('[20]', NOT1) -  CHARINDEX('[19]', NOT1) - 4  ) AS Note19
, SUBSTRING(NOT1,CHARINDEX('[20]', NOT1)  + 4 ,CHARINDEX('[21]', NOT1) -  CHARINDEX('[20]', NOT1) - 4  ) AS Note20
, SUBSTRING(NOT1,CHARINDEX('[21]', NOT1)  + 4 ,CHARINDEX('[22]', NOT1) -  CHARINDEX('[21]', NOT1) - 4  ) AS Note21
, SUBSTRING(NOT1,CHARINDEX('[22]', NOT1)  + 4 ,CHARINDEX('[23]', NOT1) -  CHARINDEX('[22]', NOT1) - 4  ) AS Note22
, SUBSTRING(NOT1,CHARINDEX('[23]', NOT1)  + 4 ,CHARINDEX('[24]', NOT1) -  CHARINDEX('[23]', NOT1) - 4  ) AS Note23
, SUBSTRING(NOT1,CHARINDEX('[24]', NOT1)  + 4 ,CHARINDEX('[25]', NOT1) -  CHARINDEX('[24]', NOT1) - 4  ) AS Note24
, SUBSTRING(NOT1,CHARINDEX('[25]', NOT1)  + 4 ,CHARINDEX('[26]', NOT1) -  CHARINDEX('[25]', NOT1) - 4  ) AS Note25
, SUBSTRING(NOT1,CHARINDEX('[26]', NOT1)  + 4 ,CHARINDEX('[27]', NOT1) -  CHARINDEX('[26]', NOT1) - 4  ) AS Note26
, SUBSTRING(NOT1,CHARINDEX('[27]', NOT1)  + 4 ,CHARINDEX('[28]', NOT1) -  CHARINDEX('[27]', NOT1) - 4  ) AS Note27
, SUBSTRING(NOT1,CHARINDEX('[28]', NOT1)  + 4 ,CHARINDEX('[29]', NOT1) -  CHARINDEX('[28]', NOT1) - 4  ) AS Note28
, SUBSTRING(NOT1,CHARINDEX('[29]', NOT1)  + 4 ,CHARINDEX('[30]', NOT1) -  CHARINDEX('[29]', NOT1) - 4  ) AS Note29
, SUBSTRING(NOT1,CHARINDEX('[30]', NOT1)  + 4 ,CHARINDEX('[31]', NOT1) -  CHARINDEX('[30]', NOT1) - 4  ) AS Note30
, SUBSTRING(NOT1,CHARINDEX('[31]', NOT1)  + 4 ,CHARINDEX('[32]', NOT1) -  CHARINDEX('[31]', NOT1) - 4  ) AS Note31
, SUBSTRING(NOT1,CHARINDEX('[32]', NOT1)  + 4 ,CHARINDEX('[33]', NOT1) -  CHARINDEX('[32]', NOT1) - 4  ) AS Note32
, SUBSTRING(NOT1,CHARINDEX('[33]', NOT1)  + 4 ,CHARINDEX('[34]', NOT1) -  CHARINDEX('[33]', NOT1) - 4  ) AS Note33
, SUBSTRING(NOT1,CHARINDEX('[34]', NOT1)  + 4 ,CHARINDEX('[35]', NOT1) -  CHARINDEX('[34]', NOT1) - 4  ) AS Note34 
, SUBSTRING(NOT1,CHARINDEX('[35]', NOT1)  + 4 ,CHARINDEX('[36]', NOT1) -  CHARINDEX('[35]', NOT1) - 4  ) AS Note35 
--, SUBSTRING(NOT1,CHARINDEX('[35]', NOT1)  + 4 ,CHARINDEX('[37]', NOT1) -  CHARINDEX('[36]', NOT1) - 4  ) AS Note36
 
  FROM [dbo].[GRS_EDESPATCHHEADERs_TBL] ) tbl
