
SELECT ASSIGN.PERREF,PERSONS.NAME + ' ' + PERSONS.SURNAME AS AdiSoyadi, 
(SELECT TOP 1 ORGUNITS.DESCRIPTION FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.FIRMREF AND ORGUNITS.LEVELNR=0) AS KurumAdi,
(SELECT TOP 1 ORGUNITS.CODE FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.LOCREF AND ORGUNITS.LEVELNR=1) AS IsyeriKodu,
(SELECT TOP 1 ORGUNITS.DESCRIPTION FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.LOCREF AND ORGUNITS.LEVELNR=1) AS IsyeriAdi,
(SELECT TOP 1 ORGUNITS.SOCSECNR FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.LOCREF AND ORGUNITS.LEVELNR=1) AS IsyeriSicilNo,
ASSIGN.BEGDATE,ASSIGN.ENDDATE
FROM H_001_ASSIGNS ASSIGN
LEFT JOIN H_001_PERSONS PERSONS ON  ASSIGN.PERREF = PERSONS.LOGICALREF
WHERE PERSONS.FIRMREF <> 67 AND PERSONS.NAME = 'SERKAN' AND PERSONS.SURNAME = 'sönmez' --AND ENDDATE IS NOT NULL
--group by FIRMREF,LOCREF
ORDER BY BEGDATE




/*
KANUNÝ DEÐÝÞÝKLÝKLERE GÖRE KONTROL
SELECT ASSIGN.PERREF,PERSONS.NAME + ' ' + PERSONS.SURNAME AS AdiSoyadi, 
(SELECT TOP 1 ORGUNITS.DESCRIPTION FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.FIRMREF AND ORGUNITS.LEVELNR=0) AS KurumAdi,
(SELECT TOP 1 ORGUNITS.CODE FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.LOCREF AND ORGUNITS.LEVELNR=1) AS IsyeriKodu,
(SELECT TOP 1 ORGUNITS.DESCRIPTION FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.LOCREF AND ORGUNITS.LEVELNR=1) AS IsyeriAdi,
(SELECT TOP 1 ORGUNITS.SOCSECNR FROM S_ORGUNITS ORGUNITS WHERE ORGUNITS.LOGICALREF=ASSIGN.LOCREF AND ORGUNITS.LEVELNR=1) AS IsyeriSicilNo,
ASSIGN.BEGDATE,ASSIGN.ENDDATE
FROM H_001_LAWCHGS ASSIGN
LEFT JOIN H_001_PERSONS PERSONS ON  ASSIGN.PERREF = PERSONS.LOGICALREF
WHERE PERSONS.FIRMREF <> 67 AND PERSONS.NAME = 'SERKAN' AND PERSONS.SURNAME = 'sönmez' --AND ENDDATE IS NOT NULL
--group by FIRMREF,LOCREF
ORDER BY BEGDATE
*/