SELECT 01 AS PERIOD, 
CLASS.ACTIVE AS CLASS_ACTIVE, 
(CASE CLASS.ACTIVE WHEN 0 THEN '(*%:13046,0)Kullanýmda..........' 
WHEN 1 THEN '(*%:13046,1)Kullaným Dýþý..........' ELSE '' END) AS CLASS_ACTIVE_ADI, 
CLASS.CARDTYPE AS CLASS_CARDTYPE, 
(CASE CLASS.CARDTYPE WHEN 20 THEN '(*%:1009,20)(MS) Genel Malzeme Sýnýfý..........' 
WHEN 21 THEN '(*%:1009,21)(MT) Tablolu Malzeme Sýnýfý..........' ELSE '' END) AS CLASS_CARDTYPE_TIPI, 
CLASS.CODE AS CLASS_CODE, CLASS.NAME AS CLASS_NAME, CLASS.STGRPCODE AS CLASS_STGRPCODE, 
CLASS.PRODUCERCODE AS CLASS_PRODUCERCODE, CLASS.SPECODE AS CLASS_SPECODE, CLASS.CYPHCODE AS CLASS_CYPHCODE, 
ITEMS.ACTIVE AS ITEMS_ACTIVE, 
(CASE ITEMS.ACTIVE WHEN 0 THEN '(*%:13046,0)Kullanýmda..........' 
WHEN 1 THEN '(*%:13046,1)Kullaným Dýþý..........' ELSE '' END) AS ITEMS_ACTIVE_ADI, 
ITEMS.CARDTYPE AS ITEMS_CARDTYPE, 
(CASE ITEMS.CARDTYPE WHEN 1 THEN '(*%:1009,1)(TM) Ticari Mal..........' 
WHEN 2 THEN '(*%:1009,2)(KK) Karma Koli..........' 
WHEN 3 THEN '(*%:1009,3)(DM) Depozitolu Mal..........' 
WHEN 4 THEN '(*%:1009,4)(SK) Sabit Kýymet..........' 
WHEN 10 THEN '(*%:1009,10)(HM) Hammadde..........' 
WHEN 11 THEN '(*%:1009,11)(YM) Yarý Mamul..........' 
WHEN 12 THEN '(*%:1009,12)(MM) Mamul..........' 
WHEN 13 THEN '(*%:1009,13)(TK) Tüketim Malý..........' 
WHEN 20 THEN '(*%:1009,20)(MS) Genel Malzeme Sýnýfý..........' 
WHEN 21 THEN '(*%:1009,21)(MT) Tablolu Malzeme Sýnýfý..........' ELSE '' END) AS ITEMS_MALZEME_TIPI, 
ITEMS.CODE AS ITEMS_CODE, ITEMS.NAME AS ITEMS_NAME, ITEMS.STGRPCODE AS ITEMS_STGRPCODE, ITEMS.PRODUCERCODE AS ITEMS_PRODUCERCODE, 
ITEMS.SPECODE AS ITEMS_SPECODE, ITEMS.CYPHCODE AS ITEMS_CYPHCODE, ITEMS.TRACKTYPE AS ITEMS_TRACKTYPE, 
(CASE ITEMS.TRACKTYPE WHEN 0 THEN '(*%:18233,8)Ýzleme yapýlmayacak..........' 
WHEN 1 THEN '(*%:18233,8)Lot numarasý..........' 
WHEN 2 THEN '(*%:18233,8)Seri numarasý..........' 
WHEN 3 THEN '(*%:18233,8)Seri grubu..........' ELSE '' END) AS ITEMS_IZLEME_TURU, 
UNITSETF.CODE AS UNITSETF_CODE, UNITSETF.NAME AS UNITSETF_NAME, 
UNITSETF.SPECODE AS UNITSETF_SPECODE, UNITSETF.CYPHCODE AS UNITSETF_CYPHCODE, UNITSETL.CODE AS UNITSETL_CODE, 
UNITSETL.NAME AS UNITSETL_NAME, 
CASE WHEN ITMUNITA_2.CONVFACT2>0 THEN ITMUNITA_2.CONVFACT2/ITMUNITA_2.CONVFACT1 ELSE 0 END AS ITMUNITA_2_KATSAYI, 
UNITSETL_2.CODE AS UNITSETL_2_CODE, UNITSETL_2.NAME AS UNITSETL_2_NAME, 
CASE WHEN ITMUNITA_3.CONVFACT2>0 THEN ITMUNITA_3.CONVFACT2/ITMUNITA_3.CONVFACT1 ELSE 0 END AS ITMUNITA_3_KATSAYI, 
UNITSETL_3.CODE AS UNITSETL_3_CODE, UNITSETL_3.NAME AS UNITSETL_3_NAME, ITMUNITA_1.LINENR AS ITMUNITA_LINENR, ITMUNITA_1.BARCODE AS ITMUNITA_BARCODE, 
ITMUNITA_1.WIDTH AS ITMUNITA_WIDTH, UNITSETL1.CODE AS WIDTH_CODE, ITMUNITA_1.LENGTH AS ITMUNITA_LENGTH,
UNITSETL2.CODE AS LENGTH_CODE, ITMUNITA_1.HEIGHT AS ITMUNITA_HEIGHT, UNITSETL3.CODE AS HEIGHT_CODE, ITMUNITA_1.AREA AS ITMUNITA_AREA, 
UNITSETL4.CODE AS AREA_CODE, ITMUNITA_1.VOLUME_ AS ITMUNITA_VOLUME_, UNITSETL5.CODE AS VOLUME_CODE, ITMUNITA_1.GROSSVOLUME AS ITMUNITA_GROSSVOLUME, 
UNITSETL6.CODE AS GROSSVOLUME_CODE, ITMUNITA_1.WEIGHT AS ITMUNITA_WEIGHT, UNITSETL7.CODE AS WEIGHT_CODE, ITMUNITA_1.GROSSWEIGHT AS ITMUNITA_GROSSWEIGHT, 
UNITSETL8.CODE AS GROSSWEIGHT_CODE, ITMUNITA_1.CONVFACT1 AS ITMUNITA_CONVFACT1, ITMUNITA_1.CONVFACT2 AS ITMUNITA_CONVFACT2, 
ORFLINE.LOGICALREF AS ORFLINE_LOGICALREF, ORFLINE.LINETYPE AS ORFLINE_LINETYPE, 
(CASE ORFLINE.LINETYPE 
WHEN 0 THEN '(*%:13063,1)Malzeme..........' 
WHEN 1 THEN '(*%:13063,2)Promosyon..........' 
WHEN 2 THEN '(*%:13063,3)Ýndirim..........' 
WHEN 3 THEN '(*%:13063,4)Masraf..........' 
WHEN 4 THEN '(*%:13063,5)Hizmet..........' 
WHEN 5 THEN '(*%:13063,6)Depozito..........' 
WHEN 6 THEN '(*%:13063,7)Karma Koli..........' 
WHEN 7 THEN '(*%:13063,8)Karma Koli Satýrý..........' 
WHEN 8 THEN '(*%:13063,9)Sabit Kýymet..........' 
WHEN 9 THEN '(*%:13063,10)Ek Malzeme..........' 
WHEN 10 THEN '(*%:13063,11)Malzeme Sýnýfý..........' 
WHEN 11 THEN '(*%:13063,12)Fason..........' ELSE '' END) AS ORFLINE_SATIR_TURU, 
ORFLINE.PREVLINEREF AS ORFLINE_PREVLINEREF, ORFLINE.PREVLINENO AS ORFLINE_PREVLINENO, 
ORFLINE.TRCODE AS ORFLINE_TRCODE, ORFLINE.DATE_ AS ORFLINE_DATE_, DATEPART(YYYY,ORFLINE.DATE_) AS ORFLINE_YEAR, 
CASE WHEN DATEPART(qq,ORFLINE.DATE_) IN (1,2) THEN 1 ELSE 2 END AS ORFLINE_HALF, DATEPART(qq,ORFLINE.DATE_) AS ORFLINE_QUARTER, 
DATEPART(MM,ORFLINE.DATE_) AS ORFLINE_MONTH, DATEPART(wk,ORFLINE.DATE_) AS ORFLINE_WEEK, DATEPART(dd,ORFLINE.DATE_) AS ORFLINE_DAY, 
ORFLINE.TIME_ AS ORFLINE_TIME_, ORFLINE.GLOBTRANS AS ORFLINE_GLOBTRANS, 
ORFLINE.SOURCEINDEX AS ORFLINE_SOURCEINDEX, ORFLINE.SOURCECOSTGRP AS ORFLINE_SOURCECOSTGRP, 
ORFLINE.ORDFICHEREF AS ORFLINE_ORDFICHEREF, ORFLINE.LINENO_ AS ORFLINE_LINENO_, 
ORFLINE.CLIENTREF AS ORFLINE_CLIENTREF, ORFLINE.SPECODE AS ORFLINE_SPECODE, ORFLINE.DELVRYCODE AS ORFLINE_DELVRYCODE, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN (ORFLINE.AMOUNT*(CASE ORFLINE.UINFO2 WHEN 0 THEN 1 ELSE ORFLINE.UINFO2/ORFLINE.UINFO1 END)) ELSE 0 END))) AS ORFLINE_INPUT_AMOUNT, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE (ORFLINE.AMOUNT*(CASE ORFLINE.UINFO2 WHEN 0 THEN 1 ELSE ORFLINE.UINFO2/ORFLINE.UINFO1 END)) END))) AS ORFLINE_OUTPUT_AMOUNT, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.PRICE ELSE 0 END))) AS ORFLINE_INPUT_PRICE, (((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.PRICE END))) AS ORFLINE_OUTPUT_PRICE, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.TOTAL ELSE 0 END))) AS ORFLINE_INPUT_TOTAL, (((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.TOTAL END))) AS ORFLINE_OUTPUT_TOTAL, 
ORFLINE.PRCURR AS ORFLINE_PRCURR, (((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.PRPRICE ELSE 0 END))) AS ORFLINE_INPUT_PRPRICE, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.PRPRICE END))) AS ORFLINE_OUTPUT_PRPRICE, 
ORFLINE.TRCURR AS ORFLINE_TRCURR, ORFLINE.TRRATE AS ORFLINE_TRRATE, ORFLINE.REPORTRATE AS ORFLINE_REPORTRATE, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.DISTCOST ELSE 0 END))) AS ORFLINE_INPUT_DISTCOST, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.DISTCOST END))) AS ORFLINE_OUTPUT_DISTCOST, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.DISTDISC ELSE 0 END))) AS ORFLINE_INPUT_DISTDISC, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.DISTDISC END))) AS ORFLINE_OUTPUT_DISTDISC, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.DISTEXP ELSE 0 END))) AS ORFLINE_INPUT_DISTEXP, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.DISTEXP END))) AS ORFLINE_OUTPUT_DISTEXP, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.DISTPROM ELSE 0 END))) AS ORFLINE_INPUT_DISTPROM, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.DISTPROM END))) AS ORFLINE_OUTPUT_DISTPROM, ORFLINE.DISCPER AS ORFLINE_DISCPER, 
ORFLINE.LINEEXP AS ORFLINE_LINEEXP, ORFLINE.UOMREF AS ORFLINE_UOMREF, ORFLINE.USREF AS ORFLINE_USREF, ORFLINE.UINFO1 AS ORFLINE_UINFO1, 
ORFLINE.UINFO2 AS ORFLINE_UINFO2, ORFLINE.VATINC AS ORFLINE_VATINC, ORFLINE.VAT AS ORFLINE_VAT, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.VATAMNT ELSE 0 END))) AS ORFLINE_INPUT_VATAMNT, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.VATAMNT END))) AS ORFLINE_OUTPUT_VATAMNT, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.VATMATRAH ELSE 0 END))) AS ORFLINE_INPUT_VATMATRAH, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.VATMATRAH END))) AS ORFLINE_OUTPUT_VATMATRAH, ORFLINE.CANCELLED AS ORFLINE_CANCELLED, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN ORFLINE.LINENET ELSE 0 END))) AS ORFLINE_INPUT_LINENET, 
(((CASE WHEN ORFLINE.TRCODE IN (2) THEN 0 ELSE ORFLINE.LINENET END))) AS ORFLINE_OUTPUT_LINENET, 
ORFICHE.TRCODE AS ORFICHE_TRCODE, 
(CASE ORFICHE.TRCODE WHEN 2 THEN '(*%:1012,2002)Satýnalma Sipariþleri..........' 
WHEN 1 THEN '(*%:1012,5001)Satýþ Sipariþleri..........' ELSE '' END) AS ORFICHE_TRCODE_ADI, ORFICHE.FICHENO AS ORFICHE_FICHENO, 
ORFICHE.DATE_ AS ORFICHE_DATE_, ORFICHE.TIME_ AS ORFICHE_TIME_, ORFICHE.DOCODE AS ORFICHE_DOCODE, ORFICHE.SPECODE AS ORFICHE_SPECODE, 
ORFICHE.CYPHCODE AS ORFICHE_CYPHCODE, ORFICHE.STATUS AS ORFICHE_STATUS, 
(CASE ORFICHE.STATUS 
WHEN 0 THEN '(*%:3137,1)Öneri..........' 
WHEN 2 THEN '(*%:3137,2)Sevkedilemez..........' 
WHEN 4 THEN '(*%:3137,4)Sevkedilebilir..........' ELSE '' END) AS ORFICHE_STATUS_ADI, 
ORFICHE.CLIENTREF AS FORFICHE_CLIENTREF, ORFICHE.RECVREF AS ORFICHE_RECVREF, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.ADDDISCOUNTS ELSE 0 END))) AS ORFICHE_INPUT_ADDDISCOUNTS, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.ADDDISCOUNTS END))) AS ORFICHE_OUTPUT_ADDDISCOUNTS, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.TOTALDISCOUNTS ELSE 0 END))) AS ORFICHE_INPUT_TOTALDISCOUNTS, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.TOTALDISCOUNTS END))) AS ORFICHE_OUTPUT_TOTALDISCOUNTS, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.TOTALDISCOUNTED ELSE 0 END))) AS ORFICHE_INPUT_TOTALDISCOUNTED, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.TOTALDISCOUNTED END))) AS ORFICHE_OUTPUT_TOTALDISCOUNTED, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.ADDEXPENSES ELSE 0 END))) AS ORFICHE_INPUT_ADDEXPENSES, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.ADDEXPENSES END))) AS ORFICHE_OUTPUT_ADDEXPENSES, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.TOTALEXPENSES ELSE 0 END))) AS ORFICHE_INPUT_TOTALEXPENSES, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.TOTALEXPENSES END))) AS ORFICHE_OUTPUT_TOTALEXPENSES, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.TOTALPROMOTIONS ELSE 0 END))) AS ORFICHE_INPUT_TOTALPROMOTIONS, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.TOTALPROMOTIONS END))) AS ORFICHE_OUTPUT_TOTALPROMOTIONS, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.TOTALVAT ELSE 0 END))) AS ORFICHE_INPUT_TOTALVAT, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.TOTALVAT END))) AS ORFICHE_OUTPUT_TOTALVAT, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.GROSSTOTAL ELSE 0 END))) AS ORFICHE_INPUT_GROSSTOTAL, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.GROSSTOTAL END))) AS ORFICHE_OUTPUT_GROSSTOTAL, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.NETTOTAL ELSE 0 END))) AS ORFICHE_INPUT_NETTOTAL, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.NETTOTAL END))) AS ORFICHE_OUTPUT_NETTOTAL, ORFICHE.REPORTRATE AS ORFICHE_REPORTRATE, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.REPORTNET ELSE 0 END))) AS ORFICHE_INPUT_REPORTNET, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.REPORTNET END))) AS ORFICHE_OUTPUT_REPORTNET, 
ORFICHE.TRCURR AS ORFICHE_TRCURR, ORFICHE.TRRATE AS ORFICHE_TRRATE, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN ORFICHE.TRNET ELSE 0 END))) AS ORFICHE_INPUT_TRNET, 
(((CASE WHEN ORFLINE.TRCODE IN (1,2,3) THEN 0 ELSE ORFICHE.TRNET END))) AS ORFICHE_OUTPUT_TRNET, ORFICHE.CANCELLED AS ORFICHE_CANCELLED, 
(CASE ORFICHE.CANCELLED WHEN 0 THEN '(*%:9504,0)Ýptal Edilmemiþ Fiþler..........' 
WHEN 1 THEN '(*%:9504,1)Ýptal Edilmiþ Fiþler..........' ELSE '' END) AS ORFICHE_CANCELLED_AÇIKLAMA, SHIPINFO.CODE AS SHIPINFO_CODE, 
SHIPINFO.NAME AS SHIPINFO_NAME, SHIPINFO.SPECODE AS SHIPINFO_SPECODE, SHIPINFO.CYPHCODE AS SHIPINFO_CYPHCODE, CAPIWHOUSE.NR AS CAPIWHOUSE_NR, 
CAPIWHOUSE.NAME AS CAPIWHOUSE_NAME, CAPIDIV.NR AS CAPIDIV_NR, CAPIDIV.NAME AS CAPIDIV_NAME, CAPIDEPT.NR AS CAPIDEPT_NR, 
CAPIDEPT.NAME AS CAPIDEPT_NAME, CLCARD.CODE AS CLCARD_CODE, CLCARD.DEFINITION_ AS CLCARD_DEFINITION_, CLCARD.SPECODE AS CLCARD_SPECODE, 
CLCARD.TAXOFFICE AS CLCARD_TAXOFFICE, CLCARD.TAXNR AS CLCARD_TAXNR, CLCARD.CYPHCODE AS CLCARD_CYPHCODE, CLCARD.INCHARGE AS CLCARD_INCHARGE, 
CLCARD.ACTIVE AS CLCARD_ACTIVE, 
(CASE CLCARD.ACTIVE WHEN 0 THEN '(*%:13046,0)Kullanýmda..........' WHEN 1 THEN '(*%:13046,1)Kullaným Dýþý..........' ELSE '' END) AS CLCARD_ACTIVE_ADI,
CLCARD.CITY AS CLCARD_CITY, CLCARD.TRADINGGRP AS CLCARD_TRADINGGRP, CLCARD.CARDTYPE AS CLCARD_CARDTYPE, (CASE CLCARD.CARDTYPE 
WHEN 1 THEN '(*%:5003,1)(AL) Alýcý..........' WHEN 2 THEN '(*%:5003,2)(SA) Satýcý..........' WHEN 3 THEN '(*%:5003,3)(AS) Alýcý + Satýcý..........' 
WHEN 4 THEN '(*%:5003,1)(GS) Grup Þirketi..........' ELSE '' END) AS CLCARD_CARDTYPE_ADI, PAYPLANS.CODE AS PAYPLANS_CODE, PAYPLANS.DEFINITION_ AS PAYPLANS_DEFINITION_, 
PAYPLANS.SPECODE AS PAYPLANS_SPECODE, PAYPLANS.CYPHCODE AS PAYPLANS_CYPHCODE, PROJECT.CODE AS PROJECT_CODE, PROJECT.NAME AS PROJECT_NAME, 
EMCENTER.CODE AS EMCENTER_CODE, EMCENTER.DEFINITION_ AS EMCENTER_DEFINITION_, SLSMAN.CODE AS SLSMAN_CODE,
SLSMAN.DEFINITION_ AS SLSMAN_DEFINITION_ FROM LG_002_ITEMS ITEMS (NOLOCK) 
LEFT OUTER JOIN LG_002_ITMCLSAS ITC (NOLOCK) ON ITEMS.LOGICALREF=ITC.CHILDREF AND ITC.UPLEVEL=0 
LEFT OUTER JOIN LG_002_ITEMS CLASS (NOLOCK) ON ITC.PARENTREF=CLASS.LOGICALREF
LEFT OUTER JOIN LG_002_ITMUNITA ITMUNITA_1 (NOLOCK) ON ITEMS.LOGICALREF=ITMUNITA_1.ITEMREF AND ITMUNITA_1.LINENR=1 
LEFT OUTER JOIN LG_002_ITMUNITA ITMUNITA_2 (NOLOCK) ON ITEMS.LOGICALREF=ITMUNITA_2.ITEMREF AND ITMUNITA_2.LINENR=2 
LEFT OUTER JOIN LG_002_ITMUNITA ITMUNITA_3 (NOLOCK) ON ITEMS.LOGICALREF=ITMUNITA_3.ITEMREF AND ITMUNITA_3.LINENR=3 
LEFT OUTER JOIN LG_002_UNITSETF UNITSETF (NOLOCK) ON ITEMS.UNITSETREF=UNITSETF.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL (NOLOCK) ON ITMUNITA_1.UNITLINEREF=UNITSETL.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL_2 (NOLOCK) ON ITMUNITA_2.UNITLINEREF=UNITSETL_2.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL_3 (NOLOCK) ON ITMUNITA_3.UNITLINEREF=UNITSETL_3.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL1 (NOLOCK) ON ITMUNITA_1.WIDTHREF=UNITSETL1.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL2 (NOLOCK) ON ITMUNITA_1.LENGTHREF=UNITSETL2.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL3 (NOLOCK) ON ITMUNITA_1.HEIGHTREF=UNITSETL3.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL4 (NOLOCK) ON ITMUNITA_1.AREAREF=UNITSETL4.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL5 (NOLOCK) ON ITMUNITA_1.VOLUMEREF=UNITSETL5.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL6 (NOLOCK) ON ITMUNITA_1.GROSSVOLREF=UNITSETL6.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL7 (NOLOCK) ON ITMUNITA_1.WEIGHTREF=UNITSETL7.LOGICALREF 
LEFT OUTER JOIN LG_002_UNITSETL UNITSETL8 (NOLOCK) ON ITMUNITA_1.GROSSWGHTREF=UNITSETL8.LOGICALREF 
LEFT OUTER JOIN LG_002_01_ORFLINE ORFLINE (NOLOCK) ON ITEMS.LOGICALREF=ORFLINE.STOCKREF AND ORFLINE.LINETYPE NOT IN (2,3,4) 
LEFT OUTER JOIN LG_002_01_ORFICHE ORFICHE (NOLOCK) ON ORFLINE.ORDFICHEREF=ORFICHE.LOGICALREF 
LEFT OUTER JOIN "TIGER3"..LG_SLSMAN SLSMAN (NOLOCK) ON ORFICHE.SALESMANREF=SLSMAN.LOGICALREF AND SLSMAN.FIRMNR=002 
LEFT OUTER JOIN LG_002_SHIPINFO SHIPINFO (NOLOCK) ON ORFICHE.SHIPINFOREF=SHIPINFO.LOGICALREF
LEFT OUTER JOIN "TIGER3"..L_CAPIWHOUSE CAPIWHOUSE WITH(NOLOCK) ON ORFICHE.SOURCEINDEX=CAPIWHOUSE.NR AND CAPIWHOUSE.FIRMNR=002 
LEFT OUTER JOIN "TIGER3"..L_CAPIDIV CAPIDIV (NOLOCK) ON ORFICHE.BRANCH=CAPIDIV.NR AND CAPIDIV.FIRMNR=002 
LEFT OUTER JOIN "TIGER3"..L_CAPIDEPT CAPIDEPT (NOLOCK) ON ORFICHE.DEPARTMENT=CAPIDEPT.NR AND CAPIDEPT.FIRMNR=002 
LEFT OUTER JOIN LG_002_CLCARD CLCARD (NOLOCK) ON ORFICHE.CLIENTREF=CLCARD.LOGICALREF 
LEFT OUTER JOIN LG_002_PAYPLANS PAYPLANS (NOLOCK) ON ORFICHE.PAYDEFREF = PAYPLANS.LOGICALREF 
LEFT OUTER JOIN LG_002_EMCENTER EMCENTER (NOLOCK) ON ORFICHE.CENTERREF = EMCENTER.LOGICALREF 
LEFT OUTER JOIN LG_002_PROJECT PROJECT (NOLOCK) ON ORFICHE.PROJECTREF = PROJECT.LOGICALREF WHERE ITEMS.CARDTYPE<>22