CREATE view VW_BordoPlusAgiParametreleri as 
SELECT top 10000
TYPD.LREF, TYPD.TYP, TYPD.NR, TYPD.STATIC, TYPD.EXP, TYPD.DESC_, TYPD.NETFLAG
 FROM 
LH_001_TYPEDEF TYPD WITH(NOLOCK) 
 WHERE 
(TYPD.TYP = -43)

ORDER BY 
TYPD.NR
