 
 ALTER view VW_MUHTASARLISTESI as 
SELECT
    [LH_001_EDOCMLIST].[LREF], [LH_001_EDOCMLIST].[FIRMNR]
       ,[LH_001_EDOCMLIST].[LOCNR]
	  ,L_CAPIFIRM.NAME AS FIRMNAME
	  ,L_CAPIDIV.NAME AS DIVNAME
 ,CASE WHEN [DOCREASON]='Asýl' then 'A'
 else 'E' end as [DOCREASON]
      ,[SSKDOCTYP]
      ,case when LH_001_LAWCHG.SSKDISCLAW  =0  then
'Kanun türü yoktur.'
else 
isnull(VW_IndirimKanunlariListesi.EXP,'Kanun türü yoktur.')  END  [SSKDISCLAW]
      ,[NEWUNITCODE]
      ,[OLDUNITCODE]
      ,[LOCORDNUMBER]
      ,[CITYCODE]
      ,[EMPLOYERNUMBER]
      ,[LH_001_EDOCMLIST].[SSKNO]
      ,[IDTCNO]
      ,[LH_001_EDOCMLIST].[NAME]
      ,[SURNAME]
      ,[TOTSSKNDAY]
      ,[TOTSSKNBASE_WG]
      ,[TOTSSKNBASE_AP]
      ,[INDAY]
      ,[INMONTH]
      ,[OUTDAY]
      ,[OUTMONTH]
      ,[LH_001_EDOCMLIST].[OUTREASON]
      ,[SGKMDAYCOUNT]
      ,[SSKMDAYREASON]
      ,[JOBCODE]
      ,[NONWORKEDONREST]
      ,[REALIZREASON]
      ,[PNTMONTH]
      ,[PNTYEAR]
      ,case when [TAXDISCTYP] = 'Hayýr' then '2' else '1' end  as [TAXDISCTYP]
      ,[MINWAGEDISC]
      ,[TAXNBASE]
      ,[TAXNBASEINJRATE]
      ,[TAXDISC] + [MINWAGEDISC] as [TAXDISC]
    
    
  FROM [dbo].[LH_001_EDOCMLIST]
    left jOIN dbo.L_CAPIFIRM ON dbo.[LH_001_EDOCMLIST].FIRMNR = dbo.L_CAPIFIRM.NR 
	LEFT JOIN dbo.L_CAPIDIV ON dbo.[LH_001_EDOCMLIST].LOCNR = dbo.L_CAPIDIV.NR AND  dbo.[LH_001_EDOCMLIST].FIRMNR = dbo.L_CAPIDIV.FIRMNR
left JOIN VW_PERSONEL_SICIL_001 on LH_001_EDOCMLIST.IDTCNO = VW_PERSONEL_SICIL_001.TCKIMLIKNO
left JOIN LH_001_LAWCHG ON LH_001_LAWCHG.PERREF = VW_PERSONEL_SICIL_001.LH_001_PERSONREF AND ENDDATE IS NULL
left JOIN VW_IndirimKanunlariListesi ON VW_IndirimKanunlariListesi.NR = LH_001_LAWCHG.SSKDISCLAW  
 
  
GO


