
SELECT 
	LINE.CR_CODE,
	LINE.CR_DEFINITION,
	LINE.INVENNO,
                ISNULL(SUM(LINE.SLTRANS_AMOUNT),0) +ISNULL(CIKAN.CIKAN_MIKTAR*-1,0) - ISNULL(GIREN.GIREN_MIKTAR,0)  DEVIR,
	GIREN.GIREN_MIKTAR ,
	CIKAN.CIKAN_MIKTAR*-1 CIKAN_MIKTAR,
                UNITSETL_CODE,
	SUM(LINE.SLTRANS_AMOUNT) KALAN_MIKTAR,
                BASTAR =CONVERT(dateTime,{FLTDATEVAL(1)}, 101),
               BITTAR =CONVERT(dateTime,{FLTDATEVAL(2)}, 101),
LINE.CAPIWHOUSE_NAME,
SUM(LINE.SLTRANS_AMOUNT * LINE.GIRIS_FIYATI) KALAN_TUTAR
FROM 
TRP_213_01_SLTRANS_LINE LINE
LEFT OUTER JOIN 
	(
SELECT 
		GIREN.CR_CODE ,
		GIREN.CAPIWHOUSE_NAME,
		SUM(SLTRANS_AMOUNT) GIREN_MIKTAR
	FROM 
		TRP_213_01_SLTRANS_LINE GIREN
	WHERE 
		SLTRANS_DATE> =  CONVERT(dateTime,{FLTDATEVAL(1)}, 101)  AND 
		SLTRANS_DATE< =  CONVERT(dateTime,{FLTDATEVAL(2)}, 101)  AND  
		STLINE_IOCODE IN (1,2)
		GROUP BY GIREN.CR_CODE ,
		GIREN.CAPIWHOUSE_NAME 	
	) GIREN ON LINE.CR_CODE = GIREN.CR_CODE  AND LINE.CAPIWHOUSE_NAME = GIREN.CAPIWHOUSE_NAME
LEFT OUTER JOIN 
	(
SELECT 
		CIKAN.CR_CODE ,
		CIKAN.CAPIWHOUSE_NAME,
		SUM(SLTRANS_AMOUNT) CIKAN_MIKTAR
	FROM 
		TRP_213_01_SLTRANS_LINE CIKAN
	WHERE 
		SLTRANS_DATE> =  CONVERT(dateTime,{FLTDATEVAL(1)}, 101)  AND 
		SLTRANS_DATE< =  CONVERT(dateTime,{FLTDATEVAL(2)}, 101)  AND  
		STLINE_IOCODE IN (3,4)
		GROUP BY CIKAN.CR_CODE ,
		CIKAN.CAPIWHOUSE_NAME 	
	) CIKAN ON LINE.CR_CODE = CIKAN.CR_CODE  AND LINE.CAPIWHOUSE_NAME = CIKAN.CAPIWHOUSE_NAME
WHERE 
LINE.SLTRANS_DATE<=  CONVERT(dateTime,{FLTDATEVAL(2)}, 101) 
AND LINE.CR_CODE LIKE '120.01.%'
AND LINE.ITEMS_CODE LIKE 'T.01%'
GROUP BY 
LINE.CR_CODE,
	LINE.CR_DEFINITION,
	LINE.INVENNO,
	GIREN.GIREN_MIKTAR,
	CIKAN.CIKAN_MIKTAR,
                UNITSETL_CODE,
LINE.CAPIWHOUSE_NAME,
GIREN.CAPIWHOUSE_NAME,
CIKAN.CAPIWHOUSE_NAME