
-- SELECT * FROM GO3DB..LG_423_01_STFICHE 
--SELECT * FROM GO3DB..LG_423_01_STLINE WHERE STFICHEREF = 12326
-- EXECUTE DBO.SP_GO3_STFICHE_INSERT_23  '15224'
ALTER PROCEDURE SP_GO3_STFICHE_INSERT_23
          --@TigerInvoiceRef INT
		    @SecilenKayitlar varchar(MAX)
as
begin 
    CREATE TABLE #TempTable (Id varchar(30))

    -- Split the input string by comma and insert values into the temporary table
    DECLARE @StartPosition INT = 1, @CommaPosition INT

    WHILE @StartPosition <= LEN(@SecilenKayitlar)
    BEGIN
        SET @CommaPosition = CHARINDEX(',', @SecilenKayitlar, @StartPosition)

        IF @CommaPosition = 0
            SET @CommaPosition = LEN(@SecilenKayitlar) + 1

        INSERT INTO #TempTable (Id)
        SELECT SUBSTRING(@SecilenKayitlar, @StartPosition, @CommaPosition - @StartPosition)

        SET @StartPosition = @CommaPosition + 1
    END
	DECLARE @TigerInvoiceRef INT
	DECLARE @GRPCODE smallint
	DECLARE @TRCODE smallint
	DECLARE @IOCODE smallint
	DECLARE @FICHENO varchar(17) --= (SELECT RIGHT('0000000000' + CAST(MAX(FICHENO) + 1 AS VARCHAR(10)), 10)  FROM GO3DB..LG_423_01_STFICHE WHERE TRCODE = 8)
	DECLARE @DATE_ datetime
	DECLARE @FTIME int
	DECLARE @DOCODE varchar(33)
	DECLARE @INVNO varchar(17)
	DECLARE @SPECODE varchar(11)
	DECLARE @CYPHCODE varchar(11)
	DECLARE @INVOICEREF int
	DECLARE @CLIENTREF int
	DECLARE @RECVREF int
	DECLARE @ACCOUNTREF int
	DECLARE @CENTERREF int
	DECLARE @PRODORDERREF int
	DECLARE @PORDERFICHENO varchar(17)
	DECLARE @SOURCETYPE smallint
	DECLARE @SOURCEINDEX smallint
	DECLARE @SOURCEWSREF int
	DECLARE @SOURCEPOLNREF int
	DECLARE @SOURCECOSTGRP smallint
	DECLARE @DESTTYPE smallint
	DECLARE @DESTINDEX smallint
	DECLARE @DESTWSREF int
	DECLARE @DESTPOLNREF int
	DECLARE @DESTCOSTGRP smallint
	DECLARE @FACTORYNR smallint
	DECLARE @BRANCH smallint
	DECLARE @DEPARTMENT smallint
	DECLARE @COMPBRANCH smallint
	DECLARE @COMPDEPARTMENT smallint
	DECLARE @COMPFACTORY smallint
	DECLARE @PRODSTAT smallint
	DECLARE @DEVIR smallint
	DECLARE @CANCELLED smallint
	DECLARE @BILLED smallint
	DECLARE @ACCOUNTED smallint
	DECLARE @UPDCURR smallint
	DECLARE @INUSE smallint
	DECLARE @INVKIND smallint
	DECLARE @ADDDISCOUNTS float
	DECLARE @TOTALDISCOUNTS float
	DECLARE @TOTALDISCOUNTED float
	DECLARE @ADDEXPENSES float
	DECLARE @TOTALEXPENSES float
	DECLARE @TOTALDEPOZITO float
	DECLARE @TOTALPROMOTIONS float
	DECLARE @TOTALVAT float
	DECLARE @GROSSTOTAL float
	DECLARE @NETTOTAL float
	DECLARE @GENEXP1 varchar(51)
	DECLARE @GENEXP2 varchar(51)
	DECLARE @GENEXP3 varchar(51)
	DECLARE @GENEXP4 varchar(51)
	DECLARE @GENEXP5 varchar(51)
	DECLARE @GENEXP6 varchar(51)
	DECLARE @REPORTRATE float
	DECLARE @REPORTNET float
	DECLARE @EXTENREF int
	DECLARE @PAYDEFREF int
	DECLARE @PRINTCNT smallint
	DECLARE @FICHECNT smallint
	DECLARE @ACCFICHEREF int
	DECLARE @CAPIBLOCK_CREATEDBY smallint
	DECLARE @CAPIBLOCK_CREADEDDATE datetime
	DECLARE @CAPIBLOCK_CREATEDHOUR smallint
	DECLARE @CAPIBLOCK_CREATEDMIN smallint
	DECLARE @CAPIBLOCK_CREATEDSEC smallint
	DECLARE @CAPIBLOCK_MODIFIEDBY smallint
	DECLARE @CAPIBLOCK_MODIFIEDDATE datetime
	DECLARE @CAPIBLOCK_MODIFIEDHOUR smallint
	DECLARE @CAPIBLOCK_MODIFIEDMIN smallint
	DECLARE @CAPIBLOCK_MODIFIEDSEC smallint
	DECLARE @SALESMANREF int
	DECLARE @CANCELLEDACC smallint
	DECLARE @SHPTYPCOD varchar(13)
	DECLARE @SHPAGNCOD varchar(13)
	DECLARE @TRACKNR varchar(65)
	DECLARE @GENEXCTYP smallint
	DECLARE @LINEEXCTYP smallint
	DECLARE @TRADINGGRP varchar(17)
	DECLARE @TEXTINC smallint
	DECLARE @SITEID smallint
	DECLARE @RECSTATUS smallint
	DECLARE @ORGLOGICREF int
	DECLARE @WFSTATUS int
	DECLARE @SHIPINFOREF int
	DECLARE @DISTORDERREF int
	DECLARE @SENDCNT smallint
	DECLARE @DLVCLIENT smallint
	DECLARE @DOCTRACKINGNR varchar(21)
	DECLARE @ADDTAXCALC smallint
	DECLARE @TOTALADDTAX float
	DECLARE @UGIRTRACKINGNO varchar(17)
	DECLARE @QPRODFCREF int
	DECLARE @VAACCREF int
	DECLARE @VACENTERREF int
	DECLARE @ORGLOGOID varchar(25)
	DECLARE @FROMEXIM smallint
	DECLARE @FRGTYPCOD varchar(13)
	DECLARE @TRCURR smallint
	DECLARE @TRRATE float
	DECLARE @TRNET float
	DECLARE @EXIMWHFCREF int
	DECLARE @EXIMFCTYPE smallint
	DECLARE @MAINSTFCREF int
	DECLARE @FROMORDWITHPAY smallint
	DECLARE @PROJECTREF int
	DECLARE @WFLOWCRDREF int
	DECLARE @STATUS smallint
	DECLARE @UPDTRCURR smallint
	DECLARE @TOTALEXADDTAX float
	DECLARE @AFFECTCOLLATRL smallint
	DECLARE @DEDUCTIONPART1 smallint
	DECLARE @DEDUCTIONPART2 smallint
	DECLARE @GRPFIRMTRANS smallint
	DECLARE @AFFECTRISK smallint
	DECLARE @DISPSTATUS smallint
	DECLARE @APPROVE smallint
	DECLARE @APPROVEDATE datetime
	DECLARE @CANTCREDEDUCT smallint
	DECLARE @SHIPDATE datetime
	DECLARE @SHIPTIME int
	DECLARE @ENTRUSTDEVIR smallint
	DECLARE @RELTRANSFCREF int
	DECLARE @FROMTRANSFER smallint
	DECLARE @GUID varchar(37)
	DECLARE @GLOBALID varchar(51)
	DECLARE @COMPSTFCREF int
	DECLARE @COMPINVREF int
	DECLARE @TOTALSERVICES float
	DECLARE @CAMPAIGNCODE varchar(25)
	DECLARE @OFFERREF int
	DECLARE @EINVOICETYP smallint
	DECLARE @EINVOICE smallint
	DECLARE @NOCALCULATE smallint
	DECLARE @PRODORDERTYP smallint
	DECLARE @QPRODFCTYP smallint
	DECLARE @PRINTDATE datetime
	DECLARE @PRDORDSLPLNRESERVE smallint
	DECLARE @CONTROLINFO smallint
	DECLARE @EDESPATCH smallint
	DECLARE @DOCDATE datetime
	DECLARE @DOCTIME int
	DECLARE @EDESPSTATUS smallint
	DECLARE @PROFILEID smallint
	DECLARE @DELIVERYCODE varchar(11)
	DECLARE @DESTSTATUS smallint
	DECLARE @CANCELEXP varchar(251)
	DECLARE @UNDOEXP varchar(251)
	DECLARE @CANCELDATE datetime
	DECLARE @CREATEWHERE smallint
	DECLARE @PUBLICBNACCREF int
	DECLARE @ACCEPTEINVPUBLIC smallint
	DECLARE @VATEXCEPTCODE varchar(11)
	DECLARE @VATEXCEPTREASON varchar(201)
	DECLARE @ATAXEXCEPTCODE varchar(11)
	DECLARE @ATAXEXCEPTREASON varchar(201)
	DECLARE @TAXFREECHX smallint
	DECLARE @MNTORDERFREF int
	DECLARE @PRINTEDDESPFCNO varchar(17)
	DECLARE @OKCFICHE smallint
	DECLARE @ESENDDATE datetime
	DECLARE @RECHASH varchar(100)
	DECLARE @FROMINTEGREF int = 0
	DECLARE @FROMINTEGTYPE smallint  = 0
	DECLARE @EPRINTCNT smallint  = 0
	DECLARE @CLNOTREFLACNTRREF int  = 0
	DECLARE @CLNOTREFLAACCREF int  = 0
	DECLARE @CANCELLEDINVREF1 int  = 0
	DECLARE @NOTIFYCRDREF int  = 0
	DECLARE @CANCELLEDINVREF2 int  = 0
	DECLARE @CANCELLEDINVREF4 int  = 0
	DECLARE @CANCELLEDINVREF3 int  = 0
	DECLARE @InputString varchar(500)
	-- SELECT * FROM GO3DB..LG_423_01_STFICHE WHERE LOGICALREF = 12326
	--1. seçilen kayýtlar döngüye alýnýyor...
	DECLARE processes CURSOR FOR

	 
	SELECT Id FROM #TempTable
	OPEN processes
 
	FETCH NEXT FROM processes
	INTO  @InputString
	WHILE @@FETCH_STATUS = 0
	BEGIN

	--2 ÖNCE TIGER2'DEN FÝÞÝN DETAY BÝLGÝLERÝ ALINIYOR, REFERANSLARA DÝKKAT EDÝLECEK.
	set @TigerInvoiceRef = CAST(@InputString as int)
	SET @IOCODE = 3
	SET @INVOICEREF = 0
	SET @PRODORDERREF     = 0
	SET @PORDERFICHENO     = 0 
	SET @SOURCETYPE     = 0
	SET @SOURCEWSREF     =[SOURCEWSREF]
	SET @SOURCEPOLNREF     =[SOURCEPOLNREF]
	SET @SOURCECOSTGRP     =[SOURCECOSTGRP]
	SET @DESTTYPE     =[DESTTYPE]
	SET @DESTINDEX     =[DESTINDEX]
		  ,@DESTWSREF     =[DESTWSREF]
		  ,@DESTPOLNREF     =[DESTPOLNREF]
		  ,@DESTCOSTGRP     =[DESTCOSTGRP]

	SELECT  
		  @GRPCODE = [GRPCODE],
		  @TRCODE= [TRCODE]
		  --,@IOCODE=[IOCODE]
		  ,@FICHENO = [FICHENO]
		  ,@DATE_ = [DATE_]
		  ,@FTIME = [TIME_]
		  ,@DOCODE= [DOCODE]
		  ,@INVNO = [FICHENO]
		  ,@SPECODE= [SPECODE]
		  ,@CYPHCODE = [CYPHCODE]
		  --,@INVOICEREF = [INVOICEREF]
		  ,@CLIENTREF     = CLIENTREF
		  ,@RECVREF     =[RECVREF]
		  ,@ACCOUNTREF     = ACCOUNTREF
		  ,@CENTERREF     =[CENTERREF]
		  --,@PRODORDERREF     =[PRODORDERREF]
		  --,@PORDERFICHENO     =[PORDERFICHENO]
		  --,@SOURCETYPE     =[SOURCETYPE]
		  ,@SOURCEINDEX     =[SOURCEINDEX]
		  --,@SOURCEWSREF     =[SOURCEWSREF]
		  --,@SOURCEPOLNREF     =[SOURCEPOLNREF]
		  --,@SOURCECOSTGRP     =[SOURCECOSTGRP]
		  --,@DESTTYPE     =[DESTTYPE]
		  --,@DESTINDEX     =[DESTINDEX]
		  --,@DESTWSREF     =[DESTWSREF]
		  --,@DESTPOLNREF     =[DESTPOLNREF]
		  --,@DESTCOSTGRP     =[DESTCOSTGRP]
		  ,@FACTORYNR     =[FACTORYNR]
		  ,@BRANCH     =[BRANCH]
		  ,@DEPARTMENT     =[DEPARTMENT]
		  ,@COMPBRANCH     =COMPBRANCH
		  ,@COMPDEPARTMENT     =COMPDEPARTMENT
		  ,@COMPFACTORY     =COMPFACTORY
		  ,@PRODSTAT     =PRODSTAT
		  ,@DEVIR     =DEVIR
		  ,@CANCELLED     =CANCELLED
		  ,@BILLED     =BILLED
		  ,@ACCOUNTED     =ACCOUNTED
		  ,@UPDCURR     =UPDCURR
		  ,@INUSE     =INUSE
		  ,@INVKIND     =INVKIND
		  ,@ADDDISCOUNTS     =ADDDISCOUNTS
		  ,@TOTALDISCOUNTS     =TOTALDISCOUNTS
		  ,@TOTALDISCOUNTED     =TOTALDISCOUNTED
		  ,@ADDEXPENSES     =ADDEXPENSES
		  ,@TOTALEXPENSES     =TOTALEXPENSES
		  ,@TOTALDEPOZITO     =TOTALDEPOZITO
		  ,@TOTALPROMOTIONS     =TOTALPROMOTIONS
		  ,@TOTALVAT     =TOTALVAT
		  ,@GROSSTOTAL     =GROSSTOTAL
		  ,@NETTOTAL     =NETTOTAL
		  ,@GENEXP1     =GENEXP1
		  ,@GENEXP2     =GENEXP2
		  ,@GENEXP3     =GENEXP3
		  ,@GENEXP4     =GENEXP4
		  ,@REPORTRATE     =REPORTRATE
		  ,@REPORTNET     =REPORTNET
		  ,@EXTENREF     =EXTENREF
		  ,@PAYDEFREF     =PAYDEFREF
		  ,@PRINTCNT     =PRINTCNT
		  ,@FICHECNT     =FICHECNT
		  ,@ACCFICHEREF     =ACCFICHEREF
		  ,@CAPIBLOCK_CREATEDBY     =CAPIBLOCK_CREATEDBY
		  ,@CAPIBLOCK_CREADEDDATE     =CAPIBLOCK_CREADEDDATE
		  ,@CAPIBLOCK_CREATEDHOUR     =CAPIBLOCK_CREATEDHOUR
		  ,@CAPIBLOCK_CREATEDMIN     =CAPIBLOCK_CREATEDMIN
		  ,@CAPIBLOCK_CREATEDSEC     =CAPIBLOCK_CREATEDSEC
		  ,@CAPIBLOCK_MODIFIEDBY     =CAPIBLOCK_MODIFIEDBY
		  ,@CAPIBLOCK_MODIFIEDDATE     =CAPIBLOCK_MODIFIEDDATE
		  ,@CAPIBLOCK_MODIFIEDHOUR     =CAPIBLOCK_MODIFIEDHOUR
		  ,@CAPIBLOCK_MODIFIEDMIN     =CAPIBLOCK_MODIFIEDMIN
		  ,@CAPIBLOCK_MODIFIEDSEC     =CAPIBLOCK_MODIFIEDSEC
		  ,@SALESMANREF     =SALESMANREF
		  ,@CANCELLEDACC     =CANCELLEDACC
		  ,@SHPTYPCOD     =SHPTYPCOD
		  ,@SHPAGNCOD     =SHPAGNCOD
		  ,@TRACKNR     =TRACKNR
		  ,@GENEXCTYP     =GENEXCTYP
		  ,@LINEEXCTYP     =LINEEXCTYP
		  ,@TRADINGGRP     =TRADINGGRP
		  ,@TEXTINC     =TEXTINC
		  ,@SITEID     =SITEID
		  ,@RECSTATUS     =RECSTATUS
		  ,@ORGLOGICREF     =ORGLOGICREF
		  ,@WFSTATUS     =WFSTATUS
		  ,@SHIPINFOREF     =SHIPINFOREF
		  ,@DISTORDERREF     =DISTORDERREF
		  ,@SENDCNT     =SENDCNT
		  ,@DLVCLIENT     =DLVCLIENT
		  ,@DOCTRACKINGNR     =DOCTRACKINGNR
		  ,@ADDTAXCALC     =ADDTAXCALC
		  ,@TOTALADDTAX    =TOTALADDTAX
		  ,@UGIRTRACKINGNO     =UGIRTRACKINGNO
		  ,@QPRODFCREF     =QPRODFCREF
		  ,@VAACCREF     =VAACCREF
		  ,@VACENTERREF     =VACENTERREF
		  ,@ORGLOGOID     =ORGLOGOID
		  ,@FROMEXIM     =FROMEXIM
		  ,@FRGTYPCOD     =FRGTYPCOD
		  ,@TRCURR     =TRCURR
		  ,@TRRATE     =TRRATE
		  ,@TRNET     =TRNET
		  ,@EXIMWHFCREF     =EXIMWHFCREF
		  ,@EXIMFCTYPE     =EXIMFCTYPE
		  ,@MAINSTFCREF     =MAINSTFCREF
		  ,@FROMORDWITHPAY     =FROMORDWITHPAY
		  ,@PROJECTREF     =PROJECTREF
		  ,@WFLOWCRDREF     =WFLOWCRDREF
		  ,@STATUS     =STATUS
		  ,@UPDTRCURR     =UPDTRCURR
		  ,@TOTALEXADDTAX     =TOTALEXADDTAX
		  ,@AFFECTCOLLATRL     =AFFECTCOLLATRL
		  ,@DEDUCTIONPART1     =DEDUCTIONPART1
		  ,@DEDUCTIONPART2     =DEDUCTIONPART2
		  ,@GRPFIRMTRANS     =GRPFIRMTRANS
		  ,@AFFECTRISK     =AFFECTRISK
		  ,@DISPSTATUS     =DISPSTATUS
		  ,@APPROVE     =APPROVE
		  ,@APPROVEDATE     =APPROVEDATE
		  ,@CANTCREDEDUCT     =CANTCREDEDUCT
		  ,@SHIPDATE     =SHIPDATE
		  ,@SHIPTIME     =SHIPTIME
		  ,@ENTRUSTDEVIR     =ENTRUSTDEVIR
		  ,@RELTRANSFCREF     =RELTRANSFCREF
		  ,@FROMTRANSFER     =FROMTRANSFER
		  ,@GUID     =GUID
		  ,@GLOBALID     =GLOBALID
		  ,@RECHASH     =RECHASH
	  FROM CEZVE.[dbo].[LG_323_01_INVOICE] WHERE LOGICALREF = @TigerInvoiceRef

	--
	  SET @CLIENTREF     = ( SELECT LOGICALREF FROM GO3DB..LG_423_CLCARD GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 CODE FROM CEZVE..LG_323_CLCARD TGRCL WHERE TGRCL.LOGICALREF=   @CLIENTREF))
      
	  SET @ACCOUNTREF     = ( SELECT LOGICALREF FROM GO3DB..LG_423_EMUHACC GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 CODE FROM CEZVE..LG_323_EMUHACC TGRCL WHERE TGRCL.LOGICALREF=   @ACCOUNTREF))

	-- 2. TIGER2'DEKÝ  DEÐERLERLE INSERT TAMAMLANIYOR.
	INSERT INTO go3db.[dbo].[LG_423_01_STFICHE]
			   ([GRPCODE]
			   ,[TRCODE]
			   ,[IOCODE]
			   ,[FICHENO]
			   ,[DATE_]
			   ,[FTIME]
			   ,[DOCODE]
			   ,[INVNO]
			   ,[SPECODE]
			   ,[CYPHCODE]
			   ,[INVOICEREF]
			   ,[CLIENTREF]
			   ,[RECVREF]
			   ,[ACCOUNTREF]
			   ,[CENTERREF]
			   ,[PRODORDERREF]
			   ,[PORDERFICHENO]
			   ,[SOURCETYPE]
			   ,[SOURCEINDEX]
			   ,[SOURCEWSREF]
			   ,[SOURCEPOLNREF]
			   ,[SOURCECOSTGRP]
			   ,[DESTTYPE]
			   ,[DESTINDEX]
			   ,[DESTWSREF]
			   ,[DESTPOLNREF]
			   ,[DESTCOSTGRP]
			   ,[FACTORYNR]
			   ,[BRANCH]
			   ,[DEPARTMENT]
			   ,[COMPBRANCH]
			   ,[COMPDEPARTMENT]
			   ,[COMPFACTORY]
			   ,[PRODSTAT]
			   ,[DEVIR]
			   ,[CANCELLED]
			   ,[BILLED]
			   ,[ACCOUNTED]
			   ,[UPDCURR]
			   ,[INUSE]
			   ,[INVKIND]
			   ,[ADDDISCOUNTS]
			   ,[TOTALDISCOUNTS]
			   ,[TOTALDISCOUNTED]
			   ,[ADDEXPENSES]
			   ,[TOTALEXPENSES]
			   ,[TOTALDEPOZITO]
			   ,[TOTALPROMOTIONS]
			   ,[TOTALVAT]
			   ,[GROSSTOTAL]
			   ,[NETTOTAL]
			   ,[GENEXP1]
			   ,[GENEXP2]
			   ,[GENEXP3]
			   ,[GENEXP4]
			   ,[GENEXP5]
			   ,[GENEXP6]
			   ,[REPORTRATE]
			   ,[REPORTNET]
			   ,[EXTENREF]
			   ,[PAYDEFREF]
			   ,[PRINTCNT]
			   ,[FICHECNT]
			   ,[ACCFICHEREF]
			   ,[CAPIBLOCK_CREATEDBY]
			   ,[CAPIBLOCK_CREADEDDATE]
			   ,[CAPIBLOCK_CREATEDHOUR]
			   ,[CAPIBLOCK_CREATEDMIN]
			   ,[CAPIBLOCK_CREATEDSEC]
			   ,[CAPIBLOCK_MODIFIEDBY]
			   ,[CAPIBLOCK_MODIFIEDDATE]
			   ,[CAPIBLOCK_MODIFIEDHOUR]
			   ,[CAPIBLOCK_MODIFIEDMIN]
			   ,[CAPIBLOCK_MODIFIEDSEC]
			   ,[SALESMANREF]
			   ,[CANCELLEDACC]
			   ,[SHPTYPCOD]
			   ,[SHPAGNCOD]
			   ,[TRACKNR]
			   ,[GENEXCTYP]
			   ,[LINEEXCTYP]
			   ,[TRADINGGRP]
			   ,[TEXTINC]
			   ,[SITEID]
			   ,[RECSTATUS]
			   ,[ORGLOGICREF]
			   ,[WFSTATUS]
			   ,[SHIPINFOREF]
			   ,[DISTORDERREF]
			   ,[SENDCNT]
			   ,[DLVCLIENT]
			   ,[DOCTRACKINGNR]
			   ,[ADDTAXCALC]
			   ,[TOTALADDTAX]
			   ,[UGIRTRACKINGNO]
			   ,[QPRODFCREF]
			   ,[VAACCREF]
			   ,[VACENTERREF]
			   ,[ORGLOGOID]
			   ,[FROMEXIM]
			   ,[FRGTYPCOD]
			   ,[TRCURR]
			   ,[TRRATE]
			   ,[TRNET]
			   ,[EXIMWHFCREF]
			   ,[EXIMFCTYPE]
			   ,[MAINSTFCREF]
			   ,[FROMORDWITHPAY]
			   ,[PROJECTREF]
			   ,[WFLOWCRDREF]
			   ,[STATUS]
			   ,[UPDTRCURR]
			   ,[TOTALEXADDTAX]
			   ,[AFFECTCOLLATRL]
			   ,[DEDUCTIONPART1]
			   ,[DEDUCTIONPART2]
			   ,[GRPFIRMTRANS]
			   ,[AFFECTRISK]
			   ,[DISPSTATUS]
			   ,[APPROVE]
			   ,[APPROVEDATE]
			   ,[CANTCREDEDUCT]
			   ,[SHIPDATE]
			   ,[SHIPTIME]
			   ,[ENTRUSTDEVIR]
			   ,[RELTRANSFCREF]
			   ,[FROMTRANSFER]
			   ,[GUID]
			   ,[GLOBALID]
			   ,[COMPSTFCREF]
			   ,[COMPINVREF]
			   ,[TOTALSERVICES]
			   ,[CAMPAIGNCODE]
			   ,[OFFERREF]
			   ,[EINVOICETYP]
			   ,[EINVOICE]
			   ,[NOCALCULATE]
			   ,[PRODORDERTYP]
			   ,[QPRODFCTYP]
			   ,[PRINTDATE]
			   ,[PRDORDSLPLNRESERVE]
			   ,[CONTROLINFO]
			   ,[EDESPATCH]
			   ,[DOCDATE]
			   ,[DOCTIME]
			   ,[EDESPSTATUS]
			   ,[PROFILEID]
			   ,[DELIVERYCODE]
			   ,[DESTSTATUS]
			   ,[CANCELEXP]
			   ,[UNDOEXP]
			   ,[CANCELDATE]
			   ,[CREATEWHERE]
			   ,[PUBLICBNACCREF]
			   ,[ACCEPTEINVPUBLIC]
			   ,[VATEXCEPTCODE]
			   ,[VATEXCEPTREASON]
			   ,[ATAXEXCEPTCODE]
			   ,[ATAXEXCEPTREASON]
			   ,[TAXFREECHX]
			   ,[MNTORDERFREF]
			   ,[PRINTEDDESPFCNO]
			   ,[OKCFICHE]
			   ,[ESENDDATE]
			   ,[RECHASH]
			   ,[FROMINTEGREF]
			   ,[FROMINTEGTYPE]
			   ,[EPRINTCNT]
			   ,[CLNOTREFLACNTRREF]
			   ,[CLNOTREFLAACCREF]
			   ,[CANCELLEDINVREF1]
			   ,[NOTIFYCRDREF]
			   ,[CANCELLEDINVREF2]
			   ,[CANCELLEDINVREF4]
			   ,[CANCELLEDINVREF3])
		 VALUES
			   (@GRPCODE 
			   ,@TRCODE 
			   ,@IOCODE
			   ,@FICHENO 
			   ,@DATE_
			   ,@FTIME
			   ,@DOCODE
			   ,@INVNO
			   ,@SPECODE
			   ,@CYPHCODE
			   ,@INVOICEREF
			   ,@CLIENTREF
			   ,@RECVREF
			   ,@ACCOUNTREF
			   ,@CENTERREF
			   ,@PRODORDERREF
			   ,@PORDERFICHENO
			   ,@SOURCETYPE
			   ,@SOURCEINDEX
			   ,@SOURCEWSREF
			   ,@SOURCEPOLNREF
			   ,@SOURCECOSTGRP
			   ,@DESTTYPE
			   ,@DESTINDEX
			   ,@DESTWSREF
			   ,@DESTPOLNREF
			   ,@DESTCOSTGRP
			   ,@FACTORYNR
			   ,@BRANCH
			   ,@DEPARTMENT
			   ,@COMPBRANCH
			   ,@COMPDEPARTMENT
			   ,@COMPFACTORY
			   ,@PRODSTAT
			   ,@DEVIR
			   ,@CANCELLED
			   ,@BILLED
			   ,@ACCOUNTED
			   ,@UPDCURR
			   ,@INUSE
			   ,@INVKIND
			   ,@ADDDISCOUNTS
			   ,@TOTALDISCOUNTS
			   ,@TOTALDISCOUNTED
			   ,@ADDEXPENSES
			   ,@TOTALEXPENSES
			   ,@TOTALDEPOZITO
			   ,@TOTALPROMOTIONS
			   ,@TOTALVAT
			   ,@GROSSTOTAL
			   ,@NETTOTAL
			   ,@GENEXP1
			   ,@GENEXP2
			   ,@GENEXP3
			   ,@GENEXP4
			   ,@GENEXP5
			   ,@GENEXP6
			   ,@REPORTRATE
			   ,@REPORTNET
			   ,@EXTENREF
			   ,@PAYDEFREF
			   ,@PRINTCNT
			   ,@FICHECNT
			   ,@ACCFICHEREF
			   ,@CAPIBLOCK_CREATEDBY
			   ,@CAPIBLOCK_CREADEDDATE
			   ,@CAPIBLOCK_CREATEDHOUR
			   ,@CAPIBLOCK_CREATEDMIN
			   ,@CAPIBLOCK_CREATEDSEC
			   ,@CAPIBLOCK_MODIFIEDBY
			   ,@CAPIBLOCK_MODIFIEDDATE
			   ,@CAPIBLOCK_MODIFIEDHOUR
			   ,@CAPIBLOCK_MODIFIEDMIN
			   ,@CAPIBLOCK_MODIFIEDSEC
			   ,@SALESMANREF
			   ,@CANCELLEDACC
			   ,@SHPTYPCOD
			   ,@SHPAGNCOD
			   ,@TRACKNR 
			   ,@GENEXCTYP
			   ,@LINEEXCTYP
			   ,@TRADINGGRP
			   ,@TEXTINC
			   ,@SITEID
			   ,@RECSTATUS
			   ,@ORGLOGICREF
			   ,@WFSTATUS
			   ,@SHIPINFOREF
			   ,@DISTORDERREF
			   ,@SENDCNT
			   ,@DLVCLIENT
			   ,@DOCTRACKINGNR 
			   ,@ADDTAXCALC
			   ,@TOTALADDTAX
			   ,@UGIRTRACKINGNO
			   ,@QPRODFCREF
			   ,@VAACCREF
			   ,@VACENTERREF
			   ,@ORGLOGOID 
			   ,@FROMEXIM
			   ,@FRGTYPCOD
			   ,@TRCURR
			   ,@TRRATE
			   ,@TRNET
			   ,@EXIMWHFCREF
			   ,@EXIMFCTYPE
			   ,@MAINSTFCREF
			   ,@FROMORDWITHPAY
			   ,@PROJECTREF
			   ,@WFLOWCRDREF
			   ,@STATUS
			   ,@UPDTRCURR
			   ,@TOTALEXADDTAX
			   ,@AFFECTCOLLATRL
			   ,@DEDUCTIONPART1
			   ,@DEDUCTIONPART2
			   ,@GRPFIRMTRANS
			   ,@AFFECTRISK
			   ,@DISPSTATUS
			   ,@APPROVE
			   ,@APPROVEDATE
			   ,@CANTCREDEDUCT
			   ,@SHIPDATE
			   ,@SHIPTIME
			   ,@ENTRUSTDEVIR
			   ,@RELTRANSFCREF
			   ,@FROMTRANSFER
			   ,@GUID 
			   ,@GLOBALID
			   ,@COMPSTFCREF
			   ,@COMPINVREF
			   ,@TOTALSERVICES
			   ,@CAMPAIGNCODE 
			   ,@OFFERREF
			   ,@EINVOICETYP
			   ,@EINVOICE
			   ,@NOCALCULATE
			   ,@PRODORDERTYP
			   ,@QPRODFCTYP
			   ,@PRINTDATE
			   ,@PRDORDSLPLNRESERVE
			   ,@CONTROLINFO
			   ,@EDESPATCH
			   ,@DOCDATE
			   ,@DOCTIME
			   ,@EDESPSTATUS
			   ,@PROFILEID
			   ,@DELIVERYCODE
			   ,@DESTSTATUS
			   ,@CANCELEXP 
			   ,@UNDOEXP 
			   ,@CANCELDATE
			   ,@CREATEWHERE
			   ,@PUBLICBNACCREF
			   ,@ACCEPTEINVPUBLIC
			   ,@VATEXCEPTCODE
			   ,@VATEXCEPTREASON 
			   ,@ATAXEXCEPTCODE
			   ,@ATAXEXCEPTREASON 
			   ,@TAXFREECHX
			   ,@MNTORDERFREF
			   ,@PRINTEDDESPFCNO
			   ,@OKCFICHE
			   ,@ESENDDATE
			   ,@RECHASH 
			   ,@FROMINTEGREF
			   ,@FROMINTEGTYPE
			   ,@EPRINTCNT
			   ,@CLNOTREFLACNTRREF
			   ,@CLNOTREFLAACCREF
			   ,@CANCELLEDINVREF1
			   ,@NOTIFYCRDREF
			   ,@CANCELLEDINVREF2
			   ,@CANCELLEDINVREF4
			   ,@CANCELLEDINVREF3)
		--3. irsaliye fiþinin referansý alýndý, detay satýrlarda kullanýlacak
		DECLARE @Go3IrsaliyeFisiReferans INT;
		SET @Go3IrsaliyeFisiReferans = SCOPE_IDENTITY();
		--4. detay bölümünde SP_Detay Kullanýcýlacak
			EXEC DBO.SP_GO3_STLINE_INSERT_23 @TigerInvoiceRef, @Go3IrsaliyeFisiReferans
		--5. Tiger' docNo'ya insert edilen kayýt update edilecek
		     update  CEZVE..LG_323_01_STFICHE SET DOCODE = @FICHENO    WHERE LOGICALREF = @TigerInvoiceRef
    FETCH NEXT FROM processes
	INTO  @InputString
	END

	CLOSE processes
	DEALLOCATE processes

--return  @Go3IrsaliyeFisiReferans
END
SELECT DOCTRACKINGNR, * FROM CEZVE..LG_323_01_STFICHE WHERE LOGICALREF=15224

 
