 
ALTER PROCEDURE SP_GO3_STLINE_INSERT_23
          @TIGERIRSALIYEREF INT,
		  @GO3IRSALIYEREF INT
		   
as
begin 
--TANIMLAMALAR
DECLARE @LOGICALREF int
DECLARE @STOCKREF int
DECLARE @LINETYPE smallint
DECLARE @PREVLINEREF int
DECLARE @PREVLINENO smallint
DECLARE @DETLINE smallint
DECLARE @TRCODE smallint
DECLARE @DATE_ datetime
DECLARE @FTIME int
DECLARE @GLOBTRANS smallint
DECLARE @CALCTYPE smallint
DECLARE @PRODORDERREF int
DECLARE @SOURCETYPE smallint
DECLARE @SOURCEINDEX smallint
DECLARE @SOURCECOSTGRP smallint
DECLARE @SOURCEWSREF int
DECLARE @SOURCEPOLNREF int
DECLARE @DESTTYPE smallint
DECLARE @DESTINDEX smallint
DECLARE @DESTCOSTGRP smallint
DECLARE @DESTWSREF int
DECLARE @DESTPOLNREF int
DECLARE @FACTORYNR smallint
DECLARE @IOCODE smallint
DECLARE @STFICHEREF int
DECLARE @STFICHELNNO smallint
DECLARE @INVOICEREF int
DECLARE @INVOICELNNO smallint
DECLARE @CLIENTREF int
DECLARE @ORDTRANSREF int
DECLARE @ORDFICHEREF int
DECLARE @CENTERREF int
DECLARE @ACCOUNTREF int
DECLARE @VATACCREF int
DECLARE @VATCENTERREF int
DECLARE @PRACCREF int
DECLARE @PRCENTERREF int
DECLARE @PRVATACCREF int
DECLARE @PRVATCENREF int
DECLARE @PROMREF int
DECLARE @PAYDEFREF int
DECLARE @SPECODE varchar(17)
DECLARE @DELVRYCODE varchar(11)
DECLARE @AMOUNT float
DECLARE @PRICE float
DECLARE @TOTAL float
DECLARE @PRCURR smallint
DECLARE @PRPRICE float
DECLARE @TRCURR smallint
DECLARE @TRRATE float
DECLARE @REPORTRATE float
DECLARE @DISTCOST float
DECLARE @DISTDISC float
DECLARE @DISTEXP float
DECLARE @DISTPROM float
DECLARE @DISCPER float
DECLARE @LINEEXP varchar(251)
DECLARE @UOMREF int
DECLARE @USREF int
DECLARE @UINFO1 float
DECLARE @UINFO2 float
DECLARE @UINFO3 float
DECLARE @UINFO4 float
DECLARE @UINFO5 float
DECLARE @UINFO6 float
DECLARE @UINFO7 float
DECLARE @UINFO8 float
DECLARE @PLNAMOUNT float
DECLARE @VATINC smallint
DECLARE @VAT float
DECLARE @VATAMNT float
DECLARE @VATMATRAH float
DECLARE @BILLEDITEM int
DECLARE @BILLED smallint
DECLARE @CPSTFLAG smallint
DECLARE @RETCOSTTYPE smallint
DECLARE @SOURCELINK int
DECLARE @RETCOST float
DECLARE @RETCOSTCURR float
DECLARE @OUTCOST float
DECLARE @OUTCOSTCURR float
DECLARE @RETAMOUNT float
DECLARE @FAREGREF int
DECLARE @FAATTRIB smallint
DECLARE @CANCELLED smallint
DECLARE @LINENET float
DECLARE @DISTADDEXP float
DECLARE @FADACCREF int
DECLARE @FADCENTERREF int
DECLARE @FARACCREF int
DECLARE @FARCENTERREF int
DECLARE @DIFFPRICE float
DECLARE @DIFFPRCOST float
DECLARE @DECPRDIFF smallint
DECLARE @LPRODSTAT smallint
DECLARE @PRDEXPTOTAL float
DECLARE @DIFFREPPRICE float
DECLARE @DIFFPRCRCOST float
DECLARE @SALESMANREF int
DECLARE @FAPLACCREF int
DECLARE @FAPLCENTERREF int
DECLARE @OUTPUTIDCODE varchar(25)
DECLARE @DREF int
DECLARE @COSTRATE float
DECLARE @XPRICEUPD smallint
DECLARE @XPRICE float
DECLARE @XREPRATE float
DECLARE @DISTCOEF float
DECLARE @TRANSQCOK smallint
DECLARE @SITEID smallint
DECLARE @RECSTATUS smallint
DECLARE @ORGLOGICREF int
DECLARE @WFSTATUS int
DECLARE @POLINEREF int
DECLARE @PLNSTTRANSREF int
DECLARE @NETDISCFLAG smallint
DECLARE @NETDISCPERC float
DECLARE @NETDISCAMNT float
DECLARE @VATCALCDIFF float
DECLARE @CONDITIONREF int
DECLARE @DISTORDERREF int
DECLARE @DISTORDLINEREF int
DECLARE @CAMPAIGNREFS1 int
DECLARE @CAMPAIGNREFS2 int
DECLARE @CAMPAIGNREFS3 int
DECLARE @CAMPAIGNREFS4 int
DECLARE @CAMPAIGNREFS5 int
DECLARE @POINTCAMPREF int
DECLARE @CAMPPOINT float
DECLARE @PROMCLASITEMREF int
DECLARE @CMPGLINEREF int
DECLARE @PLNSTTRANSPERNR int
DECLARE @PORDCLSPLNAMNT float
DECLARE @VENDCOMM float
DECLARE @PREVIOUSOUTCOST float
DECLARE @COSTOFSALEACCREF int
DECLARE @PURCHACCREF int
DECLARE @COSTOFSALECNTREF int
DECLARE @PURCHCENTREF int
DECLARE @PREVOUTCOSTCURR float
DECLARE @ABVATAMOUNT float
DECLARE @ABVATSTATUS int
DECLARE @PRRATE float
DECLARE @ADDTAXRATE float
DECLARE @ADDTAXCONVFACT float
DECLARE @ADDTAXAMOUNT float
DECLARE @ADDTAXPRCOST float
DECLARE @ADDTAXRETCOST float
DECLARE @ADDTAXRETCOSTCURR float
DECLARE @GROSSUINFO1 float
DECLARE @GROSSUINFO2 float
DECLARE @ADDTAXPRCOSTCURR float
DECLARE @ADDTAXACCREF int
DECLARE @ADDTAXCENTERREF int
DECLARE @ADDTAXAMNTISUPD smallint
DECLARE @INFIDX float
DECLARE @ADDTAXCOSACCREF int
DECLARE @ADDTAXCOSCNTREF int
DECLARE @PREVIOUSATAXPRCOST float
DECLARE @PREVATAXPRCOSTCURR float
DECLARE @PRDORDTOTCOEF float
DECLARE @DEMPEGGEDAMNT float
DECLARE @STDUNITCOST float
DECLARE @STDRPUNITCOST float
DECLARE @COSTDIFFACCREF int
DECLARE @COSTDIFFCENREF int
DECLARE @TEXTINC smallint
DECLARE @ADDTAXDISCAMOUNT float
DECLARE @ORGLOGOID varchar(25)
DECLARE @EXIMFICHENO varchar(31)
DECLARE @EXIMFCTYPE smallint
DECLARE @TRANSEXPLINE smallint
DECLARE @INSEXPLINE smallint
DECLARE @EXIMWHFCREF int
DECLARE @EXIMWHLNREF int
DECLARE @EXIMFILEREF int
DECLARE @EXIMPROCNR smallint
DECLARE @EISRVDSTTYP smallint
DECLARE @MAINSTLNREF int
DECLARE @MADEOFSHRED smallint
DECLARE @FROMORDWITHPAY smallint
DECLARE @PROJECTREF int
DECLARE @STATUS smallint
DECLARE @DORESERVE smallint
DECLARE @POINTCAMPREFS1 int
DECLARE @POINTCAMPREFS2 int
DECLARE @POINTCAMPREFS3 int
DECLARE @POINTCAMPREFS4 int
DECLARE @CAMPPOINTS1 float
DECLARE @CAMPPOINTS2 float
DECLARE @CAMPPOINTS3 float
DECLARE @CAMPPOINTS4 float
DECLARE @CMPGLINEREFS1 int
DECLARE @CMPGLINEREFS2 int
DECLARE @CMPGLINEREFS3 int
DECLARE @CMPGLINEREFS4 int
DECLARE @PRCLISTREF int
DECLARE @PORDSYMOUTLN smallint
DECLARE @MONTH_ smallint
DECLARE @YEAR_ smallint
DECLARE @EXADDTAXRATE float
DECLARE @EXADDTAXCONVF float
DECLARE @EXADDTAXAREF int
DECLARE @EXADDTAXCREF int
DECLARE @OTHRADDTAXAREF int
DECLARE @OTHRADDTAXCREF int
DECLARE @EXADDTAXAMNT float
DECLARE @AFFECTCOLLATRL smallint
DECLARE @ALTPROMFLAG smallint
DECLARE @EIDISTFLNNR smallint
DECLARE @EXIMTYPE smallint
DECLARE @VARIANTREF int
DECLARE @CANDEDUCT smallint
DECLARE @OUTREMAMNT float
DECLARE @OUTREMCOST float
DECLARE @OUTREMCOSTCURR float
DECLARE @REFLVATACCREF int
DECLARE @REFLVATOTHACCREF int
DECLARE @PARENTLNREF int
DECLARE @AFFECTRISK smallint
DECLARE @INEFFECTIVECOST smallint
DECLARE @ADDTAXVATMATRAH float
DECLARE @REFLACCREF int
DECLARE @REFLOTHACCREF int
DECLARE @CAMPPAYDEFREF int
DECLARE @FAREGBINDDATE datetime
DECLARE @RELTRANSLNREF int
DECLARE @FROMTRANSFER smallint
DECLARE @COSTDISTPRICE float
DECLARE @COSTDISTREPPRICE float
DECLARE @DIFFPRICEUFRS float
DECLARE @DIFFREPPRICEUFRS float
DECLARE @OUTCOSTUFRS float
DECLARE @OUTCOSTCURRUFRS float
DECLARE @DIFFPRCOSTUFRS float
DECLARE @DIFFPRCRCOSTUFRS float
DECLARE @RETCOSTUFRS float
DECLARE @RETCOSTCURRUFRS float
DECLARE @OUTREMCOSTUFRS float
DECLARE @OUTREMCOSTCURRUFRS float
DECLARE @INFIDXUFRS float
DECLARE @ADJPRICEUFRS float
DECLARE @ADJREPPRICEUFRS float
DECLARE @ADJPRCOSTUFRS float
DECLARE @ADJPRCRCOSTUFRS float
DECLARE @COSTDISTPRICEUFRS float
DECLARE @COSTDISTREPPRICEUFRS float
DECLARE @PURCHACCREFUFRS int
DECLARE @PURCHCENTREFUFRS int
DECLARE @COSACCREFUFRS int
DECLARE @COSCNTREFUFRS int
DECLARE @PROUTCOSTUFRSDIFF float
DECLARE @PROUTCOSTCRUFRSDIFF float
DECLARE @UNDERDEDUCTLIMIT smallint
DECLARE @GLOBALID varchar(51)
DECLARE @DEDUCTIONPART1 smallint
DECLARE @DEDUCTIONPART2 smallint
DECLARE @GUID varchar(37)
DECLARE @SPECODE2 varchar(41)
DECLARE @OFFERREF int
DECLARE @OFFTRANSREF int
DECLARE @VATEXCEPTREASON varchar(201)
DECLARE @PLNDEFSERILOTNO varchar(101)
DECLARE @PLNUNRSRVAMOUNT float
DECLARE @PORDCLSPLNUNRSRVAMNT float
DECLARE @LPRODRSRVSTAT smallint
DECLARE @FALINKTYPE smallint
DECLARE @DEDUCTCODE varchar(11)
DECLARE @UPDTHISLINE smallint
DECLARE @VATEXCEPTCODE varchar(11)
DECLARE @PORDERFICHENO varchar(17)
DECLARE @QPRODFCREF int
DECLARE @RELTRANSFCREF int
DECLARE @ATAXEXCEPTREASON varchar(201)
DECLARE @ATAXEXCEPTCODE varchar(11)
DECLARE @PRODORDERTYP smallint
DECLARE @SUBCONTORDERREF int
DECLARE @QPRODFCTYP smallint
DECLARE @PRDORDSLPLNRESERVE smallint
DECLARE @INFDATE datetime
DECLARE @DESTSTATUS smallint
DECLARE @REGTYPREF int
DECLARE @FAPROFITACCREF int
DECLARE @FAPROFITCENTREF int
DECLARE @FALOSSACCREF int
DECLARE @FALOSSCENTREF int
DECLARE @CPACODE varchar(25)
DECLARE @GTIPCODE varchar(25)
DECLARE @PUBLICCOUNTRYREF int
DECLARE @QPRODITEMTYPE smallint
DECLARE @FUTMONTHCNT smallint
DECLARE @FUTMONTHBEGDATE int
DECLARE @QCTRANSFERREF int
DECLARE @QCTRANSFERAMNT float
DECLARE @FUTMONTHENDDATE datetime
DECLARE @KKEGACCREF int
DECLARE @KKEGCENTREF int
DECLARE @MNTORDERFREF int
DECLARE @FAKKEGAMOUNT float
DECLARE @MIDDLEMANEXPTYP smallint
DECLARE @EXPRACCREF int
DECLARE @EXPRCNTRREF int
DECLARE @KKEGVATACCREF int
DECLARE @KKEGVATCENTREF int
DECLARE @MARKINGTAGNO varchar(21)
DECLARE @OWNER varchar(201)
DECLARE @TCKTAXNR varchar(16)
DECLARE @FUTMONTHBEGDATE_ datetime
DECLARE @ADDTAXVATACCREF int
DECLARE @ADDTAXVATCENREF int
DECLARE @TAXFREECNTRREF int
DECLARE @TAXFREEACCREF int
DECLARE @FROMINTEGREF int
DECLARE @QCTRANSFERAMNT2 float
DECLARE @QCTRANSFERREF2 int
DECLARE @EISRVDSTADDTAXINC smallint
DECLARE @CANCELLEDINVREF2 int
DECLARE @CANCELLEDINVREF1 int
DECLARE @EXPDAYS smallint
DECLARE @FROMINTEGTYPE smallint
DECLARE @CANCELLEDINVREF4 int
DECLARE @CANCELLEDINVREF3 int
  SET @CLIENTREF     = ( SELECT LOGICALREF FROM GO3DB..LG_423_CLCARD GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 CODE FROM CEZVE..LG_323_CLCARD TGRCL WHERE TGRCL.LOGICALREF=   @CLIENTREF))
--2- tiger irsaliye satýrlarý döngüye alýnacak
DECLARE processes CURSOR FOR

 
SELECT [LOGICALREF]
      ,[STOCKREF]
      ,[LINETYPE]
      ,[PREVLINEREF]
      ,[PREVLINENO]
      ,[DETLINE]
      ,[TRCODE]
      ,[DATE_]
      ,[FTIME]
      ,[GLOBTRANS]
      ,[CALCTYPE]
      ,[PRODORDERREF]
      ,[SOURCETYPE]
      ,[SOURCEINDEX]
      ,[SOURCECOSTGRP]
      ,[SOURCEWSREF]
      ,[SOURCEPOLNREF]
      ,[DESTTYPE]
      ,[DESTINDEX]
      ,[DESTCOSTGRP]
      ,[DESTWSREF]
      ,[DESTPOLNREF]
      ,[FACTORYNR]
      ,[IOCODE]
      ,@GO3IRSALIYEREF AS [STFICHEREF]
      ,[STFICHELNNO]
      ,[INVOICEREF]
      ,[INVOICELNNO]
      ,@CLIENTREF
      ,[ORDTRANSREF]
      ,[ORDFICHEREF]
      ,[CENTERREF]
      ,[ACCOUNTREF]
      ,[VATACCREF]
      ,[VATCENTERREF]
      ,[PRACCREF]
      ,[PRCENTERREF]
      ,[PRVATACCREF]
      ,[PRVATCENREF]
      ,[PROMREF]
      ,[PAYDEFREF]
      ,[SPECODE]
      ,[DELVRYCODE]
      ,[AMOUNT]
      ,[PRICE]
      ,[TOTAL]
      ,[PRCURR]
      ,[PRPRICE]
      ,[TRCURR]
      ,[TRRATE]
      ,[REPORTRATE]
      ,[DISTCOST]
      ,[DISTDISC]
      ,[DISTEXP]
      ,[DISTPROM]
      ,[DISCPER]
      ,[LINEEXP]
      ,[UOMREF]
      ,[USREF]
      ,[UINFO1]
      ,[UINFO2]
      ,[UINFO3]
      ,[UINFO4]
      ,[UINFO5]
      ,[UINFO6]
      ,[UINFO7]
      ,[UINFO8]
      ,[PLNAMOUNT]
      ,[VATINC]
      ,[VAT]
      ,[VATAMNT]
      ,[VATMATRAH]
      ,[BILLEDITEM]
      ,[BILLED]
      ,[CPSTFLAG]
      ,[RETCOSTTYPE]
      ,[SOURCELINK]
      ,[RETCOST]
      ,[RETCOSTCURR]
      ,[OUTCOST]
      ,[OUTCOSTCURR]
      ,[RETAMOUNT]
      ,[FAREGREF]
      ,[FAATTRIB]
      ,[CANCELLED]
      ,[LINENET]
      ,[DISTADDEXP]
      ,[FADACCREF]
      ,[FADCENTERREF]
      ,[FARACCREF]
      ,[FARCENTERREF]
      ,[DIFFPRICE]
      ,[DIFFPRCOST]
      ,[DECPRDIFF]
      ,[LPRODSTAT]
      ,[PRDEXPTOTAL]
      ,[DIFFREPPRICE]
      ,[DIFFPRCRCOST]
      ,[SALESMANREF]
      ,[FAPLACCREF]
      ,[FAPLCENTERREF]
      ,[OUTPUTIDCODE]
      ,[DREF]
      ,[COSTRATE]
      ,[XPRICEUPD]
      ,[XPRICE]
      ,[XREPRATE]
      ,[DISTCOEF]
      ,[TRANSQCOK]
      ,[SITEID]
      ,[RECSTATUS]
      ,[ORGLOGICREF]
      ,[WFSTATUS]
      ,[POLINEREF]
      ,[PLNSTTRANSREF]
      ,[NETDISCFLAG]
      ,[NETDISCPERC]
      ,[NETDISCAMNT]
      ,[VATCALCDIFF]
      ,[CONDITIONREF]
      ,[DISTORDERREF]
      ,[DISTORDLINEREF]
      ,[CAMPAIGNREFS1]
      ,[CAMPAIGNREFS2]
      ,[CAMPAIGNREFS3]
      ,[CAMPAIGNREFS4]
      ,[CAMPAIGNREFS5]
      ,[POINTCAMPREF]
      ,[CAMPPOINT]
      ,[PROMCLASITEMREF]
      ,[CMPGLINEREF]
      ,[PLNSTTRANSPERNR]
      ,[PORDCLSPLNAMNT]
      ,[VENDCOMM]
      ,[PREVIOUSOUTCOST]
      ,[COSTOFSALEACCREF]
      ,[PURCHACCREF]
      ,[COSTOFSALECNTREF]
      ,[PURCHCENTREF]
      ,[PREVOUTCOSTCURR]
      ,[ABVATAMOUNT]
      ,[ABVATSTATUS]
      ,[PRRATE]
      ,[ADDTAXRATE]
      ,[ADDTAXCONVFACT]
      ,[ADDTAXAMOUNT]
      ,[ADDTAXPRCOST]
      ,[ADDTAXRETCOST]
      ,[ADDTAXRETCOSTCURR]
      ,[GROSSUINFO1]
      ,[GROSSUINFO2]
      ,[ADDTAXPRCOSTCURR]
      ,[ADDTAXACCREF]
      ,[ADDTAXCENTERREF]
      ,[ADDTAXAMNTISUPD]
      ,[INFIDX]
      ,[ADDTAXCOSACCREF]
      ,[ADDTAXCOSCNTREF]
      ,[PREVIOUSATAXPRCOST]
      ,[PREVATAXPRCOSTCURR]
      ,[PRDORDTOTCOEF]
      ,[DEMPEGGEDAMNT]
      ,[STDUNITCOST]
      ,[STDRPUNITCOST]
      ,[COSTDIFFACCREF]
      ,[COSTDIFFCENREF]
      ,[TEXTINC]
      ,[ADDTAXDISCAMOUNT]
      ,[ORGLOGOID]
      ,[EXIMFICHENO]
      ,[EXIMFCTYPE]
      ,[TRANSEXPLINE]
      ,[INSEXPLINE]
      ,[EXIMWHFCREF]
      ,[EXIMWHLNREF]
      ,[EXIMFILEREF]
      ,[EXIMPROCNR]
      ,[EISRVDSTTYP]
      ,[MAINSTLNREF]
      ,[MADEOFSHRED]
      ,[FROMORDWITHPAY]
      ,[PROJECTREF]
      ,[STATUS]
      ,[DORESERVE]
      ,[POINTCAMPREFS1]
      ,[POINTCAMPREFS2]
      ,[POINTCAMPREFS3]
      ,[POINTCAMPREFS4]
      ,[CAMPPOINTS1]
      ,[CAMPPOINTS2]
      ,[CAMPPOINTS3]
      ,[CAMPPOINTS4]
      ,[CMPGLINEREFS1]
      ,[CMPGLINEREFS2]
      ,[CMPGLINEREFS3]
      ,[CMPGLINEREFS4]
      ,[PRCLISTREF]
      ,[PORDSYMOUTLN]
      ,[MONTH_]
      ,[YEAR_]
      ,[EXADDTAXRATE]
      ,[EXADDTAXCONVF]
      ,[EXADDTAXAREF]
      ,[EXADDTAXCREF]
      ,[OTHRADDTAXAREF]
      ,[OTHRADDTAXCREF]
      ,[EXADDTAXAMNT]
      ,[AFFECTCOLLATRL]
      ,[ALTPROMFLAG]
      ,[EIDISTFLNNR]
      ,[EXIMTYPE]
      ,[VARIANTREF]
      ,[CANDEDUCT]
      ,[OUTREMAMNT]
      ,[OUTREMCOST]
      ,[OUTREMCOSTCURR]
      ,[REFLVATACCREF]
      ,[REFLVATOTHACCREF]
      ,[PARENTLNREF]
      ,[AFFECTRISK]
      ,[INEFFECTIVECOST]
      ,[ADDTAXVATMATRAH]
      ,[REFLACCREF]
      ,[REFLOTHACCREF]
      ,[CAMPPAYDEFREF]
      ,[FAREGBINDDATE]
      ,[RELTRANSLNREF]
      ,[FROMTRANSFER]
      ,[COSTDISTPRICE]
      ,[COSTDISTREPPRICE]
      ,[DIFFPRICEUFRS]
      ,[DIFFREPPRICEUFRS]
      ,[OUTCOSTUFRS]
      ,[OUTCOSTCURRUFRS]
      ,[DIFFPRCOSTUFRS]
      ,[DIFFPRCRCOSTUFRS]
      ,[RETCOSTUFRS]
      ,[RETCOSTCURRUFRS]
      ,[OUTREMCOSTUFRS]
      ,[OUTREMCOSTCURRUFRS]
      ,[INFIDXUFRS]
      ,[ADJPRICEUFRS]
      ,[ADJREPPRICEUFRS]
      ,[ADJPRCOSTUFRS]
      ,[ADJPRCRCOSTUFRS]
      ,[COSTDISTPRICEUFRS]
      ,[COSTDISTREPPRICEUFRS]
      ,[PURCHACCREFUFRS]
      ,[PURCHCENTREFUFRS]
      ,[COSACCREFUFRS]
      ,[COSCNTREFUFRS]
      ,[PROUTCOSTUFRSDIFF]
      ,[PROUTCOSTCRUFRSDIFF]
      ,[UNDERDEDUCTLIMIT]
      ,[GLOBALID]
      ,[DEDUCTIONPART1]
      ,[DEDUCTIONPART2]
  FROM CEZVE.[dbo].[LG_323_01_STLINE] WHERE STFICHEREF = @TIGERIRSALIYEREF

OPEN processes
 
FETCH NEXT FROM processes
INTO  @LOGICALREF,@STOCKREF,@LINETYPE,@PREVLINEREF,@PREVLINENO,@DETLINE,@TRCODE,@DATE_,@FTIME,@GLOBTRANS,@CALCTYPE,@PRODORDERREF,@SOURCETYPE,@SOURCEINDEX,@SOURCECOSTGRP,@SOURCEWSREF,@SOURCEPOLNREF,@DESTTYPE
,@DESTINDEX,@DESTCOSTGRP,@DESTWSREF,@DESTPOLNREF,@FACTORYNR,@IOCODE,@STFICHEREF,@STFICHELNNO,@INVOICEREF,@INVOICELNNO,@CLIENTREF,@ORDTRANSREF,@ORDFICHEREF,@CENTERREF,@ACCOUNTREF,@VATACCREF,@VATCENTERREF
,@PRACCREF,@PRCENTERREF,@PRVATACCREF,@PRVATCENREF,@PROMREF,@PAYDEFREF,@SPECODE,@DELVRYCODE,@AMOUNT,@PRICE,@TOTAL,@PRCURR,@PRPRICE,@TRCURR,@TRRATE,@REPORTRATE,@DISTCOST,@DISTDISC,@DISTEXP,@DISTPROM,@DISCPER
,@LINEEXP,@UOMREF,@USREF,@UINFO1,@UINFO2,@UINFO3,@UINFO4,@UINFO5,@UINFO6,@UINFO7,@UINFO8,@PLNAMOUNT,@VATINC,@VAT,@VATAMNT,@VATMATRAH,@BILLEDITEM,@BILLED,@CPSTFLAG,@RETCOSTTYPE,@SOURCELINK,@RETCOST,@RETCOSTCURR
,@OUTCOST,@OUTCOSTCURR,@RETAMOUNT,@FAREGREF,@FAATTRIB,@CANCELLED,@LINENET,@DISTADDEXP,@FADACCREF,@FADCENTERREF,@FARACCREF,@FARCENTERREF,@DIFFPRICE,@DIFFPRCOST,@DECPRDIFF,@LPRODSTAT,@PRDEXPTOTAL,@DIFFREPPRICE
,@DIFFPRCRCOST,@SALESMANREF,@FAPLACCREF,@FAPLCENTERREF,@OUTPUTIDCODE,@DREF,@COSTRATE,@XPRICEUPD,@XPRICE,@XREPRATE,@DISTCOEF,@TRANSQCOK,@SITEID,@RECSTATUS,@ORGLOGICREF,@WFSTATUS,@POLINEREF,@PLNSTTRANSREF
,@NETDISCFLAG,@NETDISCPERC,@NETDISCAMNT,@VATCALCDIFF,@CONDITIONREF,@DISTORDERREF,@DISTORDLINEREF,@CAMPAIGNREFS1,@CAMPAIGNREFS2,@CAMPAIGNREFS3,@CAMPAIGNREFS4,@CAMPAIGNREFS5,@POINTCAMPREF,@CAMPPOINT,@PROMCLASITEMREF
,@CMPGLINEREF,@PLNSTTRANSPERNR,@PORDCLSPLNAMNT,@VENDCOMM,@PREVIOUSOUTCOST,@COSTOFSALEACCREF,@PURCHACCREF,@COSTOFSALECNTREF,@PURCHCENTREF,@PREVOUTCOSTCURR,@ABVATAMOUNT,@ABVATSTATUS,@PRRATE,@ADDTAXRATE
,@ADDTAXCONVFACT,@ADDTAXAMOUNT,@ADDTAXPRCOST,@ADDTAXRETCOST,@ADDTAXRETCOSTCURR,@GROSSUINFO1,@GROSSUINFO2,@ADDTAXPRCOSTCURR,@ADDTAXACCREF,@ADDTAXCENTERREF,@ADDTAXAMNTISUPD,@INFIDX,@ADDTAXCOSACCREF,@ADDTAXCOSCNTREF
,@PREVIOUSATAXPRCOST,@PREVATAXPRCOSTCURR,@PRDORDTOTCOEF,@DEMPEGGEDAMNT,@STDUNITCOST,@STDRPUNITCOST,@COSTDIFFACCREF,@COSTDIFFCENREF,@TEXTINC,@ADDTAXDISCAMOUNT,@ORGLOGOID,@EXIMFICHENO,@EXIMFCTYPE,@TRANSEXPLINE
,@INSEXPLINE,@EXIMWHFCREF,@EXIMWHLNREF,@EXIMFILEREF,@EXIMPROCNR,@EISRVDSTTYP,@MAINSTLNREF,@MADEOFSHRED,@FROMORDWITHPAY,@PROJECTREF,@STATUS,@DORESERVE,@POINTCAMPREFS1,@POINTCAMPREFS2,@POINTCAMPREFS3
,@POINTCAMPREFS4,@CAMPPOINTS1,@CAMPPOINTS2,@CAMPPOINTS3,@CAMPPOINTS4,@CMPGLINEREFS1,@CMPGLINEREFS2,@CMPGLINEREFS3,@CMPGLINEREFS4,@PRCLISTREF,@PORDSYMOUTLN,@MONTH_,@YEAR_,@EXADDTAXRATE,@EXADDTAXCONVF,@EXADDTAXAREF
,@EXADDTAXCREF,@OTHRADDTAXAREF,@OTHRADDTAXCREF,@EXADDTAXAMNT,@AFFECTCOLLATRL,@ALTPROMFLAG,@EIDISTFLNNR,@EXIMTYPE,@VARIANTREF,@CANDEDUCT,@OUTREMAMNT,@OUTREMCOST,@OUTREMCOSTCURR,@REFLVATACCREF,@REFLVATOTHACCREF,@PARENTLNREF
,@AFFECTRISK,@INEFFECTIVECOST,@ADDTAXVATMATRAH,@REFLACCREF,@REFLOTHACCREF,@CAMPPAYDEFREF,@FAREGBINDDATE,@RELTRANSLNREF,@FROMTRANSFER,@COSTDISTPRICE,@COSTDISTREPPRICE,@DIFFPRICEUFRS,@DIFFREPPRICEUFRS
,@OUTCOSTUFRS,@OUTCOSTCURRUFRS,@DIFFPRCOSTUFRS,@DIFFPRCRCOSTUFRS,@RETCOSTUFRS,@RETCOSTCURRUFRS,@OUTREMCOSTUFRS,@OUTREMCOSTCURRUFRS,@INFIDXUFRS,@ADJPRICEUFRS,@ADJREPPRICEUFRS,@ADJPRCOSTUFRS,@ADJPRCRCOSTUFRS
,@COSTDISTPRICEUFRS,@COSTDISTREPPRICEUFRS,@PURCHACCREFUFRS,@PURCHCENTREFUFRS,@COSACCREFUFRS,@COSCNTREFUFRS,@PROUTCOSTUFRSDIFF,@PROUTCOSTCRUFRSDIFF,@UNDERDEDUCTLIMIT,@GLOBALID,@DEDUCTIONPART1,@DEDUCTIONPART2
WHILE @@FETCH_STATUS = 0
BEGIN
        --3 REFERANSLARA DÝKKAT EDÝLECEK
		--SELECT * FROM GO3DB..LG_423_01_STLINE WHERE STFICHEREF = 12326
		--SELECT * FROM CEZVE..LG_323_ITEMS TGRCL WHERE TGRCL.LOGICALREF=   886
	SET @STOCKREF = ( SELECT LOGICALREF FROM GO3DB..LG_423_ITEMS GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 PRODUCERCODE FROM CEZVE..LG_323_ITEMS TGRCL WHERE TGRCL.LOGICALREF=   @CLIENTREF))
	SET @ACCOUNTREF = ( SELECT LOGICALREF FROM GO3DB..LG_423_EMUHACC GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 CODE FROM CEZVE..LG_323_EMUHACC TGRCL WHERE TGRCL.LOGICALREF=   @CLIENTREF))
	SET @VATACCREF = ( SELECT LOGICALREF FROM GO3DB..LG_423_EMUHACC GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 CODE FROM CEZVE..LG_323_EMUHACC TGRCL WHERE TGRCL.LOGICALREF=   @CLIENTREF))
	SET @PURCHACCREF = ( SELECT LOGICALREF FROM GO3DB..LG_423_EMUHACC GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 CODE FROM CEZVE..LG_323_EMUHACC TGRCL WHERE TGRCL.LOGICALREF=   @CLIENTREF)) --2482
	SET @PURCHACCREFUFRS = ( SELECT LOGICALREF FROM GO3DB..LG_423_EMUHACC GOCL WITH(NOLOCK) WHERE GOCL.CODE IN (SELECT TOP 1 CODE FROM CEZVE..LG_323_EMUHACC TGRCL WHERE TGRCL.LOGICALREF=   @CLIENTREF)) --2482
      
INSERT INTO GO3DB.[dbo].[LG_423_01_STLINE]
           ([STOCKREF]
           ,[LINETYPE]
           ,[PREVLINEREF]
           ,[PREVLINENO]
           ,[DETLINE]
           ,[TRCODE]
           ,[DATE_]
           ,[FTIME]
           ,[GLOBTRANS]
           ,[CALCTYPE]
           ,[PRODORDERREF]
           ,[SOURCETYPE]
           ,[SOURCEINDEX]
           ,[SOURCECOSTGRP]
           ,[SOURCEWSREF]
           ,[SOURCEPOLNREF]
           ,[DESTTYPE]
           ,[DESTINDEX]
           ,[DESTCOSTGRP]
           ,[DESTWSREF]
           ,[DESTPOLNREF]
           ,[FACTORYNR]
           ,[IOCODE]
           ,[STFICHEREF]
           ,[STFICHELNNO]
           ,[INVOICEREF]
           ,[INVOICELNNO]
           ,[CLIENTREF]
           ,[ORDTRANSREF]
           ,[ORDFICHEREF]
           ,[CENTERREF]
           ,[ACCOUNTREF]
           ,[VATACCREF]
           ,[VATCENTERREF]
           ,[PRACCREF]
           ,[PRCENTERREF]
           ,[PRVATACCREF]
           ,[PRVATCENREF]
           ,[PROMREF]
           ,[PAYDEFREF]
           ,[SPECODE]
           ,[DELVRYCODE]
           ,[AMOUNT]
           ,[PRICE]
           ,[TOTAL]
           ,[PRCURR]
           ,[PRPRICE]
           ,[TRCURR]
           ,[TRRATE]
           ,[REPORTRATE]
           ,[DISTCOST]
           ,[DISTDISC]
           ,[DISTEXP]
           ,[DISTPROM]
           ,[DISCPER]
           ,[LINEEXP]
           ,[UOMREF]
           ,[USREF]
           ,[UINFO1]
           ,[UINFO2]
           ,[UINFO3]
           ,[UINFO4]
           ,[UINFO5]
           ,[UINFO6]
           ,[UINFO7]
           ,[UINFO8]
           ,[PLNAMOUNT]
           ,[VATINC]
           ,[VAT]
           ,[VATAMNT]
           ,[VATMATRAH]
           ,[BILLEDITEM]
           ,[BILLED]
           ,[CPSTFLAG]
           ,[RETCOSTTYPE]
           ,[SOURCELINK]
           ,[RETCOST]
           ,[RETCOSTCURR]
           ,[OUTCOST]
           ,[OUTCOSTCURR]
           ,[RETAMOUNT]
           ,[FAREGREF]
           ,[FAATTRIB]
           ,[CANCELLED]
           ,[LINENET]
           ,[DISTADDEXP]
           ,[FADACCREF]
           ,[FADCENTERREF]
           ,[FARACCREF]
           ,[FARCENTERREF]
           ,[DIFFPRICE]
           ,[DIFFPRCOST]
           ,[DECPRDIFF]
           ,[LPRODSTAT]
           ,[PRDEXPTOTAL]
           ,[DIFFREPPRICE]
           ,[DIFFPRCRCOST]
           ,[SALESMANREF]
           ,[FAPLACCREF]
           ,[FAPLCENTERREF]
           ,[OUTPUTIDCODE]
           ,[DREF]
           ,[COSTRATE]
           ,[XPRICEUPD]
           ,[XPRICE]
           ,[XREPRATE]
           ,[DISTCOEF]
           ,[TRANSQCOK]
           ,[SITEID]
           ,[RECSTATUS]
           ,[ORGLOGICREF]
           ,[WFSTATUS]
           ,[POLINEREF]
           ,[PLNSTTRANSREF]
           ,[NETDISCFLAG]
           ,[NETDISCPERC]
           ,[NETDISCAMNT]
           ,[VATCALCDIFF]
           ,[CONDITIONREF]
           ,[DISTORDERREF]
           ,[DISTORDLINEREF]
           ,[CAMPAIGNREFS1]
           ,[CAMPAIGNREFS2]
           ,[CAMPAIGNREFS3]
           ,[CAMPAIGNREFS4]
           ,[CAMPAIGNREFS5]
           ,[POINTCAMPREF]
           ,[CAMPPOINT]
           ,[PROMCLASITEMREF]
           ,[CMPGLINEREF]
           ,[PLNSTTRANSPERNR]
           ,[PORDCLSPLNAMNT]
           ,[VENDCOMM]
           ,[PREVIOUSOUTCOST]
           ,[COSTOFSALEACCREF]
           ,[PURCHACCREF]
           ,[COSTOFSALECNTREF]
           ,[PURCHCENTREF]
           ,[PREVOUTCOSTCURR]
           ,[ABVATAMOUNT]
           ,[ABVATSTATUS]
           ,[PRRATE]
           ,[ADDTAXRATE]
           ,[ADDTAXCONVFACT]
           ,[ADDTAXAMOUNT]
           ,[ADDTAXPRCOST]
           ,[ADDTAXRETCOST]
           ,[ADDTAXRETCOSTCURR]
           ,[GROSSUINFO1]
           ,[GROSSUINFO2]
           ,[ADDTAXPRCOSTCURR]
           ,[ADDTAXACCREF]
           ,[ADDTAXCENTERREF]
           ,[ADDTAXAMNTISUPD]
           ,[INFIDX]
           ,[ADDTAXCOSACCREF]
           ,[ADDTAXCOSCNTREF]
           ,[PREVIOUSATAXPRCOST]
           ,[PREVATAXPRCOSTCURR]
           ,[PRDORDTOTCOEF]
           ,[DEMPEGGEDAMNT]
           ,[STDUNITCOST]
           ,[STDRPUNITCOST]
           ,[COSTDIFFACCREF]
           ,[COSTDIFFCENREF]
           ,[TEXTINC]
           ,[ADDTAXDISCAMOUNT]
           ,[ORGLOGOID]
           ,[EXIMFICHENO]
           ,[EXIMFCTYPE]
           ,[TRANSEXPLINE]
           ,[INSEXPLINE]
           ,[EXIMWHFCREF]
           ,[EXIMWHLNREF]
           ,[EXIMFILEREF]
           ,[EXIMPROCNR]
           ,[EISRVDSTTYP]
           ,[MAINSTLNREF]
           ,[MADEOFSHRED]
           ,[FROMORDWITHPAY]
           ,[PROJECTREF]
           ,[STATUS]
           ,[DORESERVE]
           ,[POINTCAMPREFS1]
           ,[POINTCAMPREFS2]
           ,[POINTCAMPREFS3]
           ,[POINTCAMPREFS4]
           ,[CAMPPOINTS1]
           ,[CAMPPOINTS2]
           ,[CAMPPOINTS3]
           ,[CAMPPOINTS4]
           ,[CMPGLINEREFS1]
           ,[CMPGLINEREFS2]
           ,[CMPGLINEREFS3]
           ,[CMPGLINEREFS4]
           ,[PRCLISTREF]
           ,[PORDSYMOUTLN]
           ,[MONTH_]
           ,[YEAR_]
           ,[EXADDTAXRATE]
           ,[EXADDTAXCONVF]
           ,[EXADDTAXAREF]
           ,[EXADDTAXCREF]
           ,[OTHRADDTAXAREF]
           ,[OTHRADDTAXCREF]
           ,[EXADDTAXAMNT]
           ,[AFFECTCOLLATRL]
           ,[ALTPROMFLAG]
           ,[EIDISTFLNNR]
           ,[EXIMTYPE]
           ,[VARIANTREF]
           ,[CANDEDUCT]
           ,[OUTREMAMNT]
           ,[OUTREMCOST]
           ,[OUTREMCOSTCURR]
           ,[REFLVATACCREF]
           ,[REFLVATOTHACCREF]
           ,[PARENTLNREF]
           ,[AFFECTRISK]
           ,[INEFFECTIVECOST]
           ,[ADDTAXVATMATRAH]
           ,[REFLACCREF]
           ,[REFLOTHACCREF]
           ,[CAMPPAYDEFREF]
           ,[FAREGBINDDATE]
           ,[RELTRANSLNREF]
           ,[FROMTRANSFER]
           ,[COSTDISTPRICE]
           ,[COSTDISTREPPRICE]
           ,[DIFFPRICEUFRS]
           ,[DIFFREPPRICEUFRS]
           ,[OUTCOSTUFRS]
           ,[OUTCOSTCURRUFRS]
           ,[DIFFPRCOSTUFRS]
           ,[DIFFPRCRCOSTUFRS]
           ,[RETCOSTUFRS]
           ,[RETCOSTCURRUFRS]
           ,[OUTREMCOSTUFRS]
           ,[OUTREMCOSTCURRUFRS]
           ,[INFIDXUFRS]
           ,[ADJPRICEUFRS]
           ,[ADJREPPRICEUFRS]
           ,[ADJPRCOSTUFRS]
           ,[ADJPRCRCOSTUFRS]
           ,[COSTDISTPRICEUFRS]
           ,[COSTDISTREPPRICEUFRS]
           ,[PURCHACCREFUFRS]
           ,[PURCHCENTREFUFRS]
           ,[COSACCREFUFRS]
           ,[COSCNTREFUFRS]
           ,[PROUTCOSTUFRSDIFF]
           ,[PROUTCOSTCRUFRSDIFF]
           ,[UNDERDEDUCTLIMIT]
           ,[GLOBALID]
           ,[DEDUCTIONPART1]
           ,[DEDUCTIONPART2]
           ,[GUID]
           ,[SPECODE2]
           ,[OFFERREF]
           ,[OFFTRANSREF]
           ,[VATEXCEPTREASON]
           ,[PLNDEFSERILOTNO]
           ,[PLNUNRSRVAMOUNT]
           ,[PORDCLSPLNUNRSRVAMNT]
           ,[LPRODRSRVSTAT]
           ,[FALINKTYPE]
           ,[DEDUCTCODE]
           ,[UPDTHISLINE]
           ,[VATEXCEPTCODE]
           ,[PORDERFICHENO]
           ,[QPRODFCREF]
           ,[RELTRANSFCREF]
           ,[ATAXEXCEPTREASON]
           ,[ATAXEXCEPTCODE]
           ,[PRODORDERTYP]
           ,[SUBCONTORDERREF]
           ,[QPRODFCTYP]
           ,[PRDORDSLPLNRESERVE]
           ,[INFDATE]
           ,[DESTSTATUS]
           ,[REGTYPREF]
           ,[FAPROFITACCREF]
           ,[FAPROFITCENTREF]
           ,[FALOSSACCREF]
           ,[FALOSSCENTREF]
           ,[CPACODE]
           ,[GTIPCODE]
           ,[PUBLICCOUNTRYREF]
           ,[QPRODITEMTYPE]
           ,[FUTMONTHCNT]
           ,[FUTMONTHBEGDATE]
           ,[QCTRANSFERREF]
           ,[QCTRANSFERAMNT]
           ,[FUTMONTHENDDATE]
           ,[KKEGACCREF]
           ,[KKEGCENTREF]
           ,[MNTORDERFREF]
           ,[FAKKEGAMOUNT]
           ,[MIDDLEMANEXPTYP]
           ,[EXPRACCREF]
           ,[EXPRCNTRREF]
           ,[KKEGVATACCREF]
           ,[KKEGVATCENTREF]
           ,[MARKINGTAGNO]
           ,[OWNER]
           ,[TCKTAXNR]
           ,[FUTMONTHBEGDATE_]
           ,[ADDTAXVATACCREF]
           ,[ADDTAXVATCENREF]
           ,[TAXFREECNTRREF]
           ,[TAXFREEACCREF]
           ,[FROMINTEGREF]
           ,[QCTRANSFERAMNT2]
           ,[QCTRANSFERREF2]
           ,[EISRVDSTADDTAXINC]
           ,[CANCELLEDINVREF2]
           ,[CANCELLEDINVREF1]
           ,[EXPDAYS]
           ,[FROMINTEGTYPE]
           ,[CANCELLEDINVREF4]
           ,[CANCELLEDINVREF3])
     VALUES
           ( @STOCKREF
           ,@LINETYPE
           ,@PREVLINEREF
           ,@PREVLINENO
           ,@DETLINE
           ,@TRCODE
           ,@DATE_
           ,@FTIME
           ,@GLOBTRANS
           ,@CALCTYPE
           ,@PRODORDERREF
           ,@SOURCETYPE
           ,@SOURCEINDEX
           ,@SOURCECOSTGRP
           ,@SOURCEWSREF
           ,@SOURCEPOLNREF
           ,@DESTTYPE
           ,@DESTINDEX
           ,@DESTCOSTGRP
           ,@DESTWSREF
           ,@DESTPOLNREF
           ,@FACTORYNR
           ,@IOCODE
           ,@STFICHEREF
           ,@STFICHELNNO
           ,@INVOICEREF
           ,@INVOICELNNO
           ,@CLIENTREF
           ,@ORDTRANSREF
           ,@ORDFICHEREF
           ,@CENTERREF
           ,@ACCOUNTREF
           ,@VATACCREF
           ,@VATCENTERREF
           ,@PRACCREF
           ,@PRCENTERREF
           ,@PRVATACCREF
           ,@PRVATCENREF
           ,@PROMREF
           ,@PAYDEFREF
           ,@SPECODE
           ,@DELVRYCODE
           ,@AMOUNT
           ,@PRICE
           ,@TOTAL
           ,@PRCURR
           ,@PRPRICE
           ,@TRCURR
           ,@TRRATE
           ,@REPORTRATE
           ,@DISTCOST
           ,@DISTDISC
           ,@DISTEXP
           ,@DISTPROM
           ,@DISCPER
           ,@LINEEXP
           ,@UOMREF
           ,@USREF
           ,@UINFO1
           ,@UINFO2
           ,@UINFO3
           ,@UINFO4
           ,@UINFO5
           ,@UINFO6
           ,@UINFO7
           ,@UINFO8
           ,@PLNAMOUNT
           ,@VATINC
           ,@VAT
           ,@VATAMNT
           ,@VATMATRAH
           ,@BILLEDITEM
           ,@BILLED
           ,@CPSTFLAG
           ,@RETCOSTTYPE
           ,@SOURCELINK
           ,@RETCOST
           ,@RETCOSTCURR
           ,@OUTCOST
           ,@OUTCOSTCURR
           ,@RETAMOUNT
           ,@FAREGREF
           ,@FAATTRIB
           ,@CANCELLED
           ,@LINENET
           ,@DISTADDEXP
           ,@FADACCREF
           ,@FADCENTERREF
           ,@FARACCREF
           ,@FARCENTERREF
           ,@DIFFPRICE
           ,@DIFFPRCOST
           ,@DECPRDIFF
           ,@LPRODSTAT
           ,@PRDEXPTOTAL
           ,@DIFFREPPRICE
           ,@DIFFPRCRCOST
           ,@SALESMANREF
           ,@FAPLACCREF
           ,@FAPLCENTERREF
           ,@OUTPUTIDCODE
           ,@DREF
           ,@COSTRATE
           ,@XPRICEUPD
           ,@XPRICE
           ,@XREPRATE
           ,@DISTCOEF
           ,@TRANSQCOK
           ,@SITEID
           ,@RECSTATUS
           ,@ORGLOGICREF
           ,@WFSTATUS
           ,@POLINEREF
           ,@PLNSTTRANSREF
           ,@NETDISCFLAG
           ,@NETDISCPERC
           ,@NETDISCAMNT
           ,@VATCALCDIFF
           ,@CONDITIONREF
           ,@DISTORDERREF
           ,@DISTORDLINEREF
           ,@CAMPAIGNREFS1
           ,@CAMPAIGNREFS2
           ,@CAMPAIGNREFS3
           ,@CAMPAIGNREFS4
           ,@CAMPAIGNREFS5
           ,@POINTCAMPREF
           ,@CAMPPOINT
           ,@PROMCLASITEMREF
           ,@CMPGLINEREF
           ,@PLNSTTRANSPERNR
           ,@PORDCLSPLNAMNT
           ,@VENDCOMM
           ,@PREVIOUSOUTCOST
           ,@COSTOFSALEACCREF
           ,@PURCHACCREF
           ,@COSTOFSALECNTREF
           ,@PURCHCENTREF
           ,@PREVOUTCOSTCURR
           ,@ABVATAMOUNT
           ,@ABVATSTATUS
           ,@PRRATE
           ,@ADDTAXRATE
           ,@ADDTAXCONVFACT
           ,@ADDTAXAMOUNT
           ,@ADDTAXPRCOST
           ,@ADDTAXRETCOST
           ,@ADDTAXRETCOSTCURR
           ,@GROSSUINFO1
           ,@GROSSUINFO2
           ,@ADDTAXPRCOSTCURR
           ,@ADDTAXACCREF
           ,@ADDTAXCENTERREF
           ,@ADDTAXAMNTISUPD
           ,@INFIDX
           ,@ADDTAXCOSACCREF
           ,@ADDTAXCOSCNTREF
           ,@PREVIOUSATAXPRCOST
           ,@PREVATAXPRCOSTCURR
           ,@PRDORDTOTCOEF
           ,@DEMPEGGEDAMNT
           ,@STDUNITCOST
           ,@STDRPUNITCOST
           ,@COSTDIFFACCREF
           ,@COSTDIFFCENREF
           ,@TEXTINC
           ,@ADDTAXDISCAMOUNT
           ,@ORGLOGOID
           ,@EXIMFICHENO
           ,@EXIMFCTYPE
           ,@TRANSEXPLINE
           ,@INSEXPLINE
           ,@EXIMWHFCREF
           ,@EXIMWHLNREF
           ,@EXIMFILEREF
           ,@EXIMPROCNR
           ,@EISRVDSTTYP
           ,@MAINSTLNREF
           ,@MADEOFSHRED
           ,@FROMORDWITHPAY
           ,@PROJECTREF
           ,@STATUS
           ,@DORESERVE
           ,@POINTCAMPREFS1
           ,@POINTCAMPREFS2
           ,@POINTCAMPREFS3
           ,@POINTCAMPREFS4
           ,@CAMPPOINTS1
           ,@CAMPPOINTS2
           ,@CAMPPOINTS3
           ,@CAMPPOINTS4
           ,@CMPGLINEREFS1
           ,@CMPGLINEREFS2
           ,@CMPGLINEREFS3
           ,@CMPGLINEREFS4
           ,@PRCLISTREF
           ,@PORDSYMOUTLN
           ,@MONTH_
           ,@YEAR_
           ,@EXADDTAXRATE
           ,@EXADDTAXCONVF
           ,@EXADDTAXAREF
           ,@EXADDTAXCREF
           ,@OTHRADDTAXAREF
           ,@OTHRADDTAXCREF
           ,@EXADDTAXAMNT
           ,@AFFECTCOLLATRL
           ,@ALTPROMFLAG
           ,@EIDISTFLNNR
           ,@EXIMTYPE
           ,@VARIANTREF
           ,@CANDEDUCT
           ,@OUTREMAMNT
           ,@OUTREMCOST
           ,@OUTREMCOSTCURR
           ,@REFLVATACCREF
           ,@REFLVATOTHACCREF
           ,@PARENTLNREF
           ,@AFFECTRISK
           ,@INEFFECTIVECOST
           ,@ADDTAXVATMATRAH
           ,@REFLACCREF
           ,@REFLOTHACCREF
           ,@CAMPPAYDEFREF
           ,@FAREGBINDDATE
           ,@RELTRANSLNREF
           ,@FROMTRANSFER
           ,@COSTDISTPRICE
           ,@COSTDISTREPPRICE
           ,@DIFFPRICEUFRS
           ,@DIFFREPPRICEUFRS
           ,@OUTCOSTUFRS
           ,@OUTCOSTCURRUFRS
           ,@DIFFPRCOSTUFRS
           ,@DIFFPRCRCOSTUFRS
           ,@RETCOSTUFRS
           ,@RETCOSTCURRUFRS
           ,@OUTREMCOSTUFRS
           ,@OUTREMCOSTCURRUFRS
           ,@INFIDXUFRS
           ,@ADJPRICEUFRS
           ,@ADJREPPRICEUFRS
           ,@ADJPRCOSTUFRS
           ,@ADJPRCRCOSTUFRS
           ,@COSTDISTPRICEUFRS
           ,@COSTDISTREPPRICEUFRS
           ,@PURCHACCREFUFRS
           ,@PURCHCENTREFUFRS
           ,@COSACCREFUFRS
           ,@COSCNTREFUFRS
           ,@PROUTCOSTUFRSDIFF
           ,@PROUTCOSTCRUFRSDIFF
           ,@UNDERDEDUCTLIMIT
           ,@GLOBALID
           ,@DEDUCTIONPART1
           ,@DEDUCTIONPART2
           ,@GUID 
           ,@SPECODE2 
           ,@OFFERREF
           ,@OFFTRANSREF
           ,@VATEXCEPTREASON 
           ,@PLNDEFSERILOTNO 
           ,@PLNUNRSRVAMOUNT
           ,@PORDCLSPLNUNRSRVAMNT
           ,@LPRODRSRVSTAT
           ,@FALINKTYPE
           ,@DEDUCTCODE
           ,@UPDTHISLINE
           ,@VATEXCEPTCODE
           ,@PORDERFICHENO
           ,@QPRODFCREF
           ,@RELTRANSFCREF
           ,@ATAXEXCEPTREASON 
           ,@ATAXEXCEPTCODE
           ,@PRODORDERTYP
           ,@SUBCONTORDERREF
           ,@QPRODFCTYP
           ,@PRDORDSLPLNRESERVE
           ,@INFDATE
           ,@DESTSTATUS
           ,@REGTYPREF
           ,@FAPROFITACCREF
           ,@FAPROFITCENTREF
           ,@FALOSSACCREF
           ,@FALOSSCENTREF
           ,@CPACODE
           ,@GTIPCODE
           ,@PUBLICCOUNTRYREF
           ,@QPRODITEMTYPE
           ,@FUTMONTHCNT
           ,@FUTMONTHBEGDATE
           ,@QCTRANSFERREF
           ,@QCTRANSFERAMNT
           ,@FUTMONTHENDDATE
           ,@KKEGACCREF
           ,@KKEGCENTREF
           ,@MNTORDERFREF
           ,@FAKKEGAMOUNT
           ,@MIDDLEMANEXPTYP
           ,@EXPRACCREF
           ,@EXPRCNTRREF
           ,@KKEGVATACCREF
           ,@KKEGVATCENTREF
           ,@MARKINGTAGNO 
           ,@OWNER 
           ,@TCKTAXNR 
           ,@FUTMONTHBEGDATE_
           ,@ADDTAXVATACCREF
           ,@ADDTAXVATCENREF
           ,@TAXFREECNTRREF
           ,@TAXFREEACCREF
           ,@FROMINTEGREF
           ,@QCTRANSFERAMNT2
           ,@QCTRANSFERREF2
           ,@EISRVDSTADDTAXINC
           ,@CANCELLEDINVREF2
           ,@CANCELLEDINVREF1
           ,@EXPDAYS
           ,@FROMINTEGTYPE
           ,@CANCELLEDINVREF4
           ,@CANCELLEDINVREF3)

		   
FETCH NEXT FROM processes
INTO  @LOGICALREF,@STOCKREF,@LINETYPE,@PREVLINEREF,@PREVLINENO,@DETLINE,@TRCODE,@DATE_,@FTIME,@GLOBTRANS,@CALCTYPE,@PRODORDERREF,@SOURCETYPE,@SOURCEINDEX,@SOURCECOSTGRP,@SOURCEWSREF,@SOURCEPOLNREF,@DESTTYPE
,@DESTINDEX,@DESTCOSTGRP,@DESTWSREF,@DESTPOLNREF,@FACTORYNR,@IOCODE,@STFICHEREF,@STFICHELNNO,@INVOICEREF,@INVOICELNNO,@CLIENTREF,@ORDTRANSREF,@ORDFICHEREF,@CENTERREF,@ACCOUNTREF,@VATACCREF,@VATCENTERREF
,@PRACCREF,@PRCENTERREF,@PRVATACCREF,@PRVATCENREF,@PROMREF,@PAYDEFREF,@SPECODE,@DELVRYCODE,@AMOUNT,@PRICE,@TOTAL,@PRCURR,@PRPRICE,@TRCURR,@TRRATE,@REPORTRATE,@DISTCOST,@DISTDISC,@DISTEXP,@DISTPROM,@DISCPER
,@LINEEXP,@UOMREF,@USREF,@UINFO1,@UINFO2,@UINFO3,@UINFO4,@UINFO5,@UINFO6,@UINFO7,@UINFO8,@PLNAMOUNT,@VATINC,@VAT,@VATAMNT,@VATMATRAH,@BILLEDITEM,@BILLED,@CPSTFLAG,@RETCOSTTYPE,@SOURCELINK,@RETCOST,@RETCOSTCURR
,@OUTCOST,@OUTCOSTCURR,@RETAMOUNT,@FAREGREF,@FAATTRIB,@CANCELLED,@LINENET,@DISTADDEXP,@FADACCREF,@FADCENTERREF,@FARACCREF,@FARCENTERREF,@DIFFPRICE,@DIFFPRCOST,@DECPRDIFF,@LPRODSTAT,@PRDEXPTOTAL,@DIFFREPPRICE
,@DIFFPRCRCOST,@SALESMANREF,@FAPLACCREF,@FAPLCENTERREF,@OUTPUTIDCODE,@DREF,@COSTRATE,@XPRICEUPD,@XPRICE,@XREPRATE,@DISTCOEF,@TRANSQCOK,@SITEID,@RECSTATUS,@ORGLOGICREF,@WFSTATUS,@POLINEREF,@PLNSTTRANSREF
,@NETDISCFLAG,@NETDISCPERC,@NETDISCAMNT,@VATCALCDIFF,@CONDITIONREF,@DISTORDERREF,@DISTORDLINEREF,@CAMPAIGNREFS1,@CAMPAIGNREFS2,@CAMPAIGNREFS3,@CAMPAIGNREFS4,@CAMPAIGNREFS5,@POINTCAMPREF,@CAMPPOINT,@PROMCLASITEMREF
,@CMPGLINEREF,@PLNSTTRANSPERNR,@PORDCLSPLNAMNT,@VENDCOMM,@PREVIOUSOUTCOST,@COSTOFSALEACCREF,@PURCHACCREF,@COSTOFSALECNTREF,@PURCHCENTREF,@PREVOUTCOSTCURR,@ABVATAMOUNT,@ABVATSTATUS,@PRRATE,@ADDTAXRATE
,@ADDTAXCONVFACT,@ADDTAXAMOUNT,@ADDTAXPRCOST,@ADDTAXRETCOST,@ADDTAXRETCOSTCURR,@GROSSUINFO1,@GROSSUINFO2,@ADDTAXPRCOSTCURR,@ADDTAXACCREF,@ADDTAXCENTERREF,@ADDTAXAMNTISUPD,@INFIDX,@ADDTAXCOSACCREF,@ADDTAXCOSCNTREF
,@PREVIOUSATAXPRCOST,@PREVATAXPRCOSTCURR,@PRDORDTOTCOEF,@DEMPEGGEDAMNT,@STDUNITCOST,@STDRPUNITCOST,@COSTDIFFACCREF,@COSTDIFFCENREF,@TEXTINC,@ADDTAXDISCAMOUNT,@ORGLOGOID,@EXIMFICHENO,@EXIMFCTYPE,@TRANSEXPLINE
,@INSEXPLINE,@EXIMWHFCREF,@EXIMWHLNREF,@EXIMFILEREF,@EXIMPROCNR,@EISRVDSTTYP,@MAINSTLNREF,@MADEOFSHRED,@FROMORDWITHPAY,@PROJECTREF,@STATUS,@DORESERVE,@POINTCAMPREFS1,@POINTCAMPREFS2,@POINTCAMPREFS3
,@POINTCAMPREFS4,@CAMPPOINTS1,@CAMPPOINTS2,@CAMPPOINTS3,@CAMPPOINTS4,@CMPGLINEREFS1,@CMPGLINEREFS2,@CMPGLINEREFS3,@CMPGLINEREFS4,@PRCLISTREF,@PORDSYMOUTLN,@MONTH_,@YEAR_,@EXADDTAXRATE,@EXADDTAXCONVF,@EXADDTAXAREF
,@EXADDTAXCREF,@OTHRADDTAXAREF,@OTHRADDTAXCREF,@EXADDTAXAMNT,@AFFECTCOLLATRL,@ALTPROMFLAG,@EIDISTFLNNR,@EXIMTYPE,@VARIANTREF,@CANDEDUCT,@OUTREMAMNT,@OUTREMCOST,@OUTREMCOSTCURR,@REFLVATACCREF,@REFLVATOTHACCREF,@PARENTLNREF
,@AFFECTRISK,@INEFFECTIVECOST,@ADDTAXVATMATRAH,@REFLACCREF,@REFLOTHACCREF,@CAMPPAYDEFREF,@FAREGBINDDATE,@RELTRANSLNREF,@FROMTRANSFER,@COSTDISTPRICE,@COSTDISTREPPRICE,@DIFFPRICEUFRS,@DIFFREPPRICEUFRS
,@OUTCOSTUFRS,@OUTCOSTCURRUFRS,@DIFFPRCOSTUFRS,@DIFFPRCRCOSTUFRS,@RETCOSTUFRS,@RETCOSTCURRUFRS,@OUTREMCOSTUFRS,@OUTREMCOSTCURRUFRS,@INFIDXUFRS,@ADJPRICEUFRS,@ADJREPPRICEUFRS,@ADJPRCOSTUFRS,@ADJPRCRCOSTUFRS
,@COSTDISTPRICEUFRS,@COSTDISTREPPRICEUFRS,@PURCHACCREFUFRS,@PURCHCENTREFUFRS,@COSACCREFUFRS,@COSCNTREFUFRS,@PROUTCOSTUFRSDIFF,@PROUTCOSTCRUFRSDIFF,@UNDERDEDUCTLIMIT,@GLOBALID,@DEDUCTIONPART1,@DEDUCTIONPART2
END

END


