USE [AltinCezveB2B_Default_v1]
GO

/****** Object:  View [dbo].[VW_TigerSatisFISsiKontrolListesi]    Script Date: 14.02.2024 14:10:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*
SELECT INV.FICHENO AS TIGERFISNO, 
T_CL.DEFINITION_ AS CARIADI,
G_CL.CODE, T_CL.CODE FROM CEZVE..LG_324_01_STFICHE T_CLF
left join CEZVE..LG_324_01_CLFICHE INV ON INV.LOGICALREF = T_CLF.CLFICHEREF
left JOIN CEZVE..LG_324_CLCARD T_CL ON T_CL.LOGICALREF = T_CLF.CLIENTREF
left JOIN GO3DB..LG_424_CLCARD G_CL ON G_CL.CODE = T_CL.CODE
WHERE T_CLF.CLFICHEREF <> 0 AND T_CLF.TRCODE IN (4, 8)

*/

--ALTER VIEW [dbo].[VW_CariHesapFisiKontrolListesi] as 
SELECT 
 ROW_NUMBER() over (order by T_CLF.FICHENO) as ID,
 T_CLF.DATE_ AS FISTARIHI,
T_CLF.TRCODE,
dbo.Ay_isl('cl',T_CLF.TRCODE) as FisTuru,
T_CLF.FICHENO AS TIGERCARIFISNO, 
T_CL.DEFINITION_ AS CARIADI,
T_BN.DEFINITION_ AS BANKAADI,
G_CL.CODE AS GO3CARIKODU, T_CL.CODE AS TIGERCARIKODU, 
T_CLF.DEBIT AS BORC,
T_CLF.CREDIT AS ALACAK,
 CASE WHEN T_CLF.FICHENO IS NULL THEN 'Aktarýlmadý' else 'Aktarýldý' end as AKTARIMDURUMU
FROM CEZVE..LG_324_01_CLFICHE T_CLF
 
 
left JOIN CEZVE..LG_324_CLCARD T_CL ON T_CL.LOGICALREF = T_CLF.CLCARDREF
left JOIN CEZVE..LG_324_BANKACC T_BN ON T_BN.LOGICALREF = T_CLF.BANKACCREF
left JOIN GO3DB..LG_424_CLCARD G_CL ON G_CL.CODE = T_CL.CODE

 --left JOIN CEZVE..LG_324_01_STLINE T_STL ON T_STL.STFICHEREF = T_CLF.LOGICALREF
--left JOIN CEZVE..LG_324_ITEMS T_ITM ON T_ITM.LOGICALREF = T_STL.STOCKREF 
 left JOIN go3db..LG_424_01_CLFICHE G_CLF ON G_CLF.FICHENO = T_CLF.FICHENO
  

--WHERE  T_ITM.CODE IS NOT NULL AND  G_ITM.CODE IS  NULL
--AND INV.FICHENO = '0000000000000068'


--select * from CEZVE..LG_324_BANKACC

--SELECT PRODUCERCODE, * FROM go3db..LG_424_ITEMS
GO


