SELECT BNL.LOGICALREF, BNC.CODE as BankaKodu , BNC.DEFINITION_ AS [BankaAdi],
BNACC.CODE AS HesapKodu, BNACC.DEFINITION_ as HesapAdi,
BNF.FICHENO AS BankaFisNo, BNL.DATE_ AS Tarih, BNL.TRANNO AS IslemNo,
CASE bnl.TRCODE
WHEN 1 THEN 'Banka Ýþlem Fiþi'                WHEN 2 THEN 'Banka Virman Fiþi'
WHEN 3 THEN 'Gelen Havale-EFT'                WHEN 4 THEN 'Gönderilen EFT/Havale'
WHEN 5 THEN 'Banka Açýlýþ Fiþi'               WHEN 6 THEN 'Banka Kur Farký Fiþi'
WHEN 16 THEN 'Banka Alýnan Hizmet Faturasý'   WHEN 17 THEN 'Banka Verilen Hizmet Faturasý'
WHEN 18 THEN 'Bankadan Çek Ödemesi'           WHEN 19 THEN 'Bankadan Senet Ödemesi'
END AS [IslemTuru],
(SELECT CODE FROM GO3DB..LG_423_BANKACC WHERE LOGICALREF=BNL.BNACCREF) AS [HesapKodu],
BNL.LINEEXP AS [IslemAciklamasi],
 CL.DEFINITION_ AS CariAdi,
ISNULL(CASE WHEN BNL.SIGN = 0 AND BNL.TRCURR = 0 THEN BNL.AMOUNT END, 0) AS [BorcTL],
ISNULL(CASE WHEN BNL.SIGN = 1 AND BNL.TRCURR = 0 THEN BNL.AMOUNT END, 0) AS [AlacakTL],
ISNULL(CASE WHEN BNL.SIGN = 0 AND BNL.TRCURR = 1 THEN BNL.AMOUNT END, 0) AS [Borc$],
ISNULL(CASE WHEN BNL.SIGN = 1 AND BNL.TRCURR = 1 THEN BNL.AMOUNT END, 0) AS [Alacak$],
ISNULL(CASE WHEN BNL.SIGN = 0 AND BNL.TRCURR = 20 THEN BNL.AMOUNT END, 0) AS [Borc€],
ISNULL(CASE WHEN BNL.SIGN = 1 AND BNL.TRCURR = 20 THEN BNL.AMOUNT END, 0) AS [Alacak€]
FROM GO3DB..LG_423_BNCARD AS BNC
LEFT OUTER JOIN GO3DB..LG_423_01_BNFLINE AS BNL ON BNC.LOGICALREF = BNL.BANKREF
LEFT OUTER JOIN GO3DB..LG_423_CLCARD AS CL ON CL.LOGICALREF = BNL.BNACCOUNTREF
LEFT OUTER JOIN  GO3DB..LG_423_BANKACC AS BNACC ON BNACC.LOGICALREF= BNL.BNACCREF
LEFT OUTER JOIN GO3DB..LG_423_01_BNFICHE AS BNF ON BNF.LOGICALREF = BNL.SOURCEFREF
WHERE     (BNL.TRCODE IN (1, 2, 3, 4, 5, 6, 16, 17, 18, 19)) 
AND (BNL.TRANSTYPE NOT IN (3,2)) -- Çek Tahsilatý Banka Virman Fiþleri gösterilmiyor
 --AND BNF.FICHENO = '00000007'
  AND BNF.DATE_ >= '20231128'


--select * from GO3DB..LG_423_01_BNFLINE
--select * from GO3DB..LG_423_01_BNFICHE