 SELECT        CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT  ELSE 0  END   AS M2,CL.SPECODE AS CARITUR,INV.FICHENO AS FISNO,INV.DATE_ AS TARIH, 
 ROUND((STL.TOTAL  / CASE WHEN STL.TRRATE = 0 THEN 1 ELSE STL.TRRATE END ),2) * -1 AS DOVIZTUTAR,     MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,  
 INV.SOURCEINDEX, 0.00 AS DISCPER, INV.VAT, '' AS OUTPUTIDCODE,    STL.AMOUNT , STL.TOTAL  * -1 as TOTAL ,STL.LINENET  * -1  LINENET    ,
 CL.CODE as CARIKODU ,CL.DEFINITION_ AS CARIADI   ,ITM.CODE AS MALZEMEKODU, ITM.NAME AS MALZEMEADI   ,EMCENTER.CODE AS MASRAFMERKEZIKODU, 
 EMCENTER.DEFINITION_ AS MASRAFMERKEZIADI, STL.PRICE AS BIRIMFIYAT   FROM         TIGER..LG_024_01_STLINE STL  WITH(NOLOCK)    
 LEFT OUTER JOIN  TIGER..LG_024_ITEMS ITM WITH(NOLOCK) ON ITM.LOGICALREF=STL.STOCKREF  
 LEFT OUTER JOIN  TIGER..LG_024_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF  
 LEFT OUTER JOIN  TIGER..LG_024_CLCARD CL WITH(NOLOCK) ON INV.CLIENTREF=CL.LOGICALREF  
 LEFT OUTER JOIN  TIGER..LG_024_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF  
 WHERE INV.TRCODE <> 25 and cl.DEFINITION_ LIKE '%kole%' AND MONTH(INV.DATE_) >1  
 