 
	
	SELECT   
SUM(AMOUNT)    as 'GirisMiktari',
                      
						INV.SPECODE,					 
					 		year(INV.DATE_) AS YIL,
							MONTH(INV.DATE_) AS AY 
							 
FROM         LG_023_01_BNFLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  LG_023_01_BNFICHE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.SOURCEFREF
 
LEFT OUTER JOIN  LG_023_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
 WHERE  INV.SPECODE LIKE 'MAK.REVÝZY'  

GROUP BY year(INV.DATE_) , MONTH(INV.DATE_) ,INV.SPECODE

   UNION ALL


   	SELECT   
SUM(AMOUNT)    as 'GirisMiktari',
                      
						 				 
					 		year(LGMAIN.DATE_) AS YIL,
							MONTH(LGMAIN.DATE_) AS AY 

   FROM
     LG_023_01_KSLINES LGMAIN
	  
  LEFT OUTER JOIN LG_023_KSCARD BANK WITH(NOLOCK) ON LGMAIN.CARDREF = BANK.LOGICALREF
   LEFT JOIN LG_EXCHANGE_023 tblEuro ON CAST( tblEuro.EDATE AS DATE) = CAST(LGMAIN.DATE_ AS DATE) AND tblEuro.CRTYPE = 20
  LEFT JOIN LG_EXCHANGE_023 tblDolar ON CAST( tblDolar.EDATE AS DATE) = CAST(LGMAIN.DATE_  AS DATE) AND tblDolar.CRTYPE = 1

 WHERE LGMAIN.SPECODE LIKE 'MAK.REVÝZY'
 GROUP BY year(LGMAIN.DATE_) , MONTH(LGMAIN.DATE_)  


	
	SELECT   
 AMOUNT    as 'GirisMiktari',
                      
							STL				 
					 		year(INV.DATE_) AS YIL,
							MONTH(INV.DATE_) AS AY 
							 
FROM         LG_023_01_BNFLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  LG_023_01_BNFICHE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.SOURCEFREF
 
LEFT OUTER JOIN  LG_023_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
 WHERE  INV.SPECODE = 'MAK.REVÝZYON' AND STL.SIGN  = 0
 order by INV.DATE_

GROUP BY year(INV.DATE_) , MONTH(INV.DATE_) 
--SELECT* FROM LG_023_01_BNFLINE
  

   