declare @plakaRengi varchar(200) = '002'
declare @plakaKalinligi varchar(200) = '05'

select 
PROD.MASTERREF,
PROD.LOGICALREF,
FICHENO,
DATE_,
ITM.CODE AS ITEMCODE,
ITM.NAME AS ITEMNAME,
PROD.STATUS,
CASE WHEN PROD.STATUS = 0 THEN 'BAÞLAMADI'
     WHEN PROD.STATUS = 1 THEN 'DEVAM EDÝYOR'
     WHEN PROD.STATUS = 3 THEN 'TAMAMLANDI' END STATUSEXPLAIN  from TIGER..LG_024_PRODORD   PROD
left join TIGER.dbo.LG_024_BOMASTER AS BOMMASTER WITH (NOLOCK) on BOMMASTER.MAINPRODREF = PROD.MASTERREF
left join TIGER.dbo.LG_024_ITEMS AS ITM WITH (NOLOCK) on ITM.LOGICALREF = PROD.MASTERREF
LEFT OUTER JOIN
TIGER.dbo.LG_024_BOMREVSN BOMREVISIO WITH(NOLOCK) ON (BOMMASTER.LOGICALREF  =  BOMREVISIO.BOMMASTERREF) LEFT OUTER JOIN
TIGER.dbo.LG_024_BOMLINE BOMLINES WITH(NOLOCK) ON (BOMREVISIO.LOGICALREF  =  BOMLINES.BOMREVREF) LEFT OUTER JOIN
TIGER.dbo.LG_024_ITEMS RECETEITEM WITH(NOLOCK) ON (RECETEITEM.LOGICALREF  =  BOMLINES.ITEMREF)
WHERE 1=1   
--RECETEITEM.CARDTYPE = 10  
--AND  SUBSTRING(RECETEITEM.CODE,11,3) = @plakaRengi   
--AND SUBSTRING(RECETEITEM.CODE,8,2)= @plakaKalinligi
and FICHENO = '2403.0013'

--SELECT * FROM LG_024_BOMASTER WHERE MAINPRODREF = 674