--1.Ana insert sorgusu otomatik çalýþacak.
--insert into EmyFercamDB.. PlakaEbatlari
select  LG_024_VARIANT.CODE  from TIGER..LG_024_VARIANT
left JOIN  TIGER..LG_024_ITEMS ON LG_024_ITEMS.LOGICALREF = LG_024_VARIANT.ITEMREF
WHERE  LG_024_ITEMS.CARDTYPE = 10  --AND LG_024_ITEMS.CODE = '150.01.06.001'
AND LG_024_VARIANT.CODE LIKE '%X%'
GROUP BY LG_024_VARIANT.CODE 


--2 . Renk ve Kalýnlýða göre plakalarý filtreleyen sorgu
select  LG_024_VARIANT.CODE,LG_024_ITEMS.NAME  from TIGER..LG_024_VARIANT
left JOIN  TIGER..LG_024_ITEMS ON LG_024_ITEMS.LOGICALREF = LG_024_VARIANT.ITEMREF
WHERE  LG_024_ITEMS.CARDTYPE = 10  
AND  SUBSTRING(LG_024_ITEMS.CODE,11,3) = '001'  -- renk
AND SUBSTRING(LG_024_ITEMS.CODE,8,2)= '03'  -- Kalýnlýk
AND LG_024_VARIANT.CODE LIKE '%X%'
GROUP BY LG_024_VARIANT.CODE ,LG_024_ITEMS.NAME 

-- renk sorgusu
select DISTINCT SUBSTRING(CODE,11,3),*  from lg_024_ITEMS WHERE SUBSTRING(CODE,1,6) = '150.01' 
-- kalinlik sorgusu
select DISTINCT SUBSTRING(CODE,8,2),*  from lg_024_ITEMS WHERE SUBSTRING(CODE,1,6) = '150.01' 

--3 . Kodun içine metotada eklenecek, Renk ve Kalýnlýða göre plakalarý filtreleyen sorgu
select * from EmyFercamDB.. PlakaEbatlari where PlakaEbadi in (
select  LG_024_VARIANT.CODE   from TIGER..LG_024_VARIANT
left JOIN  TIGER..LG_024_ITEMS ON LG_024_ITEMS.LOGICALREF = LG_024_VARIANT.ITEMREF
WHERE  TIGER..LG_024_ITEMS.CARDTYPE = 10  
AND  SUBSTRING(LG_024_ITEMS.CODE,11,3) = '001'  -- renk
AND SUBSTRING(LG_024_ITEMS.CODE,8,2)= '03'  -- Kalýnlýk
AND LG_024_VARIANT.CODE LIKE '%X%'
GROUP BY LG_024_VARIANT.CODE ,LG_024_ITEMS.NAME )