--1-ÝÇ PÝYASA

--  select * from VW_PERFORMANSTOPLAM_23
ALTER VIEW VW_PERFORMANSTOPLAM_23 AS 
SELECT ROW_NUMBER() OVER (ORDER BY YIL,AY) ID, GELIRGIDER,MUSTERITURU,YIL,AY,M2,TOPLAM,CARITUR,DOVIZ AS DOVIZTOPLAM,CASE WHEN M2 > 0 THEN ROUND(TOPLAM / M2 ,2) ELSE 0 END  AS ORTALAMAFIYAT FROM (

	 SELECT 'GELÝR' AS GELIRGIDER,
			'ÝÇ PÝYASA' AS MUSTERITURU,
	 YIL,AY,
	 SUM(M2) AS M2, sum(LINENET) AS TOPLAM,CARITUR,SUM(DOVIZTUTAR) AS DOVIZ FROM (
	SELECT 
	ROUND(EN * BOY * AMOUNT / 1000000,2) AS M2,CL.SPECODE AS CARITUR,INV.FICHENO,0 AS DOVIZTUTAR, MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,
	STRNS.SOURCEINDEX, STRNS.DISCPER, STRNS.VAT, STRNS.OUTPUTIDCODE, STRNS.AMOUNT,STRNS.TOTAL  ,STRNS.LINENET
	 FROM LG_023_01_INVOICE INV WITH(NOLOCK) 
	 LEFT JOIN  LG_023_CLCARD CL ON INV.CLIENTREF = CL.LOGICALREF
	LEFT JOIN LG_023_01_STLINE STRNS WITH(NOLOCK) ON  INV.LOGICALREF = STRNS.INVOICEREF
	LEFT JOIN LG_023_ITEMS ITM WITH(NOLOCK) ON  ITM.LOGICALREF = STRNS.STOCKREF
	LEFT OUTER JOIN LG_023_EMUHACC GLACC WITH(NOLOCK) ON (STRNS.ACCOUNTREF  =  GLACC.LOGICALREF) LEFT OUTER JOIN "TIGER"..LG_SLSMAN SLSMC WITH(NOLOCK) ON (STRNS.SALESMANREF = SLSMC.LOGICALREF)
	 LEFT JOIN LG_XT050_023 WITH(NOLOCK) ON PARLOGREF=STOCKREF
	 WHERE 
	 EN> 0 AND 
  
	   INV.CANCELLED = 0
	--(STRNS.INVOICEREF = 7869) 
	AND (STRNS.DETLINE = 0) AND (STRNS.SOURCEINDEX IN (0,1,3,7,8,10,11,12))      
	AND INV.TRCODE IN (8)
	 AND CL.SPECODE = '' --AND FICHENO = 'FEG2023000000128' AND AMOUNT = 30 ORDER BY INV.FICHENO
	 ) AS TblSatis2  GROUP BY CARITUR,YIL,AY

	 UNION ALL

	  SELECT 'GELÝR' AS GELIRGIDER,
			'ÝHRACAT' AS MUSTERITURU,
	  YIL,AY,
	 SUM(M2) AS M2, sum(LINENET) AS TOPLAM,CARITUR,SUM(DOVIZTUTAR) AS DOVIZ FROM (
	SELECT 
	ROUND(EN * BOY * AMOUNT / 1000000,2) AS M2,CL.SPECODE AS CARITUR,INV.FICHENO, ROUND((STRNS.LINENET  / CASE WHEN INV.TRRATE = 0 THEN 1 ELSE INV.TRRATE END ),2) AS DOVIZTUTAR, MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,
	STRNS.SOURCEINDEX, STRNS.DISCPER, STRNS.VAT, STRNS.OUTPUTIDCODE, STRNS.AMOUNT,STRNS.TOTAL ,STRNS.LINENET 
	 FROM LG_023_01_INVOICE INV WITH(NOLOCK) 
	 LEFT JOIN  LG_023_CLCARD CL ON INV.CLIENTREF = CL.LOGICALREF
	LEFT JOIN LG_023_01_STLINE STRNS WITH(NOLOCK) ON  INV.LOGICALREF = STRNS.INVOICEREF
	LEFT JOIN LG_023_ITEMS ITM WITH(NOLOCK) ON  ITM.LOGICALREF = STRNS.STOCKREF
	LEFT OUTER JOIN LG_023_EMUHACC GLACC WITH(NOLOCK) ON (STRNS.ACCOUNTREF  =  GLACC.LOGICALREF) LEFT OUTER JOIN "TIGER"..LG_SLSMAN SLSMC WITH(NOLOCK) ON (STRNS.SALESMANREF = SLSMC.LOGICALREF)
	 LEFT JOIN LG_XT050_023 WITH(NOLOCK) ON PARLOGREF=STOCKREF
	 WHERE 
	 EN> 0 AND 
 
	   INV.CANCELLED = 0
	--(STRNS.INVOICEREF = 7869) 
	AND (STRNS.DETLINE = 0) AND (STRNS.SOURCEINDEX IN (0,1,3,7,8,10,11,12))      
	AND INV.TRCODE IN (8)
	 AND CL.SPECODE = 'ÝHRACAT' --AND FICHENO = 'FEG2023000000128' AND AMOUNT = 30 ORDER BY INV.FICHENO
	 ) AS TblSatis2  GROUP BY CARITUR, YIL,AY

	 --3.HÝZMET FATURALARI
	 UNION ALL
	  SELECT 'GELÝR' AS GELIRGIDER,
			'HÝZMET' AS MUSTERITURU,
	 YIL,AY,
	0 AS M2, sum(LINENET) AS TOPLAM,CARITUR,SUM(DOVIZTUTAR) AS DOVIZ FROM (
	SELECT 
	0 AS M2,CL.SPECODE AS CARITUR,INV.FICHENO,0 AS DOVIZTUTAR, MONTH(INV.DATE_) AS AY,YEAR(INV.DATE_) AS YIL,INV.TRRATE,
	STRNS.SOURCEINDEX, STRNS.DISCPER, STRNS.VAT, STRNS.OUTPUTIDCODE, STRNS.AMOUNT,STRNS.TOTAL  ,STRNS.LINENET
	 FROM LG_023_01_INVOICE INV WITH(NOLOCK) 
	 LEFT JOIN  LG_023_CLCARD CL ON INV.CLIENTREF = CL.LOGICALREF
	LEFT JOIN LG_023_01_STLINE STRNS WITH(NOLOCK) ON  INV.LOGICALREF = STRNS.INVOICEREF
	LEFT JOIN LG_023_ITEMS ITM WITH(NOLOCK) ON  ITM.LOGICALREF = STRNS.STOCKREF
	LEFT OUTER JOIN LG_023_EMUHACC GLACC WITH(NOLOCK) ON (STRNS.ACCOUNTREF  =  GLACC.LOGICALREF) LEFT OUTER JOIN "TIGER"..LG_SLSMAN SLSMC WITH(NOLOCK) ON (STRNS.SALESMANREF = SLSMC.LOGICALREF)
	 
	 WHERE 
	 
  
	   INV.CANCELLED = 0
	--(STRNS.INVOICEREF = 7869) 
	AND (STRNS.DETLINE = 0) AND (STRNS.SOURCEINDEX IN (0,1,3,7,8,10,11,12))      
	AND INV.TRCODE IN (9)
	   --AND FICHENO = 'FEG2023000000128' AND AMOUNT = 30 ORDER BY INV.FICHENO
	 ) AS TblSatis2  GROUP BY CARITUR,YIL,AY
	 
	 --4 Cam Alýþ Giderleri
 UNION ALL
	  SELECT 'GÝDER' AS GELIRGIDER,
			'CAM' AS MUSTERITURU,
	 YIL,AY,
	sum(GirisMiktari) AS M2, sum(GirisKdvMatrahi) * -1 AS TOPLAM,'' CARITUR,0 AS DOVIZ FROM (
	 SELECT   
 sum(	CASE      WHEN STL.IOCODE IN(1,0) THEN AMOUNT
											 ELSE 0 END )  as 'GirisMiktari',
                    sum(   CASE   WHEN STL.IOCODE IN(1,0)  THEN VATMATRAH
											 ELSE 0 END  ) as 'GirisKdvMatrahi',
					 		year(INV.DATE_) AS YIL,
							MONTH(INV.DATE_) AS AY
FROM         LG_023_01_STLINE STL  WITH(NOLOCK)
 
LEFT OUTER JOIN  LG_023_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
 
LEFT OUTER JOIN  LG_023_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE EMCENTER.CODE =  '15' AND INV.TRCODE <> 25  GROUP BY year(INV.DATE_) , MONTH(INV.DATE_) 

	  ) AS TblSatis2  GROUP BY YIL,AY

	  --5. ENERJÝ GÝDERLERÝ
 --4 Cam Alýþ Giderleri
 UNION ALL
	  SELECT 'GÝDER' AS GELIRGIDER,
			'ENERJÝ' AS MUSTERITURU,
	 YIL,AY,
	sum(GirisMiktari) AS M2, sum(GirisKdvMatrahi) * -1 AS TOPLAM,'' CARITUR,0 AS DOVIZ FROM (
	 SELECT   
 
											CAST(INV.SPECODE AS FLOAT) as 'GirisMiktari',
                    sum(   CASE   WHEN STL.IOCODE IN(1,0)  THEN VATMATRAH
											 ELSE 0 END  ) as 'GirisKdvMatrahi',
					 		year(INV.DATE_) AS YIL,
							MONTH(INV.DATE_) - 1 AS AY  
							
FROM         LG_023_01_STLINE STL  WITH(NOLOCK)
LEFT OUTER JOIN  LG_023_01_INVOICE INV WITH(NOLOCK) ON INV.LOGICALREF=STL.INVOICEREF
LEFT OUTER JOIN  LG_023_CLCARD CLC WITH(NOLOCK) ON CLC.LOGICALREF=STL.CLIENTREF
LEFT OUTER JOIN  LG_023_EMCENTER EMCENTER WITH(NOLOCK) ON EMCENTER.LOGICALREF=STL.CENTERREF
WHERE   INV.TRCODE <> 25 and clc.DEFINITION_ LIKE '%kole%' AND MONTH(INV.DATE_) >1  GROUP BY year(INV.DATE_) , MONTH(INV.DATE_) ,INV.SPECODE 

	  ) AS TblSatis2  GROUP BY YIL,AY



	 ) TBLGenelListe