SELECT 
INVFC.FICHENO, INVFC.DATE_, INVFC.DEPARTMENT, INVFC.BRANCH, INVFC.SPECODE, INVFC.CYPHCODE, INVFC.DOCODE, INVFC.FACTORYNR, INVFC.TRCODE, INVFC.TRNET, INVFC.TRADINGGRP, INVFC.REFLECTED, INVFC.STATUS, INVFC.TRCURR, INVFC.LOGICALREF, INVFC.CLIENTREF, INVFC.SOURCEINDEX, INVFC.TIME_, INVFC.TRRATE, INVFC.REPORTRATE, INVFC.RECVREF, INVFC.CANCELLED, INVFC.DISTORDERREF, INVFC.GROSSTOTAL, INVFC.TOTALDISCOUNTS, INVFC.TOTALEXPENSES, INVFC.TOTALVAT, INVFC.NETTOTAL, INVFC.DECPRDIFF, INVFC.DEDUCTIONPART1, INVFC.DEDUCTIONPART2, INVFC.EXIMFCTYPE, CLNTC.DEFINITION_, CLNTC.CODE, CLNTC.SPECODE, CLNTC.SPECODE2, CLNTC.SPECODE3, CLNTC.SPECODE4, CLNTC.SPECODE5, CLNTC.ACTIVE, CLNTC.CYPHCODE, CLNTC.LOGICALREF, PAYPL.CODE, PAYPL.LOGICALREF, SLSMC.CODE, SLSMC.POSITION_, SLSMC.DEFINITION_, SLSMC.ACTIVE, PROJECT.CODE, PROJECT.NAME
 FROM 
LG_023_01_INVOICE INVFC WITH(NOLOCK)  LEFT OUTER JOIN LG_023_CLCARD CLNTC WITH(NOLOCK) ON (INVFC.CLIENTREF = CLNTC.LOGICALREF) LEFT OUTER JOIN LG_023_PAYPLANS PAYPL WITH(NOLOCK) ON (INVFC.PAYDEFREF = PAYPL.LOGICALREF) LEFT OUTER JOIN "TIGER"..LG_SLSMAN SLSMC WITH(NOLOCK) ON (INVFC.SALESMANREF = SLSMC.LOGICALREF) LEFT OUTER JOIN LG_023_PROJECT PROJECT WITH(NOLOCK) ON (INVFC.PROJECTREF  =  PROJECT.LOGICALREF)
 WHERE 
(INVFC.CANCELLED = 0) AND ((INVFC.DATE_ >= CONVERT(dateTime, '11-1-2023', 101)) AND (INVFC.DATE_ <= CONVERT(dateTime, '11-30-2023', 101))) AND (INVFC.TRCODE IN (2,3,7,8,9,11,14)) AND (INVFC.STATUS IN (0,1)) AND (INVFC.DEPARTMENT IN (0)) AND (INVFC.BRANCH IN (0)) AND (INVFC.FACTORYNR IN (0)) AND (INVFC.DEVIR IN (0)) AND (( (INVFC.TRCODE IN (11,12)) OR (EXISTS ( SELECT 1 FROM LG_023_01_STLINE STRNS WHERE STRNS.INVOICEREF = INVFC.LOGICALREF AND STRNS.SOURCEINDEX IN (0,1,3,7,8,10,11,12))) ))

ORDER BY 
INVFC.DATE_, INVFC.FICHENO, INVFC.DOCODE, INVFC.SPECODE, INVFC.TIME_, INVFC.TRCODE
 
 SELECT SUM(M2) AS M2, sum(TOTAL) AS TOPLAM,CARITUR,SUM(DOVIZTUTAR) AS DOVIZ FROM (
SELECT 
ROUND(EN * BOY * AMOUNT / 1000000,2) AS M2,CL.SPECODE AS CARITUR,INV.FICHENO, (NETTOTAL / CASE WHEN INV.TRRATE = 0 THEN 1 ELSE INV.TRRATE END ) AS DOVIZTUTAR,
STRNS.SOURCEINDEX, STRNS.DISCPER, STRNS.VAT, STRNS.OUTPUTIDCODE, STRNS.AMOUNT,STRNS.TOTAL 
 FROM LG_023_01_INVOICE INV WITH(NOLOCK) 
 LEFT JOIN  LG_023_CLCARD CL ON INV.CLIENTREF = CL.LOGICALREF
LEFT JOIN LG_023_01_STLINE STRNS WITH(NOLOCK) ON  INV.LOGICALREF = STRNS.INVOICEREF
LEFT JOIN LG_023_ITEMS ITM WITH(NOLOCK) ON  ITM.LOGICALREF = STRNS.STOCKREF
LEFT OUTER JOIN LG_023_EMUHACC GLACC WITH(NOLOCK) ON (STRNS.ACCOUNTREF  =  GLACC.LOGICALREF) LEFT OUTER JOIN "TIGER"..LG_SLSMAN SLSMC WITH(NOLOCK) ON (STRNS.SALESMANREF = SLSMC.LOGICALREF)
 LEFT JOIN LG_XT050_023 WITH(NOLOCK) ON PARLOGREF=STOCKREF
 WHERE 
 EN> 0 AND 
 MONTH(INV.DATE_) = 10
 and INV.CANCELLED = 0
--(STRNS.INVOICEREF = 7869) 
AND (STRNS.DETLINE = 0) AND (STRNS.SOURCEINDEX IN (0,1,3,7,8,10,11,12))      
AND INV.TRCODE IN (8)
--AND CL.SPECODE = 'ÝHRACAT' AND FICHENO = 'FEG2023000000128' AND AMOUNT = 30 ORDER BY INV.FICHENO
 ) AS TblSatis2  GROUP BY CARITUR

 

SELECT 
ROUND(EN * BOY * 37 / 1000000,2)
 FROM 
LG_XT050_023 WITH(NOLOCK) 
 WHERE 
(PARLOGREF='26')
