SELECT ITM.CODE,ITM.NAME, VRY.CODE,  ITMYM.CODE AS YMITEMCODE,ITMYM.NAME AS YMITEMNAME, VRY.CODE AS VARYANTCODE,VRYYM.CODE AS YMVARYANTCODE 
,VRY.LOGICALREF AS MasterVaryantRef, VRY.CODE AS AcilacakVaryantKodu,ITMYM.LOGICALREF as AcilacakMalzemeReferansi

FROM LG_024_ITEMS ITM 
left JOIN LG_024_VARIANT VRY ON VRY.ITEMREF = ITM.LOGICALREF 
left JOIN LG_024_ITEMS ITMYM ON    ITMYM.CODE LIKE ITM.CODE + '%' AND ITMYM.CARDTYPE = 11
left JOIN LG_024_VARIANT VRYYM ON    VRYYM.CODE =  VRY.CODE  AND VRYYM.ITEMREF = ITMYM.LOGICALREF
--LEFT JOIN (SELECT VRY.* FROM LG_024_ITEMS ITM 
--left JOIN LG_024_VARIANT VRY ON VRY.ITEMREF = ITM.LOGICALREF 
--WHERE ITM.CARDTYPE = 11 
--AND ITM.CODE LIKE    '10 048%' ) TB1 ON TB1.CODE = VRY.CODE
WHERE ITM.CARDTYPE = 12 and VRYYM.CODE is null and VRY.CODE IS NOT NULL
--AND ITM.CODE LIKE    '10 048%' 


--SELECT VRY.* FROM LG_024_ITEMS ITM 
--left JOIN LG_024_VARIANT VRY ON VRY.ITEMREF = ITM.LOGICALREF 
--WHERE ITM.CARDTYPE = 11 
--AND ITM.CODE LIKE    '10 048%' 
 



 /*
SELECT * FROM LG_024_ITEMS WHERE CODE LIKE    '10 048%'


SELECT * FROM LG_024_VARIANT WHERE ITEMREF = 141336

SELECT * FROM LG_024_VARIANT WHERE ITEMREF = 141342

SELECT * FROM LG_024_VARIANT WHERE ITEMREF =141336
*/