USE [TIGER]
GO

/****** Object:  View [dbo].[VW_SATIS_SIPARIS_LISTESI_24]    Script Date: 18.01.2024 14:41:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 -- select * from TIGER..VW_UretimPlanlama_24
alter view VW_UretimPlanlama_24 as 
SELECT   ORFLINE.LOGICALREF,   
ORFICHE.FICHENO AS SiparisNo,
ORFICHE.DOCODE as MusteriSiparisNo,
ORFICHE.DATE_ as SiparisTarihi,
ITEMS.CODE AS [MalzemeKodu],                         

 PRODORD.FICHENO as UretimEmriNo,
tblDetay.ROTA_KODU AS RotaKodu,
tblDetay.FIRIN_ROTA_KODU AS FirinRotaKodu,
ITEMS.NAME AS UrunKodu,

CLCARD.CODE AS [FirmaKodu], 
CLCARD.DEFINITION_ AS [FirmaAdi], 
ORFLINE.AMOUNT AS [SiparisAdet],
PRODORD.ACTAMOUNT AS [KesimAdet],

tblDetay.RENK AS Renk,
tblDetay.EN AS En,
tblDetay.BOY AS Boy,
tblDetay.KALINLIK AS Kalinlik,
tblDetay.EN * tblDetay.BOY * ORFLINE.AMOUNT / 1000000 AS SiparisToplamAlan,
tblDetay.BOMBE  as Firin,
tblDetay.SERIGRAF  as Serigraf,
0  as ToplamCap,
tblDetay.EN * tblDetay.BOY  / 10000 AS BirimM2
 
--DATEPART(WEEK, ORFICHE.DATE_) AS [Sipariþ Haftasý], ORFICHE.DATE_ AS [Sipariþ Tarihi],                         
--(CASE ORFLINE.CLOSED WHEN 0 THEN 'Bekliyor' WHEN 1 THEN 'Kapandý' END) AS Statü, 
--  ITEMS.STGRPCODE AS [Malzeme Grup Kodu], ITEMS.SPECODE3 AS [Özel Kod3],                         
--  ORFLINE.SHIPPEDAMOUNT AS [Sevk Miktarý], ORFLINE.AMOUNT - ORFLINE.SHIPPEDAMOUNT AS Kalan,                         
--ORFLINE.LINEEXP AS [Satýr Açýklamasý], ORFLINE.DUEDATE AS [Teslim Tarihi], ORFLINE.PRICE AS Fiyat, (ORFLINE.AMOUNT - ORFLINE.SHIPPEDAMOUNT)   
--* ORFLINE.PRICE AS [Kalan Tutar], TEDARIKCI.ICUSTSUPCODE AS [Musteri Kodu], MONTH(ORFLINE.DUEDATE) AS [Teslim Ay]   

FROM         dbo.LG_024_01_ORFLINE AS ORFLINE 
INNER JOIN                        
dbo.LG_024_01_ORFICHE AS ORFICHE ON ORFLINE.ORDFICHEREF = ORFICHE.LOGICALREF 
INNER JOIN                        dbo.LG_024_ITEMS AS ITEMS ON ORFLINE.STOCKREF = ITEMS.LOGICALREF 
INNER JOIN                        dbo.LG_024_CLCARD AS CLCARD ON ORFLINE.CLIENTREF = CLCARD.LOGICALREF 
LEFT OUTER JOIN                            
(SELECT     ITEMREF, CLIENTREF, ICUSTSUPCODE                              FROM          
dbo.LG_024_SUPPASGN) AS TEDARIKCI ON CLCARD.LOGICALREF = TEDARIKCI.CLIENTREF AND ITEMS.LOGICALREF = TEDARIKCI.ITEMREF  

LEFT JOIN LG_024_PEGGING PEGGING ON PEGGING.PORDFICHEREF = ORFICHE.LOGICALREF and PEGGING.PORDLINEREF = ORFLINE.LOGICALREF 
LEFT JOIN LG_024_PRODORD PRODORD ON PEGGING.PEGREF = PRODORD.LOGICALREF
LEFT JOIN LG_XT050_024 tblDetay ON tblDetay.PARLOGREF = ORFLINE.STOCKREF


WHERE    
(ORFICHE.TRCODE = 1) AND (ORFLINE.AMOUNT - ORFLINE.SHIPPEDAMOUNT > 0)       

--and ORFICHE.FICHENO  = '231201002'

--SELECT * FROM LG_XT050_024


