select UNITSETREF,* from LG_326_ITEMS WHERE NAME LIKE 'KUÞBURNU GRA%'

select UNITSETREF,* from LG_326_ITEMS WHERE NAME LIKE '% 300 GR%' AND ACTIVE=0

UPDATE LG_326_ITEMS SET UNITSETREF=30  WHERE NAME LIKE '% 300 GR%' AND ACTIVE=0

SELECT CONVFACT1, CONVFACT2 FROM LG_326_UNITSETL WHERE UNITSETREF = 30 AND CODE = 'KOLÝ'

SELECT * FROM LG_326_UNITSETL WHERE UNITSETREF = 30 AND CODE = 'KOLÝ'

 SELECT * FROM LG_326_UNITSETL WHERE UNITSETREF = 7 AND CODE = 'KOLÝ'

  SELECT * FROM LG_326_UNITSETL WHERE   CODE = 'KOLÝ'  --  7 YERÝNE 30 OLMASI GEREKÝR MALZEMEDEKÝ UNITSETREF DEÐERÝNÝN

  