SELECT
M.LOGICALREF,
M.CODE AS MLZKOD,
M.NAME AS MLZADI,
OZKOD.CODE AS 'OZKODCODE',
OZKOD.NAME AS OZKODNAME,
OZDEG.CODE AS 'OZDEGCODE',
OZKOD.LOGICALREF  AS OZKODREF,
OZDEG.LOGICALREF  AS OZDEGREF
FROM LG_006_CHARASGN AS OZBAG WITH(NOLOCK) LEFT JOIN LG_006_ITEMS AS M WITH(NOLOCK) ON OZBAG.ITEMREF = M.LOGICALREF
LEFT JOIN LG_006_CHARCODE AS OZKOD WITH(NOLOCK) ON OZBAG.CHARCODEREF =OZKOD.LOGICALREF
LEFT JOIN LG_006_CHARVAL AS OZDEG WITH(NOLOCK) ON OZBAG.CHARVALREF =OZDEG.LOGICALREF

select * from LG_006_CHARASGN
SELECT * FROM LG_006_CHARCODE
SELECT * FROM LG_006_CHARVAL
/*

SELECT AttId,AttName
  FROM [dbo].[tbl_001_EPazar_TrendKategoriAttributes] where Required = 0
  group by AttId,AttName

SELECT AttId,AttName
  FROM [dbo].[tbl_001_EPazar_TrendKategoriAttributes] where Required = 1
  group by AttId,AttName
  */