select   PT_DPKODLARI.ID,LG_221_ITEMS.CODE,LG_221_ITEMS.NAME
,'UPDATE PT_DPKODLARI SET ITEMREF=' + CAST(LG_221_ITEMS.LOGICALREF AS VARCHAR(20)) +  '   WHERE ID = ' +  CAST( PT_DPKODLARI.ID  AS VARCHAR(20)) from LG_221_ITEMS 
LEFT JOIN PT_DPKODLARI ON PT_DPKODLARI.STOKKODU = LG_221_ITEMS.CODE 
WHERE PT_DPKODLARI.ID IS NOT NULL

--SELECT * FROM PT_DPKODLARI