USE [TIGER2_DB]
GO

/****** Object:  View [dbo].[LV_058_21_EMUHTOTV1]    Script Date: 6.10.2022 11:37:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



 CREATE VIEW [dbo].[LV_058_21_EMUHTOTV1] WITH SCHEMABINDING AS
  SELECT TRCODE,ACCOUNTREF AS ACCOUNTREF,
         (CASE WHEN TRCODE = 1 THEN -1   WHEN TRCODE = 7 THEN -2 WHEN   LINEEXP = '690 HS.VÝRMAN' THEN -3 ELSE MONTH_ END) AS MONTH_,
         YEAR_,
         SUM(ISNULL(DEBIT, 0)) AS DEBIT,
         SUM(ISNULL(CREDIT, 0)) AS CREDIT,
         SUM(ISNULL((REPORTNET * (1 - SIGN)), 0)) AS DEBIT_RC,
         SUM(ISNULL((REPORTNET * SIGN), 0)) AS CREDIT_RC,
         SUM(ISNULL((TRNET * (1 - SIGN)), 0)) AS DEBIT_LC,
         SUM(ISNULL((TRNET * SIGN), 0)) AS CREDIT_LC,
         SUM(ISNULL((AMNT * (1 - SIGN)), 0)) AS DEBIT_AMNT,
         SUM(ISNULL((AMNT * SIGN), 0)) AS CREDIT_AMNT,
         SUM(ISNULL(EMUDEBIT, 0)) AS DEBIT_EMU,
         SUM(ISNULL(EMUCREDIT, 0)) AS CREDIT_EMU,
         BRANCH AS BRANCH,
         DEPARTMENT AS DEPARTMENT,
         TRCURR AS TRCURR,
         SUM(0) AS DEBITRESRV,
         SUM(0) AS CREDITRESRV,
         SUM(0) AS DEBITRESRV_RC,
         COUNT_BIG(*) AS CNT
    FROM [dbo].LG_058_21_EMFLINE
   WHERE STATUS = 0 AND CANCELLED = 0 AND TRCODE NOT IN (5, 10) --  AND  LINEEXP <> '690 HS.VÝRMAN'
GROUP BY ACCOUNTREF,
         (CASE TRCODE WHEN 1 THEN -1 WHEN 7 THEN -2 ELSE MONTH_ END),
         YEAR_,
         BRANCH,
         DEPARTMENT,
         TRCURR,TRCODE,LINEEXP,MONTH_

GO


