

--select * from ServisReceteOperations

SELECT DISTINCT
case ISNULL (LEN (VRNT.CODE),0) when 0 THEN ITMSC.CODE

                    ELSE ITMSC.CODE+'['+VRNT.CODE +']' END as 'ReceteKodu',
OPERATION.CODE AS 'OperasyonKodu',
[dbo].[fn_LogoTimetoSystemTime] (OPRTREQ.FIXEDSETUPTIME ) as 'SabitHazirlikSuresi',
--OPRTREQ.FIXEDSETUPTIME AS 'Sabit hazýrlýk süresi',

--OPRTREQ.RUNTIME AS 'Ýþlem Süresi',

[dbo].[fn_LogoTimetoSystemTime] (OPRTREQ.RUNTIME ) AS 'IslemSuresi'

 

FROM LG_022_BOMASTER BOMMASTER WITH(NOLOCK) LEFT OUTER JOIN

LG_022_ITEMS ITMSC WITH(NOLOCK) ON (BOMMASTER.MAINPRODREF  =  ITMSC.LOGICALREF)

LEFT JOIN  LG_022_VARIANT VRNT ON ITMSC.LOGICALREF = VRNT.ITEMREF

LEFT OUTER JOIN LG_022_BOMREVSN BOMREVISIO WITH(NOLOCK) ON (BOMMASTER.LOGICALREF  =  BOMREVISIO.BOMMASTERREF)

LEFT OUTER JOIN LG_022_ROUTING ROUTING WITH(NOLOCK) ON (BOMREVISIO.ROUTINGREF  =  ROUTING.LOGICALREF) LEFT OUTER JOIN

LG_022_RTNGLINE  RTNGLINE  WITH(NOLOCK) ON ROUTING.LOGICALREF=RTNGLINE.ROUTINGREF LEFT OUTER JOIN

LG_022_OPERTION OPERATION  WITH(NOLOCK) ON RTNGLINE.OPERATIONREF=OPERATION.LOGICALREF  LEFT OUTER JOIN

LG_022_OPRTREQ OPRTREQ   WITH(NOLOCK) ON RTNGLINE.OPERATIONREF=OPRTREQ.OPERATIONREF
 left join ServisReceteOperations on 
--(case ISNULL (LEN (VRNT.CODE),0) when 0 THEN ITMSC.CODE ELSE ITMSC.CODE+'['+VRNT.CODE +']'  END   ) = ServisReceteInputs.title and 

ServisReceteOperations.code = (case ISNULL (LEN (VRNT.CODE),0) when 0 THEN ITMSC.CODE

                    ELSE ITMSC.CODE+'['+VRNT.CODE +']' END)
WHERE ServisReceteOperations.Id is  null and
 OPRTREQ.LINENO_ = 1 and  (BOMREVISIO.BOMTYPE IN (1,2)) AND (BOMREVISIO.ACTIVE = 1) AND (BOMREVISIO.WITHOUTROUTING IN (0)) 
AND (BOMREVISIO.USEDEPTTIMEFORPRD IN (0)) AND (BOMREVISIO.USEWSFORPRD IN (0))   
 AND BOMMASTER.SPECODE = 'FERCAM' 