USE [TrendyolDb]
GO
insert into [tbl_001_stok]
SELECT  -- [a_id],
       emyEticaret.[Stok Kodu] [a_kod]
      ,emyEticaret.[Stok Adý] [a_adi]
      ,'' [a_aadi]
      ,'ADET' [a_birim]
      ,'Lastik' [a_tur]
      ,LOGICALREF AS [a_ekod]
      ,'' [a_eadi]
      ,'' [a_okod]
      ,UreticiKodu [a_barkod]
      ,'' [a_1birim]
      ,0 [a_1brmcar]
      ,'' [a_2birim]
      ,0 [a_2brmcar]
      ,18 [a_alkdvor]
      ,0 [a_sakdvor]
      ,0 [a_aisk]
      ,0 [a_sisk]
      ,'' [a_acik]
      , round(EmyEticaret.[Depo Miktarý] / 2,0) as [a_giren]
      ,0 [a_cikan]
      ,round(EmyEticaret.[Depo Miktarý] / 2,0) [a_kalan]
      ,round((EmyEticaret.HesaplananTrendyolFiyati * 1.05) * 1.05,0) [a_afiyat]
      ,round(EmyEticaret.HesaplananTrendyolFiyati  * 1.05,0) [a_sfiyat]
      ,'H' [a_flkul]
      ,0 [a_afliste]
      ,0 [a_sfliste]
      ,1 [a_cuser]
      ,getdate () [a_cdate]
      ,getdate ()  [a_ctime]
      ,15 [a_muser]
      ,getdate () [a_mdate]
      ,getdate () [a_mtime]
      ,0 [a_bloke]
      ,Marka [a_grup1]
      ,Ebat [a_grup2]
      , [a_grup3]
      ,0 [a_aon]
      ,0 [a_son]
      ,0 [a_afkurid]
      ,0 [a_sfkurid]
      ,0 [a_fcarp]
      ,0 [a_yazar]
      ,0 [a_yayinevi]
      ,' ' [a_malim]
      ,' '[a_yansitma]
      ,' '[a_saircikis]
      ,' '[a_muretim_giris]
      ,' '[a_malim_iade]
      ,' '[a_mdiger_giris]
      ,' '[a_malim_indirim]
      ,' '[a_msatis]
      ,' '[a_mydsatis]
      ,' '[a_msarf]
      ,' '[a_mfire]
      ,' '[a_msatis_iade]
      ,' '[a_msatis_indirim]
      ,' '[a_mdiger_cikis]
      ,' '[a_mafiyatfarki]
      ,' '[a_msfiyatfarki]
      ,0 [a_otvid]
      ,' '[a_kresim]
      ,' '[a_bresim]
      ,round(EmyEticaret.HesaplananTrendyolFiyati  * 1.05,0) [a_ofiyat1]
      ,round((EmyEticaret.HesaplananTrendyolFiyati * 1.05) * 1.05,0) [a_ofiyat2]
      ,0 [a_ofiyat3]
      ,0 [a_ofiyat4]
      ,0 [a_ofiyat5]
      ,0 [a_ofiyat6]
      ,0 [a_ofkurid1]
      ,0 [a_ofkurid2]
      ,0 [a_ofkurid3]
      ,0 [a_ofkurid4]
      ,0 [a_ofkurid5]
      ,0 [a_ofkurid6]
      ,0 [a_puan]
      ,0 [a_tplu]
      ,0 [a_ykasa]
      ,'EAN13' [a_bartip]
      ,Marka [a_marka]
      ,UreticiKodu [a_model]
      ,'' [a_raf]
      ,0 [a_grup4]
      ,ebat [a_grup5]
      ,'' [a_grup6]
      ,'' [a_grup7]
      ,0 [a_intpfiyat]
      ,0 [a_intvfiyat]
      ,'Aktif' [a_akpas]
      ,0 [a_pesfkurid]
      ,0 [a_vadfkurid]
      ,0 [a_mailkgilkc]
      ,getdate() [a_mailkgilkctar]
      ,0 [a_masongilkc]
      ,getdate() [a_masongilkctar]
      ,0 [a_mayuragort]
      ,getdate() [a_mayuragorttar]
      ,0 [a_maagort]
      ,getdate() [a_maagorttar]
      ,'' [a_1brmbar]
      ,0 [a_1brmfiy]
      ,0 [a_1brmkurid]
      ,'' [a_2brmbar]
      ,0 [a_2brmfiy]
      ,0 [a_2brmkurid]
      ,0 [a_oivy]
      ,0 [a_mauretim]
      ,[a_mauretimtar]
      ,0 [a_xen]
      ,0 [a_xboy]
      ,0 [a_xyuk]
      ,0 [a_xagir]
      ,0 [a_xrenk]
      ,0 [a_xursur]
      ,[a_resim]
      ,0 [a_selo]
      ,'' [a_kdvdh]
      ,0 [a_opsgun]
      ,0 [a_boyid]
      ,0 [a_refstokid]
      ,0 [a_reftip]
      ,'-1' [a_kulrenk]
      ,0 [a_kulbeden]
      ,0 [a_kulkavala]
      ,0 [a_renkid]
      ,0 [a_renk]
      ,0 [a_renkadi]
      ,0 [a_bedenid]
      ,0 [a_beden]
      ,0 [a_kavalaid]
      ,0 [a_kavala]
      ,null [a_subeid]
      ,'' [a_bilgi1]
      ,'' [a_bilgi2]
      ,'' [a_bilgi3]
      ,'' [a_bilgi4]
      ,'' [a_bilgi5]
      ,'' [a_bilgi6]
      ,'' [a_bilgi7]
      ,'' [a_bilgi8]
      ,'' [a_bilgi9]
      ,'' [a_bilgi10]
      ,'' [a_bilgi11]
      ,'' [a_bilgi12]
      ,'' [a_bilgi13]
      ,'' [a_bilgi14]
      ,'' [a_bilgi15]
      ,'' [a_bilgi16]
      ,'' [a_bilgi17]
      ,'' [a_bilgi18]
      ,'' [a_bilgi19]
      ,'' [a_bilgi20]
      ,'' [a_ofiyisk1]
      ,'' [a_ofiyisk2]
      ,'' [a_ofiyisk3]
      ,'' [a_ofiyisk4]
      ,'' [a_ofiyisk5]
      ,'' [a_ofiyisk6]
     , ''  [a_1brmbartip]
      ,'' [a_2brmbartip]
      ,0 [a_intpfisk]
      ,0 [a_intvfisk]
      ,[a_foto]
      ,0 [a_dipfiyat]
      ,0 [a_dipdov]
      ,0 [a_ykfiydeg]
      ,0 [a_uretim]
      ,0 [a_intyay]
      ,0 [a_webyay]
      ,0 [a_int_sfiyat]
      ,0 [a_int_pfiyat]
      ,getdate() [a_baskiyili]
      ,'0' [a_sayfa_sayisi]
      ,'0' [a_kagit_kalite]
      ,'0' [a_uretim_ekmaliyet]
      ,'0' [a_rf_id]
      ,'0' [a_mensei]
      ,'0' [a_cpa]
      ,'0' [a_webdesc]
      ,'0' [a_gtip]
      ,'0' [a_gsure]
      ,'0' [a_eticaret]
      ,'0' [a_bar1islem]
      ,'0' [a_bar1deg]
      ,'0' [a_bar2islem]
      ,'0'  [a_bar2deg]
  FROM ArgelasB2B_Default_v1..EmyEticaret emyEticaret
  left join [dbo].[tbl_001_stok] stok on stok.a_kod = emyEticaret.[Stok Kodu]
  where stok.a_id is null

--  UNION ALL
 --select * from  [dbo].[tbl_001_stok]
--select * from ArgelasB2B_Default_v1..EmyEticaret

