--declare 2481 int = 2481

  WITH ISTSIRA AS  (         SELECT                WSGRPASS.WSGRPREF ,                 ISGTGRUPKODU = WSGRPF.CODE,                
  ISGTGRUPACIKLAMA = WSGRPF.NAME,                  WSREF = WORKSTAT.LOGICALREF ,               ISTKODU = WORKSTAT.CODE,               
  ISTACIKLAMA = WORKSTAT.NAME,          ISTKODU_ACK = WORKSTAT.CODE+'/'+WORKSTAT.NAME,      DWSREF= ISNULL((SELECT  TOP 1 ISNULL(WSREF,0) 
  WSREF FROM LG_022_DISPLINE WHERE WSREF = WORKSTAT.LOGICALREF AND    PRODORDREF =2481)   ,0)         
  FROM LG_022_WSGRPF WSGRPF LEFT JOIN  LG_022_WSGRPASS WSGRPASS ON WSGRPF.LOGICALREF = WSGRPASS.WSGRPREF                  
  LEFT JOIN  LG_022_WORKSTAT WORKSTAT ON WSGRPASS.WSREF = WORKSTAT.LOGICALREF           WHERE WORKSTAT.ACTIVE = 0  ),     
  URETIM AS  (  SELECT  DISPLINE.LINENO_ , [ÜRETÝM EMRÝ]         = PRODORD.FICHENO,  [PLANLANAN_ADET]      = ORFLINE.AMOUNT,  
  [BAÞLANGIÇ TARÝHÝ]       = PRODORD.DATE_ ,  [BÝTÝÞ TARÝHÝ]    = DISPLINE.OPDUEDATE  ,  [MÜÞTERÝ ADI]         = CLCARD.DEFINITION_,  
  [MALZEME_KODU]        =   ITEMS.CODE,  [MLZKODU_URETICIKODU]='',  [MALZEME ADI]         = ITEMS.NAME,  [SÝPARÝÞ NO]          =
  ORFICHE.FICHENO,  [SÝPARÝÞ TARÝHÝ]      =   ORFICHE.DATE_,  [TESLÝM TARÝHÝ]       = ORFLINE.DUEDATE,    [BELGE_NO]     = ORFICHE.DOCODE, 
  VARYANT_KODU= ITEMS.PRODUCERCODE,  [URETICI_KODU]       =  VARIANT.CODE ,  [XT_RENK]               = XT050.RENK,  [XT_EN]             
  = XT050.EN,  [XT_BOY]               = XT050.BOY,  [XT_KALINLIK]           = XT050.KALINLIK,  [XT_SERIGRAF]           = XT050.SERIGRAF,
  [XT_KALIPLIMI]       = XT050.KALIPLIMI ,  [XT_BOMBE]           = XT050.BOMBE ,  [XT_RODAJTIPI]       = XT050.RODAJTIPI ,  [XT_OYUKLU_OYUKSUZ]  
  = XT050.OYUKLU_OYUKSUZ ,  [XT_TAMPERLI_LAMINE]   = XT050.TAMPERLI_LAMINE ,  [XT_FIRINTIPI]       = XT050.FIRINTIPI ,  [XT_GABARI_KALIP_NO]  
  = XT050.GABARI_KALIP_NO ,  [XT_SAHIT_NUMUNE_NO]   = XT050.SAHIT_NUMUNE_NO ,  [XT_ERKEK_BASMA_KALIP_NO] = XT050.ERKEK_BASMA_KALIP_NO , 
  [XT_SERIGRAF_KALIP_NO] = XT050.SERIGRAF_KALIP_NO ,  [XT_DISI_BASMA_KALIP_NO] = XT050.DISI_BASMA_KALIP_NO,  [XT_DELIKACIKLAMA]   = 
  (SELECT ISNULL(STRING_AGG(ACIKLAMA, ','), '') FROM LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = 'Delik'),  [XT_RODAJACIKLAMA]   =
  (SELECT ISNULL(STRING_AGG(ACIKLAMA, ','), '') FROM LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = 'Rodaj')         
  FROM LG_022_DISPLINE DISPLINE  LEFT JOIN LG_022_PRODORD PRODORD     ON DISPLINE.PRODORDREF = PRODORD.LOGICALREF     
  INNER JOIN LG_022_POLINE POLINE       ON POLINE.DISPLINEREF  = DISPLINE.LOGICALREF AND POLINE.LINETYPE = 4     
  INNER JOIN LG_022_ITEMS ITEMS         ON PRODORD.ITEMREF      = ITEMS.LOGICALREF     LEFT JOIN LG_022_PEGGING PEGGING      
  ON PEGGING.PEGREF      = PRODORD.LOGICALREF   
  LEFT  JOIN LG_022_01_ORFICHE ORFICHE  ON ORFICHE.LOGICALREF  = PEGGING.PORDFICHEREF      
  LEFT  JOIN LG_022_01_ORFLINE ORFLINE  ON ORFICHE.LOGICALREF  = ORFLINE.ORDFICHEREF       
  LEFT  JOIN LG_022_01_ORFLINE ORFLINE2  ON ORFICHE.LOGICALREF  = ORFLINE2.ORDFICHEREF AND ITEMS.LOGICALREF = ORFLINE2.STOCKREF     
  LEFT  JOIN LG_022_VARIANT VARIANT  ON VARIANT.LOGICALREF  = ORFLINE2.VARIANTREF      
  LEFT  JOIN LG_022_CLCARD CLCARD       ON CLCARD.LOGICALREF   = ORFICHE.CLIENTREF    
  INNER  JOIN LG_XT050_022 XT050        ON XT050.PARLOGREF     = ITEMS.LOGICALREF  WHERE PRODORD.LOGICALREF = 2481  )  , 
  URETIM1 AS    (  SELECT DISPLINE.LINENO_, [ÜRETÝM EMRÝ]         = PRODORD.FICHENO,  [PLANLANAN_ADET]      = PEGGING.AMOUNT,  
  [BAÞLANGIÇ TARÝHÝ]    = PRODORD.DATE_,  [BÝTÝÞ TARÝHÝ]    = DISPLINE.OPDUEDATE  ,  [MÜÞTERÝ ADI]         = '',  
  [MALZEME_KODU]         = ITEMS.CODE,  [MLZKODU_URETICIKODU]='',  [MALZEME ADI]         = ITEMS.NAME,  [SÝPARÝÞ NO]          = '', 
  [SÝPARÝÞ TARÝHÝ]     = CONVERT(DATETIME, NULL),  [TESLÝM TARÝHÝ]       = CONVERT(DATETIME, NULL),    [BELGE_NO]     = '',  [URETICI_KODU]        
  = ITEMS.PRODUCERCODE,  [XT_RENK]               = XT050.RENK,  [XT_EN]               = XT050.EN,  [XT_BOY] = XT050.BOY,  [XT_KALINLIK]      
  = XT050.KALINLIK,  [XT_SERIGRAF]           = XT050.SERIGRAF,  [XT_KALIPLIMI]        = XT050.KALIPLIMI ,  [XT_BOMBE]           = XT050.BOMBE ,
  [XT_RODAJTIPI]       = XT050.RODAJTIPI ,   [XT_OYUKLU_OYUKSUZ]   = XT050.OYUKLU_OYUKSUZ ,  [XT_TAMPERLI_LAMINE]   = XT050.TAMPERLI_LAMINE ,   
  [XT_FIRINTIPI]       = XT050.FIRINTIPI ,  [XT_GABARI_KALIP_NO]    = XT050.GABARI_KALIP_NO ,   [XT_SAHIT_NUMUNE_NO]   = XT050.SAHIT_NUMUNE_NO ,
  [XT_ERKEK_BASMA_KALIP_NO] = XT050.ERKEK_BASMA_KALIP_NO ,   [XT_SERIGRAF_KALIP_NO] = XT050.SERIGRAF_KALIP_NO ,  
  [XT_DISI_BASMA_KALIP_NO] = XT050.DISI_BASMA_KALIP_NO,    [XT_DELIKACIKLAMA]   = (SELECT ISNULL(STRING_AGG(ACIKLAMA, ' , '), '')
  FROM  LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = 'Delik'),  [XT_RODAJACIKLAMA]     = (SELECT ISNULL(STRING_AGG(ACIKLAMA, ' ,  '), '') 
  FROM LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = 'Rodaj')         
  FROM LG_022_DISPLINE DISPLINE 
  INNER JOIN LG_022_PRODORD PRODORD  ON DISPLINE.PRODORDREF = PRODORD.LOGICALREF    
  INNER JOIN LG_022_POLINE POLINE ON POLINE.DISPLINEREF = DISPLINE.LOGICALREF AND   POLINE.LINETYPE IN (2,3)     
  INNER JOIN LG_022_ITEMS ITEMS   ON PRODORD.ITEMREF        = ITEMS.LOGICALREF  
  INNER JOIN LG_022_PEGGING PEGGING   ON PEGGING.PEGREF         = PRODORD.LOGICALREF        
  INNER  JOIN LG_XT050_022 XT050  ON XT050.PARLOGREF = ITEMS.LOGICALREF  WHERE PRODORD.LOGICALREF = 2481  )  ,   
  SIRA1 AS  (  SELECT  * ,  KULLANILDI = CASE WHEN (SELECT COUNT([MÜÞTERÝ ADI]) FROM URETIM1 WHERE ISTSIRA.DWSREF  =  
  ISTSIRA.WSREF )>0 THEN 'X' ELSE '' END,  [MUSTERI_ADI] = (SELECT TOP 1 [MÜÞTERÝ ADI] FROM URETIM1  ),    [MALZEME_KODU] =
  (SELECT TOP 1 [MALZEME_KODU] FROM URETIM1  ),  [MLZKODU_URETICIKODU]='',  [MALZEME ADI] = (  SELECT TOP 1 [MALZEME ADI] FROM URETIM1  ), 
  [SIPARIS_NO] = (SELECT TOP 1 [SÝPARÝÞ NO] FROM URETIM1  ),   [SÝPARÝÞ TARÝHÝ] = (SELECT TOP 1 [SÝPARÝÞ TARÝHÝ] FROM URETIM1  ),  
  [TESLÝM TARÝHÝ] = (SELECT TOP 1 [TESLÝM TARÝHÝ]   FROM URETIM1  ),  [LINENO_]   =  (SELECT TOP 1 LINENO_ FROM URETIM1  ), [ÜRETÝM EMRÝ]   =  
  (SELECT TOP 1 [ÜRETÝM EMRÝ] FROM URETIM1  ),  [PLANLANAN_ADET] = (SELECT TOP 1   [PLANLANAN_ADET] FROM URETIM1  ),  [BAÞLANGIÇ TARÝHÝ] =
  (SELECT TOP 1 [BAÞLANGIÇ TARÝHÝ] FROM URETIM1  ),  [BÝTÝÞ TARÝHÝ] =  (SELECT TOP 1 [BÝTÝÞ TARÝHÝ] FROM URETIM1  ),  [AÇIKLAMA]   = '', 
  [BELGE NO] = (SELECT TOP 1 BELGE_NO FROM URETIM1  ),   [ÜRETÝCÝ KODU] = (SELECT TOP 1 URETICI_KODU FROM URETIM1), 
  [RENK]= (SELECT TOP 1  XT_RENK FROM URETIM1),            [EN]= (SELECT TOP 1  XT_EN FROM URETIM1),             
  [BOY]= (SELECT TOP 1 XT_BOY FROM URETIM1),           [KALINLIK]= (SELECT TOP 1 XT_KALINLIK FROM URETIM1),            
  [SERÝGRAF]=  (SELECT TOP 1  XT_SERIGRAF FROM URETIM1),             [KALIPLIMI]= (SELECT TOP 1  XT_KALIPLIMI FROM URETIM1),  
  [BOMBE]= (SELECT TOP 1  XT_BOMBE FROM URETIM1),            [RODAJ TÝPÝ]= (SELECT TOP 1  XT_RODAJTIPI FROM URETIM1),         
  [OYUKLU/OYUKSUZ]= (SELECT TOP 1  XT_OYUKLU_OYUKSUZ FROM URETIM1),     [TAMPERLÝ LAMÝNE]= (SELECT TOP 1  XT_TAMPERLI_LAMINE FROM URETIM1),  
  [FIRIN TÝPÝ]= (SELECT TOP 1  XT_FIRINTIPI FROM URETIM1),         [GABARÝ KALIP NO]= (SELECT TOP 1  XT_GABARI_KALIP_NO FROM URETIM1),   
  [ÞAHÝT NUMUNE NO]= (SELECT TOP 1  XT_SAHIT_NUMUNE_NO FROM URETIM1),       [ERKEK BASMA KALIP NO]= (SELECT TOP 1  XT_ERKEK_BASMA_KALIP_NO 
  FROM URETIM1),  [SERÝGRAF KALIP NO]=    (SELECT TOP 1  XT_SERIGRAF_KALIP_NO FROM URETIM1),   
  [DÝÞÝ BASMA KALIP NO]= (SELECT TOP 1  XT_DISI_BASMA_KALIP_NO FROM URETIM1),    
  [XT_DELIKACIKLAMA]   = (SELECT TOP 1  XT_DELIKACIKLAMA FROM URETIM1),  
  [XT_RODAJACIKLAMA]   =     (SELECT TOP 1  XT_RODAJACIKLAMA FROM URETIM1)    FROM ISTSIRA  
  WHERE NOT (SELECT TOP 1 [MALZEME_KODU] FROM URETIM1 ) IS NULL  ),      SIRA AS  
  (  SELECT  * ,  KULLANILDI = CASE WHEN (SELECT COUNT([MÜÞTERÝ ADI]) FROM URETIM WHERE ISTSIRA.DWSREF  = ISTSIRA.WSREF )>0    
  THEN  CAST( (SELECT TOP 1 [PLANLANAN_ADET] FROM URETIM  ) AS VARCHAR(20)) ELSE '' END,  [MUSTERIADI] = (SELECT TOP 1 [MÜÞTERÝ ADI] FROM URETIM  ),  [MALZEME_KODU] = (SELECT TOP 1 [MALZEME_KODU] FROM URETIM  ),     [MLZKODU_URETICIKODU]= (SELECT TOP 1 [MALZEME_KODU] FROM URETIM)+'/'+(SELECT TOP 1 VARYANT_KODU FROM URETIM),  [MALZEME_ADI] = (SELECT TOP 1 [MALZEME ADI] FROM URETIM  ),      [SIPARISNO] = (SELECT TOP 1 [SÝPARÝÞ NO] FROM URETIM  ),  [SIPARIS_TARIHI] = (SELECT TOP 1 [SÝPARÝÞ TARÝHÝ] FROM URETIM  ),  [TESLIM_TARIHI] = (SELECT TOP 1 [TESLÝM TARÝHÝ] FROM URETIM  ),     [LINENO_]   =  (SELECT TOP 1 [LINENO_] FROM URETIM  ), [URETIM_EMRI]   =  (SELECT TOP 1 [ÜRETÝM EMRÝ] FROM URETIM  ), 
  [PLANLANAN_ADET] = (SELECT TOP 1 [PLANLANAN_ADET] FROM URETIM  ),  [BASLANGICTARIHI] =    (SELECT TOP 1 [BAÞLANGIÇ TARÝHÝ] FROM URETIM  ), 
  [BITIS_TARIHI] = (SELECT TOP 1 [BÝTÝÞ TARÝHÝ] FROM URETIM  ),  ACIKLAMA   = '',  [BELGE_NO] =     (SELECT TOP 1 BELGE_NO FROM URETIM  ),  
  [URETICI_KODU] = (SELECT TOP 1 URETICI_KODU FROM URETIM),  [RENK]= (SELECT TOP 1  XT_RENK FROM URETIM),                  
  [EN]= (SELECT TOP 1  XT_EN FROM URETIM),              [BOY]= (SELECT TOP 1 XT_BOY FROM URETIM),                 
  [KALINLIK]= (SELECT TOP 1 XT_KALINLIK FROM URETIM),               [SERIGRAF]= (SELECT TOP 1  XT_SERIGRAF FROM URETIM),            
  [KALIPLIMI]= (SELECT TOP 1  XT_KALIPLIMI FROM URETIM),         [BOMBE]= (SELECT TOP 1  XT_BOMBE FROM URETIM),          
  [RODAJ_TIPI]= (SELECT TOP 1  XT_RODAJTIPI FROM URETIM),         [OYUKLU_OYUKSUZ]= (SELECT TOP 1  XT_OYUKLU_OYUKSUZ FROM URETIM),        
  [TAMPERLI_LAMINE]= (SELECT TOP 1  XT_TAMPERLI_LAMINE FROM URETIM),     [FIRIN_TIPI]= (SELECT TOP 1  XT_FIRINTIPI FROM URETIM),             
  [GABARI_KALIP_NO]= (SELECT TOP 1  XT_GABARI_KALIP_NO FROM URETIM),      [SAHIT_NUMUNE_NO]=     (SELECT TOP 1  XT_SAHIT_NUMUNE_NO FROM URETIM),    
  [ERKEK_BASMA_KALIP_NO]= (SELECT TOP 1  XT_ERKEK_BASMA_KALIP_NO FROM URETIM),      
  [SERIGRAF_KALIP_NO]= (SELECT TOP 1  XT_SERIGRAF_KALIP_NO FROM URETIM),   
  [DISI_BASMA_KALIP_NO]= (SELECT TOP 1  XT_DISI_BASMA_KALIP_NO FROM URETIM),       
  [DELIK_ACIKLAMA]=(SELECT TOP 1 XT_DELIKACIKLAMA FROM URETIM),  
  [RODAJ_ACIKLAMA]=(SELECT TOP 1 XT_RODAJACIKLAMA FROM URETIM)    FROM ISTSIRA   )      
  SELECT *,'Z:\UYGULAMALAR\TIGER3E\IMAGE\'+[MALZEME_KODU]+'.JPG' AS DOSYA_YOLU FROM SIRA   
  UNION ALL       SELECT *,'Z:\UYGULAMALAR\TIGER3E\IMAGE\'+[MALZEME_KODU]+'.JPG' AS DOSYA_YOLU FROM SIRA1 


  SELECT TOP 100  * FROM LG_022_PRODORD ORDER BY LOGICALREF DESC