USE [TIGER]
GO

/****** Object:  StoredProcedure [dbo].[SP_IsEmriFormu]    Script Date: 13.09.2022 10:57:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*

 select * from LG_022_PRODORD WHERE FICHENO = '2209.0101'
 select * from LG_020_PRODORD WHERE FICHENO = '000120'
 select * from LG_020_01_ORFICHE WHERE FICHENO = '201207005'
 select VARIANTREF,* from LG_020_01_ORFLINE WHERE ORDFICHEREF = 1482 AND STOCKREF = 1317  --1317'YÝ NEREDEN BULDUK?
 SELECT * FROM LG_020_VARIANT WHERE LOGICALREF = 2196
 SELECT PRODUCERCODE,* FROM LG_020_ITEMS WHERE CODE = '07 047'
 */

 --EXEC [SP_IsEmriFormu] '','022','01',2481
  
ALTER PROCEDURE [dbo].[SP_IsEmriFormu]
( @DB varchar(255),@FRM varchar(3), @PRD varchar(2), @UretimEmriReferans int)
as 
 

 

 
 
declare @strSQL nvarchar(max)  = ''
 declare @strSQL1 nvarchar(max)  = ''
 declare @strSQL2 nvarchar(max)  = ''
  declare @strSQL3 nvarchar(max)  = ''
if (LEN(@FRM) = 2 )
set @FRM = '0' + @FRM

  
 
 
    
	if (LEN(@PRD) = 1 )
     set @PRD = '0' + @PRD
	 
 
 
	 
	   

		set @strSQL += '
WITH ISTSIRA AS  (         SELECT                WSGRPASS.WSGRPREF ,              
 ISGTGRUPKODU = WSGRPF.CODE,                ISGTGRUPACIKLAMA = WSGRPF.NAME,              
  WSREF = WORKSTAT.LOGICALREF ,               ISTKODU = WORKSTAT.CODE,               ISTACIKLAMA = WORKSTAT.NAME,      
  ISTKODU_ACK = WORKSTAT.CODE+''/''+WORKSTAT.NAME,      DWSREF= ISNULL((SELECT  TOP 1 ISNULL(WSREF,0) WSREF FROM LG_' + @FRM + '_DISPLINE WHERE WSREF = WORKSTAT.LOGICALREF AND
  PRODORDREF =@UretimEmriReferans)   ,0)      
 FROM LG_' + @FRM + '_WSGRPF WSGRPF LEFT JOIN  LG_' + @FRM + '_WSGRPASS WSGRPASS ON WSGRPF.LOGICALREF = WSGRPASS.WSGRPREF                
 LEFT JOIN  LG_' + @FRM + '_WORKSTAT WORKSTAT ON WSGRPASS.WSREF = WORKSTAT.LOGICALREF           WHERE WORKSTAT.ACTIVE = 0  ),  
 URETIM AS  (  SELECT  [ÜRETÝM EMRÝ]         = PRODORD.FICHENO,  [PLANLANAN_ADET]      = POLINE.AMOUNT,  [BAÞLANGIÇ TARÝHÝ]    
 = PRODORD.DATE_ ,  [BÝTÝÞ TARÝHÝ]    = DISPLINE.OPDUEDATE  ,  [MÜÞTERÝ ADI]         = CLCARD.DEFINITION_,  [MALZEME_KODU]        =
 ITEMS.CODE,  [MLZKODU_URETICIKODU]='''',  [MALZEME ADI]         = ITEMS.NAME,  [SÝPARÝÞ NO]          = ORFICHE.FICHENO,  [SÝPARÝÞ TARÝHÝ]      =
 ORFICHE.DATE_,  [TESLÝM TARÝHÝ]       = ORFLINE.DUEDATE,    [BELGE_NO]     = ORFICHE.DOCODE, VARYANT_KODU= ITEMS.PRODUCERCODE,  [URETICI_KODU]       =  VARIANT.CODE ,  [XT_RENK]               = XT050.RENK,  [XT_EN]               = XT050.EN,  [XT_BOY]               = XT050.BOY,  [XT_KALINLIK]           = XT050.KALINLIK,  [XT_SERIGRAF]           = XT050.SERIGRAF,  [XT_KALIPLIMI]       = XT050.KALIPLIMI ,  [XT_BOMBE]           = XT050.BOMBE ,  [XT_RODAJTIPI]       = XT050.RODAJTIPI ,  [XT_OYUKLU_OYUKSUZ]   = XT050.OYUKLU_OYUKSUZ ,  [XT_TAMPERLI_LAMINE]   = XT050.TAMPERLI_LAMINE ,  [XT_FIRINTIPI]       = XT050.FIRINTIPI ,  [XT_GABARI_KALIP_NO]    = XT050.GABARI_KALIP_NO ,  [XT_SAHIT_NUMUNE_NO]   = XT050.SAHIT_NUMUNE_NO ,  [XT_ERKEK_BASMA_KALIP_NO] = XT050.ERKEK_BASMA_KALIP_NO ,  [XT_SERIGRAF_KALIP_NO] = XT050.SERIGRAF_KALIP_NO ,  [XT_DISI_BASMA_KALIP_NO] = XT050.DISI_BASMA_KALIP_NO,  [XT_DELIKACIKLAMA]   = (SELECT ISNULL(STRING_AGG(ACIKLAMA, '',''), '''') FROM LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = ''Delik''),  [XT_RODAJACIKLAMA]   = (SELECT ISNULL(STRING_AGG(ACIKLAMA, '',''), '''') FROM LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = ''Rodaj'')       
 FROM LG_' + @FRM + '_DISPLINE DISPLINE  LEFT JOIN LG_' + @FRM + '_PRODORD PRODORD     ON DISPLINE.PRODORDREF = PRODORD.LOGICALREF  
 INNER JOIN LG_' + @FRM + '_POLINE POLINE       ON POLINE.DISPLINEREF  = DISPLINE.LOGICALREF AND POLINE.LINETYPE = 4  
 INNER JOIN LG_' + @FRM + '_ITEMS ITEMS         ON PRODORD.ITEMREF      = ITEMS.LOGICALREF  
 LEFT JOIN LG_' + @FRM + '_PEGGING PEGGING      ON PEGGING.PEGREF      = PRODORD.LOGICALREF  
 LEFT  JOIN LG_' + @FRM + '_' + @PRD + '_ORFICHE ORFICHE  ON ORFICHE.LOGICALREF  = PEGGING.PORDFICHEREF  
  LEFT  JOIN LG_' + @FRM + '_' + @PRD + '_ORFLINE ORFLINE  ON ORFICHE.LOGICALREF  = ORFLINE.ORDFICHEREF 
    LEFT  JOIN LG_' + @FRM + '_' + @PRD + '_ORFLINE ORFLINE2  ON ORFICHE.LOGICALREF  = ORFLINE2.ORDFICHEREF AND ITEMS.LOGICALREF = ORFLINE2.STOCKREF
   LEFT  JOIN LG_' + @FRM +  '_VARIANT VARIANT  ON VARIANT.LOGICALREF  = ORFLINE2.VARIANTREF 
   LEFT  JOIN LG_' + @FRM + '_CLCARD CLCARD       ON CLCARD.LOGICALREF   = ORFICHE.CLIENTREF  
INNER  JOIN LG_XT050_' + @FRM + ' XT050        ON XT050.PARLOGREF     = ITEMS.LOGICALREF  WHERE PRODORD.LOGICALREF = @UretimEmriReferans  )  , 
URETIM1 AS  
(  SELECT  [ÜRETÝM EMRÝ]         = PRODORD.FICHENO,  [PLANLANAN_ADET]      = POLINE.AMOUNT, 
[BAÞLANGIÇ TARÝHÝ]    = PRODORD.DATE_,  [BÝTÝÞ TARÝHÝ]    = DISPLINE.OPDUEDATE  ,  [MÜÞTERÝ ADI]         = '''',  [MALZEME_KODU]       
= ITEMS.CODE,  [MLZKODU_URETICIKODU]='''',  [MALZEME ADI]         = ITEMS.NAME,  [SÝPARÝÞ NO]          = '''',  [SÝPARÝÞ TARÝHÝ]   
= CONVERT(DATETIME, NULL),  [TESLÝM TARÝHÝ]       = CONVERT(DATETIME, NULL),    [BELGE_NO]     = '''',  [URETICI_KODU]      
= ITEMS.PRODUCERCODE,  [XT_RENK]               = XT050.RENK,  [XT_EN]               = XT050.EN,  [XT_BOY] '               
 SET @strSQL1 = '= XT050.BOY,  [XT_KALINLIK]           = XT050.KALINLIK,  [XT_SERIGRAF]           = XT050.SERIGRAF,  [XT_KALIPLIMI]      
= XT050.KALIPLIMI ,  [XT_BOMBE]           = XT050.BOMBE ,  [XT_RODAJTIPI]       = XT050.RODAJTIPI , 
[XT_OYUKLU_OYUKSUZ]   = XT050.OYUKLU_OYUKSUZ ,  [XT_TAMPERLI_LAMINE]   = XT050.TAMPERLI_LAMINE , 
[XT_FIRINTIPI]       = XT050.FIRINTIPI ,  [XT_GABARI_KALIP_NO]    = XT050.GABARI_KALIP_NO , 
[XT_SAHIT_NUMUNE_NO]   = XT050.SAHIT_NUMUNE_NO ,  [XT_ERKEK_BASMA_KALIP_NO] = XT050.ERKEK_BASMA_KALIP_NO , 
[XT_SERIGRAF_KALIP_NO] = XT050.SERIGRAF_KALIP_NO ,  [XT_DISI_BASMA_KALIP_NO] = XT050.DISI_BASMA_KALIP_NO,  
[XT_DELIKACIKLAMA]   = (SELECT ISNULL(STRING_AGG(ACIKLAMA, '' , ''), '''') FROM
LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = ''Delik''),  [XT_RODAJACIKLAMA]   
= (SELECT ISNULL(STRING_AGG(ACIKLAMA, '' ,  ''), '''') FROM LG_XT052 WHERE ITEMREF = ITEMS.LOGICALREF AND TIP = ''Rodaj'')       
FROM LG_' + @FRM + '_DISPLINE DISPLINE  INNER JOIN LG_' + @FRM + '_PRODORD PRODORD     ON DISPLINE.PRODORDREF = PRODORD.LOGICALREF 
 INNER JOIN LG_' + @FRM + '_POLINE POLINE ON POLINE.DISPLINEREF = DISPLINE.LOGICALREF AND POLINE.LINETYPE IN (2,3) 
  INNER JOIN LG_' + @FRM + '_ITEMS ITEMS         ON PRODORD.ITEMREF        = ITEMS.LOGICALREF  INNER JOIN LG_' + @FRM + '_PEGGING PEGGING    
   ON PEGGING.PEGREF         = PRODORD.LOGICALREF  
   
INNER  JOIN LG_XT050_' + @FRM + ' XT050        ON XT050.PARLOGREF = ITEMS.LOGICALREF  WHERE PRODORD.LOGICALREF = @UretimEmriReferans  )  , 
SIRA1 AS  (  SELECT  * ,  KULLANILDI = CASE WHEN (SELECT COUNT([MÜÞTERÝ ADI]) FROM URETIM1 WHERE ISTSIRA.DWSREF  = 
ISTSIRA.WSREF )>0 THEN ''X'' ELSE '''' END,  [MUSTERI_ADI] = (SELECT TOP 1 [MÜÞTERÝ ADI] FROM URETIM1  ),  
[MALZEME_KODU] = (SELECT TOP 1 [MALZEME_KODU] FROM URETIM1  ),  [MLZKODU_URETICIKODU]='''',  [MALZEME ADI] = (
SELECT TOP 1 [MALZEME ADI] FROM URETIM1  ),  [SIPARIS_NO] = (SELECT TOP 1 [SÝPARÝÞ NO] FROM URETIM1  ), 
[SÝPARÝÞ TARÝHÝ] = (SELECT TOP 1 [SÝPARÝÞ TARÝHÝ] FROM URETIM1  ),  [TESLÝM TARÝHÝ] = (SELECT TOP 1 [TESLÝM TARÝHÝ] 
FROM URETIM1  ),  [ÜRETÝM EMRÝ]   =  (SELECT TOP 1 [ÜRETÝM EMRÝ] FROM URETIM1  ),  [PLANLANAN_ADET] = (SELECT TOP 1 
[PLANLANAN_ADET] FROM URETIM1  ),  [BAÞLANGIÇ TARÝHÝ] = (SELECT TOP 1 [BAÞLANGIÇ TARÝHÝ] FROM URETIM1  ),  [BÝTÝÞ TARÝHÝ] =
(SELECT TOP 1 [BÝTÝÞ TARÝHÝ] FROM URETIM1  ),  [AÇIKLAMA]   = '''',  [BELGE NO] = (SELECT TOP 1 BELGE_NO FROM URETIM1  ), 
[ÜRETÝCÝ KODU] = (SELECT TOP 1 URETICI_KODU FROM URETIM1),  [RENK]= (SELECT TOP 1  XT_RENK FROM URETIM1),          
[EN]= (SELECT TOP 1  XT_EN FROM URETIM1),              [BOY]= (SELECT TOP 1 XT_BOY FROM URETIM1),         
[KALINLIK]= (SELECT TOP 1 XT_KALINLIK FROM URETIM1),             [SERÝGRAF]=
(SELECT TOP 1  XT_SERIGRAF FROM URETIM1),             [KALIPLIMI]= (SELECT TOP 1  XT_KALIPLIMI FROM URETIM1), 
[BOMBE]= (SELECT TOP 1  XT_BOMBE FROM URETIM1),          
[RODAJ TÝPÝ]= (SELECT TOP 1  XT_RODAJTIPI FROM URETIM1),       
[OYUKLU/OYUKSUZ]= (SELECT TOP 1  XT_OYUKLU_OYUKSUZ FROM URETIM1),   
[TAMPERLÝ LAMÝNE]= (SELECT TOP 1  XT_TAMPERLI_LAMINE FROM URETIM1),  '
SET @strSQL2 = '
[FIRIN TÝPÝ]= (SELECT TOP 1  XT_FIRINTIPI FROM URETIM1),       
[GABARÝ KALIP NO]= (SELECT TOP 1  XT_GABARI_KALIP_NO FROM URETIM1),  
[ÞAHÝT NUMUNE NO]= (SELECT TOP 1  XT_SAHIT_NUMUNE_NO FROM URETIM1),    
 [ERKEK BASMA KALIP NO]= (SELECT TOP 1  XT_ERKEK_BASMA_KALIP_NO FROM URETIM1),  [SERÝGRAF KALIP NO]= 
 (SELECT TOP 1  XT_SERIGRAF_KALIP_NO FROM URETIM1),   [DÝÞÝ BASMA KALIP NO]= (SELECT TOP 1  XT_DISI_BASMA_KALIP_NO FROM URETIM1), 
  [XT_DELIKACIKLAMA]   = (SELECT TOP 1  XT_DELIKACIKLAMA FROM URETIM1),  [XT_RODAJACIKLAMA]   = 
  (SELECT TOP 1  XT_RODAJACIKLAMA FROM URETIM1)    FROM ISTSIRA   WHERE NOT (SELECT TOP 1 [MALZEME_KODU] FROM URETIM1 ) IS NULL  ),  
  SIRA AS  (  SELECT  * ,  KULLANILDI = CASE WHEN (SELECT COUNT([MÜÞTERÝ ADI]) FROM URETIM WHERE ISTSIRA.DWSREF  = ISTSIRA.WSREF )>0 
  THEN ''X'' ELSE '''' END,  [MUSTERIADI] = (SELECT TOP 1 [MÜÞTERÝ ADI] FROM URETIM  ),  [MALZEME_KODU] = (SELECT TOP 1 [MALZEME_KODU] FROM URETIM  ), 
  [MLZKODU_URETICIKODU]= (SELECT TOP 1 [MALZEME_KODU] FROM URETIM)+''/''+(SELECT TOP 1 VARYANT_KODU FROM URETIM),  [MALZEME_ADI] = (SELECT TOP 1 [MALZEME ADI] FROM URETIM  ),  
  [SIPARISNO] = (SELECT TOP 1 [SÝPARÝÞ NO] FROM URETIM  ),  [SIPARIS_TARIHI] = (SELECT TOP 1 [SÝPARÝÞ TARÝHÝ] FROM URETIM  ),  [TESLIM_TARIHI] = (SELECT TOP 1 [TESLÝM TARÝHÝ] FROM URETIM  ), 
  [URETIM_EMRI]   =  (SELECT TOP 1 [ÜRETÝM EMRÝ] FROM URETIM  ),  [PLANLANAN_ADET] = (SELECT TOP 1 [PLANLANAN_ADET] FROM URETIM  ),  [BASLANGICTARIHI] =
  (SELECT TOP 1 [BAÞLANGIÇ TARÝHÝ] FROM URETIM  ),  [BITIS_TARIHI] = (SELECT TOP 1 [BÝTÝÞ TARÝHÝ] FROM URETIM  ),  ACIKLAMA   = '''',  [BELGE_NO] = 
  (SELECT TOP 1 BELGE_NO FROM URETIM  ),  [URETICI_KODU] = (SELECT TOP 1 URETICI_KODU FROM URETIM),  [RENK]= (SELECT TOP 1  XT_RENK FROM URETIM),               
  [EN]= (SELECT TOP 1  XT_EN FROM URETIM),              [BOY]= (SELECT TOP 1 XT_BOY FROM URETIM),                 [KALINLIK]= (SELECT TOP 1 XT_KALINLIK FROM URETIM),           
  [SERIGRAF]= (SELECT TOP 1  XT_SERIGRAF FROM URETIM),             [KALIPLIMI]= (SELECT TOP 1  XT_KALIPLIMI FROM URETIM),         [BOMBE]= (SELECT TOP 1  XT_BOMBE FROM URETIM),      
  [RODAJ_TIPI]= (SELECT TOP 1  XT_RODAJTIPI FROM URETIM),         [OYUKLU_OYUKSUZ]= (SELECT TOP 1  XT_OYUKLU_OYUKSUZ FROM URETIM),    
  [TAMPERLI_LAMINE]= (SELECT TOP 1  XT_TAMPERLI_LAMINE FROM URETIM),     [FIRIN_TIPI]= (SELECT TOP 1  XT_FIRINTIPI FROM URETIM),         
  [GABARI_KALIP_NO]= (SELECT TOP 1  XT_GABARI_KALIP_NO FROM URETIM),      [SAHIT_NUMUNE_NO]= 
  (SELECT TOP 1  XT_SAHIT_NUMUNE_NO FROM URETIM),     [ERKEK_BASMA_KALIP_NO]= (SELECT TOP 1  XT_ERKEK_BASMA_KALIP_NO FROM URETIM), 
   [SERIGRAF_KALIP_NO]= (SELECT TOP 1  XT_SERIGRAF_KALIP_NO FROM URETIM),   [DISI_BASMA_KALIP_NO]= (SELECT TOP 1  XT_DISI_BASMA_KALIP_NO FROM URETIM),  
   [DELIK_ACIKLAMA]=(SELECT TOP 1 XT_DELIKACIKLAMA FROM URETIM),  [RODAJ_ACIKLAMA]=(SELECT TOP 1 XT_RODAJACIKLAMA FROM URETIM)    FROM ISTSIRA   ) 
   SELECT *,''Z:\UYGULAMALAR\TIGER3E\IMAGE\''+[MALZEME_KODU]+''.JPG'' AS DOSYA_YOLU FROM SIRA   UNION ALL  
   SELECT *,''Z:\UYGULAMALAR\TIGER3E\IMAGE\''+[MALZEME_KODU]+''.JPG'' AS DOSYA_YOLU FROM SIRA1 '
		


	 
 
 --SELECT PRODUCERCODE,* FROM LG_020_ITEMS WHERE CODE = '10 008'

 
 SET @strSQL3 = CONCAT(@strSQL, @strSQL1 , @strSQL2 )

 
-- SELECT @strSQL3
declare  @Tbl table
( 

 WSGRPREF int,
           ISGTGRUPKODU varchar(25),
           ISGTGRUPACIKLAMA varchar(51),
           WSREF int,
           ISTKODU varchar(25),
           ISTACIKLAMA varchar(51),
           ISTKODU_ACK varchar(77),
           DWSREF int,
           KULLANILDI varchar(1),
           MUSTERIADI varchar(201),
           MALZEME_KODU varchar(25),
           MLZKODU_URETICIKODU varchar(127),
           MALZEME_ADI varchar(51),
           SIPARISNO varchar(17),
           SIPARIS_TARIHI datetime  NOT NULL,
           TESLIM_TARIHI datetime  NOT NULL,
           URETIM_EMRI varchar(17),
           PLANLANAN_ADET float  NOT NULL,
           BASLANGICTARIHI datetime NOT NULL,
           BITIS_TARIHI datetime  NOT NULL,
           ACIKLAMA varchar(1),
           BELGE_NO varchar(33),
           URETICI_KODU varchar(101),
           RENK varchar(50),
           EN float  NOT NULL,
           BOY float  NOT NULL,
           KALINLIK float  NOT NULL,
           SERIGRAF varchar(50),
           KALIPLIMI varchar(50),
           BOMBE varchar(50),
           RODAJ_TIPI varchar(50),
           OYUKLU_OYUKSUZ varchar(50),
           TAMPERLI_LAMINE varchar(50),
           FIRIN_TIPI varchar(50),
           GABARI_KALIP_NO varchar(50),
           SAHIT_NUMUNE_NO varchar(50),
           ERKEK_BASMA_KALIP_NO varchar(50),
           SERIGRAF_KALIP_NO varchar(50),
           DISI_BASMA_KALIP_NO varchar(50),
           DELIK_ACIKLAMA varchar(8000),
           RODAJ_ACIKLAMA varchar(8000),
           DOSYA_YOLU varchar(58)

)
insert into @tbl
exec sp_executesql @strSQL3
            ,N'@UretimEmriReferans int'
            ,@UretimEmriReferans

			select  * from @tbl
			--UNION ALL 
			--select TOP 1 * from VW_ISEMRI_FORMU

 

         
 

  
 
GO


