 
/****** Object:  StoredProcedure [dbo].[Sp_Specode_Kontrol]    Script Date: 25.03.2022 10:45:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--EXEC [Sp_Specode_Kontrol]
--SELECT * FROM L_CAPIFIRM  WHERE PERNR > 15
ALTER  PROCEDURE [dbo].[Sp_IrsaliyeNo_FaturaBelgeNoAktar]
as
DECLARE @LOGICALREF INT
DECLARE @FICHENO VARCHAR(150)
DECLARE @NR VARCHAR(50)
DECLARE @String VARCHAR(8000)
 
 

DECLARE MainProc CURSOR FOR

select LG_221_01_INVOICE.LOGICALREF,  LG_221_01_STFICHE.INVNO ,LG_221_01_INVOICE.FICHENO,LG_221_01_INVOICE.DOCODE,* from LG_221_01_INVOICE 
 LEFT JOIN LG_221_01_STFICHE ON LG_221_01_STFICHE.INVOICEREF = LG_221_01_INVOICE.LOGICALREF
WHERE   LG_221_01_INVOICE.TRCODE = 1 AND
   LEN(LG_221_01_INVOICE.DOCODE)=0 AND LG_221_01_STFICHE.INVNO IS NOT NULL --AND LEN(LG_221_01_STFICHE.FICHENO)> 10 
 --AND LG_221_01_INVOICE.FICHENO LIKE '%2981'

OPEN MainProc

FETCH NEXT FROM MainProc
INTO @LOGICALREF,@FICHENO
WHILE @@FETCH_STATUS = 0
BEGIN
    IF (LEN(@NR) = 2)
      SET @NR = '0' + @NR
	Set @String	= 'DECLARE @SPECODE VARCHAR(25)
		DECLARE @SPECODE_COUNT INT
		DECLARE @VARMI INT
		DECLARE @LastSeq INT 

		DECLARE @DEFINITION_  VARCHAR(100)
		DECLARE @COLOR        INT
		DECLARE @WINCOLOR     INT
		DECLARE @SITEID       INT
		DECLARE @RECSTATUS    INT
		DECLARE @ORGLOGICREF  INT
		DECLARE @MARKA        VARCHAR(50)
		DECLARE @MODEL        INT
		DECLARE @KAPASITE     INT
		DECLARE @GRUBU        VARCHAR(50)
		SELECT  SPECODE,COUNT(SPECODE) FROM LG_' + @NR + '_SPECODES (NOLOCK) WHERE SPECODETYPE IN (3,17,20,21,24,25,27,33) GROUP BY SPECODE
				HAVING  COUNT(SPECODE)<8


		DECLARE processes CURSOR FOR
		SELECT  SPECODE,COUNT(SPECODE) FROM LG_' + @NR + '_SPECODES (NOLOCK) WHERE SPECODETYPE IN (3,17,20,21,24,25,27,33) GROUP BY SPECODE
				HAVING  COUNT(SPECODE)<8
		OPEN processes

		FETCH NEXT FROM processes
		INTO @SPECODE,@SPECODE_COUNT
		WHILE @@FETCH_STATUS = 0
		BEGIN
		   SET @VARMI = 0 
		   --TÜM BÝLGÝLERÝN OLDUÐU KAYIT TESPÝT EDÝLÝYOR...
		   SELECT TOP 1 @DEFINITION_=DEFINITION_,@COLOR=COLOR,@WINCOLOR=WINCOLOR,@SITEID=SITEID,@RECSTATUS=RECSTATUS,@ORGLOGICREF=ORGLOGICREF  FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE ORDER BY SITEID DESC
		   --SIRASIYLA TUM SPECODE''LAR KONTROL EDÝLÝYOR
		   --1. SPECODETYPE=3
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 3
			IF  @VARMI = 0 
			BEGIN
				 
				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,3,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END
			
		   --2. SPECODETYPE=17 satýnalma sipariþi
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 17
			IF  @VARMI = 0 
			BEGIN
				 
				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,17,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END
			
		   --3. SPECODETYPE=20
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 20
			IF  @VARMI = 0 
			BEGIN
				 
			
				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,20,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END
		   --4. SPECODETYPE=21
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 21
			IF  @VARMI = 0 
			BEGIN
				  
				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,21,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END  
		   --5. SPECODETYPE=24
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 24
			IF  @VARMI = 0 
			BEGIN

				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,24,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END   
		   --6. SPECODETYPE=25
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 25
			IF  @VARMI = 0 
			BEGIN

				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,25,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END  
		   --7. SPECODETYPE=27
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 27
			IF  @VARMI = 0 
			BEGIN

				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,27,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END 
		   --8. SPECODETYPE=33
			SET @VARMI = 0
			SELECT @VARMI=LOGICALREF FROM  LG_' + @NR + '_SPECODES WHERE SPECODE = @SPECODE AND SPECODETYPE = 33
			IF  @VARMI = 0 
			BEGIN
				 
				  INSERT INTO [LG_' + @NR + '_SPECODES] ([CODETYPE],[SPECODETYPE],[SPECODE],[DEFINITION_],[COLOR],[WINCOLOR],[SITEID],[RECSTATUS],[ORGLOGICREF])
	   			  VALUES (1,33,@SPECODE,@DEFINITION_,@COLOR,@WINCOLOR,@SITEID,@RECSTATUS,@ORGLOGICREF)	
			END 
		FETCH NEXT FROM processes
		INTO @SPECODE,@SPECODE_COUNT
		END
		CLOSE processes
		DEALLOCATE processes'
		select @string
   EXEC (@string)


FETCH NEXT FROM MainProc
INTO @NR
END
CLOSE MainProc
DEALLOCATE MainProc

