declare @SPDAHIL int

set @SPDAHIL = 1
Select * from (
select CARIREF, CARIADI, SUM(ISNULL(GENELTOPLAM,0) - ISNULL(TOPLAMOIV,0) - (ISNULL(TOPLAMKDV,0)-ISNULL(TOPLAMTVK,0)) + case when @SPDAHIL=1 and TUR = 271 THEN ISNULL(TOPLAMGV,0) when TUR = 69 THEN ISNULL(TOPLAMKESINTI,0) ELSE 0 end+isnull(TOPLAMMERAFONU,0)) as 'TUTAR', COUNT(SIRANO) as 'EVRAKADEDI', SUM(CASE WHEN AORS='S' THEN ISNULL(GENELTOPLAM,0) - (ISNULL(TOPLAMKDV,0)-ISNULL(TOPLAMTVK,0)) END+isnull(TOPLAMMERAFONU,0)) as 'TUTAR_S', COUNT(CASE WHEN AORS='S' THEN SIRANO END) as 'EVRAKADEDI_S', SUM(CASE WHEN AORS='A' THEN ISNULL(GENELTOPLAM,0) - (ISNULL(TOPLAMKDV,0)-ISNULL(TOPLAMTVK,0)) END+case when TUR = 271 THEN ISNULL(TOPLAMGV,0) ELSE 0 end+isnull(TOPLAMMERAFONU,0)) as 'TUTAR_A', COUNT(CASE WHEN AORS='A' THEN SIRANO END) as 'EVRAKADEDI_A',Carivergino as VERGINO,GMHK,ISNULL(ULKEKODU,'052') AS ULKEKODU,TELFAX,VERGID, sum(case when zirvegenel.dbo.EBelgemi(EVRAKNO, EVRAKTAR)=1 then 1 end) EBELGE_ADET, SUM(case when zirvegenel.dbo.EBelgemi(EVRAKNO, EVRAKTAR)=1 then ISNULL(GENELTOPLAM,0) - ISNULL(TOPLAMOIV,0) - (ISNULL(TOPLAMKDV,0)-ISNULL(TOPLAMTVK,0)) + case when @SPDAHIL=1 and TUR = 271 THEN ISNULL(TOPLAMGV,0) when TUR = 69 THEN ISNULL(TOPLAMKESINTI,0) ELSE 0 end+isnull(TOPLAMMERAFONU,0) end) as 'EBELGE_TUTAR', sum(case when zirvegenel.dbo.EBelgemi(EVRAKNO, EVRAKTAR)=0 then 1 end) KAGIT_ADET, SUM(case when zirvegenel.dbo.EBelgemi(EVRAKNO, EVRAKTAR)=0 then ISNULL(GENELTOPLAM,0) - ISNULL(TOPLAMOIV,0) - (ISNULL(TOPLAMKDV,0)-ISNULL(TOPLAMTVK,0)) + case when @SPDAHIL=1 and TUR = 271 THEN ISNULL(TOPLAMGV,0) when TUR = 69 THEN ISNULL(TOPLAMKESINTI,0) ELSE 0 end+isnull(TOPLAMMERAFONU,0) end) as 'KAGIT_TUTAR' FROM LISTEFATURA() AS FATURA
where CARIREF IN (SELECT REF FROM CARIGEN WHERE (CRK>='120.0010067299') and (CRK<='336.62986085532')) AND ISNULL(IPTAL,0) = 0

GROUP BY CARIREF,CARIADI,Carivergino,GMHK,ISNULL(ULKEKODU,'052'),TELFAX,VERGID
) A Where A.TUTAR_S>='8000' or TUTAR_A>='8000'


ORDER BY 3 DESC
