USE [AltinCezveB2B_Default_v1]
GO

/****** Object:  View [dbo].[VW_MalzemeReferanslar_25]    Script Date: 04.01.2025 13:52:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER  VIEW [dbo].[VW_MalzemeReferanslar_25] AS 
SELECT 
ITM.LOGICALREF AS ITEMREF,
ITM.CODE as ITEMCODE,
ITM.NAME AS NAME,
BOM.LOGICALREF AS BOMREF ,
ITMU.UNITLINEREF AS UOMREF,
VALIDREVREF AS REVISIONREF
FROM  CEZVE..LG_325_BOMASTER BOM
LEFT JOIN CEZVE..LG_325_ITEMS ITM ON ITM.LOGICALREF = MAINPRODREF
LEFT JOIN CEZVE..LG_325_ITMUNITA ITMU ON ITEMREF = MAINPRODREF AND LINENR= 1
--LEFT JOIN CEZVE..LG_325_BOMREVSN RVS ON RVS.BOMMASTERREF= BOM.LOGICALREF 
 WHERE BOM.ACTIVE = 0

-- UNION ALL

--SELECT 
--ITM.LOGICALREF AS ITEMREF,
--ITM.CODE as ITEMCODE,
--ITM.NAME AS NAME,
--BOM.LOGICALREF AS BOMREF ,
--ITMU.UNITLINEREF AS UOMREF,
--VALIDREVREF AS REVISIONREF
--FROM  CEZVE..LG_324_BOMASTER BOM
--LEFT JOIN CEZVE..LG_324_ITEMS ITM ON ITM.LOGICALREF = MAINPRODREF
--LEFT JOIN CEZVE..LG_324_ITMUNITA ITMU ON ITEMREF = MAINPRODREF AND LINENR= 1
----LEFT JOIN CEZVE..LG_325_BOMREVSN RVS ON RVS.BOMMASTERREF= BOM.LOGICALREF 
-- WHERE BOM.ACTIVE = 0 


SELECT [VW_MalzemeReferanslar_25].ITEMCODE,UretimEmri.ItemCode , 
'UPDATE UretimEmri SET ItemCode=''' + [VW_MalzemeReferanslar_25].ITEMCODE + ''' WHERE UretimEmriId=' + cast(UretimEmriId as varchar(30)) FROM UretimEmri 
left join [VW_MalzemeReferanslar_25] ON [VW_MalzemeReferanslar_25].ITEMREF = UretimEmri.ItemRef
Where YEAR(FicheDate) >= 2025




SELECT * FROM [VW_MalzemeReferanslar_25] WHERE ITEMREF = 2789


SELECT * FROM VW_UretimEmirleriListesi Where UretimEmriId = 1935
