USE [AltinCezveB2B_Default_v1]
GO

/****** Object:  View [dbo].[VW_TigerGoSatinalmaFaturaKarsilastirmaListesi]    Script Date: 23.05.2025 12:04:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--ALTER view [dbo].[VW_TigerGoSatinalmaFaturaKarsilastirmaListesi] AS

/*
select 
GO3_STL.LOGICALREF,
TGR_CLC.CODE AS TigerCariKodu,TGR_CLC.DEFINITION_ AS TigerCariAdi,
TGR_INV.FICHENO As TigerFaturaNoOrijinal,
TGR_INV.DOCODE as TigerFaturaNoDocode,
--TGR_ITM.code as TigerMalzemeKodu,
--TGR_ITM.NAME as TigerMalzemeAdi,
CASE WHEN TGR_STL.LINETYPE = 4 THEN TGR_SRV.code ELSE TGR_ITM.code END  as TigerMalzemeKodu,
CASE WHEN TGR_STL.LINETYPE = 4 THEN TGR_SRV.DEFINITION_ ELSE TGR_ITM.NAME END  as TigerMalzemeAdi,
TGR_STL.AMOUNT as TigerMalzemeAdet,
TGR_STL.PRICE as TigerMalzemeBirimFiyat,
TGR_STL.LINENET as TigerMalzemeToplam,
 
cASE WHEN GO3_INV.TRCODE =1 THEN 'Satýnalma Faturasý' else 'Alýnan Hizmet Faturasý'  end as GoFaturaTuru, 
GO3_CLC.CODE AS GoCariKodu,
GO3_CLC.DEFINITION_ AS GoCariAdi, 
GO3_INV.FICHENO GoFaturaNo,
GO3_INV.DATE_ GoFaturaTarih,
CASE WHEN GO3_STL.LINETYPE = 4 THEN GO3_SRV.code ELSE GO3_ITM.code END  as GoMalzemeKodu,
CASE WHEN GO3_STL.LINETYPE = 4 THEN GO3_SRV.DEFINITION_ ELSE GO3_ITM.NAME END  as GoMalzemeAdi,
--GO3_ITM.NAME as GoMalzemeAdi,
GO3_STL.AMOUNT as GoMalzemeAdet,
GO3_STL.PRICE as GoMalzemeBirimFiyat,
GO3_STL.LINENET as GoMalzemeToplam,
'1- Tiger ile Go fatura satýr tutarlarý eþleþmiyor' as Aciklama
from GO3DB..LG_425_01_INVOICE GO3_INV WITH(NOLOCK)
LEFT JOIN CEZVE..LG_325_01_INVOICE TGR_INV  WITH(NOLOCK) ON TGR_INV.DOCODE = GO3_INV.FICHENO

LEFT JOIN GO3DB..LG_425_CLCARD GO3_CLC WITH(NOLOCK) ON GO3_INV.CLIENTREF = GO3_CLC.LOGICALREF

LEFT JOIN CEZVE..LG_325_CLCARD TGR_CLC WITH(NOLOCK) ON TGR_INV.CLIENTREF = TGR_CLC.LOGICALREF --TGR_CLC.CODE = GO3_CLC.CODE

LEFT JOIN GO3DB..LG_425_01_STLINE GO3_STL WITH(NOLOCK) ON GO3_STL.INVOICEREF = GO3_INV.LOGICALREF
LEFT JOIN GO3DB..LG_425_ITEMS GO3_ITM WITH(NOLOCK) ON GO3_ITM.LOGICALREF = GO3_STL.STOCKREF  
LEFT JOIN GO3DB..LG_425_SRVCARD GO3_SRV WITH(NOLOCK) ON GO3_SRV.LOGICALREF = GO3_STL.STOCKREF  
LEFT JOIN CEZVE..LG_325_01_STLINE TGR_STL WITH(NOLOCK) ON TGR_STL.INVOICEREF = TGR_INV.LOGICALREF AND   
									TGR_STL.AMOUNT =  GO3_STL.AMOUNT AND TGR_STL.PRICE BETWEEN  GO3_STL.PRICE -1  AND GO3_STL.PRICE +1 
LEFT JOIN CEZVE..LG_325_ITEMS TGR_ITM WITH(NOLOCK) ON TGR_ITM.LOGICALREF = TGR_STL.STOCKREF  
LEFT JOIN CEZVE..LG_325_SRVCARD TGR_SRV WITH(NOLOCK) ON TGR_SRV.LOGICALREF = TGR_STL.STOCKREF  
WHERE GO3_INV.TRCODE  IN  (1,4)
--AND ROUND(GO3_STL.LINENET,0) <> ROUND(TGR_STL.LINENET,0)
AND ABS(ROUND(GO3_STL.LINENET, 2) - ROUND(TGR_STL.LINENET, 2)) > 1   -- +1 TL toleranslý hale getirildi.
 
UNION ALL
SELECT 
    TGR_STL.LOGICALREF,
    TGR_CLC.CODE AS TigerCariKodu, TGR_CLC.DEFINITION_ AS TigerCariAdi,
    TGR_INV.FICHENO AS TigerFaturaNo,
    TGR_INV.DOCODE AS TigerFaturaNo2,
    CASE WHEN TGR_STL.LINETYPE = 4 THEN TGR_SRV.CODE ELSE TGR_ITM.CODE END AS TigerMalzemeKodu,
    CASE WHEN TGR_STL.LINETYPE = 4 THEN TGR_SRV.DEFINITION_ ELSE TGR_ITM.NAME END AS TigerMalzemeAdi,
    TGR_STL.AMOUNT AS TigerMalzemeAdet,
    TGR_STL.PRICE AS TigerMalzemeBirimFiyat,
    TGR_STL.LINENET AS TigerMalzemeToplam,
    
    NULL AS GoFaturaTuru,
    NULL AS GoCariKodu,
    NULL AS GoCariAdi,
    NULL AS GoFaturaNo,
    NULL AS GoFaturaTarih,
    NULL AS GoMalzemeKodu,
    NULL AS GoMalzemeAdi,
    NULL AS GoMalzemeAdet,
    NULL AS GoMalzemeBirimFiyat,
    NULL AS GoMalzemeToplam,
	'2-Tiger"da bulunan ancak Go"da bulunmayan irsaliyeler' as Aciklama
FROM CEZVE..LG_325_01_INVOICE TGR_INV WITH(NOLOCK)
LEFT JOIN CEZVE..LG_325_01_STLINE TGR_STL WITH(NOLOCK) ON TGR_STL.INVOICEREF = TGR_INV.LOGICALREF
LEFT JOIN CEZVE..LG_325_CLCARD TGR_CLC WITH(NOLOCK) ON TGR_INV.CLIENTREF = TGR_CLC.LOGICALREF
LEFT JOIN CEZVE..LG_325_ITEMS TGR_ITM WITH(NOLOCK) ON TGR_ITM.LOGICALREF = TGR_STL.STOCKREF
LEFT JOIN CEZVE..LG_325_SRVCARD TGR_SRV WITH(NOLOCK) ON TGR_SRV.LOGICALREF = TGR_STL.STOCKREF

-- Go tarafýnda eþleþme bulunamayanlar
LEFT JOIN GO3DB..LG_425_01_INVOICE GO3_INV WITH(NOLOCK) ON GO3_INV.FICHENO = TGR_INV.DOCODE
LEFT JOIN GO3DB..LG_425_01_STLINE GO3_STL WITH(NOLOCK) 
    ON GO3_STL.INVOICEREF = GO3_INV.LOGICALREF 
    AND GO3_STL.AMOUNT = TGR_STL.AMOUNT 
    AND GO3_STL.PRICE BETWEEN TGR_STL.PRICE - 1 AND TGR_STL.PRICE + 1

WHERE GO3_STL.LOGICALREF IS NULL and (TGR_INV.TRCODE=1 or TGR_INV.TRCODE=4) and   (GO3_INV.TRCODE=1 or GO3_INV.TRCODE=4)
 

UNION ALL

*/

SELECT 
    TGR_STL.LOGICALREF,
    TGR_CLC.CODE AS TigerCariKodu, TGR_CLC.DEFINITION_ AS TigerCariAdi,
    TGR_INV.FICHENO AS TigerFaturaNo,
    TGR_INV.DOCODE AS TigerFaturaNo2,
    CASE WHEN TGR_STL.LINETYPE = 4 THEN TGR_SRV.CODE ELSE TGR_ITM.CODE END AS TigerMalzemeKodu,
    CASE WHEN TGR_STL.LINETYPE = 4 THEN TGR_SRV.DEFINITION_ ELSE TGR_ITM.NAME END AS TigerMalzemeAdi,
    TGR_STL.AMOUNT AS TigerMalzemeAdet,
    TGR_STL.PRICE AS TigerMalzemeBirimFiyat,
    TGR_STL.LINENET AS TigerMalzemeToplam,

    CASE WHEN GO3_INV.TRCODE = 1 THEN 'Satýnalma Faturasý' ELSE 'Alýnan Hizmet Faturasý' END AS GoFaturaTuru,
    GO3_CLC.CODE AS GoCariKodu,
    GO3_CLC.DEFINITION_ AS GoCariAdi,
    GO3_INV.FICHENO AS GoFaturaNo,
    GO3_INV.DATE_ AS GoFaturaTarih,
    CASE WHEN GO3_STL.LINETYPE = 4 THEN GO3_SRV.CODE ELSE GO3_ITM.CODE END AS GoMalzemeKodu,
    CASE WHEN GO3_STL.LINETYPE = 4 THEN GO3_SRV.DEFINITION_ ELSE GO3_ITM.NAME END AS GoMalzemeAdi,
    GO3_STL.AMOUNT AS GoMalzemeAdet,
    GO3_STL.PRICE AS GoMalzemeBirimFiyat,
    GO3_STL.LINENET AS GoMalzemeToplam,
	'3-Go"da bulunan ancak Tiger"da bulunmayan irsaliyeler' as Aciklama
	 
FROM GO3DB..LG_425_01_INVOICE GO3_INV WITH(NOLOCK)
LEFT JOIN GO3DB..LG_425_01_STLINE GO3_STL WITH(NOLOCK) ON GO3_STL.INVOICEREF = GO3_INV.LOGICALREF
LEFT JOIN GO3DB..LG_425_CLCARD GO3_CLC WITH(NOLOCK) ON GO3_INV.CLIENTREF = GO3_CLC.LOGICALREF
LEFT JOIN GO3DB..LG_425_ITEMS GO3_ITM WITH(NOLOCK) ON GO3_ITM.LOGICALREF = GO3_STL.STOCKREF
LEFT JOIN GO3DB..LG_425_SRVCARD GO3_SRV WITH(NOLOCK) ON GO3_SRV.LOGICALREF = GO3_STL.STOCKREF

-- Tiger tarafýnda eþleþme bulunamayanlar
LEFT JOIN CEZVE..LG_325_01_INVOICE TGR_INV WITH(NOLOCK) ON (TGR_INV.DOCODE = GO3_INV.FICHENO OR TGR_INV.FICHENO = GO3_INV.FICHENO)
LEFT JOIN CEZVE..LG_325_CLCARD TGR_CLC WITH(NOLOCK) ON TGR_INV.CLIENTREF = TGR_CLC.LOGICALREF --TGR_CLC.CODE = GO3_CLC.CODE
LEFT JOIN CEZVE..LG_325_01_STLINE TGR_STL WITH(NOLOCK) 
    ON TGR_STL.INVOICEREF = TGR_INV.LOGICALREF 
    --AND TGR_STL.AMOUNT = GO3_STL.AMOUNT 
    --AND TGR_STL.PRICE BETWEEN GO3_STL.PRICE - 1 AND GO3_STL.PRICE + 1
LEFT JOIN CEZVE..LG_325_SRVCARD TGR_SRV WITH(NOLOCK) ON TGR_SRV.LOGICALREF = TGR_STL.STOCKREF
LEFT JOIN CEZVE..LG_325_ITEMS TGR_ITM WITH(NOLOCK) ON TGR_ITM.LOGICALREF = TGR_STL.STOCKREF
WHERE   (TGR_INV.TRCODE=1 or TGR_INV.TRCODE=4) and   (GO3_INV.TRCODE=1 or GO3_INV.TRCODE=4) AND GO3_STL.STOCKREF<>0
--AND TGR_STL.LOGICALREF IS NULL 
  AND GO3_INV.FICHENO =  'KAB2025000000010'
 
 
 /*

 select * from GO3DB..LG_425_01_INVOICE GO3_INV WITH(NOLOCK) WHERE FICHENO =  'YKA2025000012451'

  select * from GO3DB..LG_425_01_STLINE GO3_INV WITH(NOLOCK) WHERE INVOICEREF = 211

  */