select TGR_CLC.CODE AS TigerCariKodu,TGR_CLC.DEFINITION_ AS TigerCariAdi,
TGR_INV.FICHENO As TigerFaturaNo,
TGR_INV.DOCODE as TigerFaturaNo2,
TGR_ITM.code as TigerMalzemeKodu,
TGR_ITM.NAME as TigerMalzemeAdi,
TGR_STL.AMOUNT as TigerMalzemeAdet,
TGR_STL.PRICE as TigerMalzemeBirimFiyat,
TGR_STL.LINENET as TigerMalzemeToplam,
cASE WHEN GO3_INV.TRCODE =1 THEN 'Satýnalma Faturasý' else 'Satýþ Ýade Faturasý' end as GoFaturaTuru, 
GO3_CLC.CODE AS GoCariKodu,
GO3_CLC.DEFINITION_ AS GoCariAdi, 
GO3_INV.FICHENO GoFaturaNo,
GO3_INV.DATE_ GoFaturaTarih,
GO3_ITM.code as GoMalzemeKodu,
GO3_ITM.NAME as GoMalzemeAdi,
GO3_STL.AMOUNT as GoMalzemeAdet,
GO3_STL.PRICE as GoMalzemeBirimFiyat,
GO3_STL.LINENET as GoMalzemeToplam
from GO3DB..LG_425_01_INVOICE GO3_INV
LEFT JOIN CEZVE..LG_325_01_INVOICE TGR_INV ON TGR_INV.DOCODE = GO3_INV.FICHENO

LEFT JOIN GO3DB..LG_425_CLCARD GO3_CLC ON GO3_INV.CLIENTREF = GO3_CLC.LOGICALREF

LEFT JOIN CEZVE..LG_325_CLCARD TGR_CLC ON TGR_CLC.CODE = GO3_CLC.CODE

LEFT JOIN GO3DB..LG_425_01_STLINE GO3_STL ON GO3_STL.INVOICEREF = GO3_INV.LOGICALREF
LEFT JOIN GO3DB..LG_425_ITEMS GO3_ITM ON GO3_ITM.LOGICALREF = GO3_STL.STOCKREF  

LEFT JOIN CEZVE..LG_325_01_STLINE TGR_STL ON TGR_STL.INVOICEREF = TGR_INV.LOGICALREF AND   TGR_STL.AMOUNT =  GO3_STL.AMOUNT


LEFT JOIN CEZVE..LG_325_ITEMS TGR_ITM ON TGR_ITM.LOGICALREF = TGR_STL.STOCKREF AND GO3_ITM.CODE =TGR_ITM.CODE

WHERE GO3_INV.TRCODE  IN  (1,4)
AND GO3_STL.LINENET <> TGR_STL.LINENET

--SELECT * FROM CEZVE..LG_325_ITEMS  WHERE CODE = '150-MAB-0051'


-- SELECT * FROM 