USE [ÝREN_PVC_2024T]
GO
DECLARE @FATURACARI VARCHAR(20) = '120.00.00.0344'
DECLARE @CARIREF INT 
DECLARE @CRK VARCHAR(200) = ''
DECLARE @STA VARCHAR(200) = ''

SELECT @CARIREF=REF,@CRK=CRK,@STA=STA  FROM [ÝREN_PVC_FATURA_2024T]..CARIGEN where CRK = @FATURACARI

SELECT ISLEM.[REF]
      ,@CARIREF AS [CARIREF]
      ,FATURABANKA.BANKAREFNO AS [BANKAREF]
      ,[KASAREF]
      ,[TARIH]
      ,[SAAT]
      ,[BORA]
      ,34 AS [ISLEMTURU]
      ,'Tahsilat Fiþi' [ISLEMAC]
      ,ISLEM.[SUBE]
      ,ISLEM.[ISLEMTIPI]
      ,[EVRAKNO]
      ,[ACIKLAMA]
      ,[TUTARB]
      ,[TUTARA]
      ,[TUTARDB]
      ,[TUTARDA]
      ,[GK]
      ,[UGDK]
      ,ISLEM.[DOVIZC]
      ,[EYNM]
      ,[EYNMK]
      ,[CMIORBMI]
      ,[KARTMUHKODU]
      ,[ISLEMMUHKODU]
      ,[GMUHENT]
      ,[FLOAT1]
      ,[FLOAT2]
      ,[MASRAFMERKEZI]
      ,[KAMPKODU]
      ,[CARISUBE]
      ,[CARIREF2]
      ,[BANKAREF2]
      ,[KASAREF2]
      ,[CARISUBE2]
      ,[MASRAFMERKEZI2]
      ,[TAHSILATIYAPAN]
      ,[MASRAFMUHKODU]
      ,[SUBE2]
      ,[OZELKOD1]
      ,[OZELKOD2]
      ,[MODUL]
      ,[FLOAT3]
      ,[FLOAT4]
      ,[FLOAT5]
      ,[FLOAT6]
      ,[FLOAT7]
      ,[FLOAT8]
      ,[F9]
      ,[F10]
      ,[F11]
      ,[F12]
      ,[MASRAFTL]
      ,[MASRAFDVZ]
      ,[VADETARIHI]
      ,[VADEGUNU]
      ,ISLEM.[KULLANICI]
      ,@CRK AS  [CRK]
      ,@STA AS  [STA]
      ,ISLEM.[BANKAKODU]
      ,ISLEM.[BANKAADI]
      ,ISLEM.[SUBESI]
      ,[BHESAPNO]
      ,[KASAKODU]
      ,[KASAADI]
      ,[CRK2]
      ,[STA2]
      ,[BANKAKODU2]
      ,[BANKAADI2]
      ,[KASAKODU2]
      ,[KASAADI2]
      ,[SUBESI2]
      ,[BHESAPNO2]
      ,[KARTMUHKODU2]
      ,[BHESAPADI]
      ,[BHESAPADI2]
      ,[CARIDOVIZC]
      ,[BANKADOVIZC]
      ,[KASADOVIZC]
      ,[CARIDOVIZC2]
      ,[BANKADOVIZC2]
      ,[KASADOVIZC2]
      ,[BANKAGMHK]
      ,[BANKAGMHK2]
      ,[KASAGMHK]
      ,[KASAGMHK2]
      ,[TUTARDB2]
      ,[TUTARDA2]
      ,[GK2]
      ,[UGDK2]
      ,[CEKBORDRONO]
      ,[BAKIYE]
      ,[NAKITTL]
      ,[NAKITD]
      ,[CEKTL]
      ,[CEKD]
      ,[DEKONTVAR]
      ,[CARIKULLAN]
      ,[GGREF]
      ,[GGKODU]
      ,[GGADI]
      ,[GGMUHKODU]
      ,[GGYUZDE]
      ,[GIDERTL]
      ,[GIDERD]
      ,[GELIRTL]
      ,[GELIRD]
      ,[GGDAHILHARIC]
      ,[NETBRUT]
      ,[KDVORANI]
      ,[STOPAJ]
      ,[FON]
      ,[KDVTUTARTL]
      ,[KDVTUTARD]
      ,[STOPAJTL]
      ,[STOPAJD]
      ,[FONTL]
      ,[FOND]
      ,[NETTL]
      ,[NETD]
      ,[KDVHESPKODU]
      ,[STOPAJHESAPKODU]
      ,[FONHESAPKODU]
      ,[BSUBESI]
      ,[BSUBESI2]
      ,ISLEM.[INT_1]
      ,[GKONTROL]
      ,[GIDERADI2]
      ,[GIDERADI3]
      ,[GIDERADI4]
      ,[GIDERKODU2]
      ,[GIDERKODU3]
      ,[GIDERKODU4]
      ,[GIDERMKOD2]
      ,[GIDERMKOD3]
      ,[GIDERMKOD4]
      ,[GIDERREF2]
      ,[GIDERREF3]
      ,[GIDERREF4]
      ,[EKKAYIT]
      ,[GELIRREF]
      ,[GELIRKODU]
      ,[GELIRADI]
      ,[GELIRMUHKODU]
      ,[CEKUGDK]
      ,[CSSATIRREF]
      ,ISLEM.[P_ID]
      ,[SATICI]
      ,[TAHSILADET]
      ,ISLEM.[AKTARIM]
      ,[KASAKODUKULLAN]
      ,[SILINDI]
      ,[BRUTTL]
      ,[EVRAKP_ID]
      ,[CARIDVZCINSI]
      ,[CARIDVZTUTAR]
      ,[CARIDVZUGDK]
      ,[CARIDVZCINS2]
      ,[CARIDVZTUTAR2]
      ,[CARIDVZUGDK2]
      ,[CARIDVZTUTARG]
      ,[ISEMRIREF]
      ,[ISEMRIP_ID]
      ,[ISEMRINO]
      ,[KURFARKI]
      ,[KURFARKIAORS]
      ,[KURFARKIGGREF]
      ,[KURFARKIGGKODU]
      ,[KAYITPID]
      ,[ODEMETAHSILKULLAN]
      ,[CARIP_ID]
      ,[KASAP_ID]
      ,[BANKAP_ID]
      ,[CARI2P_ID]
      ,[KASA2P_ID]
      ,[BANKA2P_ID]
      ,[GIDERP_ID]
      ,[GELIRP_ID]
      ,[GIDERP_ID2]
      ,[GIDERP_ID3]
      ,[GIDERP_ID4]
      ,[CEKP_ID]
      ,[DZP_ID]
      ,[SEC]
      ,[IHRDOSYANO]
      ,[ITHDOSYANO]
      ,[ONCELIK]
      ,[GUMRUKCUP_ID]
      ,[GUMRUKCU]
      ,[CSUBEP_ID]
      ,[CSUBEKODU]
      ,[DEVIR]
      ,[YERELEVNO]
      ,ISLEM.[UPDATEDATE]
      ,ISLEM.[RowVersiyon]
      ,ISLEM.[BIVERSIYON]
	  ,PVCBANKA.BANKAADI
	  ,FATURABANKA.BANKAADI
  FROM [ÝREN_PVC_2024T].[dbo].[CBKISLEM] ISLEM
  LEFT JOIN [ÝREN_PVC_2024T].[dbo].BANKGEN PVCBANKA ON PVCBANKA.BANKAREFNO = ISLEM.BANKAREF
  LEFT JOIN [ÝREN_PVC_FATURA_2024T].[dbo].BANKGEN FATURABANKA ON PVCBANKA.BANKAADI = FATURABANKA.BANKAADI
 where ISLEM.REF =  9903

 --SELECT * FROM [ÝREN_PVC_FATURA_2024T].DBO.BANKGEN
 -- SELECT * FROM [ÝREN_PVC_2024T].[dbo].[CBKISLEM] ISLEM  WHERE REF= 9903

---- SELECT * FROM [ÝREN_PVC_2024T].[dbo].BANKGEN
--UPDATE [ÝREN_PVC_FATURA_2024T].[dbo].BANKGEN SET BANKAADI = 'KUVEYTTÜRK KAT. BANK.A.Þ.',HESAPNO = '94514251-1',IBAN='TR240020500009451425100001' WHERE BANKAREFNO = 4

--SELECT * FROM [ÝREN_PVC_2024T].[dbo].[CBKISLEM] WHERE ISLEMTURU = 34