USE [FercamB2B_Default_v1]
GO

/****** Object:  View [dbo].[VW_UretimEmirleriListesi]    Script Date: 04.03.2025 12:37:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








 

ALTER VIEW [dbo].[VW_UretimEmirleriListesi] as 

select 
PROD.LOGICALREF,
FICHENO,
DATE_,
ITM.CODE AS ITEMCODE,
ITM.NAME AS ITEMNAME,
PROD.STATUS,
CASE WHEN PROD.STATUS = 0 THEN 'BAÞLAMADI'
     WHEN PROD.STATUS = 1 THEN 'DEVAM EDÝYOR'
     WHEN PROD.STATUS = 3 THEN 'TAMAMLANDI' END STATUSEXPLAIN,
	 FICHENO + '-' + ITM.CODE AS FICHEITEMCODE
	 ,ITM.LOGICALREF as ITEMLOGICALREF ,
2024 as YEAR	 
	 from TIGER..LG_024_PRODORD PROD WITH(NOLOCK)
LEFT JOIN TIGER..LG_024_ITEMS ITM WITH(NOLOCK) ON PROD.ITEMREF = ITM.LOGICALREF
where FICHENO NOT IN ( SELECT FICHENO from TIGER..LG_025_PRODORD PROD WITH(NOLOCK))
 
UNION ALL

select 
PROD.LOGICALREF,
FICHENO,
DATE_,
ITM.CODE AS ITEMCODE,
ITM.NAME AS ITEMNAME,
PROD.STATUS,
CASE WHEN PROD.STATUS = 0 THEN 'BAÞLAMADI'
     WHEN PROD.STATUS = 1 THEN 'DEVAM EDÝYOR'
     WHEN PROD.STATUS = 3 THEN 'TAMAMLANDI' END STATUSEXPLAIN,
	 FICHENO + '-' + ITM.CODE AS FICHEITEMCODE
	 ,ITM.LOGICALREF as ITEMLOGICALREF ,
2025 as YEAR	 
	 from TIGER..LG_025_PRODORD PROD WITH(NOLOCK)
LEFT JOIN TIGER..LG_025_ITEMS ITM WITH(NOLOCK) ON PROD.ITEMREF = ITM.LOGICALREF
--where FICHENO NOT IN ( SELECT FICHENO from TIGER..LG_024_PRODORD PROD WITH(NOLOCK))
 


GO


