select DISTINCT
PROD.LOGICALREF,
FICHENO,
DATE_,
ITEMS.CODE AS ITEMCODE,
ITEMS.NAME AS ITEMNAME,
PROD.STATUS,
CASE WHEN PROD.STATUS = 0 THEN 'BAÞLAMADI'
     WHEN PROD.STATUS = 1 THEN 'DEVAM EDÝYOR'
     WHEN PROD.STATUS = 3 THEN 'TAMAMLANDI' END STATUSEXPLAIN,
     FICHENO + '-' + ITEMS.CODE AS FICHEITEMCODE ,
	 RECETEITEM.CODE 
	 ,RECETEITEM.NAME from 
 TIGER.dbo.LG_024_DISPLINE DISPLINE  INNER JOIN TIGER.dbo.LG_024_PRODORD PROD     ON DISPLINE.PRODORDREF = PROD.LOGICALREF 
  INNER JOIN TIGER.dbo.LG_024_POLINE POLINE ON POLINE.DISPLINEREF = DISPLINE.LOGICALREF  
  INNER JOIN TIGER.dbo.LG_024_ITEMS ITEMS         ON PROD.ITEMREF        = ITEMS.LOGICALREF  INNER JOIN TIGER.dbo.LG_024_PEGGING PEGGING    

   ON PEGGING.PEGREF  = PROD.LOGICALREF 
     INNER JOIN TIGER.dbo.LG_024_ITEMS RECETEITEM         ON  POLINE.ITEMREF       = RECETEITEM.LOGICALREF 
   where   --PROD.STATUS IN (0,1) AND  
   SUBSTRING(RECETEITEM.CODE,11,3) = '001'   
 AND SUBSTRING(RECETEITEM.CODE,8,2)= '05'

 SELECT * FROM LG_024_VARIANT WHERE 