
declare @plakaRengi varchar(5) = '006'
declare @plakaKalinligi varchar(5) = '04'

select DISTINCT
PROD.LOGICALREF,
FICHENO,
DATE_,
ITEMS.CODE AS ITEMCODE,
ITEMS.NAME AS ITEMNAME,
PROD.STATUS,
CASE WHEN PROD.STATUS = 0 THEN 'BAÞLAMADI'
     WHEN PROD.STATUS = 1 THEN 'DEVAM EDÝYOR'
     WHEN PROD.STATUS = 3 THEN 'TAMAMLANDI' END STATUSEXPLAIN,
     FICHENO + '-' + ITEMS.CODE AS FICHEITEMCODE,
	 
	 RECETEITEM.CODE
	 from 
 TIGER.dbo.LG_025_DISPLINE DISPLINE  
 INNER JOIN TIGER.dbo.LG_025_PRODORD PROD     ON DISPLINE.PRODORDREF = PROD.LOGICALREF 
  INNER JOIN TIGER.dbo.LG_025_POLINE POLINE ON POLINE.DISPLINEREF = DISPLINE.LOGICALREF  
  INNER JOIN TIGER.dbo.LG_025_ITEMS ITEMS         ON PROD.ITEMREF        = ITEMS.LOGICALREF  
  INNER JOIN TIGER.dbo.LG_025_PEGGING PEGGING    

   ON PEGGING.PEGREF  = PROD.LOGICALREF 
     INNER JOIN TIGER.dbo.LG_025_ITEMS RECETEITEM         ON  POLINE.ITEMREF       = RECETEITEM.LOGICALREF 
   where   --PROD.STATUS IN (0,1) AND  
     PROD.FICHENO = '2412.0160'
   SUBSTRING(RECETEITEM.CODE,11,3) = @plakaRengi   
 AND SUBSTRING(RECETEITEM.CODE,8,2)= @plakaKalinligi

select * from TIGER.dbo.LG_025_PRODORD where FICHENO =  '2412.0160'
select * from TIGER.dbo.LG_024_PRODORD where FICHENO =  '2412.0160'
select * from TIGER.dbo.LG_025_DISPLINE where PRODORDREF= 689
select * from TIGER.dbo.LG_025_POLINE where DISPLINEREF= 4402
select * from TIGER.dbo.LG_024_PEGGING where  PEGREF= 6070
select * from TIGER.dbo.LG_025_PEGGING where  PEGREF= 689

UPDATE   TIGER.dbo.LG_025_PEGGING SET PORDFICHEREF=206, PORDLINEREF=776  where  PEGREF= 689

SELECT * FROM LG_025_01_ORFLINE WHERE STOCKREF = 143439

--select * from TIGER.dbo.LG_024_ITEMS where  LOGICALREF= 143439
--select * from TIGER.dbo.LG_025_ITEMS where  LOGICALREF= 143439



select * from TIGER.dbo.LG_025_PEGGING where  ITEMREF = 143439


select * from TIGER.dbo.LG_024_PEGGING