select LEN(SHPAGNCOD),SHPAGNCOD, * from LG_076_21_INVOICE  WHERE LEN(SHPAGNCOD) > 5    


select LEN(SHPAGNCOD),SHPAGNCOD, * from LG_076_21_STFICHE  WHERE LEN(SHPAGNCOD) > 5    


--UPDATE LG_076_21_INVOICE SET SHPAGNCOD= '0'  WHERE LEN(SHPAGNCOD) > 5    

--UPDATE LG_076_21_STFICHE SET SHPAGNCOD= '91981'  WHERE LEN(SHPAGNCOD) > 5 