SELECT  TOP 50 SITEID, ORGLOGICALREF,ACCTYPE,* FROM LG_063_EMUHACC WHERE CODE LIKE '10%'
UNION ALL

SELECT TOP 50 SITEID,ORGLOGICALREF,ACCTYPE,* FROM LG_054_EMUHACC WHERE CODE LIKE '10%'


UPDATE LG_063_EMUHACC SET SUBACCOUNTS = 1 WHERE   CODE LIKE '108%'

SELECT * FROM LG_063_21_EMFLINE WHERE ACCOUNTCODE LIKE '111%'


UPDATE LG_060_EMUHACC SET SUBACCOUNTS = 1 WHERE   SUBACCOUNTS = 0 AND LEVEL_ = 0

SELECT * FROM LG_064_EMUHACC   WHERE   SUBACCOUNTS = 0 AND LEVEL_ = 0