USE [PRODEYS]
GO

DECLARE @ORDERFICHEREF int
DECLARE @CNTFICHEREF int
DECLARE @CLIENTREF int
DECLARE @SHIPINFOREF int
DECLARE @QUEUENR smallint
DECLARE @TRCODE smallint
DECLARE @IOCODE smallint
DECLARE @BRANCH smallint
DECLARE @SOURCEINDEX smallint
DECLARE @DESTBRANCH smallint
DECLARE @DESTINDEX smallint
DECLARE @LGFICHEREF int
DECLARE @ISTRANSFERED bit
DECLARE @ISORDERCLIENT bit

INSERT INTO [dbo].[STFICHE]
([ORDERFICHEREF],[CNTFICHEREF],[CLIENTREF],[SHIPINFOREF],[QUEUENR],[TRCODE],[IOCODE],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX],[LGFICHEREF],[ISTRANSFERED],[ISORDERCLIENT])
VALUES
(@ORDERFICHEREF,@CNTFICHEREF,@CLIENTREF,@SHIPINFOREF,@QUEUENR,@TRCODE,@IOCODE,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@LGFICHEREF,@ISTRANSFERED,@ISORDERCLIENT)
GO


