USE [PRODEYS]
GO
DECLARE @ORDERFICHEREF int 
DECLARE @STFICHEREF  int
DECLARE @CLIENTREF int
DECLARE @ITEMREF int
DECLARE @VARIANTREF int
DECLARE @AMOUNT float
DECLARE @USREF int
DECLARE @UOMREF int
DECLARE @CONVFACT1 float
DECLARE @CONVFACT2 float
DECLARE @TRCODE smallint
DECLARE @IOCODE smallint
DECLARE @BRANCH smallint
DECLARE @SOURCEINDEX smallint
DECLARE @DESTBRANCH smallint
DECLARE @DESTINDEX smallint
DECLARE @LGORFLINEREF int
DECLARE @LGSHIPINFOREF int
DECLARE @LGORFICHEREF int
DECLARE @LGDEMANDLINEREF int
DECLARE @LGDEMANDFICHEREF int
DECLARE @PROCESSDATE datetime
DECLARE @LGSETREF int
DECLARE @LGOFFERREF int
DECLARE @LGOFFTRANSREF int
DECLARE @TUOMREF int
DECLARE @LGSTFICHEREF int
DECLARE @LGSTLINEREF int


INSERT INTO [dbo].[ORDERLINE]
 ([ORDERFICHEREF],[STFICHEREF],[CLIENTREF],[ITEMREF],[VARIANTREF],[AMOUNT],[USREF],[UOMREF],[CONVFACT1],[CONVFACT2],[TRCODE],[IOCODE],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX]
,[LGORFLINEREF],[LGSHIPINFOREF],[LGORFICHEREF],[LGDEMANDLINEREF],[LGDEMANDFICHEREF],[PROCESSDATE],[LGSETREF],[LGOFFERREF],[LGOFFTRANSREF],[TUOMREF],[LGSTFICHEREF],[LGSTLINEREF])
     VALUES
(@ORDERFICHEREF,@STFICHEREF,@CLIENTREF,@ITEMREF,@VARIANTREF,@AMOUNT,@USREF,@UOMREF,@CONVFACT1,@CONVFACT2,@TRCODE,@IOCODE,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@LGORFLINEREF
,@LGSHIPINFOREF,@LGORFICHEREF,@LGDEMANDLINEREF,@LGDEMANDFICHEREF,@PROCESSDATE,@LGSETREF,@LGOFFERREF,@LGOFFTRANSREF,@TUOMREF,@LGSTFICHEREF,@LGSTLINEREF)
GO


