--EXEC sp_configure 'clr enabled', 1;  RECONFIGURE WITH OVERRIDE;

DECLARE @Yil int = 2021
DECLARE @Hafta int = 50
DECLARE @BoxNo int = 1

DECLARE @AUTOTRANSFERPARAMETERREF INT=33
DECLARE @MODULEREF INT=116
DECLARE @LASTFICHENO INT

DECLARE @ITEMREF INT
DECLARE @USREF INT
DECLARE @UOMREF INT
DECLARE @CONVFACT1 INT
DECLARE @CONVFACT2 INT
DECLARE @KOLI_ETIKETI INT
DECLARE @BARKODNUMERIC  INT

DECLARE @ORDERFICHEREF INT
DECLARE @ORDERLINEREF INT
DECLARE @STFICHEREF INT
DECLARE @STLINEREF INT
--1-ORDERFICHE DEÐÝÞKENLER
DECLARE @FICHENO nvarchar(20) 
DECLARE @DATE_ datetime 
DECLARE @DISPATCHNO nvarchar(20) = NULL
DECLARE @TRCODE smallint 
DECLARE @IOCODE smallint 
DECLARE @STATUS smallint 
DECLARE @BRANCH smallint = 0
DECLARE @SOURCEINDEX smallint = 0
DECLARE @DESTBRANCH smallint = NULL
DECLARE @DESTINDEX smallint = NULL
DECLARE @CLIENTREF int = NULL
DECLARE @SHIPINFOREF int = NULL
DECLARE @TRANSREF int = NULL
DECLARE @NOTES nvarchar(500) = NULL
DECLARE @LGSETREF int =1
DECLARE @AUTOTRANSFER bit 
DECLARE @SHIPTYPE int = NULL
DECLARE @COMPLETEDDATE datetime = NULL
DECLARE @ISSYSTEM bit = NULL
DECLARE @LGORFICHEREF int = NULL
DECLARE @ISCSNOENTRY bit = NULL
DECLARE @LGOFFERREF int = NULL
DECLARE @ORDERCONTROL bit = 0
DECLARE @PACKING bit = 0
DECLARE @TRANSFERTYPE int = NULL
DECLARE @EAN1 bit = 0
DECLARE @COMPLETEEXACTLY smallint = 1
DECLARE @AMOUNTSURPASS bit = 0
DECLARE @PARENTREF int = NULL
DECLARE @LGINVOICEREF int  = NULL
--2-STFICHE DEÐÝÞKENLER

DECLARE @CNTFICHEREF int = NULL
DECLARE @QUEUENR smallint = NULL
DECLARE @LGFICHEREF int = NULL
DECLARE @ISTRANSFERED bit  =0
DECLARE @ISORDERCLIENT bit  = NULL
--3-ORDERLINE DEÐÝÞKENLER
 
DECLARE @VARIANTREF int  =0
DECLARE @AMOUNT float
DECLARE @LGORFLINEREF int = NULL
DECLARE @LGSHIPINFOREF int = NULL
DECLARE @LGDEMANDLINEREF int = NULL
DECLARE @LGDEMANDFICHEREF int = NULL
DECLARE @PROCESSDATE datetime = NULL
DECLARE @LGOFFTRANSREF int = NULL
DECLARE @TUOMREF int = NULL
DECLARE @LGSTFICHEREF int = NULL
DECLARE @LGSTLINEREF int = NULL
--4- STLINE DEÐÝÞKENLER
 
DECLARE @BARCODEREF int
 
DECLARE @CNTDETAILREF int
DECLARE @QPRODREF int
DECLARE @QPRODLINEREF int
DECLARE @USERREF int
DECLARE @TERMINALREF int
 
DECLARE @PPRODORDREF int
DECLARE @PPRODORDFICHEREF int
DECLARE @PPRODLINEREF int
DECLARE @SPECODE nvarchar(50)
 
DECLARE @MAINORDERLINEREF int
DECLARE @STCOMPLNREF int
DECLARE @CHECKED bit
DECLARE @CHECKEDBYTERMINALREF int
DECLARE @CHECKEDDATE datetime
DECLARE @POLINEREF int

--ORDERFICHE TRCODE=13
DECLARE ORFICHE_CURCOR CURSOR FOR
select DISTINCT 
 

 UB.ITEMREF,USL.UNITSETREF [USREF],UB.UNITLINEREF [UOMREF],ITMA.CONVFACT1,ITMA.CONVFACT2,SUM(KOLI_ETIKETI )  AS KOLI_ETIKETI ,VW_PT_BOX.BARKODNUMERIC  from 
                    ( SELECT * FROM GO3DB..PT_PAKETLEME_LOG  Q1 WITH( NOLOCK) WHERE Q1.ID IN (SELECT TOP 1 ID FROM GO3DB..PT_PAKETLEME_LOG  Q2  WITH( NOLOCK) 
                     WHERE  Q1.FISNO = Q2.FISNO AND Q1.BOX = Q2.BOX AND   DATEPART(WW,Q2.TARIH) = @Hafta AND  DATEPART(YYYY,Q2.TARIH) = @Yil AND Q2.ISLEM = 'KOLI ETIKETI BASILDI'  ORDER BY Q2.ID DESC)  AND 
                     DATEPART(WW,Q1.TARIH) = @Hafta AND  DATEPART(YYYY,Q1.TARIH) = @Yil AND Q1.ISLEM = 'KOLI ETIKETI BASILDI')    TBL_LOG
                    LEFT JOIN GO3DB..[PT_HAZIRLIK_SATIR] ON [PT_HAZIRLIK_SATIR].FISNO = TBL_LOG.FISNO --AND DATEPART(WW,PT_PAKETLEME_LOG.TARIH) =  DATEPART(WW,[PT_HAZIRLIK_SATIR].FIS_TARIHI)
                  
		LEFT JOIN GO3DB..LG_221_ITEMS ITM  ON 	ITM.CODE = 	  STOKKODU
LEFT JOIN GO3DB..LG_221_UNITBARCODE UB ON ITM.LOGICALREF=UB.ITEMREF
LEFT JOIN GO3DB..LG_221_ITMUNITA ITMA ON UB.ITMUNITAREF=ITMA.LOGICALREF
LEFT JOIN GO3DB..LG_221_UNITSETL USL ON UB.UNITLINEREF=USL.LOGICALREF
LEFT JOIN GO3DB..VW_PT_BOX ON VW_PT_BOX.YIL = @Yil AND VW_PT_BOX.HAFTA = @Hafta and  VW_PT_BOX.BOX=@BoxNo				  
				  WHERE TBL_LOG.BOX = @BoxNo  AND ( URUN_TIPI = 'ANA ÜRÜN')
                    AND DATEPART(WW,TBL_LOG.TARIH) = @Hafta   
                     AND DATEPART(YYYY,TBL_LOG.TARIH) = @Yil   
                    and ISLEM = 'KOLI ETIKETI BASILDI'
					GROUP BY UB.ITEMREF,USL.UNITSETREF ,UB.UNITLINEREF  ,ITMA.CONVFACT1,ITMA.CONVFACT2,
  VW_PT_BOX.BOX,DPKODU ,VW_PT_BOX.BARKODNUMERIC

OPEN ORFICHE_CURCOR
--USREF],UB.UNITLINEREF [UOMREF],ITMA.CONVFACT1,ITMA.CONVFACT2,SUM(KOLI_ETIKETI )  AS KOLI_ETIKETI ,VW_PT_BOX.BARKODNUMERIC
FETCH NEXT FROM ORFICHE_CURCOR INTO  @ITEMREF,@USREF ,@UOMREF,@CONVFACT1,@CONVFACT2,@KOLI_ETIKETI,@BARKODNUMERIC
WHILE @@FETCH_STATUS =0
BEGIN

--SELECT * FROM ORDER_PARAMETER
SELECT @AUTOTRANSFER=ISNULL(CONVERT(BIT,VALUE),0) FROM ORDER_PARAMETER WHERE PARAMETERREF = @AUTOTRANSFERPARAMETERREF

--CREATE FICHENO
EXEC PRO_FICHENO_CREATE @MODULEREF,@LASTFICHENO OUTPUT
SET @FICHENO = SUBSTRING ('000000',0,7-LEN(@LASTFICHENO)) + CONVERT(VARCHAR,@LASTFICHENO)

SET @DATE_ = GETDATE()
SET @TRCODE = 13
SET @IOCODE = 1
SET @STATUS = 2
-- 1- TRCODE=13 VE ORDERFICHE INSERT
SET @ORDERFICHEREF = 0
SELECT @ORDERFICHEREF=LOGICALREF FROM ORDERFICHE WHERE SHIPINFOREF=@BARKODNUMERIC  AND DISPATCHNO=@ITEMREF AND TRCODE=13
IF @ORDERFICHEREF=0 
BEGIN
    SET @SHIPINFOREF =@BARKODNUMERIC 
	SET @DISPATCHNO =  @ITEMREF
    INSERT INTO [dbo].[ORDERFICHE]
	([FICHENO],[DATE_],[DISPATCHNO],[TRCODE],[IOCODE],[STATUS],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX],[CLIENTREF],[SHIPINFOREF],[TRANSREF],[NOTES],[LGSETREF],[AUTOTRANSFER]
	,[SHIPTYPE],[COMPLETEDDATE],[ISSYSTEM],[LGORFICHEREF],[ISCSNOENTRY],[LGOFFERREF],[ORDERCONTROL],[PACKING],[TRANSFERTYPE],[EAN1],[COMPLETEEXACTLY],[AMOUNTSURPASS],[PARENTREF],[LGINVOICEREF])
		 VALUES
	(@LASTFICHENO,@DATE_,@DISPATCHNO,@TRCODE,@IOCODE,@STATUS,@BRANCH,@SOURCEINDEX ,@DESTBRANCH,@DESTINDEX,@CLIENTREF,@SHIPINFOREF,@TRANSREF,@NOTES ,@LGSETREF,@AUTOTRANSFER ,@SHIPTYPE,@COMPLETEDDATE 
	,@ISSYSTEM ,@LGORFICHEREF,@ISCSNOENTRY ,@LGOFFERREF,@ORDERCONTROL,@PACKING,@TRANSFERTYPE,@EAN1,@COMPLETEEXACTLY,@AMOUNTSURPASS,@PARENTREF,@LGINVOICEREF) 
	SELECT @ORDERFICHEREF=@@IDENTITY
END
-- 2- TRCODE=13 VE STFICHE INSERT
SET @STFICHEREF = 0    --SHIPINFOREF=BARKOD, , QUEUENR=ITEM
SELECT @STFICHEREF=LOGICALREF FROM STFICHE WHERE SHIPINFOREF=@BARKODNUMERIC AND QUEUENR=@ITEMREF AND TRCODE=13
IF @STFICHEREF=0 
BEGIN
    SET @SHIPINFOREF = @BARKODNUMERIC
	SET @CLIENTREF = NULL
	SET @QUEUENR=@ITEMREF
	SET @TRCODE=13
	SET @IOCODE=1
	SET @BRANCH=0
	SET @SOURCEINDEX=0
	SET @ISTRANSFERED=0
	INSERT INTO [dbo].[STFICHE]
	([ORDERFICHEREF],[CNTFICHEREF],[CLIENTREF],[SHIPINFOREF],[QUEUENR],[TRCODE],[IOCODE],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX],[LGFICHEREF],[ISTRANSFERED],[ISORDERCLIENT])
	VALUES
	(@ORDERFICHEREF,@CNTFICHEREF,@CLIENTREF,@SHIPINFOREF,@QUEUENR,@TRCODE,@IOCODE,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@LGFICHEREF,@ISTRANSFERED,@ISORDERCLIENT)
 
	SELECT @STFICHEREF=@@IDENTITY
END

-- 3- TRCODE=13 VE ORDERLINE INSERT
SET @ORDERLINEREF = 0
SELECT @ORDERLINEREF=LOGICALREF FROM ORDERLINE WHERE LGSHIPINFOREF=@BARKODNUMERIC AND ITEMREF=@ITEMREF AND TRCODE=13
IF @ORDERLINEREF=0 
BEGIN
    SET @LGSHIPINFOREF = @BARKODNUMERIC
	SET @AMOUNT = @KOLI_ETIKETI
	SET @CLIENTREF = NULL
	SET @VARIANTREF = 0
	SET @TRCODE = 13
	SET @IOCODE = 1
	SET @BRANCH = 0
	SET @TUOMREF = @UOMREF
	SET @PROCESSDATE = GETDATE()
   INSERT INTO [dbo].[ORDERLINE]
 ([ORDERFICHEREF],[STFICHEREF],[CLIENTREF],[ITEMREF],[VARIANTREF],[AMOUNT],[USREF],[UOMREF],[CONVFACT1],[CONVFACT2],[TRCODE],[IOCODE],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX]
,[LGORFLINEREF],[LGSHIPINFOREF],[LGORFICHEREF],[LGDEMANDLINEREF],[LGDEMANDFICHEREF],[PROCESSDATE],[LGSETREF],[LGOFFERREF],[LGOFFTRANSREF],[TUOMREF],[LGSTFICHEREF],[LGSTLINEREF])
     VALUES
(@ORDERFICHEREF,@STFICHEREF,@CLIENTREF,@ITEMREF,@VARIANTREF,@AMOUNT,@USREF,@UOMREF,@CONVFACT1,@CONVFACT2,@TRCODE,@IOCODE,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@LGORFLINEREF
,@LGSHIPINFOREF,@LGORFICHEREF,@LGDEMANDLINEREF,@LGDEMANDFICHEREF,@PROCESSDATE,@LGSETREF,@LGOFFERREF,@LGOFFTRANSREF,@TUOMREF,@LGSTFICHEREF,@LGSTLINEREF)
	 SELECT @ORDERLINEREF=@@IDENTITY
END


-- 4- TRCODE=13 VE STLINE INSERT
SET @STLINEREF = 0
SELECT @STLINEREF=LOGICALREF FROM STLINE WHERE SHIPINFOREF=@BARKODNUMERIC AND ITEMREF=@ITEMREF AND TRCODE=13
IF @STLINEREF=0 
BEGIN
    SET @SHIPINFOREF = @BARKODNUMERIC
	SET @AMOUNT = @KOLI_ETIKETI
	SET @CLIENTREF = NULL
	SET @VARIANTREF = 0
	SET @TRCODE = 13
	SET @IOCODE = 1
	SET @BRANCH = 0
	SET @SOURCEINDEX = 0
	SET @PROCESSDATE = GETDATE() 
	SET @TERMINALREF = 1

  INSERT INTO [dbo].[STLINE]
([STFICHEREF],[TRCODE],[IOCODE],[ITEMREF],[VARIANTREF],[BARCODEREF],[AMOUNT],[USREF],[UOMREF],[CONVFACT1],[CONVFACT2],[CLIENTREF],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX],[PROCESSDATE]
,[ORDERFICHEREF],[ORDERLINEREF],[CNTFICHEREF],[CNTDETAILREF],[QPRODREF],[QPRODLINEREF],[USERREF],[TERMINALREF],[SHIPINFOREF],[PPRODORDREF],[PPRODORDFICHEREF],[PPRODLINEREF],[SPECODE]
,[ISCSNOENTRY],[MAINORDERLINEREF],[STCOMPLNREF],[CHECKED],[CHECKEDBYTERMINALREF],[CHECKEDDATE],[POLINEREF])
VALUES
(@STFICHEREF,@TRCODE,@IOCODE,@ITEMREF,@VARIANTREF,@BARCODEREF,@AMOUNT,@USREF,@UOMREF,@CONVFACT1,@CONVFACT2,@CLIENTREF,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@PROCESSDATE ,@ORDERFICHEREF,@ORDERLINEREF
,@CNTFICHEREF,@CNTDETAILREF,@QPRODREF,@QPRODLINEREF,@USERREF,@TERMINALREF,@SHIPINFOREF,@PPRODORDREF,@PPRODORDFICHEREF,@PPRODLINEREF,@SPECODE ,@ISCSNOENTRY ,@MAINORDERLINEREF,@STCOMPLNREF
,@CHECKED ,@CHECKEDBYTERMINALREF,@CHECKEDDATE ,@POLINEREF)	 
END

 --SELECT  @ITEMREF,@USREF ,@UOMREF,@CONVFACT1,@CONVFACT2,@KOLI_ETIKETI,@BARKODNUMERIC
FETCH NEXT FROM ORFICHE_CURCOR 
INTO  @ITEMREF,@USREF ,@UOMREF,@CONVFACT1,@CONVFACT2,@KOLI_ETIKETI,@BARKODNUMERIC
END
CLOSE ORFICHE_CURCOR
DEALLOCATE ORFICHE_CURCOR



/*

2. ANA BÖLÜM
  TRCODE = 12 ÝÇÝN



*/



 
DECLARE ORFICHE_CURCOR CURSOR FOR
select DISTINCT 
 

 UB.ITEMREF,USL.UNITSETREF [USREF],UB.UNITLINEREF [UOMREF],ITMA.CONVFACT1,ITMA.CONVFACT2,SUM(KOLI_ETIKETI )  AS KOLI_ETIKETI ,VW_PT_BOX.BARKODNUMERIC  from 
                    ( SELECT * FROM GO3DB..PT_PAKETLEME_LOG  Q1 WITH( NOLOCK) WHERE Q1.ID IN (SELECT TOP 1 ID FROM GO3DB..PT_PAKETLEME_LOG  Q2  WITH( NOLOCK) 
                     WHERE  Q1.FISNO = Q2.FISNO AND Q1.BOX = Q2.BOX AND   DATEPART(WW,Q2.TARIH) = @Hafta AND  DATEPART(YYYY,Q2.TARIH) = @Yil AND Q2.ISLEM = 'KOLI ETIKETI BASILDI'  ORDER BY Q2.ID DESC)  AND 
                     DATEPART(WW,Q1.TARIH) = @Hafta AND  DATEPART(YYYY,Q1.TARIH) = @Yil AND Q1.ISLEM = 'KOLI ETIKETI BASILDI')    TBL_LOG
                    LEFT JOIN GO3DB..[PT_HAZIRLIK_SATIR] ON [PT_HAZIRLIK_SATIR].FISNO = TBL_LOG.FISNO --AND DATEPART(WW,PT_PAKETLEME_LOG.TARIH) =  DATEPART(WW,[PT_HAZIRLIK_SATIR].FIS_TARIHI)
                  
		LEFT JOIN GO3DB..LG_221_ITEMS ITM  ON 	ITM.CODE = 	  STOKKODU
LEFT JOIN GO3DB..LG_221_UNITBARCODE UB ON ITM.LOGICALREF=UB.ITEMREF
LEFT JOIN GO3DB..LG_221_ITMUNITA ITMA ON UB.ITMUNITAREF=ITMA.LOGICALREF
LEFT JOIN GO3DB..LG_221_UNITSETL USL ON UB.UNITLINEREF=USL.LOGICALREF
LEFT JOIN GO3DB..VW_PT_BOX ON VW_PT_BOX.YIL = @Yil AND VW_PT_BOX.HAFTA = @Hafta and  VW_PT_BOX.BOX=@BoxNo				  
				  WHERE TBL_LOG.BOX = @BoxNo  AND ( URUN_TIPI = 'ALT ÜRÜN')
                    AND DATEPART(WW,TBL_LOG.TARIH) = @Hafta   
                     AND DATEPART(YYYY,TBL_LOG.TARIH) = @Yil   
                    and ISLEM = 'KOLI ETIKETI BASILDI'
					GROUP BY UB.ITEMREF,USL.UNITSETREF ,UB.UNITLINEREF  ,ITMA.CONVFACT1,ITMA.CONVFACT2,
  VW_PT_BOX.BOX,DPKODU ,VW_PT_BOX.BARKODNUMERIC

OPEN ORFICHE_CURCOR
--USREF],UB.UNITLINEREF [UOMREF],ITMA.CONVFACT1,ITMA.CONVFACT2,SUM(KOLI_ETIKETI )  AS KOLI_ETIKETI ,VW_PT_BOX.BARKODNUMERIC
FETCH NEXT FROM ORFICHE_CURCOR INTO  @ITEMREF,@USREF ,@UOMREF,@CONVFACT1,@CONVFACT2,@KOLI_ETIKETI,@BARKODNUMERIC
WHILE @@FETCH_STATUS =0
BEGIN

--SELECT * FROM ORDER_PARAMETER
SELECT @AUTOTRANSFER=ISNULL(CONVERT(BIT,VALUE),0) FROM ORDER_PARAMETER WHERE PARAMETERREF = @AUTOTRANSFERPARAMETERREF

--CREATE FICHENO
EXEC PRO_FICHENO_CREATE @MODULEREF,@LASTFICHENO OUTPUT
SET @FICHENO = SUBSTRING ('000000',0,7-LEN(@LASTFICHENO)) + CONVERT(VARCHAR,@LASTFICHENO)


-- 1- TRCODE=13 VE ORDERFICHE INSERT
SET @ORDERFICHEREF = 0
SELECT @ORDERFICHEREF=LOGICALREF FROM ORDERFICHE WHERE SHIPINFOREF=@BARKODNUMERIC  AND DISPATCHNO=@ITEMREF AND TRCODE=12
IF @ORDERFICHEREF=0 
BEGIN
	SET @DATE_ = GETDATE()
	SET @ORDERCONTROL = 0
	SET @PACKING = 0
	SET @TRCODE = 12
	SET @IOCODE = 4
	SET @STATUS = 0
    SET @SHIPINFOREF =@BARKODNUMERIC 
	SET @DISPATCHNO =  @ITEMREF
    INSERT INTO [dbo].[ORDERFICHE]
	([FICHENO],[DATE_],[DISPATCHNO],[TRCODE],[IOCODE],[STATUS],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX],[CLIENTREF],[SHIPINFOREF],[TRANSREF],[NOTES],[LGSETREF],[AUTOTRANSFER]
	,[SHIPTYPE],[COMPLETEDDATE],[ISSYSTEM],[LGORFICHEREF],[ISCSNOENTRY],[LGOFFERREF],[ORDERCONTROL],[PACKING],[TRANSFERTYPE],[EAN1],[COMPLETEEXACTLY],[AMOUNTSURPASS],[PARENTREF],[LGINVOICEREF])
		 VALUES
	(@LASTFICHENO,@DATE_,@DISPATCHNO,@TRCODE,@IOCODE,@STATUS,@BRANCH,@SOURCEINDEX ,@DESTBRANCH,@DESTINDEX,@CLIENTREF,@SHIPINFOREF,@TRANSREF,@NOTES ,@LGSETREF,@AUTOTRANSFER ,@SHIPTYPE,@COMPLETEDDATE 
	,@ISSYSTEM ,@LGORFICHEREF,@ISCSNOENTRY ,@LGOFFERREF,@ORDERCONTROL,@PACKING,@TRANSFERTYPE,@EAN1,@COMPLETEEXACTLY,@AMOUNTSURPASS,@PARENTREF,@LGINVOICEREF) 
	SELECT @ORDERFICHEREF=@@IDENTITY
END
-- 2- TRCODE=12 VE STFICHE INSERT
SET @STFICHEREF = 0    --SHIPINFOREF=BARKOD, , QUEUENR=ITEM
SELECT @STFICHEREF=LOGICALREF FROM STFICHE WHERE SHIPINFOREF=@BARKODNUMERIC AND QUEUENR=@ITEMREF AND TRCODE=12
IF @STFICHEREF=0 
BEGIN
    SET @SHIPINFOREF = @BARKODNUMERIC
	SET @CLIENTREF = NULL
	SET @QUEUENR=@ITEMREF
	SET @TRCODE=12
	SET @IOCODE=4
	SET @BRANCH=0
	SET @SOURCEINDEX=0
	SET @ISTRANSFERED=0
	INSERT INTO [dbo].[STFICHE]
	([ORDERFICHEREF],[CNTFICHEREF],[CLIENTREF],[SHIPINFOREF],[QUEUENR],[TRCODE],[IOCODE],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX],[LGFICHEREF],[ISTRANSFERED],[ISORDERCLIENT])
	VALUES
	(@ORDERFICHEREF,@CNTFICHEREF,@CLIENTREF,@SHIPINFOREF,@QUEUENR,@TRCODE,@IOCODE,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@LGFICHEREF,@ISTRANSFERED,@ISORDERCLIENT)
 
	SELECT @STFICHEREF=@@IDENTITY
END

-- 3- TRCODE=12 VE ORDERLINE INSERT
SET @ORDERLINEREF = 0
SELECT @ORDERLINEREF=LOGICALREF FROM ORDERLINE WHERE LGSHIPINFOREF=@BARKODNUMERIC AND ITEMREF=@ITEMREF AND TRCODE=12
IF @ORDERLINEREF=0 
BEGIN
    SET @LGSHIPINFOREF = @BARKODNUMERIC
	SET @AMOUNT = @KOLI_ETIKETI
	SET @CLIENTREF = NULL
	SET @VARIANTREF = 0
	SET @TRCODE = 12
	SET @IOCODE = 4
	SET @BRANCH = 0
	SET @TUOMREF = @UOMREF
	SET @PROCESSDATE = GETDATE()
   INSERT INTO [dbo].[ORDERLINE]
 ([ORDERFICHEREF],[STFICHEREF],[CLIENTREF],[ITEMREF],[VARIANTREF],[AMOUNT],[USREF],[UOMREF],[CONVFACT1],[CONVFACT2],[TRCODE],[IOCODE],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX]
,[LGORFLINEREF],[LGSHIPINFOREF],[LGORFICHEREF],[LGDEMANDLINEREF],[LGDEMANDFICHEREF],[PROCESSDATE],[LGSETREF],[LGOFFERREF],[LGOFFTRANSREF],[TUOMREF],[LGSTFICHEREF],[LGSTLINEREF])
     VALUES
(@ORDERFICHEREF,@STFICHEREF,@CLIENTREF,@ITEMREF,@VARIANTREF,@AMOUNT,@USREF,@UOMREF,@CONVFACT1,@CONVFACT2,@TRCODE,@IOCODE,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@LGORFLINEREF
,@LGSHIPINFOREF,@LGORFICHEREF,@LGDEMANDLINEREF,@LGDEMANDFICHEREF,@PROCESSDATE,@LGSETREF,@LGOFFERREF,@LGOFFTRANSREF,@TUOMREF,@LGSTFICHEREF,@LGSTLINEREF)
	 SELECT @ORDERLINEREF=@@IDENTITY
END


-- 4- TRCODE=12 VE STLINE INSERT
SET @STLINEREF = 0
SELECT @STLINEREF=LOGICALREF FROM STLINE WHERE SHIPINFOREF=@BARKODNUMERIC AND ITEMREF=@ITEMREF AND TRCODE=12
IF @STLINEREF=0 
BEGIN
    SET @SHIPINFOREF = @BARKODNUMERIC
	SET @AMOUNT = @KOLI_ETIKETI
	SET @CLIENTREF = NULL
	SET @VARIANTREF = 0
	SET @TRCODE = 12
	SET @IOCODE = 4
	SET @BRANCH = 0
	SET @SOURCEINDEX = 0
	SET @PROCESSDATE = GETDATE() 
	SET @TERMINALREF = 1

  INSERT INTO [dbo].[STLINE]
([STFICHEREF],[TRCODE],[IOCODE],[ITEMREF],[VARIANTREF],[BARCODEREF],[AMOUNT],[USREF],[UOMREF],[CONVFACT1],[CONVFACT2],[CLIENTREF],[BRANCH],[SOURCEINDEX],[DESTBRANCH],[DESTINDEX],[PROCESSDATE]
,[ORDERFICHEREF],[ORDERLINEREF],[CNTFICHEREF],[CNTDETAILREF],[QPRODREF],[QPRODLINEREF],[USERREF],[TERMINALREF],[SHIPINFOREF],[PPRODORDREF],[PPRODORDFICHEREF],[PPRODLINEREF],[SPECODE]
,[ISCSNOENTRY],[MAINORDERLINEREF],[STCOMPLNREF],[CHECKED],[CHECKEDBYTERMINALREF],[CHECKEDDATE],[POLINEREF])
VALUES
(@STFICHEREF,@TRCODE,@IOCODE,@ITEMREF,@VARIANTREF,@BARCODEREF,@AMOUNT,@USREF,@UOMREF,@CONVFACT1,@CONVFACT2,@CLIENTREF,@BRANCH,@SOURCEINDEX,@DESTBRANCH,@DESTINDEX,@PROCESSDATE ,@ORDERFICHEREF,@ORDERLINEREF
,@CNTFICHEREF,@CNTDETAILREF,@QPRODREF,@QPRODLINEREF,@USERREF,@TERMINALREF,@SHIPINFOREF,@PPRODORDREF,@PPRODORDFICHEREF,@PPRODLINEREF,@SPECODE ,@ISCSNOENTRY ,@MAINORDERLINEREF,@STCOMPLNREF
,@CHECKED ,@CHECKEDBYTERMINALREF,@CHECKEDDATE ,@POLINEREF)	 
END

 --SELECT  @ITEMREF,@USREF ,@UOMREF,@CONVFACT1,@CONVFACT2,@KOLI_ETIKETI,@BARKODNUMERIC
FETCH NEXT FROM ORFICHE_CURCOR 
INTO  @ITEMREF,@USREF ,@UOMREF,@CONVFACT1,@CONVFACT2,@KOLI_ETIKETI,@BARKODNUMERIC
END
CLOSE ORFICHE_CURCOR
DEALLOCATE ORFICHE_CURCOR




