select * from PT_PAKETLEME_LOG
LEFT JOIN PT_HAZIRLIK_SATIR ON PT_PAKETLEME_LOG.FISNO = PT_HAZIRLIK_SATIR.FISNO
--WHERE PT_PAKETLEME_LOG.KULLANICI = 'SEYIT' 
--AND TARIH  = '20200610' 
--AND ISLEM ='ÝÞÝ BÝTÝRDÝ'

create view VW_KullaniciGunlukIcmali as 
select  CAST(TARIH AS DATE) AS Tarih, PT_PAKETLEME_LOG.KULLANICI as Kullanici,COUNT(PT_HAZIRLIK_SATIR.FISNO) as IsEmriSayisi,SUM(PT_PAKETLEME_LOG.KOLI_ETIKETI) AS UrunAdet from PT_PAKETLEME_LOG
LEFT JOIN PT_HAZIRLIK_SATIR ON PT_PAKETLEME_LOG.FISNO = PT_HAZIRLIK_SATIR.FISNO
WHERE-- PT_PAKETLEME_LOG.KULLANICI = 'SEYIT'  AND
  --TARIH  = '20200610'  AND
 ISLEM ='ÝÞÝ BÝTÝRDÝ'
 GROUP BY CAST(TARIH AS DATE), PT_PAKETLEME_LOG.KULLANICI
 
