USE [GO3DB]
GO

SELECT [ID]
      ,[FISNO]
      ,[STOKKODU]
      ,[STOKADI]
      ,[DPKODU]
      ,[TEDARIKCI_KODU]
      ,[TEDARIKCI_ADI]
      ,[TEDARIKCI_FTNO]
      ,[ADET]
      ,[URUN_TIPI]
      ,[DPKKODU]
      ,[GRUP_KODU]
      ,[FIS_TARIHI]
      ,[KULLANICI]
      ,[SIPARIS_REFERANS]
  FROM [dbo].[PT_HAZIRLIK_SATIR]

select DISTINCT PT_HAZIRLIK_SATIR.ID, TBL_LOG.FISNO, DATEPART(YYYY,TBL_LOG.TARIH) AS YIL ,DATEPART(WW,TBL_LOG.TARIH) AS HAFTA, BOX,DPKODU,KOLI_ETIKETI    from 
( SELECT * FROM PT_PAKETLEME_LOG  Q1 WITH( NOLOCK) WHERE Q1.ID IN (SELECT TOP 1 ID FROM PT_PAKETLEME_LOG  Q2  WITH( NOLOCK) 
 WHERE  Q1.FISNO = Q2.FISNO AND Q1.BOX = Q2.BOX AND   DATEPART(WW,Q2.TARIH) = 27 AND  DATEPART(YYYY,Q2.TARIH) = 2021 AND Q2.ISLEM = 'KOLI ETIKETI BASILDI'  ORDER BY Q2.ID DESC)  AND 
 DATEPART(WW,Q1.TARIH) = 27 AND  DATEPART(YYYY,Q1.TARIH) = 2021 AND Q1.ISLEM = 'KOLI ETIKETI BASILDI')    TBL_LOG
LEFT JOIN [PT_HAZIRLIK_SATIR] ON [PT_HAZIRLIK_SATIR].FISNO = TBL_LOG.FISNO --AND DATEPART(WW,PT_PAKETLEME_LOG.TARIH) =  DATEPART(WW,[PT_HAZIRLIK_SATIR].FIS_TARIHI)
WHERE TBL_LOG.BOX = '1'  AND (URUN_TIPI = 'ANA ÜRÜN' OR URUN_TIPI = 'TEK ÜRÜN')
AND DATEPART(WW,TBL_LOG.TARIH) = 27   
 AND DATEPART(YYYY,TBL_LOG.TARIH) = 2021   
--and PT_PAKETLEME_LOG.FISNO = '210525144959' 
and ISLEM = 'KOLI ETIKETI BASILDI'
--order by PT_PAKETLEME_LOG.ID DESC	
 
 SELECT * FROM PT_PAKETLEME_LOG

 SELECT * FROM PT_PAKETLEME_LOG  Q1 WITH( NOLOCK) WHERE Q1.ID IN (SELECT TOP 1 ID FROM PT_PAKETLEME_LOG  Q2  WITH( NOLOCK) 
 WHERE  Q1.FISNO = Q2.FISNO AND Q1.BOX = Q2.BOX AND   DATEPART(WW,Q2.TARIH) = 27 AND  DATEPART(YYYY,Q2.TARIH) = 2021 AND Q2.ISLEM = 'KOLI ETIKETI BASILDI'  ORDER BY Q2.ID DESC)  AND 
 DATEPART(WW,Q1.TARIH) = 27 AND  DATEPART(YYYY,Q1.TARIH) = 2021 AND Q1.ISLEM = 'KOLI ETIKETI BASILDI'

--DP3925
