SELECT max(FICHENO) SonFicheNo,SUBSTRING(max(FICHENO),8,9)  as SonNumara ,

REPLACE(STR(CAST(SUBSTRING(max(FICHENO),8,9) AS INT) + 1, 9), SPACE(1), '0') as NumaraStr
, CAST(SUBSTRING(max(FICHENO),8,9) AS INT) + 1 as AlinacakNumara ,
sUBSTRING(max(FICHENO),1,7) as EfaturaSeri  FROM LG_076_20_INVOICE WHERE FICHENO LIKE (
SELECT TOP 1  SEGMENTS1_SEGEND + CAST(YEAR(EFFSDATE) AS VARCHAR(4)) + '%' FROM [L_LDOCNUM] WHERE FIRMID = 076 AND APPMODULE = 35 
AND YEAR(EFFSDATE) = 2020)
  