
SELECT  
VR.LOGICALREF AS VRLOGICALREF,
VR.CODE AS VRCODE, 
ITEMS.LOGICALREF AS ITEMREF,
ITEMS.CARDTYPE,
ITEMS.CODE,
ITEMS.NAME  

,CASE WHEN TBL_DELIK.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_DELIK.CODE END  AS VR_DELIKCODE
,CASE WHEN TBL_FIRIN.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_FIRIN.CODE END AS VR_FIRINCODE
,CASE WHEN TBL_KESIM.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE  VR_KESIM.CODE END AS VR_KESIMCODE 
,CASE WHEN TBL_PAKETLEME.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_PAKETLEME.CODE END AS VR_PAKETLEMECODE 
,CASE WHEN TBL_RODAJ.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_RODAJ.CODE END AS VR_RODAJCODE 
,CASE WHEN TBL_SERIGRAF.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_SERIGRAF.CODE END  AS VR_SERIGRAFCODE
,CASE WHEN TBL_OTOKLAV.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_OTOKLAV.CODE END AS VR_OTOKLAVCODE
,CASE WHEN TBL_SUJETI.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE  VR_SUJETI.CODE END AS VR_SUJETICODE

FROM LG_020_ITEMS ITEMS

LEFT JOIN LG_020_ITEMS TBL_DELIK ON TBL_DELIK.CARDTYPE=11 AND TBL_DELIK.ACTIVE = 0 AND TBL_DELIK.CODE = ITEMS.CODE + ' DELÝK'  
LEFT JOIN LG_020_ITEMS TBL_FIRIN ON TBL_FIRIN.CARDTYPE=11 AND TBL_FIRIN.ACTIVE = 0 AND TBL_FIRIN.CODE = ITEMS.CODE + ' FIRIN'  
LEFT JOIN LG_020_ITEMS TBL_KESIM ON TBL_KESIM.CARDTYPE=11 AND TBL_KESIM.ACTIVE = 0 AND TBL_KESIM.CODE = ITEMS.CODE + ' KESÝM'  
LEFT JOIN LG_020_ITEMS TBL_PAKETLEME ON TBL_PAKETLEME.CARDTYPE=11 AND TBL_PAKETLEME.ACTIVE = 0 AND TBL_PAKETLEME.CODE = ITEMS.CODE + ' PAKETLEME'  
LEFT JOIN LG_020_ITEMS TBL_RODAJ ON TBL_RODAJ.CARDTYPE=11 AND TBL_RODAJ.ACTIVE = 0 AND TBL_RODAJ.CODE = ITEMS.CODE + ' RODAJ'  
LEFT JOIN LG_020_ITEMS TBL_SERIGRAF ON TBL_SERIGRAF.CARDTYPE=11 AND TBL_SERIGRAF.ACTIVE = 0 AND TBL_SERIGRAF.CODE = ITEMS.CODE + ' SERÝGRAF'  
LEFT JOIN LG_020_ITEMS TBL_OTOKLAV ON TBL_OTOKLAV.CARDTYPE=11 AND TBL_OTOKLAV.ACTIVE = 0 AND TBL_OTOKLAV.CODE = ITEMS.CODE + ' OTOKLAV'   
LEFT JOIN LG_020_ITEMS TBL_SUJETI ON TBL_SUJETI.CARDTYPE=11 AND TBL_SUJETI.ACTIVE = 0 AND TBL_SUJETI.CODE = ITEMS.CODE + ' SU JETÝ'  

LEFT JOIN LG_020_VARIANT VR ON VR.ITEMREF = ITEMS.LOGICALREF
LEFT JOIN LG_020_VARIANT VR_DELIK ON VR_DELIK.ITEMREF = TBL_DELIK.LOGICALREF AND VR_DELIK.CODE = VR.CODE
LEFT JOIN LG_020_VARIANT VR_FIRIN ON VR_FIRIN.ITEMREF = TBL_FIRIN.LOGICALREF AND VR_FIRIN.CODE = VR.CODE
LEFT JOIN LG_020_VARIANT VR_KESIM ON VR_KESIM.ITEMREF = TBL_KESIM.LOGICALREF AND VR_KESIM.CODE = VR.CODE
LEFT JOIN LG_020_VARIANT VR_PAKETLEME ON VR_PAKETLEME.ITEMREF = TBL_PAKETLEME.LOGICALREF AND VR_PAKETLEME.CODE = VR.CODE
LEFT JOIN LG_020_VARIANT VR_RODAJ ON VR_RODAJ.ITEMREF = TBL_RODAJ.LOGICALREF AND VR_RODAJ.CODE = VR.CODE
LEFT JOIN LG_020_VARIANT VR_SERIGRAF ON VR_SERIGRAF.ITEMREF = TBL_SERIGRAF.LOGICALREF AND VR_SERIGRAF.CODE = VR.CODE
LEFT JOIN LG_020_VARIANT VR_OTOKLAV ON VR_OTOKLAV.ITEMREF = TBL_OTOKLAV.LOGICALREF AND VR_OTOKLAV.CODE = VR.CODE
LEFT JOIN LG_020_VARIANT VR_SUJETI ON VR_SUJETI.ITEMREF = TBL_SUJETI.LOGICALREF AND VR_SUJETI.CODE = VR.CODE

WHERE  ITEMS.CARDTYPE = 12 AND ITEMS.ACTIVE = 0  --AND ITEMS.CODE = 'F.081.00.002' 
AND  (  (CASE WHEN TBL_DELIK.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_DELIK.CODE END ) IS NULL OR 
       (CASE WHEN TBL_FIRIN.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_FIRIN.CODE END) IS NULL OR
	   (CASE WHEN TBL_KESIM.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE  VR_KESIM.CODE END ) IS NULL OR
	   (CASE WHEN TBL_PAKETLEME.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_PAKETLEME.CODE END ) IS NULL OR 
	   (CASE WHEN TBL_RODAJ.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_RODAJ.CODE END ) IS NULL OR  
		(CASE WHEN TBL_SERIGRAF.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_SERIGRAF.CODE END) IS NULL OR
		(CASE WHEN TBL_OTOKLAV.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE VR_OTOKLAV.CODE END ) IS NULL OR
		(CASE WHEN TBL_SUJETI.LOGICALREF IS NULL THEN 'ITEM YOK' ELSE  VR_SUJETI.CODE END ) IS NULL 
     )
--select * from LG_020_VARIANT
--SELECT * FROM LG_020_ITEMS WHERE LOGICALREF= 6465 F.081.00.002 SERÝGRAF
--SELECT * FROM LG_020_ITEMS WHERE CODE like '%45 008%'