/*
ALTER VIEW [dbo].[HE_CARIMUHASEBE_018]
AS
SELECT     	dbo.LG_018_CLCARD.CODE AS [Cari Hesap Kodu], 
		dbo.LG_018_CLCARD.DEFINITION_ AS [Cari Hesap Adý], 
	 	SUBSTRING(LG_018_CLCARD.CODE,1,3) AS [Hesap Grubu], 
                      	dbo.LG_018_CLCARD.TAXNR  AS [Vergi numarasý], 
                      	dbo.LG_018_CLCARD.TAXOFFICE  AS [Vergi dairesi], 
		dbo.LG_018_EMUHACC.CODE AS [Muhasebe Kodu], 
		dbo.LG_018_EMUHACC.DEFINITION_ AS [Muhasebe Adý], 
                      	dbo.LG_018_CRDACREF.TRCODE AS [Kart Tipi], 
		dbo.LG_018_ITEMS.CODE, dbo.LG_018_ITEMS.NAME
FROM         	dbo.LG_018_CRDACREF INNER JOIN
                      	dbo.LG_018_CLCARD ON dbo.LG_018_CRDACREF.CARDREF = dbo.LG_018_CLCARD.LOGICALREF INNER JOIN
                      	dbo.LG_018_EMUHACC ON dbo.LG_018_CRDACREF.ACCOUNTREF = dbo.LG_018_EMUHACC.LOGICALREF INNER JOIN
                      	dbo.LG_018_ITEMS ON dbo.LG_018_CRDACREF.CARDREF = dbo.LG_018_ITEMS.LOGICALREF
WHERE     	(dbo.LG_018_CRDACREF.TRCODE = 5) OR
                      	(dbo.LG_018_CRDACREF.TRCODE = 1)

*/

select LG_029_ITEMS.CODE, LG_029_EMUHACC.CODE,LG_029_CRDACREF.* from 
dbo.LG_029_ITEMS 
LEFT JOIN LG_029_CRDACREF ON dbo.LG_029_CRDACREF.CARDREF = dbo.LG_029_ITEMS.LOGICALREF
LEFT JOIN dbo.LG_029_EMUHACC ON dbo.LG_029_CRDACREF.ACCOUNTREF = dbo.LG_029_EMUHACC.LOGICALREF
WHERE   	(dbo.LG_029_CRDACREF.TRCODE = 1) AND LG_029_EMUHACC.CODE IS NOT NULL AND TYP = 1 --AND LG_029_ITEMS.CODE = '01.01.01.0001'

--SELECT * FROM LG_029_CRDACREF