 /*
CREATE TABLE [dbo].[PT_BOX](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[YIL] [int] NULL,
	[HAFTA] [int] NULL,
	[BOX] [int] NULL,
	[KAYIT_TARIHI] [datetime] NULL,

) ON [PRIMARY]
GO
*/

/*
SELECT *,tblBasladi.BOX,tblKapandi.BOX FROM PT_PAKETLEME_LOG   
LEFT JOIN (
select year(TARIH) AS YIL, DATEPART(ww,TARIH) as HAFTA, BOX  from PT_PAKETLEME_LOG WHERE ISLEM LIKE 'BOX NO SEÇÝLDÝ' ) 
as tblBasladi on tblBasladi.YIL = year(PT_PAKETLEME_LOG.TARIH)  AND tblBasladi.HAFTA = DATEPART(ww,PT_PAKETLEME_LOG.TARIH) AND tblBasladi.BOX = PT_PAKETLEME_LOG.BOX
LEFT JOIN (
select year(TARIH) AS YIL, DATEPART(ww,TARIH) as HAFTA, BOX  from PT_PAKETLEME_LOG WHERE ISLEM LIKE 'BOX NO KAPATILDI' )
as tblKapandi on tblKapandi.YIL = year(PT_PAKETLEME_LOG.TARIH)  AND tblKapandi.HAFTA = DATEPART(ww,PT_PAKETLEME_LOG.TARIH) AND tblKapandi.BOX = PT_PAKETLEME_LOG.BOX

*/

CREATE VIEW VW_PT_BOX_DURUM AS 
SELECT PT_BOX.YIL,PT_BOX.HAFTA,PT_BOX.BOX,tblBasladi.BOX as Basladi,tblKapandi.BOX as Kapandi FROM PT_BOX   
LEFT JOIN (
select year(TARIH) AS YIL, DATEPART(ww,TARIH) - 2 as HAFTA, BOX  from PT_PAKETLEME_LOG WHERE ISLEM LIKE 'BOX NO SEÇÝLDÝ' group by year(TARIH) , DATEPART(ww,TARIH),BOX ) 
as tblBasladi on tblBasladi.YIL = PT_BOX.YIL  AND tblBasladi.HAFTA =PT_BOX.HAFTA AND tblBasladi.BOX = PT_BOX.BOX
LEFT JOIN (
select year(TARIH) AS YIL, DATEPART(ww,TARIH) -2  as HAFTA, BOX  from PT_PAKETLEME_LOG WHERE ISLEM LIKE 'BOX NO KAPATILDI' group by year(TARIH) , DATEPART(ww,TARIH),BOX )
as tblKapandi on tblKapandi.YIL = PT_BOX.YIL  AND tblKapandi.HAFTA = PT_BOX.HAFTA AND tblKapandi.BOX = PT_BOX.BOX


SELECT * FROM VW_PT_BOX_DURUM

select GETDATE(), DATEPART(ww,GETDATE())

SELECT TOP 1 * FROM PT_PAKETLEME_LOG where KULLANICI = 'ERGIN' AND ISLEM = 'BOX NO SEÇÝLDÝ' AND BOX <> '-1' ORDER BY TARIH DESC