USE [TIGER3]
GO

/****** Object:  StoredProcedure [dbo].[sp_BorcluVadeAnalizi]    Script Date: 22.01.2021 23:28:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--EXEC [sp_BorcluVadeAnalizi] '003' ,'01','20210101','%%',0


CREATE PROCEDURE [dbo].[sp_BorcluVadeAnalizi]
@_FIRMA AS VARCHAR(3),
@_DONEM AS VARCHAR(2),
@_RAPTAR as DATETIME  , 
@_CARKOD as VARCHAR(100), 
@_BAKIYE FLOAT = 0


AS 
BEGIN
declare @strSQL nvarchar(max)  = ''
declare @strSQL1 nvarchar(max)  = ''
declare @strSQL2 nvarchar(max)  = ''
declare @strSQL3 nvarchar(max)  = ''
declare @strSQL4 nvarchar(max)  = ''
declare @strSQL5 nvarchar(max)  = ''
declare @strSQL6 nvarchar(max)  = ''

--DECLARE @_RAPTAR DATETIME = GETDATE()
--DECLARE @_CARKOD VARCHAR(100) = ''*''
--DECLARE @_BAKIYE FLOAT = 0

 
declare @Tbl table
  (
	[CariReferans] [int] NOT NULL,
	[CariHesapKodu] [varchar](17) NULL,
	[TEL1] [varchar](51) NULL,
	[TEL2] [varchar](51) NULL,
	[Cari Hesap Ünvanı] [varchar](201) NULL,
	[Özel Kod] [varchar](11) NULL,
	[Özel Kod 2] [varchar](11) NULL,
	[Özel Kod 3] [varchar](11) NULL,
	[Özel Kod 4] [varchar](11) NULL,
	[Özel Kod 5] [varchar](11) NULL,
	[Tanımlı Vade] [varchar](201) NOT NULL,
	[Toplam Bakiye] [float] NULL,
	[Ortalama Vade] [date] NULL,
	[Dolan Bakiye] [float] NULL,
	[Dolan Vade] [date] NULL,
	[Dolacak Ilk Fatura Tutarı] [float] NULL,
	[Dolacak Ilk Fatura Vade] [date] NULL,
	[Son Tahsilat Tarihi] [date] NULL,
	[Son Tahsilat Türü] [varchar](14) NOT NULL,
	[Son Tahsilat Çek Ort.Vade] [datetime] NULL,
	[Son Tahsilat Tutarı] [float] NULL,
	[Devreden Bakiye] [float] NULL,
	[Devreden Vade] [date] NULL,
	[Son Gorusen Kisi] [varchar](25) NULL,
	[Son Gorusulen Kisi] [varchar](50) NULL,
	[Son Gorusme Tarihi] [datetime] NULL,
	[Son Gorusme Detayı] [text] NULL)

	 

set @strSQL1  = ' 
DECLARE @TARIH_1 DATE
DECLARE @TARIH_2 DATE
DECLARE @CLIENTREF integer
DECLARE @B_PAYPLANREF integer
DECLARE @B_VADE_TARIHI DATE
DECLARE @B_GIRIS_TARIHI DATE
DECLARE @B_ISLEM_TIPI varchar(55)
DECLARE @B_TUTAR AS FLOAT
DECLARE @K_PAYPLANREF AS integer 
Declare @K_VADE_TARIHI as date 
Declare @K_GIRIS_TARIHI as date 
Declare @K_ISLEM_TIPI as varchar(50) 
Declare @K_ISLEM_TUTAR as float
DECLARE @B_LOGICALREF integer declare @B_CARDREF AS integer DECLARE @B_DATE DATE DECLARE @B_PROCDATE DATE DECLARE @B_TRCODE integer declare @B_TOTAL float
DECLARE @A_LOGICALREF integer declare @A_CARDREF AS integer DECLARE @A_DATE DATE DECLARE @A_PROCDATE DATE DECLARE @A_TRCODE integer declare @A_TOTAL float
DECLARE @B_KALAN AS FLOAT DECLARE @A_KALAN AS FLOAT DECLARE @B_KAPANAN AS FLOAT
DECLARE @TABLO_SAY AS FLOAT
/* DY Paytrans Tablosu Oluþturuluyor   */
SET @TABLO_SAY = (SELECT COUNT(id) FROM sysobjects WHERE  NAME LIKE ''EMY_VADEANALIZ'')
IF @TABLO_SAY > 0 
	BEGIN
		DROP TABLE EMY_VADEANALIZ
	END
	SELECT * INTO  EMY_VADEANALIZ 
	FROM (
		SELECT 	PAYTRANS.LOGICALREF + 900000000 LOGICALREF,	PAYTRANS.CARDREF CARDREF,PAYTRANS.DATE_ DATE_,0 FTIME,PAYTRANS.PROCDATE PROCDATE,PAYTRANS.TRCODE  TRCODE,
	ROUND((CASE WHEN PAYTRANS.TRCURR IN (0,160) THEN PAYTRANS.TOTAL ELSE PAYTRANS.TOTAL * PAYTRANS.TRRATE END),2) TOTAL,PAYTRANS.FICHEREF FICHEREF,
	PAYTRANS.SIGN SIGN,	PAYTRANS.PAIDINCASH PAIDINCASH,	PAYTRANS.CLOSINGRATE  CLOSINGRATE,	PAYTRANS.CANCELLED CANCELLED
FROM   LG_' + @_FIRMA + '_' + @_DONEM + '_PAYTRANS PAYTRANS	WHERE   PAYTRANS.CANCELLED =0  
'
set @strSQL2  = '
UNION ALL

SELECT CLFLINE.LOGICALREF+ 800000000 LOGICALREF,CLFLINE.CLIENTREF CARDREF,CLFLINE.DATE_,0 FTIME,CLFLINE.DATE_ PROCDATE,CLFLINE.TRCODE,CLFLINE.AMOUNT AS TOTAL,
CLFLINE.SOURCEFREF FICHEREF,CLFLINE.SIGN,0 PAIDINCASH,0 CLOSINGRATE,CLFLINE.CANCELLED
 FROM LG_' + @_FIRMA + '_' + @_DONEM + '_CLFLINE	CLFLINE WHERE CLFLINE.MODULENR=5 AND CLFLINE.TRCODE=6 AND CLFLINE.CANCELLED=0
		) Paytrans
		  CREATE UNIQUE INDEX [LOGICALREF] ON EMY_VADEANALIZ (LOGICALREF ASC)
		  CREATE INDEX CARDREF ON EMY_VADEANALIZ (CARDREF ASC)

/*   DY Borc Takip Tablosunun Oluþturulması  */
SET @TABLO_SAY = (SELECT COUNT(id) FROM sysobjects WHERE  NAME LIKE ''EMY_BorcTakip'')
IF @TABLO_SAY > 0 
	BEGIN
		DROP TABLE EMY_BorcTakip
	END
	CREATE TABLE [EMY_BorcTakip](
		[LOGICALREF] [int] IDENTITY(1,1) NOT NULL,
		[CLIENTREF] [int] NULL,
		[B_PAYPLANREF] [int] NULL,
		[B_VADE_TARIHI] [date] NULL,
		[B_GIRIS_TARIHI] [date] NULL,
		[B_ISLEM_TIPI] [nvarchar](50) NULL,
		[B_TUTAR] [float] NULL,
		[K_PAYPLANREF] [int] NULL,
		[K_VADE_TARIHI] [date] NULL,
		[K_GIRIS_TARIHI] [date] NULL,
		[K_ISLEM_TIPI] [nvarchar](50) NULL,
		[K_ISLEM_TUTAR] [float] NULL,
	 CONSTRAINT [PK_EMY_BorcTakip] PRIMARY KEY CLUSTERED 
	(
		[LOGICALREF] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
'	
 
set @strSQL3  = '
SET @TARIH_1 = ''20000101''
SET @TARIH_2 = @_RAPTAR
DECLARE CariHesap Cursor For

SELECT LOGICALREF  FROM (
SELECT CLFLINE.CLIENTREF  LOGICALREF, SUM(CASE WHEN SIGN = 0 THEN AMOUNT ELSE 0-AMOUNT END) BAKIYE  
FROM LG_' + @_FIRMA + '_' + @_DONEM + '_CLFLINE CLFLINE
	LEFT JOIN LG_' + @_FIRMA + '_' + @_DONEM + '_INVOICE INVOICE ON CLFLINE.SOURCEFREF = INVOICE.LOGICALREF AND CLFLINE.MODULENR = 4
WHERE   ISNULL(INVOICE.FROMKASA,0) = 0 AND CLFLINE.DATE_ BETWEEN @TARIH_1 AND @TARIH_2 AND CLFLINE.CANCELLED =0  
GROUP BY CLFLINE.CLIENTREF) D WHERE D.BAKIYE >0

OPEN CariHesap
FETCH NEXT FROM CariHesap INTO @CLIENTREF
WHILE @@FETCH_STATUS =0
BEGIN

DECLARE Borc Cursor For
	SELECT LOGICALREF,CARDREF,DATE_,PROCDATE,TRCODE,TOTAL  
	FROM   EMY_VADEANALIZ WHERE CARDREF = @CLIENTREF AND SIGN =0 AND CANCELLED=0 AND PAIDINCASH = 0 AND CLOSINGRATE = 0 AND PROCDATE BETWEEN @TARIH_1 AND @TARIH_2   
	ORDER BY CARDREF,DATE_,FTIME
	
DECLARE Alacak Cursor For
	SELECT LOGICALREF,CARDREF,DATE_,PROCDATE,TRCODE,TOTAL  
	FROM   EMY_VADEANALIZ WHERE CARDREF = @CLIENTREF AND SIGN =1 AND CANCELLED=0 AND PAIDINCASH = 0 AND CLOSINGRATE = 0 AND PROCDATE BETWEEN @TARIH_1 AND @TARIH_2   
	ORDER BY CARDREF,DATE_,FTIME
OPEN Alacak
FETCH NEXT FROM ALACAK INTO @A_LOGICALREF,@A_CARDREF,@A_DATE,@A_PROCDATE,@A_TRCODE,@A_TOTAL
	IF @@FETCH_STATUS = -1  /* Alacak Kaydı bulunamazsa iþlemi boþ geçiyor  */
	BEGIN 
		SET @A_TOTAL = 0
	END 
	OPEN Borc
		FETCH NEXT FROM Borc INTO @B_LOGICALREF,@B_CARDREF,@B_DATE,@B_PROCDATE,@B_TRCODE,@B_TOTAL
			SET @B_KALAN = @B_TOTAL
			SET @A_KALAN = @A_TOTAL 
			WHILE @@FETCH_STATUS =0
				BEGIN   
TEKRAR:
					SET @B_KALAN = @B_KALAN - @A_KALAN 
					IF @B_KALAN > 0 
						BEGIN
							IF @A_KALAN > 0 
								BEGIN
									INSERT INTO EMY_BorcTakip (CLIENTREF,B_PAYPLANREF,B_VADE_TARIHI,B_GIRIS_TARIHI,B_TUTAR,K_PAYPLANREF,K_VADE_TARIHI,K_GIRIS_TARIHI,K_ISLEM_TUTAR)
									values(@B_CARDREF,@B_LOGICALREF,@B_DATE,@B_PROCDATE,ROUND(@A_KALAN,2),@A_LOGICALREF,@A_DATE,@A_PROCDATE,ROUND(@A_KALAN,2))
								END '
								set @strSQL4 = '
							FETCH NEXT FROM ALACAK INTO @A_LOGICALREF,@A_CARDREF,@A_DATE,@A_PROCDATE,@A_TRCODE,@A_TOTAL
								IF @@FETCH_STATUS = -1  /* Alacak Kaydı bulunamazsa iþlemi boþ geçiyor  */
									BEGIN 
										INSERT INTO EMY_BorcTakip (CLIENTREF,B_PAYPLANREF,B_VADE_TARIHI,B_GIRIS_TARIHI,B_TUTAR,K_PAYPLANREF,K_VADE_TARIHI,K_GIRIS_TARIHI,K_ISLEM_TUTAR)
										values(@B_CARDREF,@B_LOGICALREF,@B_DATE,@B_PROCDATE,ROUND(@B_KALAN,2),NULL,NULL,NULL,0)
									
										INSERT INTO EMY_BorcTakip (CLIENTREF,B_PAYPLANREF,B_VADE_TARIHI,B_GIRIS_TARIHI,B_TUTAR,K_PAYPLANREF,K_VADE_TARIHI,K_GIRIS_TARIHI,K_ISLEM_TUTAR)
										SELECT CARDREF,	LOGICALREF,DATE_,PROCDATE ,TOTAL,null ,NULL ,null ,0  FROM EMY_VADEANALIZ WHERE CARDREF = @CLIENTREF AND SIGN = 0 AND CANCELLED =0 AND PAIDINCASH = 0 AND  CLOSINGRATE = 0 AND  PROCDATE BETWEEN @TARIH_1 AND @TARIH_2 AND  LOGICALREF NOT IN (SELECT B_PAYPLANREF  FROM EMY_BorcTakip WHERE CLIENTREF =  @CLIENTREF)
											
										goto BITIR
										SET @A_KALAN = 0
									END 
								IF @@FETCH_STATUS = 0   /* Alacak Kaydy bulunamazsa i?lemi bo? geçiyor */
									BEGIN 
										SET @A_KALAN = @A_TOTAL
									END
							GOTO TEKRAR
						END 
						IF @B_KALAN = 0 OR @B_KALAN < 0
							BEGIN 
								SET @B_KAPANAN = @B_KALAN + @A_KALAN 
								INSERT INTO EMY_BorcTakip (CLIENTREF,B_PAYPLANREF,B_VADE_TARIHI,B_GIRIS_TARIHI,B_TUTAR,K_PAYPLANREF,K_VADE_TARIHI,K_GIRIS_TARIHI,K_ISLEM_TUTAR)
								values(@B_CARDREF,@B_LOGICALREF,@B_DATE,@B_PROCDATE,ROUND(@B_KAPANAN,2),@A_LOGICALREF,@A_DATE,@A_PROCDATE,ROUND(@B_KAPANAN,2))
								SET @A_KALAN  = @A_KALAN - @B_KAPANAN
								FETCH NEXT FROM Borc INTO @B_LOGICALREF,@B_CARDREF,@B_DATE,@B_PROCDATE,@B_TRCODE,@B_TOTAL
								IF @@FETCH_STATUS = -1  /* Alacak Kaydı bulunamazsa iþlemi boþ geçiyor  */
									BEGIN 
										GOTO BITIR
									END 
								SET @B_KALAN = @B_TOTAL
								GOTO TEKRAR
							END
						END
BITIR:
'
set @strSQL5 = '
CLOSE Borc
DEALLOCATE Borc
CLOSE ALACAK
DEALLOCATE ALACAK
FETCH NEXT FROM CariHesap INTO @CLIENTREF
END
CLOSE CariHesap
DEALLOCATE CariHesap
end

/* insert into @Tbl  */
SELECT *  FROM 
(
	SELECT 
	CLCARD.LOGICALREF [CariReferans],
/* 1	*/
	CLCARD.CODE [CariHesapKodu],
/*  2   */
	CLCARD.SPECODE AS Temsilci,
	CLCARD.DEFINITION_ [CariHesapÜnvanı],
	CLCARD.SPECODE [OzelKod1],
	CLCARD.SPECODE2 [OzelKod2],
	CLCARD.SPECODE3 [OzelKod3],
	CLCARD.SPECODE4 [OzelKod4],
	CLCARD.SPECODE5 [OzelKod5],
	
/*  3   */
	ISNULL(PAYPLANS.DEFINITION_,'''')  [TanimliVade],
/* 4  */
	CONVERT(FLOAT,ROUND(ISNULL((SELECT SUM(CASE WHEN SIGN = 0 THEN AMOUNT ELSE 0-AMOUNT END) BAKIYE  
	FROM LG_' + @_FIRMA + '_' + @_DONEM + '_CLFLINE CLFLINE
	LEFT JOIN LG_' + @_FIRMA + '_' + @_DONEM + '_INVOICE INVOICE ON CLFLINE.SOURCEFREF = INVOICE.LOGICALREF AND CLFLINE.MODULENR = 4
	WHERE CLFLINE.CLIENTREF = CLCARD.LOGICALREF  AND ISNULL(INVOICE.FROMKASA,0) = 0 AND CLFLINE.CANCELLED = 0 AND  CLFLINE.DATE_ BETWEEN @TARIH_1 AND @TARIH_2),0),2)) [ToplamBakiye],
/*  5   */
	CONVERT(DATE,(SELECT DATEADD(DAY,ROUND((SUM(DATEDIFF(DAY,GETDATE(),B_VADE_TARIHI) * B_TUTAR ) / SUM(B_TUTAR)),0),GETDATE()) FROM EMY_BorcTakip  WHERE B_TUTAR > 0 AND CLIENTREF = CLCARD.LOGICALREF  AND B_GIRIS_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND K_ISLEM_TUTAR =0)) [OrtalamaVade],
/*  6   */	
	CONVERT(FLOAT,ROUND(ISNULL((SELECT SUM(B_TUTAR) FROM EMY_BorcTakip WHERE CLIENTREF = CLCARD.LOGICALREF  AND B_GIRIS_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND B_VADE_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND K_ISLEM_TUTAR =0),0),2)) [DolanBakiye],
/*  7   */
	CONVERT(DATE,(SELECT DATEADD(DAY,ROUND((SUM(DATEDIFF(DAY,GETDATE(),B_VADE_TARIHI) * B_TUTAR ) / SUM(B_TUTAR)),0),GETDATE()) FROM EMY_BorcTakip  WHERE B_TUTAR > 0 AND CLIENTREF = CLCARD.LOGICALREF  AND B_GIRIS_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND B_VADE_TARIHI between @TARIH_1 AND @TARIH_2 AND K_ISLEM_TUTAR =0)) [DolanVade],
/* 8  */ '
set @strSQL6 = '
	CONVERT(FLOAT,ROUND(ISNULL((SELECT TOP 1 B_TUTAR FROM EMY_BorcTakip WHERE B_TUTAR > 0 AND CLIENTREF = CLCARD.LOGICALREF  AND B_GIRIS_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND B_VADE_TARIHI > @TARIH_2 AND K_ISLEM_TUTAR =0 ORDER BY B_VADE_TARIHI),0),2)) [DolacakIlkFaturaTutari],
/*  9   */	
	CONVERT(DATE, (SELECT TOP 1 B_VADE_TARIHI FROM EMY_BorcTakip WHERE B_TUTAR > 0 AND CLIENTREF = CLCARD.LOGICALREF  AND B_GIRIS_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND  B_VADE_TARIHI > @TARIH_2 AND K_ISLEM_TUTAR =0 ORDER BY B_VADE_TARIHI)) [DolacakIlkFaturaVade],
/*  10   */	
	CONVERT(DATE,(SELECT TOP 1 DATE_ FROM LG_' + @_FIRMA + '_' + @_DONEM + '_CLFLINE WHERE CLIENTREF = CLCARD.LOGICALREF AND DATE_ BETWEEN @TARIH_1 AND @TARIH_2 AND SIGN = 1 AND CANCELLED =0 ORDER BY DATE_ DESC,LOGICALREF DESC )) [SonTahsilatTarihi],
/*  11   */
	CONVERT(FLOAT,ROUND(ISNULL((SELECT TOP 1 AMOUNT  FROM LG_' + @_FIRMA + '_' + @_DONEM + '_CLFLINE WHERE CLIENTREF = CLCARD.LOGICALREF AND DATE_ BETWEEN @TARIH_1 AND @TARIH_2 AND SIGN = 1 AND CANCELLED =0 ORDER BY DATE_ DESC,LOGICALREF DESC ),0),2)) [SonTahsilatTutari],
	CONVERT(FLOAT,ROUND(ISNULL((SELECT SUM(B_TUTAR)  FROM EMY_BorcTakip WHERE CLIENTREF = CLCARD.LOGICALREF  AND B_GIRIS_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND B_VADE_TARIHI > @TARIH_2 AND K_ISLEM_TUTAR =0),0),2)) [DevredenBakiye],
	CONVERT(DATE,(SELECT DATEADD(DAY,ROUND((SUM(DATEDIFF(DAY,GETDATE(),B_VADE_TARIHI) * B_TUTAR ) / SUM(B_TUTAR)),0),GETDATE()) FROM EMY_BorcTakip  WHERE B_TUTAR > 0 AND CLIENTREF = CLCARD.LOGICALREF  AND B_GIRIS_TARIHI BETWEEN @TARIH_1 AND @TARIH_2 AND B_VADE_TARIHI > @TARIH_2 AND K_ISLEM_TUTAR =0)) [DevredenVade]
	FROM LG_' + @_FIRMA + '_CLCARD CLCARD
		LEFT JOIN LG_' + @_FIRMA + '_PAYPLANS PAYPLANS ON CLCARD.PAYMENTREF = PAYPLANS.LOGICALREF 
	WHERE CLCARD.ACTIVE =0  AND (@_CARKOD='''' OR CLCARD.CODE LIKE REPLACE(@_CARKOD,''*'',''%'')) 
) KK
WHERE ROUND(KK.[ToplamBakiye],2)  >@_BAKIYE

'
SET @strSQL  = CONCAT(@strSQL1, @strSQL2 , @strSQL3, @strSQL4, @strSQL5, @strSQL6)

 
 SELECT @strSQL 
insert into @tbl
exec sp_executesql @strSQL 
            ,N'@_CARKOD varchar(100)'
            
			,N'@_RAPTAR  DATETIME'
			,N'@_BAKIYE  FLOAT'


			select  * from @tbl
			END
GO


