USE [TIGER3_STEEL]
GO

/****** Object:  View [dbo].[VW_120_01_SIPARIS_LISTE]    Script Date: 25.05.2021 15:51:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--SELECT * FROM [VW_120_01_SIPARIS_LISTESI] ORDER BY LOGICALREF

CREATE view [dbo].[VW_120_01_SIPARIS_LISTE] AS

select  DISTINCT   

ORFL.LOGICALREF ,
ORFL.ORDFICHEREF ,
CLC.LOGICALREF AS ClCardRef,
ITM.LOGICALREF AS ItemRef,
ITM.NAME AS MalzemeAdi,
DTY.AEN AS X_En,
DTY.BYUKSEKLIK AS Y_Yukseklik,
DTY.KESMIK AS Z_Boy,
DTY.ADET as Adet,
ORFL.AMOUNT as Miktar,
ORFL.PRPRICE as BirimFiyat,
CASE ORFL.PRCURR WHEN 0 THEN 'TL' ELSE CURR.CURCODE END as DovizCinsi,
round(ISNULL((ORFL.DISTDISC/case when ORFL.TOTAL = 0 then 1 end),0),2)*100 AS IndirimOrani,
CLC.DEFINITION_ as MusteriAdi,
ORF.DATE_ as SiparisTarihi,
ORF.FICHENO as SiparisNo,
--NULL as TeslimTarihi,
DEBIT - CREDIT AS ChBakiye,
ORF.GENEXP1 AS Aciklama1,
ORF.GENEXP2 AS Aciklama2,
MUSTBL.MUSSIPNO AS MusteriSiparisNo,
DY_CARIBILGI.ODEMEVADE AS OdemeVade,
USR.CODE as KullaniciAdi ,
NULL as ChOrtalamaVade,
0 as BirimSiparisTutar,
0 as FaturaIrsaliyeTutar,
DEBIT - CREDIT  as ToplamBakiye
, (SELECT      ISNULL(SUM(NETTOTAL),0) AS IRSALIYE_TUTARI
         FROM   LG_120_01_STFICHE WITH (NOLOCK)
		 WHERE   (TRCODE IN (7, 8)) AND (CLIENTREF = CLC.LOGICALREF)  AND CANCELLED=0 AND BILLED=0) AS FaturalanmamisIrsaliyeTutari

,(SELECT   ISNULL(SUM(KDV_DAHIL_KAPANMAMIS_SIP_TUTAR),0)  AS KAPANMAMIS_SIPARIS
         FROM    EMY_120_01_ORFLINE_BEKLEYEN WITH (NOLOCK)
		 WHERE   (CLIENTREF =CLC.LOGICALREF) AND (ORDFICHEREF <> ORF.LOGICALREF) ) AS BekleyenSiparisTutari,

 (SELECT          ACCRISKLIMIT AS ACIK_HESAP_RISKFROM   from          LG_120_01_CLRNUMS  WHERE        (CLCARDREF = CLC.LOGICALREF)) AS AcikRiskLimiti
 ,(DEBIT - CREDIT)  
 +  (SELECT      ISNULL(SUM(NETTOTAL),0) AS IRSALIYE_TUTARI
                          FROM   LG_120_01_STFICHE WITH (NOLOCK)
                        WHERE   (TRCODE IN (7, 8)) AND (CLIENTREF = CLC.LOGICALREF)  AND CANCELLED=0 AND BILLED=0) 
+ (SELECT   ISNULL(SUM(KDV_DAHIL_KAPANMAMIS_SIP_TUTAR),0)  AS KAPANMAMIS_SIPARIS
         FROM    EMY_120_01_ORFLINE_BEKLEYEN WITH (NOLOCK)
		 WHERE   (CLIENTREF =CLC.LOGICALREF) ) as ToplamBakiye2

,ISNULL(TBL_TAHSILEDILMEMISCEKLER.TUTAR,0) AS TahsilEdilmemisCekler
,VW_120_ORTALAMA_VADE.OrtalamaVade as OrtalamaVade
,ORF.NETTOTAL AS KdvDahilSiparisTutari
,isnull(MUSTBL.ACIKLAMA,' ') as DegisiklikNedeni
,TBL_GUNCEL.USERNAME as Guncelleyen
,ORF.CAPIBLOCK_MODIFIEDDATE as GuncellemeTarihi
,PlanlamaMaster.TeslimTarihi
,PlanlamaMaster.PlanlamaDurumId
,PlanlamaMaster.Id as PlanlamaMasterId
,PlanlamaMaster.IsEmriDurumId
,PlanlamaMaster.IsEmriNo
,PlanlamaMaster.IsEmriTarih
,PlanlamaMaster.Notlar
,PlanlamaMaster.TalasFarki
,ITM.code as MalzemeKodu
,REVERSE(PARSENAME(REPLACE(REVERSE(ITM.code), ',', '.'), 2)) as KaliteKodu
,REVERSE(PARSENAME(REPLACE(REVERSE(ITM.code), ',', '.'), 3)) as Kalite
 
from LG_120_01_ORFICHE ORF  WITH(NOLOCK)
--SELECT * FROM LG_120_01_ORFICHE



LEFT JOIN L_CAPIUSER TBL_GUNCEL WITH(NOLOCK) ON TBL_GUNCEL.LOGICALREF = ORF.CAPIBLOCK_MODIFIEDBY

LEFT JOIN LG_120_01_ORFLINE ORFL WITH(NOLOCK) ON ORF.LOGICALREF = ORFL.ORDFICHEREF
 left join EmySteelDB.dbo.PlanlamaMaster PlanlamaMaster on PlanlamaMaster.OrflineRef = ORFL.LOGICALREF
 -- left join EmySteelDB.dbo.PlanlamaDurum PlanlamaDurum on PlanlamaDurum.Id = PlanlamaMaster.PlanlamaDurumId
LEFT JOIN L_CURRENCYLIST CURR WITH(NOLOCK) ON CURR.CURTYPE = ORFL.PRCURR

LEFT JOIN LG_120_ITEMS ITM WITH(NOLOCK) ON ITM.LOGICALREF = ORFL.STOCKREF

LEFT JOIN LG_120_CLCARD CLC WITH(NOLOCK) ON CLC.LOGICALREF = ORF.CLIENTREF

LEFT JOIN VW_120_ORTALAMA_VADE ON VW_120_ORTALAMA_VADE.CARDREF = CLC.LOGICALREF

---LEFT JOIN EMY_120_01_ORFLINE_BEKLEYEN ORLB WITH(NOLOCK) ON ORLB.CLIENTREF = ORF.CLIENTREF

LEFT JOIN LG_XT001001_120 DTY WITH(NOLOCK) ON DTY.PARLOGREF = ORFL.LOGICALREF

LEFT JOIN LV_120_01_CLCARD LCLC WITH(NOLOCK) ON LCLC.LOGICALREF = ORF.CLIENTREF

LEFT JOIN LG_XT004001_120 MUSTBL WITH(NOLOCK) ON MUSTBL.PARLOGREF =  ORFL.ORDFICHEREF

LEFT JOIN LG_SLSMAN USR WITH(NOLOCK) ON USR.LOGICALREF =  ORFL.SALESMANREF AND USR.FIRMNR=120

left JOIN DY_CARIBILGI WITH(NOLOCK) ON DY_CARIBILGI.CLIENTREF = ORF.CLIENTREF

LEFT JOIN (select CST.CARDREF,ISNULL(SUM(CSC.AMOUNT),0) AS TUTAR

from LG_120_01_CSCARD CSC

LEFT OUTER JOIN LG_120_01_CSTRANS CST on CSC.LOGICALREF = CST.CSREF



WHERE DOC IN (1,2) AND CURRSTAT IN (1,3,4,2)  

GROUP BY CST.CARDREF) TBL_TAHSILEDILMEMISCEKLER ON TBL_TAHSILEDILMEMISCEKLER.CARDREF = CLC.LOGICALREF

WHERE   ORFL.LINETYPE = 0 -- and ORFL.ORDFICHEREF = 5785
and ORFL.DATE_>'20210225'  
 









GO


