USE [TIGER2_DB]
GO

/****** Object:  View [dbo].[VW_118_21_NAKIT_AKIS]    Script Date: 10.09.2021 13:51:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO













--SELECT * FROM VW_118_21_NAKIT_AKIS WHERE TUTAR=DOVIZLITUTAR BASLIK3 LIKE '%STOPAJ%'

CREATE VIEW [dbo].[VW_118_21_NAKIT_AKIS] AS
SELECT     (CASE LG_118_21_BNFLINE.TRCODE WHEN 1 THEN 'Banka Ýþlem' WHEN 2 THEN 'Virman Ýþlemi' WHEN 3 THEN 'Gelen Havale' WHEN 4 THEN 'Gönderilen Havale'
                       WHEN 5 THEN 'Açýlýþ Ýþlemi' ELSE 'Belirsiz' END) AS ISLEMTURU, 
                      (CASE LG_118_21_BNFLINE.MODULENR WHEN 6 THEN 'Çek / Senet' WHEN 7 THEN 'Banka' WHEN 10 THEN 'Kasa' WHEN 61 THEN 'Çek Tahsilatý' ELSE
                       'Belirsiz' END) AS MODUL, dbo.LG_118_21_BNFLINE.DATE_ AS TARIH, DATEPART(yy, dbo.LG_118_21_BNFLINE.DATE_) AS YIL, DATEPART(m, 
                      dbo.LG_118_21_BNFLINE.DATE_) AS AY, DATEPART(dd, dbo.LG_118_21_BNFLINE.DATE_) AS GUN, dbo.LG_118_21_BNFLINE.TRANNO AS FISNO, 
                      dbo.LG_118_21_BNFLINE.REPORTRATE AS DOVIZKURU, 
                      dbo.LG_118_21_BNFLINE.REPORTNET * ISNULL(BASLIK3.FORMULA,1)  AS DOVIZLITUTAR, 
                      dbo.LG_118_21_BNFLINE.AMOUNT * ISNULL(BASLIK3.FORMULA,1) AS TUTAR, dbo.LG_118_BANKACC.DEFINITION_ AS BANKAHSPADI, 
                      dbo.LG_118_21_BNFLINE.LINEEXP AS ACIKLAMA, dbo.LG_118_21_BNFLINE.BNTRACKINGNO AS BANKAKONTNO, 
                      dbo.LG_118_BANKACC.CODE AS BANKAHSPKODU, dbo.LG_118_BNCARD.CODE AS BANKAKODU, dbo.LG_118_BNCARD.DEFINITION_ AS BANKAADI, 
                      dbo.LG_118_CLCARD.CODE AS CARINO, dbo.LG_118_CLCARD.DEFINITION_ AS CARIADI, dbo.L_CAPIDIV.NAME AS ISYERI, 
                      dbo.L_CAPIDEPT.NAME AS BOLUM, dbo.LG_118_BANKACC.SPECODE AS HESAPGRUBU, dbo.LG_118_EMCENTER.CODE AS MMRKKODU, 
                      dbo.LG_118_EMCENTER.DEFINITION_ AS MMRKADI, dbo.LG_118_EMUHACC.CODE AS MHESAPKODU, 
                      dbo.LG_118_EMUHACC.DEFINITION_ AS MHESAPADI,
                      LG_118_21_BNFICHE.SPECODE AS FINANSKOD,
                      
                      FINOZEL.DEFINITION_ AS FINANSACIKLAMA
                      ,BASLIK1.BASLIK1 AS BASLIK1
,BASLIK2.BASLIK2 AS BASLIK2
,BASLIK3.BASLIK3 AS BASLIK3
,BASLIK4.BASLIK4 AS BASLIK4

,BASLIK1.BASLIK1ID AS BASLIK1ID
,BASLIK2.BASLIK2ID AS BASLIK2ID
,BASLIK3.BASLIK3ID AS BASLIK3ID
,BASLIK4.BASLIK4ID AS BASLIK4ID
,CASE WHEN DATEPART( wk, dbo.LG_118_21_BNFLINE.DATE_) - 1 = 0 THEN 1 ELSE  DATEPART( wk, dbo.LG_118_21_BNFLINE.DATE_) - 1 END as Hafta     
    ,(CASE dbo.LG_118_BANKACC.CARDTYPE WHEN 1 THEN 'TÝCARÝ HESAP' WHEN 2 THEN 'KREDÝ HESABI' WHEN 3 THEN 'DÖVÝZLÝ TÝCARÝ HESAP' WHEN 4 THEN 'DÖVÝZLÝ KREDÝ HESABI'
                       WHEN 5 THEN 'KREDÝ KARTI HESABI' ELSE '' END) AS HESAPTURU
                 , LG_EXCHANGE_106.RATES1 DOVIZKURU_EURO
				, ROUND(dbo.LG_118_21_BNFLINE.AMOUNT * ISNULL(BASLIK3.FORMULA,1) / LG_EXCHANGE_106.RATES1,4) AS DOVIZLITUTAR_EURO 
FROM         dbo.LG_118_BANKACC LEFT OUTER JOIN
                      dbo.LG_118_BNCARD ON dbo.LG_118_BANKACC.BANKREF = dbo.LG_118_BNCARD.LOGICALREF RIGHT OUTER JOIN
                      dbo.LG_118_EMUHACC RIGHT OUTER JOIN
                      dbo.LG_118_21_BNFLINE ON dbo.LG_118_EMUHACC.LOGICALREF = dbo.LG_118_21_BNFLINE.ACCOUNTREF LEFT OUTER JOIN
                      dbo.LG_118_EMCENTER ON dbo.LG_118_21_BNFLINE.CENTERREF = dbo.LG_118_EMCENTER.LOGICALREF ON 
                      dbo.LG_118_BANKACC.LOGICALREF = dbo.LG_118_21_BNFLINE.BNACCREF LEFT OUTER JOIN
                      dbo.L_CAPIDIV ON dbo.LG_118_21_BNFLINE.BRANCH = dbo.L_CAPIDIV.NR LEFT OUTER JOIN
                      dbo.L_CAPIDEPT ON dbo.LG_118_21_BNFLINE.DEPARTMENT = dbo.L_CAPIDEPT.NR LEFT OUTER JOIN
                      dbo.LG_118_21_BNFICHE ON dbo.LG_118_21_BNFLINE.SOURCEFREF = dbo.LG_118_21_BNFICHE.LOGICALREF LEFT OUTER JOIN
                      dbo.LG_118_CLCARD ON dbo.LG_118_21_BNFLINE.CLIENTREF = dbo.LG_118_CLCARD.LOGICALREF
                      LEFT JOIN LG_118_SPECODES FINOZEL ON FINOZEL.SPECODETYPE = 43 AND FINOZEL.SPECODE =LG_118_21_BNFICHE.SPECODE  
					  LEFT JOIN LG_EXCHANGE_106 ON CRTYPE = 20 AND EDATE = dbo.LG_118_21_BNFLINE.DATE_
----------------------------------------------


--11111111111111111111111111111. BASLIK1 ADI
LEFT JOIN (
SELECT  DISTINCT BASLIK1.LOGICALREF AS BASLIK1ID , BASLIK1.ITEMNAME AS BASLIK1 
,REPLACE(ALTBASLIK.RATES1,'*','%') AS KOSUL1, BASLIK1.FORMULA FROM 
LG_118_FINTABLEITEM BASLIK1 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON BASLIK1.TABLEREF=ALTBASLIK.TABLEREF AND  ALTBASLIK.ITEMCODE LIKE BASLIK1.ITEMCODE + '%'
WHERE (BASLIK1.TABLEREF = 2) AND BASLIK1.ITEMLEVEL = 1 AND ALTBASLIK.RATES1<>''  
UNION ALL
SELECT  DISTINCT BASLIK1.LOGICALREF AS BASLIK1ID , BASLIK1.ITEMNAME AS BASLIK1 
,REPLACE(ALTBASLIK.RATES2,'*','%') AS KOSUL1, BASLIK1.FORMULA   FROM 
LG_118_FINTABLEITEM BASLIK1 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK1.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK1.ITEMCODE + '%'
WHERE (BASLIK1.TABLEREF = 2) AND BASLIK1.ITEMLEVEL = 1 AND ALTBASLIK.RATES2<>''
UNION ALL
SELECT  DISTINCT BASLIK1.LOGICALREF AS BASLIK1ID , BASLIK1.ITEMNAME AS BASLIK1 
,REPLACE(ALTBASLIK.RATES3,'*','%') AS KOSUL1, BASLIK1.FORMULA   FROM 
LG_118_FINTABLEITEM BASLIK1 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK1.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK1.ITEMCODE + '%'
WHERE (BASLIK1.TABLEREF = 2) AND BASLIK1.ITEMLEVEL = 1 AND ALTBASLIK.RATES3<>''
UNION ALL
SELECT  DISTINCT BASLIK1.LOGICALREF AS BASLIK1ID , BASLIK1.ITEMNAME AS BASLIK1 
,REPLACE(ALTBASLIK.RATES4,'*','%') AS KOSUL1, BASLIK1.FORMULA   FROM 
LG_118_FINTABLEITEM BASLIK1 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK1.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK1.ITEMCODE + '%'
WHERE (BASLIK1.TABLEREF = 2) AND BASLIK1.ITEMLEVEL = 1 AND ALTBASLIK.RATES4<>''
) AS BASLIK1   ON FINOZEL.SPECODE LIKE BASLIK1.KOSUL1 

--222222222222222222222. BASLIK2 ADI
LEFT JOIN (
SELECT  DISTINCT BASLIK2.LOGICALREF AS BASLIK2ID , BASLIK2.ITEMNAME AS BASLIK2 
,REPLACE(ALTBASLIK.RATES1,'*','%') AS KOSUL1, BASLIK2.FORMULA FROM 
LG_118_FINTABLEITEM BASLIK2 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK2.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK2.ITEMCODE + '%'
WHERE (BASLIK2.TABLEREF = 2) AND BASLIK2.ITEMLEVEL = 2 AND ALTBASLIK.RATES1<>''
UNION ALL
SELECT  DISTINCT BASLIK2.LOGICALREF AS BASLIK2ID , BASLIK2.ITEMNAME AS BASLIK2 
,REPLACE(ALTBASLIK.RATES2,'*','%') AS KOSUL1, BASLIK2.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK2 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK2.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK2.ITEMCODE + '%'
WHERE (BASLIK2.TABLEREF = 2) AND BASLIK2.ITEMLEVEL = 2 AND ALTBASLIK.RATES2<>''
UNION ALL
SELECT  DISTINCT BASLIK2.LOGICALREF AS BASLIK2ID , BASLIK2.ITEMNAME AS BASLIK2 
,REPLACE(ALTBASLIK.RATES3,'*','%') AS KOSUL1, BASLIK2.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK2 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK2.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK2.ITEMCODE + '%'
WHERE (BASLIK2.TABLEREF = 2) AND BASLIK2.ITEMLEVEL = 2 AND ALTBASLIK.RATES3<>''
UNION ALL
SELECT  DISTINCT BASLIK2.LOGICALREF AS BASLIK2ID , BASLIK2.ITEMNAME AS BASLIK2 
,REPLACE(ALTBASLIK.RATES4,'*','%') AS KOSUL1, BASLIK2.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK2 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON BASLIK2.TABLEREF=ALTBASLIK.TABLEREF AND  ALTBASLIK.ITEMCODE LIKE BASLIK2.ITEMCODE + '%'
WHERE (BASLIK2.TABLEREF = 2) AND BASLIK2.ITEMLEVEL = 2 AND ALTBASLIK.RATES4<>''
) AS BASLIK2   ON FINOZEL.SPECODE LIKE BASLIK2.KOSUL1 

--333333333333333. BASLIK3 ADI
LEFT JOIN (
SELECT  DISTINCT BASLIK3.LOGICALREF AS BASLIK3ID , BASLIK3.ITEMNAME AS BASLIK3 
,REPLACE(ALTBASLIK.RATES1,'*','%') AS KOSUL1, BASLIK3.FORMULA FROM 
LG_118_FINTABLEITEM BASLIK3 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK3.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK3.ITEMCODE + '%'
WHERE (BASLIK3.TABLEREF = 2) AND BASLIK3.ITEMLEVEL = 3 AND ALTBASLIK.RATES1<>''
UNION ALL
SELECT  DISTINCT BASLIK3.LOGICALREF AS BASLIK3ID , BASLIK3.ITEMNAME AS BASLIK3 
,REPLACE(ALTBASLIK.RATES2,'*','%') AS KOSUL1, BASLIK3.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK3 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK3.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK3.ITEMCODE + '%'
WHERE (BASLIK3.TABLEREF = 2) AND BASLIK3.ITEMLEVEL = 3 AND ALTBASLIK.RATES2<>''
UNION ALL
SELECT  DISTINCT BASLIK3.LOGICALREF AS BASLIK3ID , BASLIK3.ITEMNAME AS BASLIK3 
,REPLACE(ALTBASLIK.RATES3,'*','%') AS KOSUL1, BASLIK3.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK3 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK3.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK3.ITEMCODE + '%'
WHERE (BASLIK3.TABLEREF = 2) AND BASLIK3.ITEMLEVEL = 3 AND ALTBASLIK.RATES3<>''
UNION ALL
SELECT  DISTINCT BASLIK3.LOGICALREF AS BASLIK3ID , BASLIK3.ITEMNAME AS BASLIK3 
,REPLACE(ALTBASLIK.RATES4,'*','%') AS KOSUL1, BASLIK3.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK3 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK3.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK3.ITEMCODE + '%'
WHERE (BASLIK3.TABLEREF = 2) AND BASLIK3.ITEMLEVEL = 3 AND ALTBASLIK.RATES4<>''
) AS BASLIK3   ON FINOZEL.SPECODE LIKE BASLIK3.KOSUL1


--44444444444444. BASLIK4 ADI
LEFT JOIN (
SELECT  DISTINCT BASLIK4.LOGICALREF AS BASLIK4ID , BASLIK4.ITEMNAME AS BASLIK4 
,REPLACE(ALTBASLIK.RATES1,'*','%') AS KOSUL1, BASLIK4.FORMULA FROM 
LG_118_FINTABLEITEM BASLIK4 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK4.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK4.ITEMCODE
WHERE ((BASLIK4.TABLEREF = 7 AND BASLIK4.ITEMCODE LIKE 'S.4%') OR BASLIK4.TABLEREF = 2) AND BASLIK4.ITEMLEVEL = 4 AND ALTBASLIK.RATES1<>''
UNION ALL
SELECT  DISTINCT BASLIK4.LOGICALREF AS BASLIK4ID , BASLIK4.ITEMNAME AS BASLIK4 
,REPLACE(ALTBASLIK.RATES2,'*','%') AS KOSUL1, BASLIK4.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK4 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK4.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK4.ITEMCODE 
WHERE ((BASLIK4.TABLEREF = 7 AND BASLIK4.ITEMCODE LIKE 'S.4%') OR BASLIK4.TABLEREF = 2) AND BASLIK4.ITEMLEVEL = 4 AND ALTBASLIK.RATES2<>''
UNION ALL
SELECT  DISTINCT BASLIK4.LOGICALREF AS BASLIK4ID , BASLIK4.ITEMNAME AS BASLIK4 
,REPLACE(ALTBASLIK.RATES3,'*','%') AS KOSUL1, BASLIK4.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK4 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK4.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK4.ITEMCODE 
WHERE ((BASLIK4.TABLEREF = 7 AND BASLIK4.ITEMCODE LIKE 'S.4%') OR BASLIK4.TABLEREF = 2) AND BASLIK4.ITEMLEVEL = 4 AND ALTBASLIK.RATES3<>''
UNION ALL
SELECT  DISTINCT BASLIK4.LOGICALREF AS BASLIK4ID , BASLIK4.ITEMNAME AS BASLIK4  
,REPLACE(ALTBASLIK.RATES4,'*','%') AS KOSUL1, BASLIK4.FORMULA  FROM 
LG_118_FINTABLEITEM BASLIK4 WITH(NOLOCK)  
LEFT JOIN LG_118_FINTABLEITEM ALTBASLIK WITH(NOLOCK) ON  BASLIK4.TABLEREF=ALTBASLIK.TABLEREF AND ALTBASLIK.ITEMCODE LIKE BASLIK4.ITEMCODE 
WHERE ((BASLIK4.TABLEREF = 7 AND BASLIK4.ITEMCODE LIKE 'S.4%') OR BASLIK4.TABLEREF = 2) AND BASLIK4.ITEMLEVEL = 4 AND ALTBASLIK.RATES4<>''
) AS BASLIK4   ON FINOZEL.SPECODE LIKE BASLIK4.KOSUL1

----------------------------------------------


WHERE     (dbo.L_CAPIDEPT.FIRMNR = 118) AND (dbo.L_CAPIDIV.FIRMNR = 118)
AND LG_118_21_BNFICHE.BRANCH <> 28
AND LG_118_21_BNFLINE.TRCODE <> 2
AND LG_118_21_BNFLINE.MODULENR <> 10

-- BANKA ÝÞLEM VE ÇEK TAHSÝLATI GELMESÝN
--AND NOT(LG_118_21_BNFLINE.TRCODE = 1 AND LG_118_21_BNFLINE.MODULENR =61)
-- BELÝRSÝZ OLANLAR GELMESÝN
AND LG_118_21_BNFLINE.TRCODE<6 

--UNION ALL
--SELECT * FROM [dbo].[fnc_118_21_NAKIT_AKIS_HAFTALIK_HESAPLA]()














GO


